src/app.rs, src/arg.rs, src/lib.rs
Removed uppercasing of argument names due to Rust API stability. The same can be accomplished manually if desired by specifying uppercase argument names such as Arg::new("MYARG").
=> Moved to stable Rust APIs

src/args/arg.rs
There's an assertion on line 322 of clap-rs/master that prevents any arg
where `multiple == true` from accepting any value. This commit only
deletes that assertion. It could cause any number of other problems; I
don't really know.
It does pass the tests, at least.
This is totally my first PR on github. :P
=> Remove assertion on multi args.

src/app.rs
SubCommand names are now correctly displayed as `parent-subcommand` for version/help information and `parent subcommand` for usage information.
For example, if you had a program called `fake` with a subcommand `add` when printing help/version you would see
```
$ fake add --help
fake-add 
[...]
$ fake add --version
fake-add v1.0
$ fake add --wrong
USAGE:
fake add <file>
[...]
```
=> Correctly displays subcommand names in help, usage, and version

src/app.rs
Previously if all the arguments you defined were also required, you would still get the "optional" arguments listed in the auto-generated usage string, i.e. `[OPTIONS]` *and* `<your required option>` even though were weren't any "optional" arguments.
This is now fixed.
=> Fixed bug in determining if the only arguments are required

.travis.yml, Cargo.toml, clap-tests/Cargo.toml, clap-tests/Makefile, clap-tests/run_tests.py, clap-tests/src/main.rs, src/app.rs, src/lib.rs
Now that *did you mean* was implemented for the parts under control of `google-apis-rs`, for completeness it should also be available for clap-rs. As done in `google-apis-rs`, suggestions should only be made above a certain confidence level, e.g. `foo` will not result in `did you mean 'baz'`.
This improvement involves the following parts:
- `prog foo` results in `foo is not a valid subcommand. Did you mean 'fop'?`.
- `prog --heln` results in `--heln is not a valid option. Did you mean '--help'?`
- `prog --debug-leve=1` results in `--debug-leve is not a valid option. Did you mean '--debug-level' ?`
- Why not for short flags ? I think the input string should be more than one character to get a useful result.
- *NOTE*: We do not provide the given arguments (i.e. `--debug-level=1`) in our …
=> FOR REVIEW: `did-you-mean` for clap-rs

src/app.rs
Also seems like Atom automatically removed trailing whitespaces when I saved the file. Shouldn't be a problem though, quickly ran `cargo build` + `cargo test` and nothing seemed to be broken.
You should probably set your editor to automatically remove trailing whitespaces, it will stop the above because there will be no trailing whitespaces :smile:
=> Fix an Incorrect Code Example for `App::subcommand_required`

README.md, clap-tests/run_tests.py, src/app.rs, src/macros.rs
Big update as well as a substantial performance improvement when printing help messages!
Before merging still need to:
=> Feature rollup

src/app.rs, src/args/arg.rs
Allows setting `Arg::number_of_values(qty)` where `qty` < 2. This allows
things such as `Arg::number_of_values(1)` in conjuction with
`Arg::multiple(true)` which would make invoking the program like this
`myprog --opt val --opt val` legal, but `myprog --opt val1 val2`
illegal.
Closes #161
=> fix: fixes a logic bug and allows setting Arg::number_of_values() < 2

src/app.rs, src/args/arg.rs, src/args/argbuilder/flag.rs, src/args/argbuilder/option.rs, src/args/argbuilder/positional.rs, src/args/group.rs, src/usageparser.rs
Relates to #167 
This primarily affects printing help messages, which can't really be benchmarked...but it's still good to know ;)
When printing the `clap-tests` test program, this commit removes ~60 allocations.
=> perf: removes some unneeded allocations

src/app.rs, src/lib.rs
Feature for #169. 
For now I`ve done as in issue asked.
How is better to change docs and *setting* method example? Maybe mark somehow methods as *deprecated*? How about *info* method to string-info settings?
=> Replaced some application settings with enum variants

src/lib.rs
New tests:
* flags using short
* flags using long
* flags using mixed (short and long)
* multiple flags in single - (`-fcd` being equal to `-f` `-c` `-d`)
* options with short
* options with long and space (`--option value`)
* options with long and equals (`--option=value`)
* options with mixed
Improvements (added options value check) for:
* posix compatible options using longs
* posix compatible options using longs with `=`
* posix compatibe options using shorts
=> New tests and old tests improvements

src/args/arg.rs, src/lib.rs, src/usageparser.rs
PR to resolve #179.
Now 
```
App::new("short_flag")
.arg(Arg::from_usage("-f1, --flag 'some flag'"));
```
will panic with:
> Usage parser error, unexpected "1" at "-f1, --flag 'some flag'", check from_usage call"
And 
```
App::new("short_flag")
.arg(Arg::from_usage("-f 'some flag'"));
```
will panic with:
> Missing flag name in "-f 'some flag'", check from_usage call
=>  Fixed confusing error message

benches/benchmarks.rs
See #167.
This PR includes two benchmarks: one for building the `App` and one for clean parse. I am open to changing function names or the filename.
I think the variables (`m_val_names`, `args`, etc.) can be moved to `static`, but I don't know the consequence of doing so.
I didn't think benchmarks are big enough to have their own commit message, so I put it under `tests`.
=> tests(benchmark): Add build and clean parse benchmarks

examples/17_yaml.yml
I tried to test new features and got 
```
thread '<main>' panicked at 'The argument 'mode' cannot have a specific value set because it doesn't have takes_value(true) set', /home/vinatorul/.cargo/registry/src/github.com-121aea75f9ef2ce2/clap-1.3.0/src/app/app.rs:927
An unknown error occurred
```
This change fixed example, however error message is not much user-friendly.
=> Yaml example fix

src/app/app.rs, src/app/errors.rs, src/app/mod.rs, src/lib.rs
Now you can use `get_matches_safe` instead of `get_matches` if you want to handle errors yourself.
This will allow now to write false-negative tests and check what type of error occurs, see #166
=> Added ability for users to handle errors themselves

CONTRIBUTORS.md, examples/18_builder_macro.rs, src/macros.rs
=> feat: Builder macro to assist with App/Arg/Group/SubCommand building

benches/03_complex.rs, src/macros.rs
- `(+)` in wrong location in macro definition (Sorry).
- `value_name(s)` and `possible_value(s)`, macro implementation repeats over non plural functions
- `--long-option-2` -> `--long_option_2` Is this a problem? If so - feel free to use the manual function via `long("long-option-2")`
- `[positional]` expands to `value_name("positional") takes_value(true)` not `index(1)`
=> fix: Macro benchmarks

src/macros.rs
As of https://github.com/rust-lang/cargo/pull/1094, cargo publishes the full crate version as `CARGO_PKG_VERSION`, rather than *just* the parts of it.
This replaces the more complicated call with simply `env!("CARGO_PKG_VERSION").to_owned()`. The `.to_owned()` is there as well to ensure backwards compatibility is retained, as the old version of the macro produced a String not `&str`.
This new version of the macro is more succinct, and has slightly less overhead. This does not break compatibility with any stable rust versions, as the change to cargo was made before the 1.0.0 release.
=> Replace crate_version!() macro with simpler call

src/app/app.rs
In the functions
- `App::check_for_help_and_version`
- `App::parse_long_arg`
the `BufWriter` created for `stdout` should be explicitly flushed before calling `std::process::exit`, otherwise it will never get flushed (the destructor is not called because `exit` never returns). 
To fix this, `App::print_version`, the function actually handling the write should flush the received buffer.
Without this patch, the following example prints nothing to `stdout` when called with the `-V` argument:
```rust
extern crate clap;
use clap::App;
fn main() {
let _args = App::new("app")
.version("9001")
.get_matches();
println!("done");
}
```
=> fix: flush the buffer in App::print_version()

CONTRIBUTORS.md, README.md, examples/01c_quick_example.rs
Some various typo fixes and commas and stuff.
I did change one thing though. The portion in the README that's affected by 34b6eb2 still refers to `clap` as a sub 1.0 library. I took that out, but if that is stepping over the line, I can take it out.
=> Various typo fixes

src/app/app.rs, src/args/group.rs, src/tests.rs
Also I've added tests for this change
Now you will get 
```
ArgGroup %Your_ArgGroup_Name% doesn't contain any args
```
instead of
```
thread '<main>' panicked at 'arithmetic operation overflowed'
```
And 
```
ArgGroup %Your_ArgGroup_Name% can not have same name as arg inside it
```
instead of 
```
thread '<main>' has overflowed its stack
```
=> fix(ArgGroup) added asserts to help users to configure clap properly

src/app/app.rs, src/app/errors.rs, src/app/settings.rs, src/args/arg.rs, src/args/argmatches.rs, src/args/group.rs, src/args/subcommand.rs, src/macros.rs, tests/unicode.rs
This allows not `panic!`ing on invalid unicode characters, and the option of returning lossy results. This does **not** turn all results into an `OsStr` preserving invalid unicode.
If this helps with #262 we can merge (after review), otherwise we'll continue to discuss if there's a better way to handle this issue.
=> Issue 262 - Result and Lossy options for invalid Unicode

src/app.rs, src/error.rs, tests/app.rs
- Improved --long=val,val parsing such that each item is treated as
another occurance
- Return a ClapError when a user attempts to do --flag=val1;
UnexpectedValue.
=> fix: Improved --long=val1,val2

README.md
Replaced plain text `example/` and `example/xx_some_example.rs` by links to examples dir and appropriate examples.
=> docs: use links to examples instead of plain text

CONTRIBUTORS.md, README.md
A `*` version constraint makes it hard/impossible to release a breaking
change (e.g. clap 2.0) without causing people's code to break.  `cargo
update` with a `*` dependency will happily move from (say) 1.4 to 2.0,
even though semver says these may be a breaking change. Using a more
precise dependency constraint gives the crate author more flexibility in
making breaking changes, and makes users of the crate happier if/when
they do happen.
https://github.com/rust-lang/rfcs/pull/1241 contains a bit more
discussion about this.
=> Avoid suggesting star dependencies.

src/app/app.rs
=> fix(Usage Strings): fixes a bug ordering of elements in usage strings

src/app/app.rs, src/app/errors.rs
This should **finally** fix all the cases for @elszben since there's now only a single way to determine what goes in the usage string...not 20 :smile:
Closes #277
=> refactor(Errors): refactors how errors are created for deduplication

src/app/app.rs
Once this merges I'm going to ahead and put out 1.4.5 since this fixes a crash.
Relates to #277
=> fix: fixes crash on invalid arg error

clap-tests/run_tests.py, src/app/app.rs
Closes #309 
Turns out it's just a single message which quotes outside a sentence.
=> fix(Errors): tones down quoting in some error messages

.travis.yml
The idea is to get rid of `sudo` in the script, so `travis` can run builds on new crates infrastructure. It will increase build speed and decrease load on `travis`.
=> moving to travis crates infrastructure

src/args/arg.rs
Some fairly minor improvements to the docs for `Arg`. Some typo fixes, and more substantially, rewritten docs for the `multiple` method to clarify that it does actually work alongside `takes_value` and how the two behave together.
=> Improvements to clap::Arg docs

examples/17_yaml.rs
`cargo test` automatically compiles (but not run) examples as well. So, `cargo test` without `--features yaml` flag aborts before running tests, which IMO quite unexpected.
On the other hand, those `#[cfg(...)]` may confuse users.
=> examples(17_yaml): conditinonally compile 17_yaml example

clap-tests/run_tests.py, tests/multiple_values.rs
#166.
Currently, there are four different error types that indicate the same thing: `TooManyArgs`, `TooManyValues`, `TooFewValues`, `WrongNumValues`. I wasn't sure which error they give. Therefore, I just checked that it gives error, but I do not check which error it gives.
=> tests(multiple_values): move tests related to multiple values

examples/17_yaml.rs, tests/unicode.rs, tests/yaml.rs
For `tests/yaml.rs`, it makes sense to use scope wide attribute, which applies to the whole file, because yaml test will not be tested without yaml feature.
For `examples/17_yaml.rs`, I moved the `use` statement inside so that seemingly random unused import warning doesn't pop up.
For `tests/unicode.rs`, well, I tried fiddling around with unicode with Windows without much success...
=> Scopewide attributes

README.md
Well, I thought scrolling through half page of readme to find link to documentation was counterintuitive.
And, of course, 10,000 ns is 10 ms.
=> docs(README.md): fix typo and make documentation conspicuous

src/app/parser.rs, src/app/settings.rs
By using AppSettings::AllowLeadingHyphen values starting with a
leading hyphen (such as a negative number) are supported. This
setting should be used with caution as it silences certain
circumstances which would otherwise be an error (like forgetting
a value to an option argument).
Closes #385
=> feat: adds support values with a leading hyphen

Cargo.toml
Bump `bitflags` from 0.3.3 to 0.4.0 and `yaml-rust` from 0.2.2 to 0.3.0.
All tests pass in current stable, beta and nightly (`1.8.0-nightly (38e23e8f7 2016-01-27)`).
=> chore: bump dependencies bitflags and yaml-rust to latest version

CONTRIBUTORS.md, src/args/arg_matches.rs, src/args/matched_arg.rs, tests/multiple_occurrences.rs
Hi,
I often use tools with `xargs` and the like, and it's entirely possible to end up with inhumanly long sets of parameters being passed to a command. 
Without this fix, the library will panic with an arithmetic overflow in `ArgMatcher#inc_occurrence_of` when the 256th instance of the parameter is accounted for.
Thanks,
=> Allow for more than 256 occurrences of an argument.

CHANGELOG.md, Cargo.toml, clap-tests/run_tests.py, src/app/macros.rs, src/app/mod.rs, src/app/parser.rs, src/app/settings.rs, src/args/any_arg.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/args/arg_matcher.rs, src/errors.rs, src/macros.rs, src/usage_parser.rs, tests/app_settings.rs, tests/flags.rs, tests/help.rs, tests/opts.rs, tests/positionals.rs, tests/tests.rs
This turned into a little more than just a quick bug fix :stuck_out_tongue_winking_eye: 
Thanks to #409 I've piggy backed on that and added support for > 256 values as well.
There's also just a bunch of code deduping and super small macro cleanups.
After this merges I'll put out 2.0.3
=> Bug fixes, new setting, code clean up, and added support u64::max values per arg

src/osstringext.rs, tests/positionals.rs
The method `starts_with` as implemented for the `OsStrExt2` trait on
`OsStr` assumed that the needle given is shorter than the haystack. When
this is not the case, the method panics due to an attempted
out-of-bounds access on the byte representation of `self`. Problematic
if, say, an end-user gives us `"-"` and the library tries to see if that
starts with `"--"`.
Fortunately, slices already implement a `starts_with` method, and we can
delegate to it.
This *does* create a semantics change: if both `self` and the needle
have length 0, this implementation will return `true`, but the old
implementation would return `false`. Based on the test suite still
passing, acknowledging the vacuous truth doesn't seem to cause any
problems.
Fixes #410
=> fix: Stop lonely hyphens from causing panic

src/app/meta.rs, src/app/parser.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/args/arg_matcher.rs, src/args/arg_matches.rs, src/args/settings.rs, src/osstringext.rs, src/suggestions.rs
=> rustup: fix nightly

CHANGELOG.md, README.md, clap-tests/run_tests.py, src/app/meta.rs, src/app/mod.rs, src/app/parser.rs, src/app/settings.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/args/group.rs, src/errors.rs
Merge *after* #449 
Closes #416
=> Issue 416 - Help subcommand accepts other subcommands as arguments

src/macros.rs
I ran into an error using 
```
struct Error {}
pub type Result<T> = ::std::result::Result<T, Error>;
arg_enum!{
....
}
~~~ 
Attached is a fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/473)
=> Use ::std::result::Result to make macro hygienic.

examples/19_auto_authors.rs, src/app/mod.rs, src/macros.rs
Adds a crate_authors! macro that fetches
crate authors from a (recently added)
cargo enviromental variable populated
from the Cargo file. Like the
crate_version macro.
Closes #447 
Hopefully this fixed the previous problems.
=> feat(Authors Macro): adds a crate_authors macro

CHANGELOG.md
There was an URL accidentally pasted at the wrong position in 8a95dace62a3556fd1b9dca402435852aab2705c
=> Revert accidental pasting

examples/20_aliases.rs, src/app/mod.rs
Hey there,
I tried out the new aliasing feature, and they don't seem to play well with `.arg()`.
This produces a lifetime errors:
```bash
examples/20_aliases.rs:9:59: 9:74 error: borrowed value does not live long enough
examples/20_aliases.rs:9                                                 .aliases(&["list", "dir"])
^~~~~~~~~~~~~~~
```
=> test: adds failing alias doc test and example

src/args/arg_matches.rs, src/args/mod.rs, src/args/settings.rs, src/lib.rs
Some types weren't viewable in the docs, such as `Values`, `OsValues`,
and `ArgSettings`. All these types should now be browsable in the
docs page.
Relates to #505
=> docs: makes all publicly available types viewable in docs

src/app/help.rs, src/app/mod.rs, src/app/settings.rs, src/args/arg.rs, src/args/arg_matches.rs, src/args/group.rs, src/args/settings.rs, src/args/subcommand.rs, src/errors.rs, src/lib.rs, src/macros.rs
All doc pages should now be inter-linked between other doc pages and
Rust documentation.
Closes #505
=> docs: inter-links all types and pages

src/app/mod.rs, src/app/settings.rs, src/args/arg.rs, src/args/arg_matches.rs, src/args/group.rs, src/macros.rs, src/suggestions.rs
Just caught a couple of small typos while browsing the documentation, I believe the meaning of everything is still conveyed as intended as it's just single words.
=> docs: fix typos

src/app/parser.rs, src/args/arg.rs
Add the function `Arg.groups` that can take a `Vec<&'a str>` to add the `Arg` to multiple `ArgGroup`'s at once.
ex:
```rust
Arg::with_name("arg")
.groups(&["grp1", "grp2"])
```
Closes #426
=> imp(ArgGroup): Add multiple ArgGroups per Arg

src/macros.rs
One can now use more than one meta item, and things like `#[repr(C)]`
Example:
```rust
arg_enum! {
#[repr(C)]
#[derive(Debug)]
pub enum MyEnum {
A=1,
B=2
}
}
```
Closes #543
=> imp(arg_enum!): allows using meta items like repr(C) with arg_enum!s

src/term.rs
The term module uses the struct Winsize directly in a C ioctl call, so it must use C struct representation.
=> fix: Declare term::Winsize as repr(C)

src/app/mod.rs
A missing newline prevented the Cargo.toml excerpt in the `gen_completions` example from being properly formatted.
=> Fix the formatting in the completions example

README.md, examples/19_auto_authors.rs, src/app/mod.rs, src/macros.rs
The cargo feature it depends on has been available since april, I think we can make this stable now.
=> removed unstable gate from crate_authors

src/app/mod.rs, tests/app_settings.rs
=> feat(Settings): Add unset_setting and unset_settings fns to App

src/args/arg.rs
One can now use a list or single value for certain Arg YAML declarations
such as possible_values, etc.
Prior to this commit, if only a single value was desired one would have
to use the format:
```yaml
possible_values:
- value
```
But now once can use
```yaml
possible_values: value
```
Closes #614
Closes #613
=> feat(YAML): allows using lists or single values with arg declarations

Cargo.toml
Fixes a panic when Jaro is called with strings each with a length of one. A `clap` user discovered this: dguo/strsim-rs#5
=> chore: update dep

src/args/group.rs
=> Fix ArgGroup example not formatted as code

src/app/mod.rs
=> Fix documentation formatting for App::template()

Cargo.toml, src/app/help.rs, src/app/mod.rs, src/lib.rs
Had to revert many formatting changes, which means your code is unformatted despite the presence of `rustfmt.toml` at repo root, you should global format.
Closes #455
=> Add support for wrapping help at console width on windows

Cargo.toml, src/app/help.rs, src/lib.rs
=> Use term_size instead of home-grown solution

src/args/arg.rs, tests/app.yml
Seems this is missing from 920b559.
=> imp(YAML): supports setting Arg::require_delimiter from YAML

clap-test.rs, src/app/help.rs, src/app/mod.rs, src/app/parser.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/suggestions.rs, tests/app.yml, tests/arg_aliases.rs, tests/help.rs
There are some cases where you need to have an argument to have an
alias, an example could be when you deprecate one option in favor of
another one.
Now you are going to be able to alias arguments as follows:
```rust
Arg::with_name("opt")
.long("opt")
.short("o")
.takes_value(true)
.alias("invisible")
.visible_alias("visible")
```
Closes #669 
Also you can alias flags as follow:
```rust
Arg::with_name("flg")
.long("flag")
.short("f")
.alias("not_visible_flag")
.visible_alias("awesome_v_flag")
```
=> feat(arg_aliases): Ability to alias arguments

tests/positionals.rs, tests/tests.rs
Use `App::get_matches_from(vec![""])` instead not to fail when flags are passed to the test binary
Closes #676
=> tests(correctness): No longer use App::get_matches() in some places

src/app/mod.rs
=> Deprecate App::with_defaults()

src/app/mod.rs, src/app/parser.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, tests/derive_order.rs
Don't attempt to change the display order of flags/options until any app settings have been propagated down from a parent `App` in case `DeriveDisplayOrder` and/or `UnifiedHelpMessage` are propagated.
Adds tests that try to stress the combinations of `DeriveDisplayOrder` and `UnifiedHelpMessage` along with propagating them to subcommands and explicitly setting a display order.
=> Derive display order after propagation

examples/17_yaml.rs
change yaml example to be consistent with its configuration
fix #707, #708
=> fix(yaml-example): inconsistent args

src/app/mod.rs
This is a proposal... I would like to have this for [imag](https://github.com/matthiasbeyer/imag) ([this PR](https://github.com/matthiasbeyer/imag/pull/826)).
If this is not a good idea for some reason, I will rewrite my abstractions,... but this would be the easy way for me, so I propose this! :smile:
=> Add App::app_name() getter

src/app/parser.rs, src/completions/mod.rs, src/completions/powershell.rs, src/completions/shell.rs
Fixes #729
---
Requires PS 5.0+ for the `Microsoft.PowerShell.Core\Register-ArgumentCompleter` commandlet. Earlier versions using the equivalent commandlet from TabExpansionPlusPlus may work, but I haven't tested that. PS 5.0 is available for Windows 7 and non-Windows anyway.
The resulting script can be used by pasting it into the PS profile or saving it to a file and sourcing it into the PS profile in the usual way.
=> Completion support for PowerShell.

README.md, src/lib.rs
README still had a mistake regarding YAML parsing, and the README and lib.rs referenced the wrong folder name for tests.
=> DOCS: Simple documentation updates

src/args/arg.rs
These links are relative to the root of the server instead of the current file. This breaks causes them to be broken on docs.rs.
=> docs: fix broken docs links

justfile
I noticed that this is a common pattern in justfiles, recipes that
run a lot of commands and prefix every line with `@` so that
only output is printed.
So I added quiet recipes, which are recipes where the recipe name
is prefixed with a `@`.
Inside quiet recipes the usual meaning of `@` is inverted. Only
lines starting with `@` are echoed.
This diff makes the `update-contributors` recipe a quiet recipe,
and gets rid of all those unsightly `@`s.
PS I just added this in v0.2.21, so you'll need to install the latest version
from crates.io to test.
PPS Thanks for using just! I was super excited to see a justfile in this repo,
since I'm a huge fan of clap.
=> Make `update-contributors` a quiet recipe

src/app/help.rs
This is a proposal.
Some distros (yes, I'm using the distro rustc because my distro has some benefits over using the rustup infrastructure) do not yet have the newest compiler.
I therefor propose to stay with `try!()` instead of `?` for maybe two weeks or so, maybe even a bit more, until all distros have updated their version of `rustc`.
=> Use try!() instead of ? operator, for older compilers

src/completions/bash.rs, tests/completions.rs
With these options, in case the completion function cannot provide suggestions, Bash will perform its default completions, based on e.g. files, directories, and variable names.
This is particularly noticeable in tools that operate on paths, like ripgrep: when I type `rg should_panic te<TAB>`, I want the shell to autocomplete `tests/`, but right now the completion script will simply beep without any suggestions.
=> imp(Completions): adds fallbacks to Bash completions

src/app/mod.rs
It seems that Cargo no longer sets OUT_DIR when compiling build.rs, but
it's still available at runtime. Therefore, switch `env!` to
`env::var_os`.
=> Query OUT_DIR at runtime.

src/macros.rs
=> Handle replacing colons with custom separators in crate_authors!() 

src/app/parser.rs
Instead of using Format::Error directly, we need to use a Colorizer to
make sure that the message only gets colorized when it is appropriate
to do so.
Fixes #775
=> Only colorize missing arguments when appropriate

Cargo.toml, src/app/mod.rs, src/macros.rs
For example, given:
```toml
clap = { path = "t:/clap-rs" }
```
The macros `crate_version!()` and `crate_authors!()` exist, so the crate compiles without errors:
```
Compiling https v0.2.0 (file:///P:/Rust/http)
Finished debug [unoptimized + debuginfo] target(s) in 6.93 secs
Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
[Finished in 7.5s]
```
But, adding the `no_cargo` feature:
```toml
clap = { path = "t:/clap-rs", features = ["no_cargo"] }
```
The macros are removed, so the crate fails to compile:
```
Compiling clap v2.19.2 (file:///T:/clap-rs)
Compiling https v0.2.0 (file:///P:/Rust/http)
error: macro undefined: 'crate_version!'
--> src\options.rs:40:22
|
40 |             .version(crate_version!())
|                      ^^^^^^^^^^^^^
error: macro undefined: …
```
=> Add no_cargo feature to disable Cargo-env-var-dependent macros

src/macros.rs
=> Implement crate_description!, crate_name! and app_from_crate! macros

src/app/settings.rs, src/args/arg.rs
When calling the executable without arguments one expects a help message. However, if even one argument has a default value, the validation step of the parser will always see at least one argument, and therefore report success. This effectively disables the settings.
=> Explain how `ArgRequiredElseHelp` and `default_value` interact

src/macros.rs
In the link from `app_from_crate!` to `crate_authors!`, the link text and address are swapped.
=> docs: fix link from app_from_crate! to crate_authors!

src/app/macros.rs
This fixes #827. The problem was that the check `grp.args.contains(&grp.args[i])` was a) trivially fulfilled (of course `grp.args[i]` is contained in `grp.args`) and b) causing an out-of-bounds error, since the indices were taken from `.required.len()`.
With this change the argument in the group will be removed from the list of required arguments, as intended.
=> Fix finding required arguments in group arguments

Cargo.toml
It's good practice for a library not to depend on exact versions of any other libraries, so that downstream programs are able to update dependencies they have in common at their leisure.
This is described in the Cargo documentation at:
http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
An example of the problem an exact version depedency creates can be seen at https://gist.github.com/jimmycuadra/ac26eca5f11960c357d6fba841640f2f.
This patch modifies Cargo.toml to allow semver-compatible updates to clap's dependencies.
=> Relax dependency version constraints.

src/app/help.rs, tests/help.rs
I've been working towards integrating my [textwrap][1] crate and along the way, I found some small problems in the existing `wrap_help` function in clap. I basically added new code that calls both `textwrap::fill` and `wrap_help` and panicked on any difference:
```
fn wrap_help(help: &mut String, longest_w: usize, avail_chars: usize) {
let input = help.clone();
let mut old = help.clone();
old_wrap_help(&mut old, longest_w, avail_chars);
let mut wrapped = String::with_capacity(help.len());
for (i, line) in help.lines().enumerate() {
if i > 0 {
wrapped.push('\n');
}
wrapped.push_str(&textwrap::fill(line, avail_chars));
}
// TODO: move up, This keeps old behavior of not wrapping at all
// if one of the words would overflow the line
if longest_w < avail_chars {
*help = wrapped;
}
if *old != …
```
=> Fix wrapping bugs

.github/CONTRIBUTING.md
The current link to examples doesn't work. Probably left behind from when CONTRIBUTING.md was in the root directory.
=> docs: Fix examples link in CONTRIBUTING.md

src/macros.rs
Introduced in #238, this bug affects both `clap` `1.*` and `2.*` and was found by rust-lang/rust#39419.
I'd suggest releasing not only `2.20.5`, but also `1.5.6`, to cover downstream crates still on `1.5.5`.
=> Add missing fragment specifier to a clap_app! rule.

Cargo.toml, src/fmt.rs, src/lib.rs
Not only does this remove some unsafe code from clap itself, `atty` does the right thing on Windows too. This isn't relevant now since we don't currently support colorized output on Windows, but will come in handy if/when we implement that feature (#836).
=> refactor: use the atty crate for isatty() detection

Cargo.toml, README.md, src/lib.rs
It's not actually used anymore anywhere.
=> Remove direct dependency on libc

src/app/mod.rs, src/app/parser.rs, tests/app.yml, tests/help.rs, tests/yaml.rs
Fixes #889 
This currently doesn't support customizing them from YAML, so it still needs some work.
=> Allow customizing the --version and --help messages

src/completions/fish.rs, tests/completions.rs
Adds the `-d help_string` parameter to fish completion is present.
Example output:
```
complete -c mm3d -n "__fish_using_command mm3d" -f -a "Ann" -d "matches points [...]"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/905)
=> imp: add fish subcommand help support

src/app/help.rs, src/args/arg.rs, src/args/settings.rs, tests/help.rs
Adds a new method, `Arg::hide_default_value()`, to hide the default argument from the help string.
Fixes #902.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/913)
=> Add Arg::hide_default_value()

src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/925)
=> docs: Fix a typo the minimum rust version required

src/args/arg_matches.rs
Fixes https://github.com/kbknapp/clap-rs/issues/935.
The iterators terminate with `None` on the first call to `.next()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/939)
=> api(arg_matches.rs): Added a Default implementation for Values and OsValues iterators.

src/args/arg.rs, tests/default_vals.rs
Also add related tests, and reframe `default_value` in terms of
`defualt_value_os`.
This resolves #849.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/941)
=> api(Arg): add `default_value_os`

Cargo.toml
Version 1.2.0 of unicode-segmentation adds code that use the "?"
operator, which in turn requires Rust 1.13.0. However, clap currently
still works with Rust 1.11.0 and this caused build failures:
https://travis-ci.org/kbknapp/clap-rs/jobs/235010822
The changes since 1.1.0 seem to be related cursors/iterators and I
think clap can work fine without them.
This was found as part of #845. See also https://github.com/unicode-rs/unicode-segmentation/issues/26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/967)
=> cargo: restrict unicode-segmentation to ~1.1.0

src/app/help.rs, src/app/validator.rs, src/errors.rs, src/fmt.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/963)
=> when `TERM=dumb`, the output is colorless #847

Cargo.toml, benches/05_ripgrep.rs, src/app/help.rs, src/lib.rs, tests/help.rs
This PR replaces the `wrap_help` function with a call to my [textwrap][1] crate which does word wrapping using a simpler and faster algorithm. I've extended the `05_ripgrep` benchmarks with a benchmark that tests generating the help text -- I figured that ripgrep would be a good example since it has lots of long strings in the help output. Comparing before and after looks like this on my machine:
```
name              before ns/iter  after ns/iter  diff ns/iter   diff %  speedup 
build_app_long    22,101          21,099               -1,002   -4.53%   x 1.05 
build_app_short   22,138          21,205                 -933   -4.21%   x 1.04 
build_help_long   514,265         284,467            -229,798  -44.68%   x 1.81 
build_help_short  85,720          85,693                  -27   -0.03% …
```
=> Use my textwrap crate for wrapping help texts

src/app/help.rs
This PR aims to simplify the help generation code a little.
It also lets `textwrap` handle long words, i.e., words longer than the available line width. Before, no wrapping what so ever was done if it was detected that the longest word could not fit into the line. Now, the text is still being wrapped -- the long word will simply be put on a line by itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/974)
=> Small cleanups and refactoring in help generation

Cargo.toml, src/app/settings.rs, src/args/settings.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/966)
=> Update bitflags 0.8.0 -> 0.9

src/app/help.rs
Previously, there was a small bug with unicode widths. Clap would display the following help:
```bash
sniff-ar
Verzeichnis mit Artefakte anzeigen
USAGE:
sniff ar [FLAGS] [OPTIONS] [VERZEICHNIS]
FLAGS:
-g, --keine-gitignore    Nicht Angaben aus '.gitignore' benutzen
-h, --help               Prints help information
-x, --schwiegend         Drucken keine Warnungen.
-o, --sort               Sortieren Ergebnisse nach Größe
-V, --version            Prints version information
OPTIONS:
-a, --ausklammern <PFADNAME>    Pfade zu ausklammern
-r, --regex <REGEX>             Regulärer Ausdruck
-s, --schwelle <DATEIGRÖßE>   Ein Schwelle für Dateigröße angeben.
-t, --tiefe <NUMMER>            Wie tief zu durchqueren
ARGS:
<VERZEICHNIS>    Verzeichnis zu suchen in
```
Now, it works correctly:
```bash …
```
=> fixes bug with unicode widths

clap-test.rs, src/app/parser.rs, src/errors.rs, src/suggestions.rs, tests/help.rs, tests/subcommands.rs
Hi @kbknapp,
I saw that  https://github.com/kbknapp/clap-rs/issues/927 was mentored, so I'd like to give it a try.
Here is a first attempt. The message is simpler than what to suggest in the issue, because I could not find out how to print this part from `did_you_mean_flag_suffix`:
```
myapp --foo bar
^^^^^
```
By the way, I splitted `did_you_mean_suffix` into `did_you_mean_flag_suffix` and `did_you_mean_value_suffix`, is that ok?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/980)
=> Suggest to use flag after a sub-command 

Cargo.toml
All the other features are either irrelevant, for nightly or already included by default so this should build with all features.
https://github.com/onur/docs.rs/pull/73
Fixes #911
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/997)
=> Tell docs.rs about the yaml feature

src/args/arg_matches.rs
`Values` and `OsValues` are apparently invariant, i.e. a `Values<'static>` cannot be assigned to a `Values<'a>`
This makes the `impl Default for Values<'static>` basically useless since most of the time these types are obtained from an `ArgMatches::values_of()` as a `Values<'a>`. In particular `matches.values_of().unwrap_or_default()` would fail:
```
error[E0597]: `matches` does not live long enough
--> src/args/arg_matches.rs:650:22
|
650 |     let mut values = matches.values_of_os("").unwrap_or_default();
|                      ^^^^^^^ does not live long enough
651 |     assert_eq!(values.next(), None);
652 | }
| - borrowed value only lives until here
|
= note: borrowed value must be valid for the static lifetime...
```
This PR implemented the Default trait for all lifetimes so that …
=> impl Default for Values + OsValues for any lifetime.

src/app/mod.rs
`print_long_help()` erroneously had the same docstring as `print_help()`, so the mention of `-h` has been changed to `--help`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/999)
=> Fix documentation for print_long_help, trim whitespace

Cargo.toml
This version of textwrap uses a new wrapping algorithm that allocates
fewer strings on the heap.
The 05_ripgrep benchmarks shows a performance improvement of 3-15%.
The build_help_long benchmark benefits the most since it uses longer
help texts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1009)
=> perf: update textwrap to version 0.7.0

clap_completions/src/shell.rs
There's also an `enum Shell` in `src/builders/App.rs`, but it's marked as "@TODO-v3-beta: Remove" so this PR doesn't change it.
This PR is against the `v3-master` branch, I'm not sure if I should be using `v3-dev`.
Edit: resolves #994
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1017)
=> Make the Shell enum non-exhaustive

src/args/arg.rs
"Value" was misspelled "vaue"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1022)
=> Fix documentation typo

Cargo.toml, tests/help.rs
Generating a default help message where `set_term_width(0)` had been applied caused the app to panic due to [this line](https://github.com/mgeisler/textwrap/blob/0.7.0/src/lib.rs#L355) in textwrap 0.7.0.  In this case, `self.width` would be `usize::MAX` and the call would result in an 'attempt to divide by zero' or 'attempt to add with overflow' panic depending on the build type.
This issue no longer exists in textwrap 0.8.0 (hence I didn't file an issue there).  Tagging @mgeisler for info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1040)
=> fix: avoid panic generating default help msg if term width set to 0 due to issue in textwrap 0.7.0

src/completions/fish.rs, src/completions/zsh.rs, tests/completions.rs
Bash and PowerShell work fine as they don't support help texts.  Test cases are
taken from real world applications. For example zsh completion for rustup is
partly broken because help texts contain backticks that are interpreted as
subcommands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1039)
=> Escape special characters in zsh and fish completions

.travis.yml, Cargo.toml, README.md, src/lib.rs, tests/version-numbers.rs
Hi @kbknapp. I noticed that I tend to forget to update the version numbers in the TOML examples in my README files when I do a release, so I wrote a small crate that makes it easy to add an integration test for this: [version-sync][1].
It can check the typical
~~~markdown
```toml
[dependencies]
clap = "~2.26"
```
~~~
blocks in your README. If the version number doesn't match the crate version, the test fails. Since `version-sync` only works on Rust 1.15 and later, I remove the dependency when Travis tests with version 1.13.0 — that's a bit of a hack, but it should work okay.
I've updated your README to match the current crate version and then added an integration test. I hope you find it useful!
[1]: https://crates.io/crates/version-sync
---
This change is [<img …
=> Keep README version numbers in sync with crate version

Cargo.toml, README.md, src/app/help.rs, src/app/mod.rs, src/app/parser.rs, src/args/any_arg.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/args/arg_builder/valued.rs, src/lib.rs, src/map.rs, src/usage_parser.rs
This makes vec_map optional. vec_map is enabled by default. An implementation using BTreeMap is used if vec_map is disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1051)
=> make vec_map optional

.travis.yml, src/app/help.rs, src/app/parser.rs, src/macros.rs
This PR addresses most of https://github.com/kbknapp/clap-rs/issues/1054.
* [cad2e64](https://github.com/H2CO3/clap-rs/commit/cad2e64bdf57fa0ab01317a50e4d4276fa467931) replaces two instances of `from_utf8_unchecked()` with `from_utf8().unwrap_or_default()`. The method `unwrap_or_default()` is used instead of a plain `unwrap()` in order not to crash client code if invalid UTF-8 ever comes out of the library (which should theoretically never happen, but never say never). Since one string is just a debug message, the other one is a supplementary error message, getting an empty string instead of a crash or invalid UTF-8 should be acceptable.
For printing the error message, the function `str::from_ut8` is used instead of `String::from_utf8` because there's no point in allocating a string, …
=> Reduce amount of unsafe code

src/app/help.rs, src/app/mod.rs, src/app/parser.rs, src/args/any_arg.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/args/arg_builder/valued.rs
I noticed while using the new `Arg::env` feature, that the help string wouldn't display the env parameter as an option if it was not set in the environment.
It will now look like this:
```console
--opt <OPT>         Opt description [env:OPT_ENV: ]  [default: opt]
```
I wasn't sure what to put when not present so I went with `""`, the empty string. Let me know if you have other thoughts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1065)
=> always add env parameter when passed

src/app/validator.rs, src/macros.rs, src/osstringext.rs, tests/opts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1109)
=> Issue 1105

README.md
Since commit ac97edde9042203771e905be9c429d36b39df277, feature "wrap_help" is not enabled by default.
Update the README accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1123)
=> Update default features in README

src/macros.rs, tests/macros.rs
This resolves #1097. A test was also included. Let me know if you'd like more tests or tweaks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1124)
=> Support trailing comma in arg_enum! fields

src/lib.rs
Small correction to add a link to the source in the documentation, previously
it was a placeholder.
`rustdoc` does not appear to package assets with the docs, therefore
relative links looking for static files do not work. The links are
consistent enough on github that the static files can be directly linked
to on the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1138)
=> docs: fixes broken links.

src/completions/zsh.rs, tests/completions.rs
Long options take their argument either in the next word or after an equals sign, but the Zsh completion specified that they take it either in the same word with no separator or in the next word. See the documentation of the [Zsh _arguments function](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Completion-Functions) for more information.
```rust
extern crate clap;
use std::io;
use clap::{App, Arg, Shell};
fn build_cli() -> App<'static, 'static> {
App::new("clap-test")
.arg(Arg::with_name("wat")
.long("wat")
.takes_value(true)
.possible_values(&["foo", "bar"]))
.arg(Arg::with_name("completions")
.long("completions"))
}
fn main() {
let matches = build_cli().get_matches();
if matches.is_present("completions") {
build_cli().gen_completions_to("clap-test", Shell::Zsh, &mut …
```
=> Fix completion of long option values in Zsh

src/completions/zsh.rs, tests/completions.rs
This includes a bunch of improvements to Zsh completion, as separate commits:
1. Complete positional arguments properly
This changes the way we complete positionals to complete them using `_arguments`, as should be done, instead of completing their uppercase name as a string.
Currently I made it offer `_files` completion for all positional arguments. This can be improved to complete actual possible values of the arguments and only complete files if the argument truly takes them. But this will require further changes in clap to actually have the required functionality to get this information.
2. Maybe fix completions with mixed positionals and subcommands
Optional positionals mixed with subcommands will still break this, since I can't see how to tell which element of `$line` is the command …
=> Zsh completion improvements

src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1159)
=> Fix typo in crate documentation

src/app/parser.rs
Suppose there is a program that executes another program, then it is convenient to take the arguments of the subprogram after `--`, as illustrated in the `22_stop_parsing_with_--.rs` example. However, if the subprogram itself wants to receive `--`, then clap-rs should allow it.
Fixes #1161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1162)
=> Allow nesting of '--'

src/errors.rs, tests/possible_values.rs
Changed error message according to Issue #1160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1167)
=> style: Issue #1160

src/args/arg.rs
Decided to just fix #1173 real quick myself.
I tested with my own clap app - `--help` indicated that the last argument was applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1175)
=> Add "last" to list in Arg::from_yaml

Cargo.toml, src/lib.rs
Before this commit, ansi_term was compiled anytime the `color` feature
was used. However, on Windows the `color` feature is ignored. Even so
ansi_term was compiled, and just not used. This commit fixes that by
only compiling ansi_term on non-Windows targets. Thanks to @retep998 for
the gudiance.
Closes #1155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1178)
=> imp(Deps): doesnt compile ansi_term on Windows since its not used

README.md, src/app/parser.rs, src/args/arg.rs, src/osstringext.rs
This is a complete rebase of the existing changes in #1187 to clean up the history
cc: @kbknapp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1190)
=> Wasm redux

.github/CONTRIBUTING.md
https://github.com/Manishearth/rust-clippy => https://github.com/rust-lang-nursery/rust-clippy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1193)
=> docs(CONTRIBUTING.md): fix url to clippy upstream repo to point to rust-lang-nursery/rust-clippy

Cargo.toml
lto = true no longer implies codegen-units = 1 in nightly, however several CGUs may prevent some optimizations, thus force codegen-units to 1 in release and bench profiles.
<details><summary>cargo bench pre-patch:</summary>
<p>
````
Running target/release/deps/01_default-e8a3ee34fccb9d17
running 2 tests
test build_app   ... bench:          65 ns/iter (+/- 2)
test parse_clean ... bench:         505 ns/iter (+/- 11)
test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out
Running target/release/deps/02_simple-7f768641c259a9fc
running 12 tests
test add_flag         ... bench:         197 ns/iter (+/- 5)
test add_flag_ref     ... bench:         229 ns/iter (+/- 20)
test add_opt          ... bench:         272 ns/iter (+/- 18)
test add_opt_ref      ... bench:         330 …
```
=> Cargo.toml: use codegen-units = 1 in release and bench profiles.

Cargo.toml
This fixes some markdown warnings when building the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1199)
=> chore: Update to ansi_term 0.11

src/app/parser.rs, src/map.rs, tests/subcommands.rs
Copy the fix from https://github.com/kbknapp/clap-rs/pull/1162 into
the v3 parser, and add a test to protect against regressions in the
expected behavior of example 22.
Note: I haven't been able to lint this - `cargo build --features lints` seems to fail on current nightly. I assume CI will tell me if I messed up linting, but I wanted to mention it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1198)
=> Port 1161 fix to v3

Cargo.toml
As part of v3, @kbknapp would like to depend on term_size 1.0 instead of 0.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1202)
=> bump version on term size to 1.0.0-beta1

src/app/help.rs, tests/app_settings.rs, tests/help.rs, tests/template_help.rs
For version 3, we want the args section to immediately follow
the usage section in the default help message.
One change that I am unhappy with is needing to make "write_arg"
in app/help.rs accept an extra param that makes it suppress the
extra line. This is to prevent an extra blank line from appearing
between args and options in the default help, and seems necessary,
but there might be a better way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1208)
=> Print ARGS after usage in help

src/completions/fish.rs, tests/completions.rs
Fixes https://github.com/kbknapp/clap-rs/issues/1212 using upstream  [`__fish_use_subcommand`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_use_subcommand.fish) / [`__fish_seen_subcommand_from`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_seen_subcommand_from.fish) functions rather than creating our own custom one.
This is my first foray in to the world of Rust, so feel free to amend my changes as you see fit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1214)
=> fish: Fix completion of >1 options

src/app/parser.rs, tests/app_settings.rs
Fix for https://github.com/rust-lang/cargo/issues/5201 =P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1215)
=> Disable typo suggestions in presence of external subcommands

src/app/help.rs, src/app/parser.rs, src/args/arg.rs, src/args/settings.rs, tests/hidden_args.rs
Relates to #1064 
I've added the enum variants and related setting methods to provide the functionality. However, the usage of [Parser::use_long_help()](https://github.com/kbknapp/clap-rs/blob/master/src/app/parser.rs#L1501) is causing issues. 
It seems that the linked method will not allow `use_long` to be `true` unless there is actually a long help value defined for the `Arg`. However, I noticed in [help.rs](https://github.com/kbknapp/clap-rs/blob/master/src/app/help.rs#L445) that we would choose to use the desired long or short help based on what was specified during the run and the extra logic does not seem like it is really needed. However when I bypassed the code in `parser.rs`, there were some failing tests.
@kbknapp do you have any suggestions?
---
This change is [<img …
=> Add option to hide help based on long/short

src/app/help.rs, src/app/mod.rs, src/args/arg.rs, src/macros.rs, tests/help.rs
This partially implements the custom help sections from github
issue 805. There are still formatting issues with the output of the
custom help sections, but the general proof of design is there.
I wish that printing out custom help messages didn't have a nested
loop in it (see changes in src/app/help.rs) but this code only
runs when printing the help for a crate that has custom help sections,
so it has no performance impact in the majority of cases.
This is a rough draft at addressing https://github.com/kbknapp/clap-rs/issues/805
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1211)
=> Partial Implementation of custom help sections

src/app/settings.rs, src/app/validator.rs, src/args/settings.rs, src/completions/shell.rs, src/completions/zsh.rs, src/macros.rs, tests/possible_values.rs
Currently using `arg_enum` macro on `nightly` will trigger the following warning:
```bash
use of deprecated item 'std::ascii::AsciiExt': use inherent methods instead
```
This is due to <https://github.com/rust-lang/rust/blob/master/src/libstd/ascii.rs#L55>. Projects will fail to compile on `nightly` if `#![deny(warnings)]` is set.
Resolve by appending `#[allow(deprecated)]` to affected parts to prevent warnings from bubbling up to the projects using the library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1242)
=> Allow deprecated to remove warnings for rustc 1.26 onwards

src/args/arg.rs, tests/env.rs
From #1088.
Makes the validator functions more flexible by changing the return type from `Result<(), String>` to `Result<O, E>` where `O` is anything and `E` is anything convertible to a `String`.
This allows, for example, using the same function for validating and parsing your argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1243)
=> imp: make Arg::validator more flexible (v3)

src/macros.rs, tests/macros.rs
In particular, fix macros that take an enum of one of the the following forms:
- `#[...] enum { ... , }`
- `pub enum { ... , }`
- `enum { ... , }`
Previously, these expansions would result in an error message like "error: no
rules expected the token `:`".
Add extensive tests for each pattern.  Only two of the patterns had tests
before, so these errors did not surface automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1244)
=> fix(arg_enum!): Invalid expansions of some trailing-comma patterns

src/app/parser.rs, src/app/validator.rs, src/osstringext.rs
* `OsStr` gained `.len()` and `.is_empty()` in Rust 1.6, so remove `.len_()` and `.is_empty_()`
* `Split`'s `DoubleEndedIterator` implementation is completely wrong and unused
(moves a cursor backward instead of splitting from the end)
* `Split`'s `.size_hint()` is slightly wrong and unused
(produces (0,None) instead of (0,Some(0)) when empty, and is O(n))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1247)
=> Remove unused or unnecessary methods from osstringext

src/app/parser.rs
This seems to be something missed some time ago as the original annotation for this 'use' was only feature debug. However this broke builds using that feature on Windows for a while.
This change uses guards both for the feature and also wasm/windows specific targets/environments.
These guards are the same as are currently in use for Windows/wasm in [parser.rs](https://github.com/kbknapp/clap-rs/blob/dc7ae65fb784dc355d56f09554f1216b22755c3e/src/app/parser.rs#L659)
closes #1270 and is done in response to Drops-of-Diamond/diamond_drops#59
fyi: @jamesray1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1271)
=> Include guards around os-specific string elements.

.travis.yml, src/args/arg_matches.rs
It seems like an oversight that this was omitted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1301)
=> fix(OsValues): Add `ExactSizeIterator` implementation

README.md
Even though github redirects to the correct url, it is better to mention the correct one :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1310)
=> Fix assert_cli url

src/args/arg_matches.rs
Fixes #1286 and pre-emptively derives `Debug` for `OsValues` and `Indices` as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1314)
=> imp(arg_matches.rs): add Debug implementations

examples/04_using_matches.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1319)
=> fix typo in example 04_using_matches.rs

src/app/parser.rs, src/suggestions.rs, tests/subcommands.rs
Let's say I have a CLI app like this: 
```
foo bar --baz
foo bam --baz
```
And a user invokes it as: `foo --baz bar`
We would currently suggest something like `"Did you mean to put '--baz' after the subcommand 'bam'"`, even though the user clearly didn't show the intent to invoke `bam`, but wanted to invoke `bar`.
This PR fixes this by reading the entire argument line and checking for potential occurences of all subcommands. Of course this is super fuzzy because we have no idea what is supposed to be a value of an option, and what is part of the subcommand, but it's slightly better than just taking the first subcommand that happens to have the option.
=> fix(suggestions): Dont mention unused subcommands

src/app/mod.rs
If you have a global option, and a subcommand, print_long_help would panic
with "Non-unique argument name" error.
=> Fix print_long_help with subcommands and global option.

README.md
This PR changes the link of the license badge svg in the `README.md` to use `https` to prevent mixed content warning in browser on external sites like [crates.io](https://crates.io/crates/clap).
=> docs(README.md): use https for all links

src/args/arg.rs, tests/app.yml
There's a missing of setting [case_insensitive](https://github.com/clap-rs/clap/commit/27ecd0d76b331d36d7e1672d20f5a0b6511e3f12) in YAML.
=> Adding case_insensitive to yaml parsing

src/macros.rs
I found this usage example confusing because `matches` was actually an `App`
=> Fix clap_app! usage example

.travis.yml, CHANGELOG.md, README.md, src/macros.rs
Resolves #1329, using the `$crate::` keyword that was [stabilized with Rust 1.30.0](https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html#local-helper-macros).
**NOTE: This should be merged on or after the day of the Rust 1.32** (probably 2019-01-21, 6 weeks after 1.31.0 released) release in order to maintain the `supports($LATEST - 2)` minimum Rust compiler policy.
=> Use `$crate` prepend to make importing the `_clap_count_exprs` macro unnecessary

Cargo.toml, src/args/arg.rs, src/args/group.rs, src/lib.rs
Reverts clap-rs/clap#1415
I merged this PR yesterday, not fully aware of how the public API would be changed.
Committing to this change would _require_ us to release a `clap 3.0` for it which seems very unreasonable.
After merging the idea was to re-work the function signatures to preserve the `clap 2.0` API while bumping to a new yaml version. This doesn't seem to be possible though because `arg_yaml.as_hash()` now hands out ownership of a tree, instead of just borrowing it.
The only reasonable choice at this time is to revert this PR.
This is not to say that `clap` should depend on code that has known security vulnerabilities, small as they might be.
Because of this I feel it would be more appropriate to try to fix the recursion issue on the `0.3` branch of `yaml_rust` instead of …
=> Revert "Upgrading yaml-rust to 0.4.2"

Cargo.toml, src/app/parser.rs, src/app/settings.rs, src/args/settings.rs, src/lib.rs, src/macros.rs
The only real use of bitflags was to save a tiny bit of memory. It isn't
exposed externally and we can just use a flag enumeration combined with
a HashSet to replace it. Because of this, let's not subject this
dependency to all projects which depend on clap.
=> Remove bitflags dependency

Cargo.toml, src/app/parser.rs, src/app/settings.rs, src/args/settings.rs, src/lib.rs, src/macros.rs
=> Revert "Remove bitflags dependency"

src/macros.rs, tests/macros.rs
I discovered that `default_value_if` cannot be used inside a `clap_app!` macro. The root cause was a bad pattern which did not handle comma-separated arguments. It was probably not spotted before because almost all `Arg` methods take zero or one argument and thus don't need a comma.
This pull request contains a fix for this bug, an extra pattern to handle the unusual but valid case of a trailing comma in the parameters (which can sometimes be inserted by rustfmt), and some tests.
=> fix(macros): fixes broken pattern

.travis.yml
The pinned nightly doesn't make as much sense anymore since clippy is
part of the build system. At some point we'll add clippy back into our
travis workflow, but for now I'm OK without clippy being run on every
PR.
=> chore: removes pinned nightly

src/fmt.rs
Currently, `AppSettings::ColorAlways` doesn't do anything (see #1400). This is because the requested colorizer is changed to `ColorWhen::Never` if `TERM=dumb` or the destination stream is not a TTY.
https://github.com/clap-rs/clap/blob/47edd1c1e686fd679f14915e00cda07ddcd313c4/src/fmt.rs#L65-L69
This pull request changes the behavior for `ColorAlways` so that it ignores `atty::is()` and `TERM=dumb`.
=> fix(src/fmt.rs): Respect ColorAlways

src/macros.rs
It should be `a, b, c` instead of `a ,b ,c`.
=> fix(arg_enum!): Fix comma position for valid values.

src/app/parser.rs, tests/app_settings.rs
I am classifying this as a bugfix even though it is technically breaking - but I think the old behaviour was not sensibleand it seems unlikely anyone was relying on it. 
Basically - setting both `AppSettings::SubcommandRequired` (or `SubcommandRequiredElseHelp`) and `AppSettings::AllowExternalSubcommands` has unintuitive behaviour.
Before this fix, with both `SubcommandRequired` and `AllowExternalSubcommands` set, if any external subcommand is provided, clap prints usage and exits - but really clap should treat an external subcommand as normal and allow the calling code to handle it.
=> Fix interaction between AllowExternalSubcommands and SubcommandRequired

src/app/parser.rs, tests/groups.rs
In debug mode, assert that all arguments in a subcommand's required ArgGroup exist when printing the subcommand's help message. The previous behavior was an expectation failure with the generic INTERNAL_ERROR_MSG.
See-also: 7ad123e2c02577 (introduced relevant assertion)
=> fix: add debug assertion for missing args in subcommand ArgGroup

tests/global_args.rs
This function only tests that the program does not panic, so the result need not be used.
(Silences three warnings during compilation.)
=> tests(global_args.rs): silence unused_must_use

src/completions/bash.rs, tests/completions.rs
The current Bash completions don't quote `$cur`, which causes a problem when attempting to complete a word which contains whitespace:
```console
$ rg "- foo"<tab>
-0
-a
-A
--after-context
...
```
The bug: the word `- foo` is expanded into the words `-` and `foo`, which are passed separately to `compgen`; all words except the first (`-`) are then silently discarded, and the completions generated are based solely on the `-`.
Quoting `$cur` ensures that the completions are based on the word as a whole.
=> Improve quoting in Bash completions

src/app/parser.rs, src/app/settings.rs
This commit adds an `AppSettings::DisableHelpFlags` variant, which disables the generation of the `-h`/`--help` flags similarly to how `AppSettings::DisableVersion` works.
My original use case for this (and `AppSettings::DisableVersion`) is to use `clap` to parse a "command line" of purely subcomands in a chat client, and having `/-h` or `/--help` (or `/-V`) be valid commands is a little strange.
=>  setting(DisableHelpFlags): disable the automatic generation of the -h/--help flags

Cargo.toml
ran the tests, seems fine i guess since there were no major breaking changes between v0.10 and v0.11
=> chore: bump the version for textwrap crate from 0.10 to 0.11

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, benches/03_complex.rs, examples/17_yaml.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/mod.rs, src/build/arg/settings.rs, src/build/arg_group.rs, src/macros.rs, src/mkeymap.rs, src/output/help.rs, src/parse/features/suggestions.rs, src/parse/matches/arg_matches.rs, src/parse/matches/subcommand.rs, src/parse/parser.rs, src/util/osstringext.rs, tests/app.yml, tests/app_2space.yml, tests/possible_values.rs, tests/propagate_globals.rs, tests/yaml.rs
This fixes v3-master to pass travis and appveyor tests. To do that, it:
* bumps the minimum version to rust 1.33.0
* fixes compiling on windows.
* Removes unused `App::contains_long`
* Removes `std::ascii::AsciiExt` (deprecated in 1.26)
* Replaces `trim_left_matches` with `trim_start_matches` (added in 1.30)
* Adds `dyn` (added in 1.27)
* Removes unused `mkeymap::KeyType::{is_short,is_long}`
* Cleans up unused imports
* Fixes `--features yaml`
* Removes deprecated features (and eliminates the last of the warnings).
=> Fix building v3-master

src/mkeymap.rs, tests/groups.rs, tests/help.rs, tests/multiple_values.rs, tests/positionals.rs, tests/unique_args.rs
This PR does several things:
1. Adds a regression test for #1487 which appears to have been fixed in v3.
2. Allows `cargo test --release` to pass by omitting tests that require debug_assertions
3. Cleans up tests which use `#[should_panic]` by including an expected panic message, and in a few cases removing code from the test that was not necessary to make the test clearer.
The `non_existing_args` test appears to have regressed from v2 to v3. The result of this test used to be a friendly message letting the programmer know they made a mistake, however now it states this is an internal error and directs the programmer/user to file a bug (very incorrect). I have not looked into how to fix this. For now, this test expects "internal error" to get it to pass.
Also, there is a test in …
=> Fixup tests

src/parse/errors.rs, src/parse/parser.rs, tests/opts.rs, tests/subcommands.rs
Addresses issue #1284
Outputs a suggestion to try as pattern argument whenever an unknown argument is reached. If we'd like to limit those situations, I need more details.
I changed the `unknown_argument` function to take an `Option<String>` rather than a `str` reference and then comparing to a magic string value. Let me know If there is a good reason not to do this.
=> Pattern arg suggestion

README.md
`assert_cli` [is deprecated](https://github.com/assert-rs/assert_cli). This PR adds a link to `assert_cmd`, which is it's successor.
=> Rename assert_cli to assert_cmd

.travis.yml
Some Travis builds are errored because of caches. `cache: cargo` can be the big cache size so I attempt to reduce it.
=> chore: fix cache issue on Travis

src/macros.rs
Deprecated since 1.38.0.
Closes #1552.
=> Replace ONCE_INIT with Once::new()

src/macros.rs
ONCE_INIT is effectively an alias of Once::new(), but will be depriciated as of rust 1.38.0. 
Once::new() has been stable since 1.2.0, well before the current staetd release version in the README of 1.30.0.
This change silences the warnings in nightly builds when using crate_authors!().
Updated to v3-master per discussion on #1521
=> use std::sync::Once::new() rather than ONCE_INIT

README.md
Just a little thing I noticed, the example should now be correct.
=> Fix opts variable name in README.md

examples/04_using_matches.rs
Comments in 04_using_matches.rs list the config arg
as an optional arg. However, -c --config is currently
a flag arg. This commit sets takes_value to true on
the config arg to make it an "option" argument.
=> examples: Change flag arg to option arg

src/build/arg/mod.rs, src/output/help.rs, src/parse/parser.rs, tests/default_vals.rs
This will (someday) fix #1002 
I'm taking baby steps here. I have started by adding a `default_vals` field to `Arg`
Next steps:
=> adds Arg::default_values

README.md
Should this be fixed or did I get something wrong?
- `App::from_yaml` to `App::from`
- plus various whitespaces my `vim` just auto-fixed
=> Fix yaml docs

src/macros.rs
The lack of qualification caused odd errors such as:
```
use clap;
let foo = clap::value_t!(matches.value_of("foo"),i u32).unwrap(); # OK
lot bar = clap::value_t!(matches, "bar", u32).unwrap(); # Compile fail
```
but
```
use clap::value_t;
let foo = value_t!(matches.value_of("foo"),i u32).unwrap(); # OK
lot bar = value_t!(matches, "bar", u32).unwrap(); # OK
```
=> Qualify all names in bodies of exported macros with $crate::

Cargo.toml
This is the same as #1531 but done against the master branch.
=> Upgraded ansi_term dependency

src/macros.rs
This bit of bespoke unsafe code can be replaced with a standard library function, [`Box::leak()`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak). It's been available since Rust 1.26 so there is no MSRV concern.
Thanks to TyPR124 and Lokathor for pointing this out.
=> Drop unnecessary `unsafe`

README.md
The first example doesn't compile. The Test structure is missing a `struct` statement, and the `.config` field exists as `.file`. Looking at the flag fields, `config` seems like the expected field name.
Using 
```
[dependencies]
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"] }
```
Signed-Off-By: Matthew Fisher <matt.fisher@microsoft.com>
=> fix(README): fix compiler errors for first example

src/build/arg/mod.rs, tests/multiple_occurrences.rs
The example code.
~~~rust
use clap::{App, Arg};
fn main() {
let matches = App::new("My Super Program")
.arg(
Arg::with_name("verbose")
.help("Sets the level of verbosity")
.short('v')
.long("verbose")
.takes_value(false)
.multiple_occurrences(true)
.env("VERBOSE"),
)
.get_matches();
match matches.occurrences_of("verbose") {
0 => println!("0 No verbose info"),
1 => println!("1 Some verbose info"),
2 => println!("2 Tons of verbose info"),
3 | _ => println!("3 >= Don't be crazy"),
}
}
~~~
It code use multiple_occurrences with env.
But it do not work.
`env` method set require take value.
It result see under.
~~~console
% cargo run -- -v
Finished dev [unoptimized + debuginfo] target(s) in 0.01s
Running `target/debug/foo -v`
error: The argument '--verbose <verbose>...' requires a value but none …
=> fixed: failed of multiple_occurrences with env

README.md
As outlined in https://github.com/clap-rs/clap/issues/1619 I did not understand why the `SUBCOMMANDS` section of `help` would not print a String `/// A subcommand for controlling testing` for the `Test` subcommand.
This PR updates the README to hopefully make this clearer.
The only change is adding a doc line:
```rust
#[derive(Clap)]
enum SubCommand {
/// A help message for the Test subcommand
Test(Test),
}
```
=> Clarify documentation usage as help text for subcommands

src/output/help.rs, src/parse/validator.rs
This gets rid of an unsafe block which is not necessary and only used
when building in debug mode.
=> output: get rid of an unsafe block

Cargo.toml, src/build/app/mod.rs
=> Revert " imp: Add exitcode::USAGE exit code as suggested in #1327"

Cargo.toml, clap_derive/Cargo.toml, clap_derive/README.md, clap_generate/Cargo.toml, clap_generate/README.md, clap_generate/examples/bash_completion.rs, clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/mod.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs, clap_generate/src/lib.rs, clap_generate/src/macros.rs, clap_generate/tests/completions.rs, clap_generate/tests/version-numbers.rs, src/lib.rs, src/macros.rs, src/mkeymap.rs
I have copied the code from [clap_generate]( https://github.com/clap-rs/clap_generate) and refactored the structure a bit.
This new structure will allow people to write their own generators using our `Generator` trait which will contain some helpers (Still working on polishing them).
=> Refactor clap_generate

src/output/help.rs, tests/help.rs
I was going through the clap documentation and was under the impression that calling `help()` would call `about()` and `long_help()` would call `long_about()`, but I've actually discovered this not to be the case. Instead, the `long_about()` was always shown when it existed, rendering the output (in the about section) of programs called with `-h` and `--help` identical. Issue #1472 shows this and that is fixed here.
Note this doesn't remove the ability to use the same about in both cases: if `long_about()` is unset, then `about()` is used in both cases.
I've changed the implementation here to use `is_some()` and `unwrap()` as opposed to `if let` because it ultimately allows for less repetitive code. Ideally, I'd be able to pair `if let` with a secondary condition (namely `self.use_long`), …
=> Use about() with help() and long_about() with long_help()

src/macros.rs
I'm using `deny(missing_docs)` on my whole crate but I get warnings of `arg_enum` because it adds the function `variants()` which has no doc. This will fix the warning.
=> Allow missing docs on arg_enum

.travis.yml, Cargo.toml, benches/01_default.rs, benches/02_simple.rs, benches/03_complex.rs, benches/04_new_help.rs, benches/05_ripgrep.rs, benches/06_rustup.rs
=> Fix benchmarks

src/build/app/mod.rs, src/lib.rs, src/macros.rs, src/parse/mod.rs, src/parse/parser.rs, src/parse/validator.rs, tests/subcommands.rs
Closes #1603 
I tried several different ways of implementing the above requested feature but failed because they always ended up trying to manipulate the input which is a no-go because it was a plain `Iterator`. And then the #1693 was filed, and reading it made me think that maybe we should allow input to be changed. So, I extracted it out and made it do the replacing.
=> Allow replacing input on the fly

.travis.yml
Closes #1699 
Benchmarking is now good.
=> Allow bench to fail in travis to reduce CI time

src/build/app/settings.rs, src/build/arg/mod.rs, src/parse/parser.rs, tests/subcommands.rs
https://github.com/clap-rs/clap/blob/b86bf25c189e0b57ebe7f21df9c772295ace08cb/src/parse/parser.rs#L468-L468
This line of comment says that only positional arguments follow `--`. So there is no legit args like `-- subcommand`. So we shouldn't emit subcommand mismatching error with `--`. Is that correct? I'm not pretty sure:-/
Closes #1722 
BTW, this commit fixes two typo.
=> Fix `-- subcommand` error

src/parse/validator.rs, tests/arg_conflicts.rs
=> Fixed #1622

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, README.md
=> Advertise gitter chat

src/macros.rs
When using `arg_enum`  and the user mistypes the parameter, the valid values are printed like this:
`valid values: A ,B ,C`
Note the position of the commas; this patch fixes their position to get placed right after the item:
`valid values: A, B, C`
=> style: fix comma placement for valid values when using arg_enum

src/build/app/mod.rs, tests/subcommands.rs
Required for display_order and DeriveDisplay to work properly for subcommands. This fix lets you change the subcommand order correctly.
Add a unit test that checks that DeriveDisplay works correctly.
=> set the default disp_ord of App to 999. 

README.md, src/lib.rs
Update the documentation regarding which features are enabled by default. I also made the formatting in `README.md` more consistent, and made the documentation in `src/lib.rs` match what is written in `README.md`.
Keeping these two files in sync appears to be error prone. I suggest using something like [Tagref](https://github.com/stepchowfun/tagref) to have these files point to each other so contributors are reminded to update both together. (This PR does not set that up, however.)
@CreepySkeleton @Dylan-DPC
Closes #1430
=> Update the documentation regarding which features are enabled by default

.azure-pipelines.yml, .github/workflows/benchmark.yml, .github/workflows/linux.yml, .travis.yml, CONTRIBUTING.md, Cargo.toml, bors.toml, clap_derive/Cargo.toml, clap_generate/Cargo.toml
=> Fixing coverage test

.github/workflows/linux.yml
push(master) is not run because they would be run on staging anyway.
pull_request(staging, trying) are not run because pull requests shouldn't be made to them
=> Don't run actions on some events

clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs, clap_generate/src/lib.rs, clap_generate/src/macros.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/macros.rs, src/output/help.rs, src/parse/parser.rs, tests/macros.rs
That is my attempt of removing the `pub #[doc(hidden)]` blasphemy. It is not ready yet - far from being ready, in fact. I'm just publishing it to get some feedback from @TeXitoi and @pksunkara .
=> WIP: get rig of pub doc(hidden)

.travis.yml
They aren't working anyway and they're also ruining our CI
=> Exclude clap_derive from coverage

.azure-pipelines.yml, .travis.yml, src/build/usage_parser.rs, src/output/help.rs, tests/help.rs, tests/utils.rs
=> Remove {n} support

src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/settings.rs, src/output/fmt.rs, src/parse/arg_matcher.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs, src/parse/matches/matched_arg.rs, src/parse/matches/subcommand.rs, src/parse/mod.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/mod.rs, src/util/osstringext.rs
The infestation has been contained, majority of the patients has been cured, and those who weren't fail into one of these groups:
* Hidden `AppSettings` variants that are not exposed to user but used by clap itself. I'd prefer extracting them into separate enum, but this is not priority right now.
* Macros. I guess this explains it. Maybe I'll see into converting them into functions, but it's not an immediate concern.
* Such methods as `App::_build` and friends. The basically exist because clap has no distinction between "builder" and "built app" at type system level. I'll be looking into it too.
=> Remove almost all #[doc(hidden)]

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/build/usage_parser.rs, src/macros.rs, src/mkeymap.rs, src/output/usage.rs, src/parse/arg_matcher.rs, src/parse/matches/arg_matches.rs, src/parse/matches/subcommand.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/fnv.rs, src/util/graph.rs, src/util/id.rs, src/util/mod.rs
Talk is cheap, so let me cut to the chase:
Before;
```
DEBUG:clap:ArgMatcher::inc_occurrence_of: arg=10706354686124900129
DEBUG:clap:ArgMatcher::inc_occurrence_of: first instance
DEBUG:clap:Parser::groups_for_arg: name=10706354686124900129
DEBUG:clap:Parser::parse_opt: More arg vals required...
DEBUG:clap:Parser:get_matches_with: After parse_long_arg Opt(10706354686124900129)
DEBUG:clap:Parser::get_matches_with: Begin parsing '"foo"' ([102, 111, 111])
DEBUG:clap:Parser::is_new_arg:"foo":Opt(10706354686124900129)
DEBUG:clap:Parser::is_new_arg: arg_allows_tac=false
DEBUG:clap:Parser::is_new_arg: probably value
DEBUG:clap:Parser::is_new_arg: starts_new_arg=false
DEBUG:clap:Parser::add_val_to_arg; arg=output, val="foo"
DEBUG:clap:Parser::add_val_to_arg; trailing_vals=false, …
```
=> Make debug output show names of args along with hashes

src/mkeymap.rs, src/parse/arg_matcher.rs, src/parse/features/mod.rs, src/parse/features/suggestions.rs, src/parse/matches/arg_matches.rs, src/parse/matches/matched_arg.rs, src/parse/matches/mod.rs, src/parse/mod.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/fnv.rs, src/util/graph.rs, src/util/id.rs, src/util/map.rs, src/util/mod.rs, src/util/strext.rs
This PR ensures that `pub item` from now on actually means *public* and not "used somewhere else in this crate, but not public". I did my best to seek for such items, but I might have missed something. Please let me know if you spot another one.
=> Handle publicity properly

Cargo.toml, clap_derive/tests/custom-string-parsers.rs, clap_derive/tests/non_literal_attributes.rs, clap_derive/tests/utils.rs, clap_generate/src/generators/shells/bash.rs, src/build/app/mod.rs, src/macros.rs, src/output/fmt.rs, src/output/help.rs, src/output/mod.rs, src/parse/errors.rs, src/parse/features/suggestions.rs, src/parse/matches/arg_matches.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/mod.rs, src/util/termcolor.rs, tests/app_from_crate.rs, tests/cargo.rs, tests/multiple_occurrences.rs, tests/opts.rs, tests/possible_values.rs, tests/subcommands.rs, tests/utils.rs, tests/version.rs
=> Finished color refactor

src/output/help.rs, tests/help.rs
Don't print the 'OPTIONS' section of the short help message when all option-taking arguments are set with `.hidden_short_help(true)`.
Closes #1364
=> fix: Don't print 'OPTIONS' when all options are hidden for short help

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs
As we all [know](https://stackoverflow.com/a/37639889), rustc cannot inline functions from extern crates unless they are either generic (subject to monomorphization) or explicitly marked as `#[inline]`. Or unless the programmer enabled LTO which is slooow.
This situation is sad because clap would actually benefit from inlining: a great deal of our API consists of very short functions.
Functions that ARE NOT marked as `#[inline]`:
* Generic functions; rustc can handle them on its own.
* Functions containing loops. It rarely makes much sense to inline them, but I may be wrong here.
* Functions containing more or less complex logic.
Everything else is inlined. `cargo bloat` shows the resulted binary has been shrunken a bit.
=> Allow rustc inline small functions across crates (-5.5 kB)

src/build/arg/mod.rs, src/parse/parser.rs, tests/groups.rs
Closes #1794
The bug was fairly easy to diagnose but extremely hard to fix. I managed a small not-too-hacky hack, but it comes at cost. I believe we can pay it. See the comment in the diff for the explanation.
=> Fix positional args in groups (#1794)

src/build/arg/mod.rs, src/util/id.rs
Closes #1359
We need to do something to make sure this won't happen again with another method. I'm not even sure we aren't missing anything else
=> Add hide_default_values to yaml

src/parse/arg_matcher.rs, src/parse/matches/matched_arg.rs, src/parse/matches/mod.rs, src/parse/mod.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/termcolor.rs, tests/conflicts.rs
Closes #1605 
It also fixes a bug in the fallback implementation of `termcolor`. I got to know about it only because I accidentally did `cargo clippy --no-default-features`. @pksunkara You may want to take a look at the second commit and check the docs for [`std::io::Write`](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write) method.
=>  Default values trigger conflicts no more

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/usage_parser.rs, src/output/help.rs
Turns out we don't need a `HelpBase` I was talking about. We can keep the `Arg::help` marked as deprecated instead of removing it.
=> Rename some internal stuff

src/build/arg/mod.rs
=> Allow usage of deprecated arg::help in yaml

benches/05_ripgrep.rs, clap_derive/src/derives/into_app.rs, examples/15_custom_validator.rs, examples/18_builder_macro.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/parse/errors.rs, src/parse/validator.rs, tests/validators.rs
=> Make validator take &str instead of String

src/build/app/mod.rs
For long help, there's still `print_long_help()`.
Closes #1889.
=> fix(build/app): don't use long help for `print_help()

Cargo.toml, src/parse/parser.rs, src/util/argstr.rs
This filter can now catch all edge cases, instead of just UTF-8 prefixes. It uses a new function I added to os_str_bytes that can take advantage of some internal assumptions with minimal overhead.
I don't think the filter was being used for anything that would make the correctness matter, but it sets a good precedent. Plus, it removes the last use of `ArgStr::as_raw_bytes` outside of debugging code.
=> Handle more edge cases for an `ArgStr` prefix

README.md
Hi,
I found a broken link in README.md.
Since this is a very minor issue due to a wrong path of CONTRIBUTING.md, I have created a PR here directly without reporting an issue.
Could you please find and check it?
Many thanks,
noritada
=> docs(README.md): fix a broken link to CONTRIBUTING.md

tests/utf16.rs
These are similar to the tests backported to the 2.x branch in
https://github.com/clap-rs/clap/pull/1907. These are more comprehensive,
because the OsStr splitting methods are more robust now.
=> add tests for invalid UTF-16 on Windows

src/osstringext.rs, tests/utf16.rs
Previously, OsStr::starts_with() would panic on Windows if the OsStr
contained any invalid Unicode. Because this method is in the critical
path for parsing command line arguments, Clap up to v2.33.0 on Windows
panics on non-Unicode filenames, even when the application specifically
requests OsString to account for this case. As a workaround, this commit
adds a custom implementation of OsStr::starts_with() for Windows that
doesn't rely on OsStr::as_bytes().
With this change, examples like the following can parse successfully.
Here "X" represents invalid Unicode:
clap.exe X
clap.exe --some-arg X
However, examples like these will still panic:
clap.exe --some-arg=X
clap.exe -sX
These still panic, because they require string splitting operations like
OsStr::split_at_byte() and …
=> prevent some panics when parsing invalid Unicode on Windows

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg/tests.rs, src/build/arg_group.rs, src/build/usage_parser.rs, src/macros.rs, src/mkeymap.rs, src/output/help.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/graph.rs
Our conversation about `Option<Vec>` ergonomics got me thinking: we use this pattern in clap all the time, but there isn't a single place where `None` and `Some([])` mean different things. If fact, reducing these `Option<Vec>` to `Vec` can simplify our code considerably. 
This PR replaces all internal `Option<Vec>` occurrences with plain `Vec`. -300 LOC, yay!
=> Option vec to vec

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/macros.rs
Hi! This is my first PR to the project. I've used `clap` on projects before and wanted to give a little something back!
I'm still fairly new to Rust, so I'm hoping this change is what's needed. I also implemented `From<Yaml>` on both `Arg` and `ArgGroup` since I noticed the group was using the old way too.
I'm sure I screwed up on something though, so I'm looking forward to any feedback :smile: 
Closes #1922
=> refactor: Implement From<Yaml> on Arg and ArgGroup

src/output/usage.rs, src/parse/validator.rs, tests/require.rs
correctly filter the suggestion arguments returned by the missing_required_argument error.
- a simple argument has been supplied, don't include it
- if a required group has been satisfied, don't include it
- add test for these cases.
=> fix(errors): incorrect missing argument error messages

src/parse/errors.rs, tests/validators.rs
also add a basic test of a failed validation
=> fix(errors): ensure that validation failure error message includes a newline

clap.schema.json
Closes #1933 
What is not implemented:
* Methods that take more than one argument (`requires_if` and the like). 
* It doesn't check that a top-level `name` key is present due to [the limitation](https://stackoverflow.com/questions/61854772/how-to-use-ref-in-json-schema-properly/61855995#61855995) of JSON-schema.
@strega-nil Could you please check if this works?
=> Add JSON scheme spec

src/build/app/mod.rs, tests/help.rs
None of the other methods that move self have the `set_` prefix
=> Rename App::set_term_width to term_width

src/build/arg/mod.rs, src/parse/parser.rs, tests/default_missing_vals.rs
v3-compatible version of #1468.
Re-opened from #1507 (after upstream branch rename auto-close).
> RFC/WIP ~ this PR is a quick proof-of-concept, inviting commentary before being updated and fleshed out (documentation, tests, etc).
>
> For an OPTION taking optional values (ie, .min_values(0).require_equals(true)), currently any time that option is encountered multiple times, occurs is incremented, but no entry is made into the indices and vals arrays for options with no/missing value. "None" would seem like a good entry but the vals array contains just that, values, not Options, so that would break compatibility without any great upside. However, adding a default for missing values can be done without breaking anything else...
>
> This PR adds support to supply a value for the …
=> add 'default_missing_value' configuration option

src/parse/errors.rs
changes
```
error: The argument '<number>...' requires at least 2values, but only 1 was provided
```
to
```
error: The argument '<ICAO>...' requires at least 2 values, but only 1 was provided
```
Noticed this when testing some other library.
=> fixed spacing in to few argument error messages

src/build/app/mod.rs, src/output/help.rs
=> Limit text wrapping to 100 symbols by default

clap_derive/src/utils/spanned.rs, src/build/app/mod.rs
Fixes for the assertion parameters of `build::App::two_args_of()`for name conflicts described in Issue #1965 
`Closes #1965 `
=> fix: Corrected assertion arguments

src/macros.rs
Code cleanup. Closes #1963
Removed unused macro `_clap_count_exprs`.
The macro isn't used since the `arg_enum` macro was removed.
I don't think any additional tests are needed? 
`cargo fmt & clippy` are also satisfied.
=> refactor: removed clap_count_exprs macro

src/app/mod.rs, src/lib.rs
**ATTENTION** This PR is against `v2-master`
This PR fixes links in 2.33 docs so they point to 2.33 examples, not master examples. Cna we have a release with this so it no longer confusers people?
=> Make 2.33 examples links point to 2.33 branch, not master

README.md
=> docs(README.md): Fixes typo at line 413

justfile
This fixes usage of `just lint` on my computer. Did the syntax of rustup change or something?
=> fix(justfile): rustup uses 'component add' instead of 'add component'

clap_derive/examples/basic.rs, clap_derive/examples/keyvalue.rs, clap_derive/src/attrs.rs, clap_derive/tests/argument_naming.rs, clap_derive/tests/basic.rs, clap_derive/tests/custom-string-parsers.rs, clap_derive/tests/explicit_name_no_renaming.rs, clap_derive/tests/non_literal_attributes.rs
This PR switches the Arg::Short macro to take a character instead of a string. It removes the hacky code in the Method to_token method and implements the logic for Short when parsing the clap derive arguments.
Closes #1815
=> fix: Use character instead of string for Arg::Short

README.md
The other examples have `verbosity` as a default arg, and `debug` as a `test` subcommand arg. The macro example has these two switched up -- this corrects that.
=> docs: switch debug and verbosity args in macro example

clap_derive/src/utils/ty.rs, clap_derive/tests/nested.rs
Due to macro expansions, a `syn` type may be wrapped in multiple
'layers' of `syn::Type::Group`. However, `clap_derive` currently does
not check for `syn::Type::Group`, which will cause an `Option` (along
with other matched types) to fail to be detected when it results from a
macro expansion.
This commit 'unwraps' outer type groups before checking the
user-provided types against well-known types. Currently, these groups
may not be present due to a rustc bug (rust-lang/rust#43081)
However, once https://github.com/rust-lang/rust/pull/73084 is merged,
these groups will be present in more cases. This commit makes `clap`
compatible with both older and newer versions of rustc.
=> fix(clap_derive): Unwrap `syn::TypeGroup` when checking field types

Cargo.toml, src/output/help.rs
term_size is not maintained and we don't want to.
=> Move to terminal_size dep after the recent textwrap upgrade

src/build/app/mod.rs, src/output/help.rs, src/output/usage.rs, tests/subcommands.rs
This PR lets you change the "SUBCOMMAND" placeholder in usage text to text of your choosing.
Closes #1597.
There are a few questions I have about how this should be implemented:
- In the full help text, there is a section labeled "SUBCOMMANDS".
- Should this also change?
- Should there be a separate option for that?
- How's the naming? "subcommand_placeholder" is long but descriptive -- to me, at least.
- The current implementation does repeat some logic a bit, I could factor that into a private helper on App if you like.
- I suspect the documentation I wrote could use some work.
- ... I just read the contribution guidelines, I can redo the commit messages before this gets merged.
=> Custom subcommand placeholders

src/macros.rs, tests/macros.rs
This PR adds the ability to set global settings with `@global $setting` just like `@setting`.
```rust
let app = clap_app!(claptest =>
(@global ColorNever)
(@global DisableVersion)
);
```
instead of
```rust
let app = clap_app!(claptest =>
(global_setting: AppSettings::ColorNever)
(global_setting: AppSettings::DisableVersion)
);
```
I also added the attributes to the basic macro test.
=> feat(macros): Add `@global $setting` to set global settings

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, FAQ.md, benches/03_complex.rs, clap_derive/examples/README.md, clap_derive/examples/from_crate.rs, clap_generate/src/generators/shells/zsh.rs, examples/05_flag_args.rs, examples/06_positional_args.rs, examples/07_option_args.rs, examples/08_subcommands.rs, examples/17_yaml.rs, examples/20_subcommands.rs, examples/23_flag_subcommands_pacman.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/mod.rs, src/output/help.rs, src/output/usage.rs, src/parse/matches/arg_matches.rs, src/parse/parser.rs, src/parse/validator.rs, tests/app_settings.rs, tests/fixtures/app.yml, tests/flag_subcommands.rs, tests/help.rs, tests/macros.rs, tests/posix_compatible.rs, tests/utils.rs
Most errors detected and fixed with Topy (https://github.com/intgr/topy), all verified by hand.
=> Fix various typos in docs & code

tests/macros.rs, tests/validators.rs
The PR adds tests for builder macro with validators and `std::str::FromStr` as validator.
=> tests(validators): Add tests for `clap_app!` macro and `FromStr` trait validator

clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/build/usage_parser.rs, src/derive.rs, src/mkeymap.rs, src/output/fmt.rs, src/output/help.rs, src/output/usage.rs, src/parse/matches/arg_matches.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/argstr.rs
Extracted from https://github.com/clap-rs/clap/pull/1998
=> Make lifetimes descriptive

src/parse/errors.rs
Collect the missing required arguments for `Error::info`.
```rust
use clap::clap_app;
fn main() {
let app = clap_app!(prog =>
(@arg arg1: +required)
(@arg arg2: -o +required)
);
let m = app.try_get_matches();
dbg!(m);
}
```
```
[src/prog.rs:9] m = Err(
Error {
cause: "The following required arguments were not provided:\n    <arg1>\n    -o",
message: error: The following required arguments were not provided:
<arg1>
-o
USAGE:
prog [FLAGS] <arg1> -o
For more information try --help
,
kind: MissingRequiredArgument,
info: Some(
[
"<arg1>",
"-o",
],
),
},
)
```
=> imp(errors): Provide the missing required arguments as info

clap_generate/src/generators/mod.rs, src/build/app/mod.rs, src/output/usage.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/argstr.rs, src/util/graph.rs
There are some sub-optimal uses of iterators. These commits make the code more concise and a tiny bit faster to compile.
=> Improve iterator use

clap_generate/examples/value_hints.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/zsh.rs, clap_generate/tests/completions.rs, clap_generate/tests/value_hints.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg/value_hint.rs, src/build/macros.rs, src/build/mod.rs, src/lib.rs, tests/fixtures/app.yaml, tests/yaml.rs
Adds new method/attribute `Arg::value_hint`, taking a `ValueHint` enum
as argument. The hint can denote accepted values, for example: paths,
usernames, hostnames, commands, etc.
This initial implementation supports hints for the zsh and fish
completion generators, support for other shells can be added later.
=> Add hinting of arg value types for zsh/fish completion

clap_derive/src/derives/from_arg_matches.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/dummies.rs, examples/16_app_settings.rs, examples/20_subcommands.rs, examples/23_flag_subcommands_pacman.rs, src/build/app/settings.rs, src/derive.rs, src/parse/matches/arg_matches.rs, tests/app_settings.rs
The question was raised in https://github.com/clap-rs/clap/discussions/2047. And indeed, having both the name and the matches wrapped in `Option` feels more fitting.
=> Change the ret tyte of Argmatches::subcommand

src/build/arg/mod.rs, src/output/help.rs, tests/help.rs
=> Add blank line between items in long help

src/build/app/debug_asserts.rs, src/build/app/mod.rs, src/build/app/tests.rs, src/build/arg/mod.rs, src/build/arg/tests.rs, src/build/arg_group.rs, src/output/help.rs, src/parse/matches/arg_matches.rs, src/parse/validator.rs, tests/arg_aliases.rs, tests/arg_aliases_short.rs, tests/fixtures/app.yaml, tests/flag_subcommands.rs, tests/validators.rs
Also relaxes 'static restriction on validators.
Closes #1771
This PR also relaxes the `'static` restriction on the validator fn, thus allowing user to use proper closures that capture some context as validators. This should address (and potentially close) #572.
=> Relax some restrictions on validators

src/build/macros.rs, tests/fixtures/app.yaml, tests/yaml.rs
While working on another issue I was completely puzzled by the `yaml_opt_str!`, as it immediately starts with `$v.is_null()` and then uses `as_str()` on a `YAML::Null` value. While trying to get to the root of the issue, I've noticed that this bug will only manifest itself in `default_value_if` when compiled with `yaml` support.
I've added some integration tests for the YAML part and also noticed that `null` was misspelled in the fixture, which kept the bug hidden. If you don't apply `e20cc1c` from the set of commits, you'll notice that *all* `yaml` tests break down due to `[flag, null, some]`.
**Please note that this is my first non-documentation Rust pull request ever and I'm happy about any feedback and criticism.**
I wasn't sure about the commit message style, as the recent commits …
=> Fix YAML's default_value_if handling

src/build/app/mod.rs, src/output/help.rs, src/parse/parser.rs, tests/help.rs
This makes some changes to the template system:
- Template tags for optional items (like `{author}`) now expand to nothing when the value is unset instead of a default string (like `"unknown author"`).
- More template tags now emit line-wrapped output to match the behavior of `write_default_help`.
- Items with long variants now expand to the appropriate thing for `-h` vs `--help`.
- The now-obsolete `{long-about}` tag has been removed.
- A few new tags have been added.
These are externally-visible changes, but if this makes it into 3.0 that's probably reasonable?
Note that line-wrapping can have some odd edge cases since it does not account for preceding/trailing characters on the same line as the tag. This is already the case in `master`, but will affect some additional tags with this …
=> Use a template to produce the default help message

src/app/parser.rs, src/app/validator.rs, src/lib.rs, src/osstringext.rs
Because why not? MSRV is preserved.
I didn't try to fix clippy warnings because they are not that apparent.
=> Eradicate remaining warnings in v2

src/parse/validator.rs, tests/conflicts.rs
Closes #1464 
Saw the recent reddit post and thought I'd try my hand at this issue :smile: Please let me know your thoughts and concerns.
I added tests to ensure correct output whether required argument are applied or not, as well as to ensure more than one conflicting argument is removed from the usage if needed (`conflict_output_three_conflicting`)
I edited the `CONFLICT_ERR` and `CONFLICT_ERR_REV` static strings because they did not follow the convention that other tests were following, i.e. mention the conflicting parameters in the order in which they appear (e.g. `two_conflicting_arguments` or `three_conflicting_arguments`).
I'm especially curious to see if the output in this PR for three conflicting arguments is desired, or if tacking on the required arguments in the usage based on …
=> Issue 1464

tests/help.rs
Using `App::get_matches` from the integration tests meant that any CLI arguments passed to libtest would also be captured by clap, causing some of the tests to fail.
For example, running `cargo test --test help -- --nocapture` would result in several failed tests, even though `cargo test --test help` worked fine. This was very surprising/confusing.
This pull request makes the tests no longer implicitly rely on the value of `env::args_os()`, which means developers can now provide arguments to libtest without failures.
=> Do not capture args meant for libtest from the integration tests

src/output/help.rs, tests/help.rs, tests/hidden_args.rs
Closes #1094
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#1094: -h, --help generate trailing spaces](https://issuehunt.io/repos/31315121/issues/1094)
---
</details>
=> Don't print spaces in long help

clap_derive/src/lib.rs, clap_generate/src/lib.rs, src/lib.rs
This adds a `#![forbid(unsafe_code)]` to all the primary clap libraries.
Clap 3.0 has removed all unsafe code, and it should stay this way. Also makes it have a nice green in `cargo geiger` output.
=> Forbid all unsafe code.

src/util/graph.rs
Instead of `contains` and `unwrap` in case the element was found, simply try `position` with `unwrap_or_else`.
=> refactor: Avoid second traversal and unwrap

clap_derive/examples/env.rs
Updates the derive example handling environment variables to illustrate
the case where it contains a sensitive value which should not be
displayed on the help screen.
Closes https://github.com/clap-rs/clap/issues/2101
=> Update the env var example for derive

clap_generate/src/generators/shells/zsh.rs, clap_generate/tests/completions.rs, src/build/app/mod.rs
=> Allow for nested subcommands with ZSH generation.

examples/03_args.rs, examples/05_flag_args.rs, examples/06_positional_args.rs, examples/07_option_args.rs, examples/14_groups.rs, tests/examples.rs
This changeset was split off of #2084. It partially addresses #1652.
The sanity test currently just runs all examples with `--help`, asserting that the exit code is 0 and something is written to stdout. It could check other properties additionally/instead—let's follow up in comments.
=> Basic centralized sanity test for all examples

src/output/help.rs, tests/arg_aliases.rs, tests/arg_aliases_short.rs
Here I check for situation when there's no `about` available about the argument, but there're some `spec_vals` to be printed. If that's the case, We don't need the separator (" ") between about section and those values, so it should be omitted.
Closes #2040
=> fix: detect if space should be added before spec_vals

Cargo.toml, src/build/arg/mod.rs, src/build/arg/regex.rs, src/lib.rs, tests/fixtures/app_regex.yaml, tests/fixtures/app_regex_invalid.yaml, tests/yaml.rs
This draft introduces a new feature called `"regex"`. It adds a new function `validator_regex` to `Arg` and was inspired by the discussion in #1968. The name `validator_regex` was chosen instead of `regex_validator` to make sure that the developer keeps in mind that there may only be a single `Validator` on an `Arg`.
The feature can be used with YAML files, however there is no proper pattern in `clap_app!` (yet). The proposed solution differs from #1968 in some places:
- Since `validator_regex` doesn't use `&str` in its first argument, we cannot use `yaml_tuple2!`. That's a little bit unfortunate, but the resulting error messages should be slightly more helpful to the user.
- The function takes a `Regex` instead of a `&str` as argument to make sure that we have a valid regular expression …
=> Add new "regex" feature

examples/01b_quick_example.rs
Modified the `debug` option in example `examples/01b_quick_example.rs` to conform to the specification in the earlier comments:
```
//    - A debug flag
//        + Uses "-d" or "--debug"
//        + Allows multiple occurrences of such as "-dd" (for vary levels of debugging, as an example)
```
=> Modify debug option to conform to specification.

examples/01a_quick_example.rs
Fixed `debug` option in example `examples/01a_quick_example.rs` so that it follows the specification in the earlier comments:
```
//    - A debug flag
//        + Uses "-d" or "--debug"
//        + Allows multiple occurrences of such as "-dd" (for vary levels of debugging, as an example)
```
=> Make debug option in example 01a_quick_example follow specification.

src/build/app/mod.rs, tests/help.rs
I saw that https://github.com/clap-rs/clap/pull/2093 went stale so I decided to try to fix this issue since it was marked with the "Good First Issue" label.
Help about text is now customizable and recursively propagates to subcommands unless the subcommand defines its own help about text in which case that is used.
Closes #2080.
=> api(App): Adds help_about method to App.

src/parse/errors.rs, tests/flags.rs, tests/groups.rs, tests/opts.rs, tests/subcommands.rs
Closes #1284 BurntSushi/ripgrep#936
Related: #1744 #1943
The features disgussed in this issue was already implemented. However the error message emission introduced by #1514 is misleading.
The word `PATTERN` in the current error message comes from ripgrep-specific usage information, which is misleading in other applications. 
The error message should only be emitted when the argument looks like a flag(which is the only way the argument can be processed counterintuitively). 
This is also the first step on solving #1744 #1943.
=> Fix the error logic and error message for suggesting `--` before a flag

CONTRIBUTING.md, src/build/app/mod.rs, src/build/arg/mod.rs, src/derive.rs, src/mkeymap.rs, src/output/help.rs, src/parse/parser.rs, tests/multiple_values.rs
Some more fixes in addition to #2024 (594c535ba25b343cf52901aeb96ea246ffbdfde4)
* Some I noticed manually.
* Some were found by Topy (https://github.com/intgr/topy), either new
rules from Topy or new code in clap.
* `etc.` and `i.e.` rules were disabled during the last run.
=> Fix typos and grammar

src/output/help.rs, tests/help.rs, tests/hidden_args.rs
Closes #2059
Currently the sorting method is based on argument name. This PR introduces a new algo which sorts arguments in usage output based on each argument's short and long representation.
=> Sort options base on option's short and long representation

src/build/app/mod.rs, src/parse/parser.rs, tests/opts.rs
Also fixes more places where `get_opts_with_no_heading` is misused, i.e `has_opts`
Closes #2022
=> Fix parser skipping options without heading set

clap_derive/examples/keyvalue.rs, clap_derive/src/derives/into_app.rs, clap_derive/tests/custom-string-parsers.rs, src/build/arg/mod.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs, src/parse/parser.rs, src/parse/validator.rs
For review on whether it makes sense to fix #2151 
One issue with this is it still retains the `error:` prefix and duplicate printing of the underlying error when you use an error reporter. I took a look at what it would take to fix this and instead have `clap` use a small internal error reporter to print the error message for functions like `App::parse`, and it seems like that needs a codebase and test-wide refactor to not assume that `impl Display for Error` will be the same as what gets written to the terminal.
=> Attach validation error as Error::source

src/parse/parser.rs, tests/default_vals.rs, tests/opts.rs
This PR changes `default_value` so that it does not apply for an option when the user passes the flag without a corresponding value. This case is now handled by `default_missing_value`.
(See also my discussion question https://github.com/clap-rs/clap/discussions/2083 where I understood that this is the expected behaviour.)
Consider this sample program:
```
#[derive(Clap, Debug)]
struct Opts {
#[clap(long, default_value = "5")]
batch_size: usize
}
```
With the current master, I get the following results of execution:
```
cargo run                    // OK
batch_size = 5
cargo run -- --batch-size    // <---This should not succeed, as default_missing_value is not set
batch_size = 5
cargo run -- --batch-size 6  // OK
batch_size = 6
```
After this patch, everything works as expected:
```
cargo …
```
=> Don't use default value when option is passed

src/build/arg/mod.rs, src/build/arg/settings.rs, src/output/help.rs, tests/help.rs
This PR adds the option to hide the automatic env key (and/or value) section from the help text. This would be useful if the key is explained already and more explicitly in the defined help text.
This arose for the above reasons when adding env var parsing to bat, in https://github.com/sharkdp/bat/pull/1281.
=> Add option to hide env keys from help text

src/build/arg/mod.rs
Also update the docs to reflect that Arg.index shouldn't be
used with long or short
Closes #1330 
Let me know if I need to change something!
=> Add an assertion for positional args defining long or short

clap.schema.json, src/build/arg/mod.rs
Some options are missing in the `From<Yaml>` implementation for `Arg`, because the singular and plural version are merged into one via the `yaml_vec_or_str!()` macro. This PR adds a note warning about this, specifically in the `conflicts_with()` and `conflicts_with_all()` docs.
(I fixed a typo too)
=> Add `conflicts_with_all` note to docs

src/output/help.rs, tests/help.rs
Closes #2170
First commit and the third refactored the arg writing and subcomand writing without changing clap's behaviour. Which is needed because I think these code is a bit rotten(unnecessary side effects occurred in output functions).
Second commit introduces the help message wrap checking(refractoring above make proving the wrap checking's correctness a lot easier).
=> Consistently wrap help and subcommand messages(with refactoring)

CHANGELOG.md, benches/06_rustup.rs, clap_derive/examples/value_hints_derive.rs, clap_generate/examples/value_hints.rs, clap_generate/src/generators/mod.rs, clap_generate/tests/value_hints.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/app/tests.rs, src/parse/parser.rs, tests/help.rs, tests/macros.rs
I am wondering which is better, `DisableVersionFlagForSubcommands` or `DisableVersionForSubcommands`. Because if we ever have version subcommand, then we would want to disable even that for subcommands, so, thinking about the `Flag` in that name.
=> Help & Version settings

README.md
While reading the features available, it would be good to be informed that
colored help is available, this makes colored help more discoverable.
=> Mention colored help is not available by default

src/build/arg/mod.rs, src/parse/parser.rs, tests/env.rs
=> Make `Arg::env()` and `Arg::env_os()` `takes_value(false)` by default

src/build/app/mod.rs, src/build/app/settings.rs, src/parse/parser.rs
1. More readable replacment recovering.
2. Simplify `is_new_arg()`.
3. Remove `ValidNegNumFound` parser state.
=> Parser refactor

src/parse/parser.rs, tests/utf8.rs
The first commit that adds tests will fail in CI, and the second commit will fix bugs and make the failed tests green.
=> Fix wrong StrictUTF8 handling when AllowExternalSubcommands

clap_generate/src/generators/shells/zsh.rs, clap_generate/tests/generate_completions.rs, src/build/app/mod.rs, src/build/arg/mod.rs
This PR fixes a panic that would occur when a zsh completion file was being generated 
for an app that contains global arguments that have conflicts with other arguments which aren't 
present in all the subcommands that the global argument would be applied to.
The added test would panic before the fix.
Only the test added without the fix to observe the problem.
git clone --branch zsh_completion_bug https://github.com/ahkrr/clap.git
cd clap/clap_generate/tests && cargo test
I haven't found an open issue regarding this panic.
=> fix(clap_generate): zsh completion generation panic

src/build/app/mod.rs
This PR removes a compatibility problem that existed before 1.46.0. 
The `[]` operator would result in `&mut` is incompatible with the demanded `&` error
=> refactor: TODO 1.46.0, improve readability by using [] operator

README.md
The import `Arg` is unused, so I deleted it to make this example consistent with examples/01a_quick_example.rs.
=> docs(README.md): remove unused import in "Using Builder Pattern" example

examples/01a_quick_example.rs, examples/01b_quick_example.rs, examples/01c_quick_example.rs, examples/02_apps.rs, examples/04_using_matches.rs, examples/08_subcommands.rs, examples/18_builder_macro.rs, examples/20_subcommands.rs, examples/21_aliases.rs, src/build/app/mod.rs, src/macros.rs
Note: this is my first time contributing to clap, and I'm not familiar with the codebase. Please review that I didn't forgot anything.
I recently added [support](https://github.com/rust-lang/cargo/pull/8387) in Cargo for the environment variable CARGO_PKG_LICENSE_FILE in addition to the recently added CARGO_PKG_LICENSE. This commit automatically populate the `license` field by reading those environment variable.
If both of the environment variable are empty, should we `panic!()` instead of just returning an empty string? I don't think that panicking is a good idea, since it would possibly break crates that are using the `app_from_crate!` macro, but I don't know of a better way to add a warning.
This may help a bit with #1768.
=> Automatically read license field from Cargo.toml

clap_generate/src/generators/mod.rs, clap_generate/src/lib.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/app/tests.rs, src/build/usage_parser.rs, src/parse/parser.rs
Speed up?
And resolve a fixme (now the propagation affects next level of subcommand).
The old behaviour of propagation is when `App` building begins, propagating global args recursively. But we will also build our subcommand app, which makes this "recursive" non-sense. And also, the subcommands are "built lazilly", which makes propagating to unused subcommand even more non-sense.
Now we only propagates the global argument for one level. Since the `_build` is already lazy, and propagation happens in build process, now propagation is also lazy.
This PR also move the is built checking into `_build` function. Which will speed up the multiple _build() calls on an `App`.
=> Lazy propagation and _build cleaning

src/build/app/mod.rs, tests/global_args.rs
Closes #2053
Closes #1385 
The cause of the bug is currently we only propagate the global args in the root App.
This PR propagates all the used global args in App we met.
=> Propagate global arg in subcommand to subsubcommand

clap_derive/src/attrs.rs, clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/clap.rs, clap_derive/src/derives/from_arg_matches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/dummies.rs
This PR changes `clap_derive` to emit code that refers to clap as just `clap` instead of `::clap`. This will allow users who want to use a re-export of the clap crate to still use the derive macros. Below are some examples of this pattern used by some other prominent crates to allow re-exporting:
tokio: https://github.com/tokio-rs/tokio/blob/79d25b0a48d3e82a9d026e9cdfeef548153660ef/tokio-macros/src/entry.rs#L228
sqlx: https://github.com/launchbadge/sqlx/blob/04647ae09ae7f2d211c06e594561690ec9117acd/sqlx-macros/src/derives/encode.rs#L79
=> Use `clap` instead of `::clap` in `clap_derive`

src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg_group.rs, src/mkeymap.rs, src/parse/matches/arg_matches.rs, src/parse/matches/matched_arg.rs
Closes #952
This is the current status (after the changes) of the the public types.
The only types that I was able to add were Eq, and PartialEq.
I also noticed that for Values and ValuesOs, it explicitly said that it didn't implement debug so I'm unsure if that is a design choice.
> Regarding certain traits:
> 
> * Default is meaningless for `Arg`, `App`, `ArgGroup`. 
> * Implementing `PartialOrd + Ord` is _probably_ next to impossible because they aren't implemented  for `IndexMap`. Same with `Hash`
_Originally posted by @CreepySkeleton in https://github.com/clap-rs/clap/issues/952#issuecomment-624733954_
The three mentioned here already had explicit default implementations.
It also may be possible to add things like Eq, and PartialEq to Values and ValuesOs but it isn't possible as far …
=> imp: added more common derives App, Arg, and ArgMatches

src/build/app/mod.rs
The default was correctly changed to 100 in #1950, but later accidentally reverted in 89fcc75.
=> docs: Mention correct default value in term_width docstring

Cargo.toml, src/output/help.rs
cc https://github.com/clap-rs/clap/issues/1365#issuecomment-753356141
cc #1365
User now can disable unicode_help feature when their help message doesn't contain unicode characters. Which can reduce a dependency: "unicode_width".
=> Add unicode_help feature, Bump textwrap to 0.13.2

README.md
The 3.0 readme only shows how to use the parsed arguments with the structopt-powered API. This adds back in the usage example for the other modes of usage to the first example. Also fixes a small typo in referring to the examples.
=> docs: add back example of using non-structopt arguments

src/parse/matches/arg_matches.rs
There are some doc tests forget to set `use_delimiter()`
=> Pick up missing setting

src/build/arg/mod.rs, tests/fixtures/app.yaml, tests/yaml.rs
This PR allows users to set `visible_alias`, `visible_aliases`, `visible_short_alias` and `visible_short_aliases` for args from YAML files.
Closes #1613
=> Allow visible alias(es) for args from YAML files

examples/18_builder_macro.rs, src/macros.rs, tests/macros.rs
This PR makes `@group` accept more than one attributes, in the same way as `@arg` does.
Now, only one attribute such as `+required` and `!multiple`, etc. is supported with a `@group`:
```
(@group difficulty +required =>
(@arg hard: -h --hard "Sets hard mode")
(@arg normal: -n --normal "Sets normal mode")
(@arg easy: -e --easy "Sets easy mode")
)
```
which limits the possibility to express a `required` *and* `multiple` arg group.
This PR enables specifying multiple attributes on a group, as well as adds more possible syntaxes that are accepted by an `@arg` branch, such as:
```
(@group difficulty: +required conflicts_with[hardness]
(@arg hard: -h --hard "Sets hard mode")
(@arg normal: -n --normal "Sets normal mode")
(@arg easy: -e --easy "Sets easy mode")
)
```
**EDIT**:
New syntax with `:` …
=> Make @group accept multiple attributes

src/build/app/mod.rs, tests/app_settings.rs
`unset_setting()` accidentally changes global setting, which makes it's behaviour the same as `unset_global_setting`. This PR fixes it.
=> Fix unset_setting()

src/output/usage.rs, src/parse/parser.rs, tests/groups.rs, tests/utils.rs
This is the first part of #2297 
I don't think #1856 is the correct fix of #1794.
Reopen #1794 
Closes #1859
=> Dehack, Revert #1856

src/build/app/settings.rs, src/output/usage.rs, src/parse/arg_matcher.rs, src/parse/parser.rs, src/parse/validator.rs
=> Parser logic clean up

src/parse/parser.rs, tests/flags.rs
=> Fix eagerly trimming dash in parse_long_flag

src/build/app/settings.rs, src/parse/arg_matcher.rs, src/parse/matches/arg_matches.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs, src/parse/validator.rs, tests/grouped_values.rs
A little parser refactor.
Fixes #1026, check `tests/grouped_values.rs` for the results.
Fixes #1374, check `tests/grouped_values.rs:issue_1374()`.
Fixes #2171, check `tests/grouped_values.rs:issue_2171()`.
=> Parser refactor.

clap_generate/src/generators/mod.rs, clap_generate/src/lib.rs, clap_generate/tests/completions/fish.rs, clap_generate/tests/completions/zsh.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/mkeymap.rs, tests/app_settings.rs, tests/derive_order.rs, tests/global_args.rs, tests/help.rs, tests/version.rs
This is a start to solve the mut_arg problem. This PR builds the help and version args at the beginning when `App` is constructed but still prefers user provided args.
A nice side effect is cleaning up of some bugs in generator code.
=> Build help and version args at the beginning

src/build/app/mod.rs, src/output/help.rs, src/output/usage.rs, src/parse/parser.rs, tests/help.rs, tests/hidden_args.rs
Based on #2211, this PR fixes quite a few bugs in the help message generation regarding hidden args and the args with custom help headings.
Only the last commit is new. I will rebase this branch once #2211 is merged.
=> Better help message support for hidden and heading stuff

clap_derive/tests/custom-string-parsers.rs, clap_derive/tests/non_literal_attributes.rs, clap_generate/Cargo.toml, src/build/app/mod.rs, src/parse/validator.rs
Remove recent nightly test warnings, some of the warnings originates from version-sync.
Related: https://github.com/mgeisler/version-sync/issues/103, https://github.com/rust-lang/rust/pull/81645
=> Fix part of the non_fmt_panic warnings, bump version-sync to 0.9.2

Cargo.toml, clap_derive/Cargo.toml
Forget to bump version-sync version for clap and clap_derive(only did that for clap_generate) in #2346.😅 Now there is no check annotations from CI.
=> Bump version-sync version

src/build/arg/mod.rs, src/parse/arg_matcher.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs, src/parse/validator.rs, tests/grouped_values.rs, tests/multiple_values.rs
Fixes #2229 Fixes #1374
Let `num_vals` and etc sets `MultipleValues` with `MultipleOccurrences` left untouched, which also removes a late setting hack.
=> Change how num_vals, min_vals, max_vals interacts with Multiple*

Cargo.toml, src/output/help.rs
feat: remove direct unicode-width dependency
This removes the direct dependency on unicode-width and delegates the complexity of computing the displayed width of text to the Textwrap crate.
The [`display_width` function](https://docs.rs/textwrap/0.13.3/textwrap/core/fn.display_width.html) handles characters like “æøå” (Danish), “äöü” (German), and “joysparklesheart_eyes” (emojis) – even if the unicode-width Cargo feature is disabled.
This is an improvement of the former `str_width` function which would over-estimate the width of emojis and non-ASCII characters (since they are several bytes wide).
=> feat: count chars instead of bytes in str_width

clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs, clap_generate/tests/completions/bash.rs, clap_generate/tests/completions/elvish.rs, clap_generate/tests/completions/fish.rs, clap_generate/tests/completions/powershell.rs, clap_generate/tests/completions/zsh.rs, src/build/arg/mod.rs
Closes #2335 
This pull request implements completion for long visible aliases added with `App::visible_alias` or `App::visible_aliases`.
```rust
use clap::App;
use clap::Arg;
use clap_generate::generate;
use clap_generate::generators::Bash;
fn main() {
let mut app = App::new("foo")
.arg(
Arg::new("bar")
.short('b')
.visible_short_alias('q')
.long("bar")
.visible_alias("qux"),
);
generate::<Bash, _>(&mut app, "foo", &mut std::io::stdout());
}
```
With version `3.0.0-beta.2` generated completions are:
```
❯ cargo run --quiet > completions.bash && source completions.bash
❯ foo --
--bar      --help     --version
```
With this PR generated completions are: 
```
❯ cargo run --quiet > completions.bash && source completions.bash
❯ foo --
--bar      --help     --qux      --version
```
Note that …
=> imp: Visible aliases for arguments in completions

clap_generate/src/generators/shells/fish.rs, clap_generate/tests/completions/fish.rs, clap_generate/tests/value_hints.rs
Fish completions currently insert `-n "__fish_use_subcommand"` to detect subcommands and disable completions of top-level flags. There are unfortunately false positives, so there are no flag completions after you've typed e.g. `rg -C 10` because `10` is taken as a subcommand.
This change disables that detection when there are no subcommands defined in the first place, as an easy fix for some cases.
=> fix: Do not look for subcommands in fish completion if none exist

clap_derive/src/derives/clap.rs, clap_derive/src/derives/into_app.rs, clap_derive/tests/app_name.rs
Closes #2181 
This PR propose a fix for issue #2181.
Example application source code: 
```
❯ tree clap_issue_2181/
clap_issue_2181/
├── Cargo.lock
├── Cargo.toml
└── src
└── main.rs
1 directory, 3 files
```
`main.rs` source file: 
```rust
use clap::Clap;
#[derive(Clap)]
#[clap(name = "my-bin", version = clap::crate_version!())]
enum Opts {}
fn main() {
Opts::parse();
}
```
With beta version:
```
❯ cargo run --quiet -- -V
clap_issue_2181 0.1.0
❯ cargo run --quiet -- --version
clap_issue_2181 0.1.0
❯ cargo run --quiet -- --help
clap_issue_2181 0.1.0
USAGE:
clap_issue_2181
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
❯ cargo run --quiet -- -h
clap_issue_2181 0.1.0
USAGE:
clap_issue_2181
FLAGS:
-h, --help       Prints help information
-V, …
```
=> Fix issue #2181

src/output/help.rs
This performs the common case of adding small padding without performing an allocation.
=> Optimize common case of space padding

clap_derive/tests/doc-comments-help.rs, src/build/app/mod.rs, src/output/help.rs, tests/app_from_crate.rs, tests/app_settings.rs, tests/arg_aliases.rs, tests/arg_aliases_short.rs, tests/cargo.rs, tests/flag_subcommands.rs, tests/help.rs, tests/hidden_args.rs, tests/version.rs
Fix compatibility with help2man output (see #1432)
- Change default help template:
The new template introduce new lines before and after
author/about sections.
- Add help template placeholders:
- `about-section`
- `author-section`
- Documentation of new placeholders in `clap::App::help_template`
- Update all unit tests by incorporating new lines
Closes #1432
When [help2man](https://www.gnu.org/software/help2man/) parses standard clap help template, the generated man page unwraps `{binary_name} {version} {author} {about}` placeholders.
```
❯ tree clap_issue_1432
clap_issue_1432
├── Cargo.lock
├── Cargo.toml
├── src
|   └── main.rs
└── test.man
1 directory, 4 files
```
The `main.rs` source file:
```rust
use clap::App;
use clap::AppSettings;
use clap::Arg;
fn main() {
let app = …
```
=> fix: Compatibility with help2man

Cargo.toml, src/parse/parser.rs, src/util/argstr.rs
This makes some name changes to upgrade [os\_str\_bytes](https://crates.io/crates/os_str_bytes) to [3.0.0](https://github.com/dylni/os_str_bytes/releases/tag/3.0.0).
I also removed some unnecessary copying, which was one of the reasons for the signature changes.
=> Upgrade os_str_bytes

src/parse/errors.rs
Implement print to parse::Error. It just prints formatted error message and does not exit. It helps users to parse commands with `try_parse_from` and manage how the applications behave and print error messages by themselves.
Sorry for I do not know how to test it...
=> feat: implement print to parse::Error

clap_derive/tests/non_literal_attributes.rs, src/build/app/settings.rs, src/build/arg/mod.rs, src/parse/errors.rs, src/parse/parser.rs, tests/opts.rs
=> Implement NoEquals error

src/build/arg/debug_asserts.rs, src/build/arg/mod.rs, src/build/arg/settings.rs, src/parse/errors.rs, src/parse/parser.rs, src/parse/validator.rs, tests/default_vals.rs, tests/empty_values.rs, tests/opts.rs
=> Allow empty value by default, introduce NoEquals Error

clap_generate/src/lib.rs, clap_generate/src/shell.rs
Closes #1900
Back to my workstation, here is the pull request for the easy one.
This pull request adds `clap_generate::Shell` (non-exhaustive) enum with all currently supported shells.
```rust
pub enum Shell {
Bash,
Elvish,
Fish,
PowerShell,
Zsh,
}
```
=> api: Add clap_generate::Shell enum

src/build/arg/mod.rs, tests/fixtures/app.yaml
Closes #2413 
When loading a `yaml` file, the presence of any extra fields in any of the `Arg`s causes the program to panic. Extra fields at the `App` level are ignored without consequence. This pull request changes the behavior of extra fields at the `Arg` level to match the `App` level, extra fields at both levels will be ignored when loading a `yaml` config.
This pull request also updates `tests/fixtures/app.yaml` with examples of ignored fields for both `App` and `Arg`s. This is checked by the `create_app_from_yaml` test in `tests/yaml.rs`.
=> Ignore extra fields in Arg yaml definitions

clap_generate/src/generators/shells/elvish.rs, clap_generate/tests/completions/elvish.rs
Makes the following changes in completions for the Elvish shell:
- Changes deprecated `has-prefix` function to`str:has-prefix`
- Changes deprecated slice syntax `[1:-1]` to `[1..-1]`
- Adds `builtin` prefix to builtin functions to remove ambiguity
=> Fix completions for Elvish shell

CHANGELOG.md, src/build/app/settings.rs, src/parse/parser.rs, tests/app_settings.rs
Closes https://github.com/clap-rs/clap/issues/2435
Specifies that the help subcommand should print the long form help message (if possible), instead of the short form.
Example:
```rust
let m = App::new("myprog")
.setting(AppSettings::UseLongFormatForHelpSubcommand)
.subcommand(App::new("test")
.after_help("short form help msg")
.after_long_help("long form help msg"))
.get_matches();
```
Output:
```
myprog-test 
USAGE:
myprog test
FLAGS:
-h, --help
Prints help information
-V, --version
Prints version information
long form help message
```
=> setting: UseLongFormatForHelpSubcommand

src/macros.rs, tests/macros.rs
Hopefully should be clear enough. Currently, the following example will fail to compile, with the error "cannot find macro \`clap_app\` in this scope":
```rust
fn main() {
let app = clap::clap_app!(myapp=>
(@arg myarg: "it's a dummy argument")
);
}
```
while this will:
```rust
use clap::clap_app;
fn main() {
let app = clap_app!(myapp=>
(@arg myarg: "it's a dummy argument")
);
}
```
This is present in both v2 and v3 -- I noticed it in v3 first, hence the PR into master. Should I open another identical PR for `v2-master`?
=> add missing `$crate::` in `clap_app!` for arg.about(...)

src/build/arg/mod.rs, src/parse/arg_matcher.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs, tests/require.rs
Previously, if an argument "Arg" is specified with .possible_values() and .case_insensitive(true), other options that are conditionally required with .required_if("Arg", "Val") would only be required if "Arg" is an exact match to "Val". This results in unexpected behavior if the user instead gives "val", since the argument is accepted, but the dependent argument isn't required.
Follow-up from https://github.com/clap-rs/clap/pull/2446, which proposed similar changes on the v2-master branch.
=> imp(validator): Case-insensitive required_if_eq when arg is case-insensitive

src/output/usage.rs, tests/conflicts.rs, tests/require.rs
Fixes https://github.com/clap-rs/clap/issues/2454.
The issue was that positional arguments were being placed at the start of the usage string, rather than at the end. This poses a problem when accepting a `TrailingVarArg`.
Positional arguments should be placed at the end. For example, `git init --help` shows flags before positional arguments. I've added a `--` separator for clarity, and for correctness in the case that the last non-positional argument accepts multiple values.
=> fix(usage): Move positional args to end of usage string

src/parse/parser.rs
This PR is a follow-up of #2501:
- Add more comments explaining parsing logic change in `done_short_args` and `keep_state`.
- Replace several `.unwrap()` usages with `.expect()`.
- Fix typo.
=> docs: add more explanation to #2501 fix

src/build/app/settings.rs, src/parse/parser.rs, tests/opts.rs
Closes https://github.com/clap-rs/clap/issues/1786.
This PR add support abbreviated long options, such as writing `--test` as `--t`, `--te` or `--test` if the argument is ambiguous. It is enabled with `AppSettings::InferLongArgs`, modeled after `AppSettings::InferSubcommands`.
Also, thank you for this amazing project!
=> Infer long arguments

src/parse/validator.rs
This PR tries to make some parts of `validator` code more readable mainly by:
- Using aliases when appropriate, which reduces the number of lines.
- Using functional style to remove some of the global variables in the function scope.
PS: I understand that the functional style might not look good to everyone :)
=> refactor(validator): cleanup code

src/build/app/settings.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs
These were broken by 03333800fe8b9056823499f20f340770994e4643
=> docs: fix links to Subcommand

examples/03_args.rs, examples/08_subcommands.rs, examples/18_builder_macro.rs, examples/20_subcommands.rs
Was done in 03333800fe8b9056823499f20f340770994e4643
=> the word "Subcommand" was accidentally removed

clap.schema.json, src/build/arg/mod.rs, src/parse/errors.rs, src/parse/validator.rs, tests/multiple_occurrences.rs
Closes #2520
Allows for specifying of `max_occurrences`, similar to `max_values`.
`max_occurrences` with a value of greater than 1 also specifies `multiple_occurrences`
Example:
`main.rs`
``` rust
fn main() {
let args = App::new("foo")
.arg(Arg::new("verbosity").short('v').max_occurrences(3))
.get_matches();
match args.occurrences_of("verbosity") {
0 => println!("0"),
1 => println!("1"),
2 => println!("2"),
_ =>println!("3"),
}
}
```
The command `cargo run -- -vvv` will output:
```
3
```
whereas
`cargo run -- -vvvv` will output:
```
error: The argument '-v' allows at most 3 occurrences, but 4 were provided
USAGE:
clap-test [FLAGS]
For more information try --help
```
=> Add a new arg option for the max_occurrences

src/derive.rs
In preparing to fix #2005, I needed to understand all of the pieces fit together.  I decided to capture some of that by writing up doc comments for the traits used by `clap-derive`.
=> docs(derive): Update trait doc-comments

clap_derive/examples/arg_enum.rs, clap_derive/examples/value_hints_derive.rs, clap_derive/src/derives/clap.rs, clap_derive/src/dummies.rs, clap_derive/tests/arg_enum.rs, src/derive.rs
While having convinience derives can be helpful, deriving traits that
are not used in similar situations (`Clap` and `ArgEnum`) can make
things harder
- From a user, derives are opaque and create uncertainty on how to use
the API if not kept crystal clear (deriving a name gives you the trait
by that name)
- This makes documentation harder to write and read
- You can use types in unintended places, which is made worse for crate
APIs because changing this breaks compatibility.
Fixes #2584
=> fix(derive): `Clap` should not derive `ArgEnum`

README.md
The word "crazy" is often used in a derogatory manner to people with mental disabilities:
https://www.selfdefined.app/definitions/crazy/
This PR changes the usage to the word "ridiculous" since it's just as clear and is more inclusive.
=> Change some wording to be more inclusive

clap_derive/src/attrs.rs, clap_derive/src/derives/args.rs, clap_derive/src/derives/clap.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/mod.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/dummies.rs, clap_derive/src/lib.rs, clap_derive/tests/issues.rs, clap_derive/tests/ui/enum_variant_not_args.rs, clap_derive/tests/ui/enum_variant_not_args.stderr, clap_derive/tests/ui/flatten_on_subcommand.rs, clap_derive/tests/ui/flatten_on_subcommand.stderr, src/derive.rs, src/lib.rs
Before, partial command lines would panic at runtime.  Now it'll be a
compile error
For example:
```
#[derive(Clap)]
pub enum Opt {
Daemon(DaemonCommand),
}
#[derive(Clap)]
pub enum DaemonCommand {
Start,
Stop,
}
```
Gives:
```
error[E0277]: the trait bound `DaemonCommand: clap::Args` is not satisfied
--> clap_derive/tests/subcommands.rs:297:16
|
297 |         Daemon(DaemonCommand),
|                ^^^^^^^^^^^^^ the trait `clap::Args` is not implemented for `DaemonCommand`
|
= note: required by `augment_args`
```
To nest this, you currently need `enum -> struct -> enum`.  A later
change will make it so you can use the `subcommand` attribute within
enums to cover this case.
This is done by splitting out an `Args` trait from `IntoApp`, like `Subcommand` previously did in #1681.
As a side …
=> fix(derive)!: Compile-error on nested subcommands

clap_derive/src/attrs.rs, clap_derive/src/derives/subcommand.rs, clap_derive/tests/subcommands.rs
`structopt` originally allowed
```
#[derive(Clap)]
pub enum Opt {
Daemon(DaemonCommand),
}
#[derive(Clap)]
pub enum DaemonCommand {
Start,
Stop,
}
```
This was partially broken in #1681 where `$ cmd daemon start` works but `cmd daemon`,
panics.  Originally, `structopt` relied on exposing the implementation
details of a derived type by providing a `is_subcommand` option, so we'd
know whether to provide `SubcommandRequiredElseHelp` or not.  This was
removed in #1681
With this change, the above code is now:
```
#[derive(Clap)]
pub enum Opt {
#[clap(subcommand)]
Daemon(DaemonCommand),
}
#[derive(Clap)]
pub enum DaemonCommand {
Start,
Stop,
}
```
This can be taken a step further and support optional subcommands in variants like we do fields.  That kind of consistency would help in people …
=> fix(derive): Allow subcommands to directly nest in subcommands

src/build/app/settings.rs
=> Remove a redundant word in AppSettings::NoBinaryName enum explanation

src/parse/validator.rs, tests/default_vals.rs
=> Don't show default_vals in smart usage

src/build/app/mod.rs, src/parse/errors.rs, src/util/mod.rs
PR #1637 switched clap to report `64` on errors and then #1653 switch it
to `2`, but both missed a case.  This also documents the reason why inline
since I had to go and dig through the history to re-discover the
motivation.
=> fix(exit): Be consistent in exit code

clap_derive/src/derives/subcommand.rs, clap_derive/tests/subcommands.rs
Before, when doing an `update` involving subcommands, we generated
parsing rules for the `from` case instead, requiring all arguments to be
present.
This switches us to descending into `update` code and adds tests to
verify it works.
This is a part of #2605
=> fix(derive): Allow partial update of Subcommand arguments

clap_derive/src/derives/args.rs
One of the challenges with #2255 is for the user to discover whats going
wrong.  This helps by at least telling people how they got into a bad
state and we can search for the code within the derive.
=> fix: Provide context for panics

clap_derive/src/derives/arg_enum.rs, clap_derive/tests/arg_enum.rs, src/derive.rs
This doesn't solve the problem end-to-end but at least makes it possible
to solve by the user and improve in the future.
=> feat(derive): Make it possible to use ArgEnum with default_value

clap_derive/src/attrs.rs, clap_derive/src/derives/args.rs, clap_derive/tests/arguments.rs
I debated putting this fix inside of the Builder API but I figure this
makes it so you "pay for what you use", with the derive API giving it to
you "for free".
A potential next step is to improve the default value name.  I tend to
use value_name to hint at how to use an argument, which correlates with
types.  We could add a
`ValueName::value_name(fallback: &str) -> &str` with impls for common
types, so we get more of a usage-based result.
Fixes #2608
=> fix(derive): Follow value_name convention

clap_derive/src/derives/subcommand.rs, clap_derive/tests/subcommands.rs
When using `#[clap(subcommand)]` inside of a Subcommand, we didn't
properly do an `update` but a `from`.
This is a part of #2605
=> fix(derive): Allow partial update of Sub-Subcommands

clap_derive/src/derives/subcommand.rs, clap_derive/tests/flatten.rs, src/derive.rs
When using `#[clap(flatten)]` inside of a `Subcommand`, we would do a
`from` instead of an `update`.
The challenge is knowing when we are
going into a flattened subcommand vs changing the variant.  To resolve
this, I added a `Subcommand:has_subcommand(name)` trait method that we
generate, so we can ask.
=> fix(derive): Allow partial update of flattened Subcommand arguments

README.md, benches/05_ripgrep.rs, clap_derive/README.md, clap_generate/src/generators/shells/zsh.rs, clap_generate/tests/completions/elvish.rs, clap_generate/tests/completions/fish.rs, clap_generate/tests/completions/powershell.rs, clap_generate/tests/completions/zsh.rs, clap_generate/tests/value_hints.rs, site/content/_index.md, src/build/app/mod.rs, src/build/arg/mod.rs, tests/app_from_crate.rs, tests/app_settings.rs, tests/arg_aliases.rs, tests/arg_aliases_short.rs, tests/cargo.rs, tests/derive_order.rs, tests/flag_subcommands.rs, tests/groups.rs, tests/help.rs, tests/hidden_args.rs, tests/macros.rs, tests/subcommands.rs, tests/template_help.rs, tests/version.rs
Closes #2500 
This changes all occurences of:
- "Prints help information" to "Print help information"
- "Prints version information" to "Print version information"
- "Prints this message or the help of the given subcommand(s)" to "Print this message or the help of the given subcommand(s)"
There are a few remaining usages of "Prints", but those do not apply to the default messages.
=> Replace "Prints" with "Print" for default help and version commands

clap_derive/src/derives/args.rs, clap_derive/tests/arguments.rs
It turns out `value_name` appends, so by setting an implicit and
explicit `value_name`, the user gets both and `num_vals=2`.
There is still a question on `value_name` and whether its documentation
or behavior needs updating.  If that changes, then this can be
simplified by reverting back.
Fixes #2632
=> fix(derive): Don't mix implicit and explicit `value_name`s

src/build/app/mod.rs, src/output/usage.rs, tests/help.rs
Closes #1737
If `AppSettings::AllowMissingPositional` is enabled, then `req_string` is added after other arguments.
=> Fix order of arguments in help message with AllowMissingPositional

src/parse/matches/arg_matches.rs, src/parse/matches/matched_arg.rs, tests/default_missing_vals.rs
`value_of` shouldn't get the first value of the first value group, but the first value of the flattened value group
=> Fix `value_of` returns `None` when the first value group is empty

src/output/fmt.rs
`AppSettings::ColorAlways` currently appears to have no effect.
This was an issue in the past (see #1400), but was fixed in pr #1402; however, it seems to have been broken again.
I have tested the altered colorizer in a local project, and it seems to have the correct behavior.
No lints are triggered. All tests have passed.
This should fix issue #1400 ... again.
=> Make colorizer respect `AppSettings::ColorAlways` / `ColorChoice::Always`

clap_derive/src/derives/args.rs, clap_derive/tests/options.rs
Possibly closes #2448
When setting `min_value` and `max_value`, `multiple_values` is automatically to `true`. By moving `multiple_values(false)` to after those, it actually has an effect, and the ellipsis is not displayed.
This does not make the value appear as `[<val>]`. I was unsure of what circumstances it would apply to: only with `Option<Option<...>>`, with all values that are not required, or some other conditions.
=> Make `multiple_values` `false` with derived `Option<Option<...>>`

examples/01a_quick_example.rs, examples/01b_quick_example.rs, examples/08_subcommands.rs, examples/18_builder_macro.rs, examples/21_aliases.rs, src/macros.rs, src/parse/matches/matched_arg.rs, tests/default_missing_vals.rs, tests/help.rs, tests/require.rs
The PR solves 2 minor issues:
- The `debug!` macro fills up the IDE with `branches_sharing_code` warnings.
- Ideally this should not affect much since in release mode it's a no-op.
- Unnecessary usages of `.clone()`,`.collect()`, `ref` and `'static`, reported by `clippy`.
=> fix(style): eliminate several `clippy` warnings

examples/22_stop_parsing_with_--.rs
=> docs(example): clarify `stop_parsing_with_--`

src/build/arg/mod.rs, src/parse/parser.rs, src/util/mod.rs, src/util/str_to_bool.rs, tests/env.rs
Closes #2539.
This PR allows boolean literals following the Python [`strtobool`] convention (case-insensitive):
[`strtobool`]: https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool
> True values are y, yes, t, true, on and 1; false values are n, no, f, false, off and 0. Raises ValueError if val is anything else.
- A `false` literal or an absent env var will cause the flag to be considered absent.
- ~~If the env var gets a `true` literal, then the flag is considered present by the parser.~~
- ~~If the boolean literal is anything else, the parser returns an error.~~
- If the env var gets anything else, then the flag is considered present by the parser (suggested by @pksunkara).
- The [`pseudo-flag`](https://github.com/clap-rs/clap/issues/1649#issuecomment-891176637) …
=> feat(parser): accept boolean literal with env vars

src/build/app/mod.rs, src/build/app/settings.rs, src/build/app/tests.rs
This is the last deprecation left in #1037
=> Remove settings that are inherently global

src/output/help.rs, tests/help.rs
Closes #2533.
Passing a closure isn't the nicest, but it avoids us having to duplicate the `args.filter(|arg| {should_show_arg(...)})` logic in multiple places.
=> Hide help heading when all args are hidden

clap_derive/src/derives/args.rs, clap_derive/tests/flatten.rs
=> Derive doc clap ordering for multiple Clap

src/build/app/debug_asserts.rs, src/build/app/mod.rs, src/build/arg/debug_asserts.rs, src/build/arg/mod.rs, src/build/usage_parser.rs, src/output/help.rs, src/parse/parser.rs, tests/env.rs
Fixes #2680 since that can now be done in #2677
=> Set TakesValue to true for positional args when building

clap_derive/src/attrs.rs, clap_derive/src/parse.rs, clap_derive/tests/arg_enum.rs, clap_derive/tests/default_value.rs, clap_derive/tests/ui/default_value_wo_value_removed.rs, clap_derive/tests/ui/default_value_wo_value_removed.stderr
Right now
- `default_value="something"` is a raw method
- `default_value` uses native types
This commit splits the meanings
- `default_value="something"` is a raw method
- `default_value_t` uses `T::default()`
- `default_value_t=expr` uses an expression that evaluates to `T`
This is meant to mirror the `value_of` / `value_of_t` API.
At the moment, this is limited to `T: Display` to work with clap's
default system.  Something we can look at in the future is a way to
loosen that restriction.  One quick win is to specialize when `arg_enum`
is set.  The main downside is complicating the processing of attributes
because it then means we need some processed before others.
Since this builds on `clap`s existing default system, this also means
users do not get any performance gains out of using …
=> feat(derive): Specify defaults by native expressions

src/build/app/settings.rs
=> Tweak `ArgsNegateSubcommands`'s doc

clap_derive/src/derives/args.rs, src/build/arg/mod.rs, src/build/usage_parser.rs, src/output/help.rs
Instead they should behave like `default_value`/`default_values`.
In implementingt this, I didn't see any reason to be using a `VecMap`.
In fact, this helped simplify the code / make intent clearer.
With this, we are also able to simplify the derive macro work from #2633.
Fixes #2634
BREAKING CHANGE: `value_name`/`value_names` always overwrite, rather
than append.  We expect the impact to be minimal.
=> fix!: value_name/value_names should not append

src/build/arg/mod.rs, src/build/usage_parser.rs, tests/multiple_values.rs
=> `num_vals` is now constructed from `val_names` in only one place instead of two

Cargo.toml, README.md, src/build/app/settings.rs, src/build/arg/debug_asserts.rs, src/build/arg/mod.rs, src/build/arg/settings.rs, src/macros.rs, src/output/help.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/mod.rs, tests/env.rs, tests/help.rs, tests/multiple_occurrences.rs
Was looking at Kevin's recent changes in the `modular` branch and since we have `DisableEnv` setting, I felt like this is a better way to do it.
=> Add env feature gate

src/build/arg/mod.rs, src/parse/parser.rs, tests/posix_compatible.rs
=> Make `overrides_with` working when `MultipleValues` is enabled.

src/parse/errors.rs
When constructing the Error for an invalid value, an info `Vec` is constructed, populated with the argument, the invalid value, and possible valid values… and then discarded and an empty `Vec` is used instead.
I can only assume this is unintentional, so this PR fixes that.
=> Fix invalid_value returning an Error with no info

Cargo.toml, clap_generate/Cargo.toml
Pin since `clap_derive` is unstable. Fixes #2705
=> Pin `clap_derive` version

src/build/arg/mod.rs, src/output/help.rs, tests/help.rs
=> Fix handling of `number_of_values` when displaying arg

clap_derive/src/derives/subcommand.rs
I did some digging to root cause this but gave up and suppressed it,
like others.  Warnings like this also come with a cost of code-gen
complexity.
Fixes #2712
=> fix(derive): Don't produce warnings

src/parse/errors.rs
Previously, we paniced.  This is one less reason people have to call
lower level `get_matches` to get the commonly expected behavior, making
it more likely for the Rust community to "do the right thing"
Fixes #2659
=> fix: Swallow broken pipes

clap_generate/README.md, clap_generate/src/lib.rs
This provides a skeleton README for `clap_generate`, including a
one-line summary and a link to the docs to guide people to the examples
there.
In doing so, I tried to clarify and be consistent in what role
this crate plays.  While it is very general, being too general in the
description can lead people to not understand where they could use it.
Fixes #1711
=> docs(generate): Improve jumping off points

CHANGELOG.md, clap_derive/src/derives/args.rs, clap_derive/src/derives/subcommand.rs, clap_derive/tests/ui/external_subcommand_wrong_type.stderr, clap_derive/tests/utf8.rs, src/build/app/debug_asserts.rs, src/build/app/settings.rs, src/build/arg/debug_asserts.rs, src/build/arg/mod.rs, src/build/arg/settings.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs, src/parse/parser.rs, src/parse/validator.rs, tests/app_settings.rs, tests/utf16.rs, tests/utf8.rs
Before, validating UTF-8 was all-or-nothing and would cause a `panic` if
someone used the right API with non-UTF-8 input.
Now, all arguments are validated for UTF-8, unless opted-out.  This
ensures a non-panicing path forward at the cost of people using the
builder API that previously did `value_of_os` need to now set this flag.
Fixes #751
=> fix: Provide path to avoid UTF-8 panics

src/build/arg_group.rs, tests/examples.rs, tests/fixtures/multiple_groups.yaml, tests/yaml.rs
Because we gradually build the `ArgGroup` as we parse the YAML, we don't
use `ArgGroup::new`.  Clap3 introduced an internal `id` in addition to
the public `name` and it appears that this custom initialization code
was not updated.
This shows the problem with publically exposing `impl Default`.
Choices:
- Remove `impl Default`
- Always valid
- Requires spreading invariants
- Callers can't implement code the same way we do
- Add `ArgGroup::name`
- Can be constructed in an invalid state
- Centralizes invariants
- A caller could implement code like the yaml logic
I decided to go with `ArgGroup::name`.
Fixes #2719
=> fix(yaml): Don't panic on multiple groups

clap_generate/src/generators/shells/fish.rs, clap_generate/tests/value_hints.rs
This returns `"{a\t,b\t}"` instead of `"a b"` for possible_values
completion. Therefore fish displays and therefor hides the empty
description after the `\t`.
Fixes #2727
=> fix(generate): Hide option/argument description for argenum

src/parse/errors.rs
`anyhow::Error` requires `Send` and `Sync`: https://github.com/dtolnay/anyhow/issues/81
Last clippy resolving accidentally makes `clap::Error` `?Send` and `?Sync`.
Fixes #2742
=> Make `clap::Error` `Send` and `Sync` again

clap_derive/examples/keyvalue.rs
This was broken earlier due to 3f94d17c71d8dea26133dbe107289c7f0c187499 not
taking into account this example.
Closes #2746.
=> Fix keyvalue example

site/content/cheatsheet.md, site/content/cookbook.md, site/templates/page.html
Reading the website, I stumbled on 404 errors, according to #2601 this is expected.
However I think it would be better to be explicit about the fact this is expected ;-)
=> Add placeholders for Cookbook and Cheatsheet pages in the website

src/parse/errors.rs, src/parse/matches/arg_matches.rs, src/parse/parser.rs, src/parse/validator.rs, tests/help.rs, tests/subcommands.rs
Closes #1463
I have changed some error constructing methods to take an `app: &App`. In many cases, this also allowed for the `color` as a parameter, as it was generally based off of `app.color()`. `try_help` now checks first for if the `--help` argument is enabled, and then if the `help` subcommand is enabled. In cases where there is no access to the original `App`, I have omitted the help suggestion entirely. I'm not sure if there is a better way to do this.
The main issue described in #1463 seemed to be caused by `src/parse/errors.rs` line 696. I believe there is no reason for the `help` to be there.
=> Don't suggest `help` or `--help` when not applicable

clap_derive/src/derives/subcommand.rs, clap_derive/tests/subcommands.rs
Modify clap_derive to allow to compute sub command name dynamically (via a function for example):
```rust
fn get_name() -> String {
if runtime_check() {
"some-name".to_string()
} else {
"some-other-name".to_string()
}
}
#[derive(Clap, PartialEq, Debug)]
struct Opt {
#[clap(subcommand)]
subcmd: SubCmd,
}
#[derive(Clap, PartialEq, Debug)]
enum SubCmd {
#[clap(name = get_name())]
SubCmd1,
}
```
It was expected to be a literal and was used in `match`, I replaced it with `if` statements.
=> Allow subcmd name to be something else than a literal in clap derive

clap_generate/src/generators/shells/fish.rs, clap_generate/tests/completions/fish.rs
* Prevent completing subcommands that were already completed
* Make sure all parent subcommands actually existent
Partially does a bit of #2715 (the "simple case")
=> fix(generate): Better subcommand completion in fish

clap_generate/src/lib.rs
Maybe we should add `cargo doc` to our CI, it would have cought this:
```
warning: this URL is not a hyperlink
--> clap_generate/src/lib.rs:45:22
|
45 | /// [`cargo-xtask`]](https://github.com/matklad/cargo-xtask)
|                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/matklad/cargo-xtask>`
|
= note: `#[warn(rustdoc::bare_urls)]` on by default
= note: bare URLs are not automatically turned into clickable links
warning: 1 warning emitted
```
=> doc(generate) fix link in `generate_to`

src/output/usage.rs, tests/double_require.rs
This addresses a bug that causes duplicate flags reported in user-facing
error messages when two flags require one-another but also are required
under other conditions. The fix involves removing duplicates in unrolled
requirements, which addresses the user-facing aspect of this bug.
Closes #2770
=> Fix bug with duplicate error messages

src/output/help.rs, tests/display_order.rs
Closes #2772 
I'm aware that `VecMap` was added for performance reasons, so I'm not sure if switching back to `BTreeMap` is the correct solution.
=> Add test for very large display_order values and a possible fix

src/parse/parser.rs, tests/default_vals.rs
Closes #2760
This splits the provided `default_value`s and `default_missing_value`s on the `value_delimiter` if present.
=> Apply `value_delimiter` to default values

clap_derive/src/derives/args.rs, clap_generate/examples/value_hints.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/zsh.rs, clap_generate/tests/value_hints.rs, examples/11_only_specific_values.rs, examples/13_enum_values.rs, src/build/app/mod.rs, src/build/arg/arg_value.rs, src/build/arg/mod.rs, src/build/mod.rs, src/lib.rs, src/output/help.rs, src/parse/arg_matcher.rs, src/parse/validator.rs, tests/app_settings.rs, tests/default_vals.rs, tests/help.rs, tests/possible_values.rs, tests/require.rs, tests/utils.rs
Through the ArgValue it is possible:
* `hide` possible_values from showing in completion, help and validation
* add `about` to possible_values in completion
This PR only includes the builder, for the derive macro see #2762 
partly fixes #2756
partly fixes #2731
=> ArgValue builder

clap_generate/src/generators/shells/elvish.rs, clap_generate/tests/completions/elvish.rs
The `display-suffix` option for `edit:complex-candidate` was [deprecated in Elvish v0.14.0][1] and removed in v0.15.0 (latest version is v0.16.3), so this PR changes the Elvish completions generation to use the `display` option instead.
Additionally, this PR changes assignments to use the `var` and `set` keywords as using `name = value` without these keywords ('legacy assignment form') [will be deprecated][2].
[1]: https://elv.sh/blog/0.14.0-release-notes.html
[2]: https://elv.sh/ref/language.html#legacy-assignment-form
=> Fix Elvish completions generation

README.md, benches/03_complex.rs, benches/05_ripgrep.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/arg_value.rs, src/build/arg/mod.rs, src/build/arg/settings.rs, src/build/macros.rs, src/build/mod.rs, src/lib.rs, src/macros.rs, tests/app_settings.rs, tests/arg_settings.rs
This was one of the earliest goals for 3.0 but never got to be implemented. When I took over, I assumed this was and thus all the confusion.
The main reason IIUC behind doing this originally and removing all the `*_settings()` functions is to reduce the number of methods and complexity of the builders which are already pretty big.
=> Implement BitOr for settings

tests/app_settings.rs, tests/arg_aliases.rs, tests/arg_aliases_short.rs, tests/conflicts.rs, tests/default_vals.rs, tests/derive_order.rs, tests/display_order.rs, tests/empty_values.rs, tests/flag_subcommands.rs, tests/flags.rs, tests/groups.rs, tests/help.rs, tests/help_env.rs, tests/hidden_args.rs, tests/macros.rs, tests/opts.rs, tests/possible_values.rs, tests/require.rs, tests/subcommands.rs, tests/template_help.rs, tests/utils.rs, tests/version.rs
This changes the assertions of output to make leading and trailing whitespace significant
=> assert on leading and trailing whitespace

clap_derive/examples/arg_enum.rs, clap_derive/examples/value_hints_derive.rs, clap_derive/src/attrs.rs, clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/args.rs, clap_derive/src/dummies.rs, clap_derive/src/parse.rs, clap_derive/tests/arg_enum.rs, clap_derive/tests/ui/arg_enum_on_struct.rs, clap_derive/tests/ui/arg_enum_on_struct.stderr, src/build/arg/arg_value.rs, src/derive.rs, src/parse/validator.rs, tests/possible_values.rs
Support ArgValue in ArgEnum derive macro.
merge after:  #2758
fully closes: #2756
fully closes: #2731
For reference: https://github.com/clap-rs/clap/pull/2758#discussion_r704765892
=> ArgValue derive

clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/args.rs, clap_derive/src/dummies.rs, clap_derive/tests/arg_enum.rs, src/derive.rs
This is a follow up to #2762, adding a clarifying `to_` prefix to the function.
=> Rename `ArgEnum::arg_value` to `to_arg_value`

src/parse/parser.rs, tests/help.rs, tests/version.rs
Closes #2789
This removes the `NoAutoHelp` and `NoAutoVersion` settings. These settings were added in 471376fdc7cacd64389614787307851f809c3f03, but I believe they can now just be replaced with `DisableHelpSubcommand`, `DisableHelpFlag`, and `DisableVersionFlag`.
I've also added some tests to cover the cases not accounted for by the test `disabled_help_flag_and_subcommand` added in #2749.
=> Fix disabling the default help and version subcommands/flags

src/build/arg/debug_asserts.rs, tests/multiple_values.rs, tests/positionals.rs
This unblocks
- Defining repeated tuples in positional arguments
- Potentially using this in #1772
Fixes #2784
=> fix(parser): Allow multiple_occurrecnes with positional args

clap_derive/tests/help.rs
This is to help verify behavior added in #2943.  We separated the error
raising site from the error formatting site and this verifies that the
formatting actually happens.
=> test(derive): Verify derive-genned errors are formatted

src/parse/errors.rs
If the user prints a raw error, it may include color even if the user
turned it off at runtime.  Now we'll be more conservative and never show
color for raw errors.
This is a follow up to #2943; apparently I had missed some cases.
=> fix(error): Never show unrequested color

src/build/app/mod.rs, tests/app_settings.rs
This adds a `App::mut_args` function that can be used to programmatically mutate all or some arguments by iterating through them even without specifying or knowing the names of the arguments. 
It follows a similar pattern to the existing `App::mut_arg` but instead of specifying a single named argument it will iterate through all arguments in the app and call the closure on them where the user can create or mutate the argument or return `None` to skip affecting it.
Found it useful that the closure returns an `Option` for this so you have a choice in mutating or leaving the argument as is, because otherwise all arguments would be tagged as `ArgProvider::GeneratedMutated` including the auto-generated `version` which often led to `Used App::mut_arg("version", ..) without providing …
=> Add new `App::mut_args` for mutating all arguments

src/build/app/mod.rs, src/parse/errors.rs, src/parse/parser.rs, src/parse/validator.rs
Before, `Error::exit` didn't provide `WaitOnError`, requiring each call
site to duplicate half of `Error::exit`s behavior to get it.  This
hadn't been done for errors raised by derive-generated code.  Ideally,
these errors never happen but all the same, having this consistent would
be good.
This moves knowledge of `WaitOnError` to `Error` (including through
`Error::format`) so `Error::exit` can wait.  Now all of the callers to
`.exit` get a consistent experience without duplication.
While #2938 made a lot of `Error` fields optional for less churn-heavy
modifications, I made this new field required to minimize the risk of a
raise site forgetting to set it.
=> fix(derive): Support WaitOnError for derive-genned errors

src/parse/errors.rs
Technically, this also fixes a bug with an extra newline when building
with `debug` but that is a pretty minor cosmetic issue.  It is unclear
if `backtrace` has a trailing newline or not, so I left that as-is.
=> chore(error): Remove unused backtrace warning

clap_derive/tests/arg_enum.rs, clap_derive/tests/argument_naming.rs, clap_derive/tests/arguments.rs, clap_derive/tests/basic.rs, clap_derive/tests/boxed.rs, clap_derive/tests/custom-string-parsers.rs, clap_derive/tests/default_value.rs, clap_derive/tests/deny-warnings.rs, clap_derive/tests/explicit_name_no_renaming.rs, clap_derive/tests/flags.rs, clap_derive/tests/flatten.rs, clap_derive/tests/nested-subcommands.rs, clap_derive/tests/non_literal_attributes.rs, clap_derive/tests/options.rs, clap_derive/tests/raw_bool_literal.rs, clap_derive/tests/raw_idents.rs, clap_derive/tests/skip.rs, clap_derive/tests/special_types.rs, clap_derive/tests/subcommands.rs
`Parser::parse_from` will call `exit` on failure and we don't just lose
backtrace information but we don't even know which of the tests running
in parallel panicked.  I ran into this when experimenting with
`clap_derive` and I couldn't tell what actually failed.
So let's switch to `Parse::try_parse_from`.
Errors went from:
```
test option_option ... ok
error: Found argument 'bar' which wasn't expected, or isn't valid in this context
USAGE:
clap_derive [OPTIONS]
For more information try --help
error: test failed, to rerun pass '--test arg_enum'
```
To:
```
test option_option ... ok
test variant_with_defined_casing ... ok
test skip_variant ... ok
test default_value ... ok
test vector ... FAILED
test option_vector ... ok
failures:
---- vector stdout ----
thread 'vector' panicked at 'called …
```
=> test(derive): Provide better error info

src/parse/matches/arg_matches.rs
Added space after period in doc comment for `subcommand_name`.
=> Fix grammar in doc comment

src/build/usage_parser.rs
Besides being more explicit / clear, this makes it easier to experiment
with tweaking the logic and keeping the test updates minimal, so the
change of behavior stands out more.
=> test(usage): Make cases more consistent

src/build/arg/mod.rs, src/build/usage_parser.rs, tests/app_settings.rs, tests/posix_compatible.rs, tests/utils.rs
In looking at multiple occurrences and values for issues like #2692, I
noticed that `...` can mean both multiple values and multiple
occurrences, like before we split them.
Pros
- No syntax change with clap3
Cons
- All the reasons we split `multiple` into two
Uncertain
- I originally started this as part of another branch but I lost track
if something depended on this.  I'll have to do more digging
BREAKING CHANGE: If `--opt [val]...` was meant for
- only multiple occurrences, see `[opt]... --opt [val]`
- both multiple occurrences and values, see `[opt]... --opt [val]...`
=> fix(usage)!: Separate mutli-occ from multi-val syntax

src/macros.rs
Wow, I'm having a hard time summarizing this for the summary.
When we code-gen Settings using `impl_settings`, we have no control over
whether one instance of a Settings will use some or all functions.  I
have a fix that removes the one `ArgSettings::unset`, causing warnings
for `ArgSettings` despite needing it for `AppSettings`.
So I'm making it less dependent on how each instantiation uses it.
=> refactor: Allow partially used genned code

src/build/app/mod.rs, src/build/arg/mod.rs, tests/tests.rs
Though we store a lot of values as `&'help str`, we return them as
`&'self str`, making it so they can not be used programmatically as part
of a `App::mut_arg` call.
This loosens the lifetimes so they can be used with `App::mut_arg`.
This also includes a test simulating the desired workflow described in #2966
I skipped `get_all_aliases`.  I ran into problems with lifetimes with `all_subcommand_names`  and didn't quickly resolve it.  Rather than hold this up, I punted on it for now.
We'll have to tighten these back up with https://github.com/clap-rs/clap/issues/1041 but that will also enable turning them into owned strings, so this will still be possible after that issue is resolved, just the calls will be slightly different.
=> fix: Loosen reflection lifetimes

clap_generate/src/generators/shells/zsh.rs, src/build/arg/mod.rs, src/parse/parser.rs, tests/help.rs, tests/multiple_occurrences.rs
When supporting multiple occurrences for positional arguments in #2804,
I added some tests to cover this but apparently simpler cases fail
despite those more complicated cases being tested.
This adds more multiple-occurrences tests for positional arguments,
fixes them, and in general equates multiple values with occurrences for
positional arguments as part of #2692.  There are a couple more points
for consideration for #2692 for us to decide on once this unblocks them
(usage special case in #2977 and how subcommand help should be handled).
I fully admit I have not fully quantified the impact of all of these
changes and am heavily relying on the quality of our tests to carry this
forward.
=> fix: Always respect positional occurrences

clap_derive/Cargo.toml, clap_derive/tests/help.rs, tests/error.rs
PR #2979 reduced what dependencies we push on users and made us one step
closer to being able to test more with fewer features.  Looks like I
also need to update `clap_derive`.  I verified locally that #2976 fails
with this.
=> test: Easier to test with minimal features

src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/settings.rs, src/macros.rs
This is handling non-behavior changes in Settings as part of #2617
=> fix: Ease clap2->3 transition for Settings

src/build/usage_parser.rs
I noticed this while investigating #2692.  Since we are making
multiple-occurrences a thing for positional arguments, this allows us to
remove a special case.
Another way to look at this is that we should make the default whatever
we do for dervies (#1772).  I'm going to propose we make the derive
always turn `Vec<i32>` into multiple occurences and not multiple values
(with users being able to change it through attributes), but that is an
in-work proposal and not decided yet.
BREAKING CHANGE: `Arg::from(...)` will now use `multiple_occurrences`
for a positional `...`, rather than `multiple_values`.
=> fix(usage)!: Switch positionals... from multi-val to mulit-occur

src/parse/parser.rs
Similar to #2977, this changes positional argument `<subcmd>` in
`help <subcmd>` to be multiple occurrences, from being multiple values.
This is what identified the usage generation bug fixed in #2978 and was
isolated into the test case `positional_multiple_occurrences_is_dotted`.
This is part of #2692 where we re-evaluate the usage of multiple values
for positionals now that we accept multiple occurrences.
=> fix: Switch sub-commands from multi-val to multi-occur

src/parse/matches/matched_arg.rs
In #2985, I noticed #2834 was incomplete, there were case-insensitive
comparisons we were doing without being unicode aware (when compile
options are set).
The downside is that each comparison will require a UTF-8 validation.
These seem to be in more of corners of the API, rather than in common
calls in common usages, so hopefully that isn't too much of a problem.
=> fix: Allow unicode aware case insensitivity

src/build/app/mod.rs, tests/app_settings.rs
While #2966 communicated and solved a need, the API is fairly niche and has nuance that isn't quite clear.
#2976 generalized clap's API to allow filling the same need, lowering our reliance on `App::mut_args`, so I propose we go ahead and revert it.
=> Revert:  Add new App::mut_args for mutating all arguments #2966 

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/parse/arg_matcher.rs, src/parse/arg_predicate.rs, src/parse/matches/matched_arg.rs, src/parse/mod.rs, src/parse/validator.rs, tests/conflicts.rs, tests/require.rs
~As discussed, I have added the `contains_explicit_value` and used it instead of `is_default_value` and `contains_val`. Since `contains` is actually used in other places with a different semantic meaning, we should not be removing it.~
Some of the requirements and conflicts we have doesn't take default values into account and we have gotten multiple issues & bug reports around this because that is what user expects.
This PR is pretty straight forward in updating those conditions to take default value into account and fixes those bugs.
=> Follow up to #2950

examples/01a_quick_example.rs, examples/01b_quick_example.rs, examples/02_apps.rs, examples/04_using_matches.rs, examples/08_subcommands.rs, examples/20_subcommands.rs, examples/21_aliases.rs, src/build/app/mod.rs, src/macros.rs
This reverts commit 6898fbde334a46185d07bb40f51e4160ff67963f.
PR #2144 added the `license` field but no consumer has been added since
the (like Issue #1768).  Since this is not ready yet, I am pulling it
from the 3.0 release.
So far, our main route for pulling a feature from the release has
been to put it behind a `unstable-*` feature flag and to create a
stablization tracking issue.  I chose to instead remove the feature
because a write-only field with no effect does not provide values for
people to use in as an early access and so doesn't outweight the cost of
the extra documentation noise and code noise it creates.  Additionally,
keeping an `unstable-` feature around when it has such an unknown path
(and time table) to stalbization feels like it violates YAGNI.  I'm
uncertain how much …
=> Revert "Automatically read license field from Cargo.toml"

clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/args.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs
Looks like this is coming from `update_from_arg_matches` where we do a
ladder of `if __clap_arg_matches.is_present(...)` that clippy wants to
be `else if`s.  While for human edited code, that does clarify intent,
for machine generated code that is rarely read, its a pain to do, so
silencing it.
Unfortunately, it isn't in a group we can overall silence.
Fixes #3017
=> fix(derive): Don't emit warnings

src/build/app/mod.rs, tests/app_settings.rs
In #2851, we moved color from an AppSetting to function (with some
tweaks in #2907).  When doing this, we documented `App::color` to be
equivalent of `App::global_settings(Color...)` but never actually
propagated it.
We are now propagating it.  A test is added to ensure that no matter
how we store the color choice, we continue to propagate it.  This
required exposing `App::get_color`.
=> fix(app): Propogate color 

clap_derive/src/derives/args.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/parser.rs, clap_derive/src/derives/subcommand.rs, clap_derive/tests/generic.rs
Closes #2769
Unresolved questions:
=> Generic derive support

CHANGELOG.md
We have it marked as an `ArgSettings` when it is an `AppSettings`.
=> docs: Parent SubcommandPrecedenceOverArg under AppSettings

src/build/arg/mod.rs
Fixes links for short alias methods
=> Fix docs for Arg aliases

clap_generate/src/generators/shells/bash.rs, clap_generate/tests/completions/bash.rs
This issue came up in this pull request: https://github.com/casey/just/pull/1035
Right now bash completions break if you supply an alias to the clap command.
You have a program `just` and an alias `alias j=just`.
1. Source completions to your bash shell.
2. Add to your `~/.bash_profile` this line: `alias j=just`.
3. Add completions to the alias using the same completion function as just: `complete -o bashdefault -o default -F _just j`
2. Run `just <tab><tab>`. Completions appear as expected.
3. Run `j <tab><tab>` No completions appear.
This bug happens because the completion script hardcodes the executable name instead of looking for `$1`.
This PR addresses that bug.
=> Allow bash completions to work with an alias

src/build/app/settings.rs, src/lib.rs, src/parse/parser.rs
Until we have a modular help generator that can be configured and/or authored by the users themselves as part of #2914, we will provide the flexibility of turning off colored help messages but still wanting colored error messages.
This flexibility was available before #2845 and @dbrgn immediately noticed it and requested it back to which I agree. This was also suggested by Josh in [here](https://github.com/clap-rs/clap/issues/2806#issuecomment-933877438)
=> Add DisableColoredHelp setting to improve flexibility

Cargo.toml, examples/README.md, examples/keyvalue_derive.md, examples/keyvalue_derive.rs
This is carried over from the clap_derive examples.  Looking over the
other examples, I feel like they are covered by other examples or by the
derive reference.  We should call out deny missing docs though.
=> docs: Add key-value derive example

src/build/app/settings.rs
I missed this in my previous sweeps for re-adding-but-deprecating
Settings.
=> fix: Deprecation notice for UnifiedHelpMessage,

examples/demo.md, examples/demo.rs, examples/escaped_positional.md, examples/escaped_positional.rs, examples/escaped_positional_derive.md, examples/escaped_positional_derive.rs, examples/git_derive.md, examples/git_derive.rs, examples/keyvalue_derive.md, examples/keyvalue_derive.rs
mitsuhiko immediately jumped into the examples and got tripped up by the
lack of documentation on feature flags needed.
I limited this to just the root ones because the rest are in a more
proper tutorial that steps through it all.
=> docs: Call out features used in root examples

Cargo.toml
See https://twitter.com/wcrichton/status/1456112165744615426 or TWIR
415.
I'm mixed about the risk of using an unstable feature for our docs
though this seems like it'd be a big help.
=> docs: Include examples on docs.rs

.github/workflows/ci.yml, .github/workflows/rust-next.yml, Cargo.toml, Makefile, src/lib.rs, tests/examples.rs
My route to this was meandering as I played with how I wanted this enabled (e.g. I was playing with a `unstable-nightly` feature).  I figured the changes along the way were still worthwhile and kept them.
Fixes #3095
=> docs: Auto-tag feature flags 

src/build/arg/mod.rs, src/build/arg/settings.rs, src/parse/validator.rs
Intends to close #3072
Packs `Arg::exclusive` into `ArgSettings` to reduce memory overhead.
=> Use ArgSettings to store Arg::exclusive

src/build/app/settings.rs, src/build/arg/settings.rs, src/macros.rs
This is part of the deserialization logic on top of the builder that #3087 is targeted at.
This does involve a breaking change during the RC period (moving FromStr to the yaml feature) but it seems like a small enough case to be acceptable.
=> Deprecate Setting FromStr along with YAML

src/build/app/mod.rs
Now that we use options, we can rely on that, instead of sentinels, for
detecting a default and overriding only a default.
Noticed this as part of looking at #1807.
=> refactor: Clarify explicit display order wins

src/parse/matches/arg_matches.rs
With 3.0, we panic if the user passed in a bad arg, group, or subcommand name.  This makes the errors and backtraces more specific.
=> Improve error reporting for bad arg/group/subcommand names

clap_derive/src/derives/args.rs, tests/derive/main.rs, tests/derive/type_alias_regressions.rs
Fixes some additional unqualified types in the derive macros and adds a regression test case.
=> Fix unqualified result types causing compilation failures with derive implementations

clap_derive/src/derives/arg_enum.rs, tests/derive/type_alias_regressions.rs
My goal was just to expand the tests from #3142 to cover the basic derives but apparently, I found another case to qualify.
=> fix(derive): Allow aliased Option with ArgEnum

src/parse/matches/arg_matches.rs, tests/builder/utf8.rs
Current debug assertions around UTF-8 validations are not so friendly.
```
thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups', /path/to/clap-3.0.0-rc.4/src/parse/matches/arg_matches.rs:366:9
```
Users cannot know which argument was wrong. With this PR, the assertion message include ID information so that users can understand which argument was going wrong.
```
thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups at `name`', /path/to/clap-3.0.0-rc.4/src/parse/matches/arg_matches.rs:366:9
```
=> feat: Include argument ID in UTF-8 assertion messages

examples/README.md
I found that the link to pacman-like interface example was incorrect.
The PR fixes it.
=> docs: Fix pacman-like interface example link

src/lib.rs
See issue #3147, there is visual confusion between `SubCommand` and
`Subcommand`, only `SubCommand` is deprecated.
=> Improve `SubCommand` deprecation message.

examples/tutorial_builder/04_02_validate.rs
This PR will fix a small error in one of the builder api examples, which was most likely introduced through copy paste :D
=> docs: Fix copy paste error in example

README.md, clap_generate/CONTRIBUTING.md, clap_generate/README.md
Inspired by #2828, this connects clap to clap_generate to clap_generate_fig as well as lists out our current policy for shell completion crates.
=> Expand clap_generate's documentation

examples/multicall_busybox.md, examples/multicall_busybox.rs, examples/multicall_hostname.md, src/build/app/mod.rs, src/build/app/settings.rs, tests/builder/subcommands.rs
This follows the suggestion of Ed Page in #2861 that simplifying the behaviour and making it less magic could solve some problems.
Having spent some time writing an app to try it out this has proven correct.
Now if you want busybox-style where each applet is also available as a subcommand, you have to code it explicitly.
This is inconvenient when using it as a builder, but not too much trouble with `clap_derive`
```rust
#[derive(Args)]
struct False {}
#[derive(Args)]
struct True {}
#[derive(Parser)]
enum Busybox {
False(False),
True(True),
}
#[derive(Parser)]
#[clap(setting = AppSettings::Multicall)]
enum Applet {
#[clap(subcommand)]
Busybox(Busybox),
False(False),
True(True),
}
let applet = Applet::parse();
match applet {
Applet::Busybox(Busybox::True(true_args)) | …
```
=> Rewrite Multicall handling to just strip path off argv0

src/parse/arg_matcher.rs
I found one warning from `cargo check --release`. This PR fixes it.
```
warning: unused variable: `app`
--> src/parse/arg_matcher.rs:19:23
|
19 |     pub(crate) fn new(app: &App) -> Self {
|                       ^^^ help: if this is intentional, prefix it with an underscore: `_app`
|
= note: `#[warn(unused_variables)]` on by default
warning: `clap` (lib) generated 1 warning
```
=> Fix unused parameter warning

clap_generate/src/generators/shells/zsh.rs, src/build/app/settings.rs, src/build/arg/settings.rs, src/build/arg/value_hint.rs, src/parse/errors.rs
Without being a breaking change.
This seems minor enough that we can break this during the release
candidates.  For `ValueHint`, the completion scripts are 99% of who
should be `match`ing it.  `AppSettings` as undocumented variants that
people shouldn't use.
BREAKING CHANGE: `clap::{ValueHint, ErrorKind, AppSettings,
ArgSettings}` are now `non_exhaustive`.
=> fix!: Allow adding new enum variants

src/parse/errors.rs, tests/builder/error.rs, tests/builder/help.rs
Related to #2787.
I didn't update the CHANGELOG because this looks like a regression; it looks like clap3 always added a newline.
=> Ensure trailing newlines at the end of errors

CHANGELOG.md, clap_derive/src/attrs.rs, clap_derive/src/derives/args.rs, tests/derive/default_value.rs
The test went from panicing to not-panicing
Fixes #3031
=> fix(derive): Treat `default_value_os` like `default_value`

clap_derive/src/utils/doc_comments.rs, src/build/app/mod.rs, src/build/arg/mod.rs, tests/derive/doc_comments_help.rs
The main care about is that when we override a `flatten` / `subcommand` doc comment in a parent
container, that we make sure we take nothing from the child container,
rather than implicitly taking one `about` ut not `long_about`.
To do this, and to play the most safe with long help detection, we reset
`long_about` to default when there is no doc comment body to use for
`long_about`.
Fixes #2983
BREAKING CHANGE: We changed the signatures for `App::about`,
`App::long_about`, `Arg::help`, and `Arg::long_help` from accepting anything `Into<&str>` to `&str`.
=> fix(derive)!: Set both about/long_about with doc comments 

clap_generate/Cargo.toml, clap_generate/README.md
Using relative paths will work from github but when we include
`README.md` into `lib.rs`, they will break.
=> docs(gen): Use absolute paths for docs.rs sake

examples/demo.md, examples/derive_ref/custom_bool.md, examples/escaped_positional.md, examples/escaped_positional_derive.md, examples/git.md, examples/git_derive.md, examples/tutorial_builder/README.md, examples/tutorial_derive/README.md, src/output/help.rs, tests/builder/app_from_crate.rs, tests/builder/app_settings.rs, tests/builder/arg_aliases.rs, tests/builder/arg_aliases_short.rs, tests/builder/cargo.rs, tests/builder/flag_subcommands.rs, tests/builder/help.rs, tests/builder/hidden_args.rs, tests/derive/doc_comments_help.rs
The extra whitespace was targeted at machine processing for a subset of
users for a subset of runs of CLIs.  On the other hand, there is a lot
of concern over the extra verbose output.
A user can set the help template for man, if desired.  They can even do
something (env? feature flag?) to make it only run when doing man
generation.  We also have #3174 in the works.
So let's focus on the end-user reading `--help`.  People wanting to use
`help2man` have workarounds to do what they need.
Fixes #3096
=> revert(help): Partial revert of 3c049b4

clap_derive/src/attrs.rs, clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/args.rs, clap_derive/src/parse.rs, examples/derive_ref/README.md, src/build/arg/possible_value.rs, tests/derive/arg_enum.rs
While I'm unsure how much type specialization we should do, we
intentionally have the `arg_enum` attribute for doing special behavior
based on it, so let's take advantage of it.
By loosening `PossibleValue`s lifetimes for this, we also avoid a `lazy_static!` and string allocation.
Fixes #3185
=> feat(derive): Don't require Display for default ArgEnum

Cargo.toml, src/lib.rs
Confirmed this works with [`argfile`](https://docs.rs/argfile/latest/argfile/)
And then running in clap
```
$ RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
```
They now show up!
=> docs: Show features in docs.rs

src/derive.rs
And other derive tweaks.  I'm mixed on how far to go, including
- Linking to the derive reference
- Showing how to use each trait with both the derive and builder APIs
For now, this is an improvement.
=> docs(derive): Call out need for derive feature

src/parse/parser.rs, tests/builder/help.rs
=> fix(help): Don't infer long help from subcommands

examples/tutorial_builder/README.md, examples/tutorial_derive/README.md, src/build/app/mod.rs, src/parse/arg_matcher.rs, src/parse/errors.rs, src/parse/validator.rs, tests/builder/conflicts.rs
After some refactors to pave the way, this re-does the conflict code to disambiguate the groups an argument is a member of from the groups it conflicts with.
Now we only gather real conflicts and then report **all** of them (might as well since we have them and we went through work to do that for requireds).  Behind the scenes, we gather the potential one-way or direct conflicts and cache them.  This let's us both reuse the code and reuse the results for then calculating the reverse conflicts (A conflicts with B, therefore B conflicts with A).  By finding the reverse like this, we avoid needing to check the order of conflicts (and invert them) when reporting errors, simplifying the code.  This isn't too bad because we were able to reuse our iterating over all of the arguments.
Reusable …
=> fix: Don't panic on lack of conflicts 

src/build/app/mod.rs, src/build/arg/mod.rs, src/parse/arg_matcher.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs, src/parse/validator.rs, tests/builder/posix_compatible.rs
This allows two overriding args to interact with each other mid-line.
This was broken in 7673dfc / #1154.  Before that, we duplicated the override
logic in several places.
Now we plug into the start of a new arg which allows us to do this
incrementally without making the logic complex or inefficient, thanks to
the refactors in this PR.
Fixes #3217
=> fix: Remove overriden occurrences as we go 

CHANGELOG.md, src/build/usage_parser.rs, src/output/help.rs, tests/builder/help.rs
This reverts commit 333b993481396d84197bd6e5b54c526a3b04e6a1.
PR #1810's motivation was effectively "this is redundant with `\n`".
That is a fine motivation.  Unfortunately, we don't have a way to force
a hard break in `clap_derive`.  #2389 should help with this eventually
but we shouldn't hold up 3.0 to get that ready.  So in the mean time, we
are restoring `{n}`.
We have #3230 for tracking the re-removal of it.
=> Revert "Remove {n} support"

src/output/help.rs
When we got #3193, we decided in #3196 that `--help` will give a summary
for other commands (`subcmd --help` in this case) but not show the long
version of the output for that other command.
Now with #3215, I think the case is similar for `--help` not showing the
long version but instead preferring the short version and encouraging
people to run `--version`.
Originally. clap only showed the short version or nothing.  This was
changed in #2369 without fanfare to prefer the long version over short.
Now are we preferring short version over the long version always, just
like all other help.
Fixes #3215
=> fix(help): Prefer short version over long version

clap_complete/src/generator/mod.rs
Use `shells::Bash` instead of `generators::Bash`
=> docs(complete): Fix imports in documentation

clap_derive/src/derives/args.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, tests/derive/deny_warnings.rs
We missed covering `Args` warnings when using struct variants.
Fixes #3245
=> fix(derive): Don't enit warnings

src/parse/matches/arg_matches.rs
I was tempted to remove the exact-size nature.  Wouldn't be breaking
since it only panics but decided to go ahead and do this for now.
Fixes #3241
=> fix: Don't panic when getting number of values

src/build/app/debug_asserts.rs, src/build/arg/debug_asserts.rs
Ran into one of these being a pain with porting cargo.
=> fix: Clarify cause of debug asserts

src/parse/matches/arg_matches.rs
Cargo is an example of a user that heavily relied on using undefined
names because there is a lot of code sharing between commands.  This
allows a path forward for those users that is just painful enough to
discourage overly relying on it in the future :).
=> feat(parser): Allow users to avoid undefined arg asserts
