clap-rs/clap

src/app.rs, src/args/argmatches.rs, src/args/optarg.rs
Add support for multiple option arguments (such as "-c some -c other -c value")
=> Closes #17

src/app.rs, src/args/argmatches.rs, src/args/subcommand.rs
Changed App name, version, about, author, and usage to allow lifetimes other than 'static
=> Closes #28

src/app.rs, src/args/argmatches.rs, src/args/posarg.rs
Add support and assertions for positional arguments which take multiple values (provided they are they have the highest index of all the positional arguments...i.e. are the last one).
=> Closes #44

src/app.rs
=> fix(positional args): all previous positional args become required when a latter one is required

examples/01a_QuickExample.rs, examples/12_TypedValues.rs, src/macros.rs
=> Adds convenience macros to get typed values

examples/13a_EnumValuesAutomatic.rs, src/macros.rs
This feat allows more complete enum implementations such as `pub` and `#[derive()]` directives
Err type of FromStr trait changed from &'a str->String in order
to allow showing valid values on failed parse
Breaking Change
=> feat(macros): add ability to create enums pub or priv with derives

Cargo.toml
=> chore(cargo): fix documentation URL

clap-tests/run_tests.py, src/app.rs
=> Less color

src/app.rs
I'll look for more typos when I have some more time. :smile:
=> Documentation typo fixes

README.md
=> docs(readme): use with_name for subcommands

Cargo.toml, clap-tests/run_tests.py, src/app.rs, src/macros.rs
=> imp: writes errors to stderr

src/app.rs, src/fmt.rs
=> fix: fixes formatting bug which prevented compiling on windows

Cargo.toml, src/app.rs, src/args/argbuilder/option.rs, src/args/argmatches.rs, src/lib.rs, src/macros.rs
Uses [rust-clippy](https://github.com/Manishearth/rust-clippy) to assist with code correctness.
=> imp: code corrections thanks to rust-clippy

src/app.rs, src/args/arg.rs, src/args/argbuilder/option.rs, src/args/argbuilder/positional.rs
=> feat(Args): allows for custom argument value validations to be defined

src/app.rs, src/args/arg.rs, src/args/argbuilder/flag.rs, src/args/argbuilder/option.rs, src/args/argbuilder/positional.rs, src/macros.rs
I added a code for Issue  #176.
This was not tested, because of, I think, first we need to switch standalone tests to unit test as in #166. 
Mutually exclusive rules take precedence over being overridden, and mutually override rules take precedence over being required.
=> Added overrides to support conflicts in POSIX compatible manner

src/lib.rs
Now It`s three tests 
* long flags
* short flags
* mixed
=> Rewrote test for multiple occurrences

src/app.rs
This fixes #184 
It panics on 
```
let m = App::new("req_overridden")
.arg(Arg::from_usage("-f, --flag 'some flag'")
.requires("color"))
.arg(Arg::from_usage("-c, --color 'some other flag'")
.mutually_overrides_with("debug"))
.arg(Arg::from_usage("-d, --debug 'another other flag'"))
.get_matches_from(vec!["", "--flag", "-c", "-d"]);
```
Also i think `required` field is useless now, isn't it?
=> Fixed requirmets overriding

src/app.rs, src/lib.rs
This fix #188.
Also added test.
=> Fixed subcommand reqs negation

examples/16_AppSettings.rs
=> examples: Add AppSettings example

README.md
https://img.shields.io/crates badges sometimes works bad, sometimes doesn't work at all (as it now)
=> Changed crates.io badges

CONTRIBUTING.md, README.md
=> Fixed README.md and CONTRIBUTING.md

src/app.rs
=> fix(Unified Help Messages): fixes a crash from this setting and no opts

examples/14_Groups.rs, src/app.rs, src/args/group.rs
=> Changed Vec<&str> using to &[&str] for several ArgGroup methods

src/app/app.rs
=> fix(Conflicts): fixes bug with conflicts not removing required args

src/app.rs, src/macros.rs, tests/app.rs
=> Redesign: rename get_matches and add --long=option

src/arg.rs, src/error.rs
See #259.
An interesting idea could be chaining multiple validator.
r? @james-darkfox
=> feat: add validator

src/app/app.rs
=> fix(Possible Values): possible value validation is restored

src/app/app.rs
=> fix(Help Message): required args no longer double list in usage

examples/14_groups.rs
=> docs: fixes panic in 14_groups example

README.md, src/app/app.rs, src/app/errors.rs, src/app/settings.rs, src/args/arg.rs, src/args/argbuilder/positional.rs, src/args/group.rs, src/args/subcommand.rs, src/lib.rs, src/macros.rs
Hi,
I went through and fixed a few typos in comments here and there. I've changed the comments in the code, and the readme, but nowhere else. No code has changed other than doc comments, and the tests still pass!
=> Fix a bunch of typos in comments

clap-tests/run_tests.py, clap-tests/src/main.rs
Relates to #335 
Notably missing thing such as testing `AppSettings`
=> tests(Exit Codes): adds some formatting and exit code testing

README.md, appveyor.yml, src/errors.rs, src/fmt.rs, src/suggestions.rs, tests/unicode.rs
for windows build tests.
**Do not merge, yet**
=> Added appveyor

README.md
Fixes sentence with missing word in README.md
=> Fixes missing word in README

tests/help.rs
=> tests(help): add tests for help subcommand

Cargo.toml
Just re-syncs to a true v1-master
=> V1 master update

src/macros.rs
=> fix: clap_app! should be gated by unstable, not nightly feature

README.md
I originally set out to only change liftimes to lifetimes, but I got a little carried away.
Fear not, I decided to stop myself partially through and actually start using your library!
=> Grammatical pedantry

CHANGELOG.md, Cargo.toml
=> chore: increase version

Cargo.toml, src/app/parser.rs
@alexbool 
This is the new PR for your commit - no further action required, all rebasing is good!
=> Update VecMap to 0.6

CHANGELOG.md, Cargo.toml, README.md, clap-test.rs, src/app/help.rs, src/app/mod.rs, src/app/parser.rs, tests/app_settings.rs, tests/help.rs, tests/hidden_args.rs, tests/template_help.rs, tests/version.rs
=> Quick issues

src/app/mod.rs, src/app/parser.rs, src/completions.rs, tests/completions.rs
to write completions to buffer (e.g. stdout) instead of file. fixes #566 
(for review; will fix commit message when done)
still pretty new to rust so comments on anything from style to structure would be must appreciated!
=> add `gen_completions_to`

tests/require.rs
I created Issue #575. This is the pull request that includes the test case where the second argument is specified, which from my understanding should work.
Thank you for the great work by the way.
=> Unless one fail: Test for Issue #575

src/app/parser.rs, src/completions.rs, src/lib.rs
=> Wdv4758h fish completion

.travis.yml, Cargo.toml, README.md
=> docs: moves docs to docs.rs

src/app/help.rs
Addresses comments on https://github.com/kbknapp/clap-rs/commit/c76785239fd42adc8ca04f9202b6fec615aa9f14
=> Fix redundant contains() checks

src/app/help.rs, src/app/meta.rs, src/app/mod.rs
=> Allow for limiting detected term width

src/app/settings.rs
=> Document AppSetting::DisableVersion

src/app/help.rs, src/app/parser.rs
I was fixing the clippy errors, but saw afiuna had already fixed them.
This is what's left after I rebased.
=> Some refactors / cleanups

src/completions.rs
=> fix(Completions): fish completions for nested subcommands

src/app/help.rs, src/app/mod.rs, src/app/parser.rs, src/args/arg_builder/mod.rs, src/args/arg_builder/option.rs, src/args/mod.rs, src/completions.rs, src/lib.rs
Why are lints denied when nightly is allowed to fail on travis?
=> Fix more lints

README.md
=> docs(README.md): fixes failing yaml example

README.md
=> Fix typo: 2.12.0 -> 1.12.0

README.md, src/app/mod.rs
Just some typos I noticed while reading the docs.
=> Spelling in docs

examples/18_builder_macro.rs, src/macros.rs, tests/macros.rs
=> Support `("some string")` for app names and long arg names in clap_app!

src/app/help.rs, src/app/macros.rs, src/app/parser.rs, src/args/arg_builder/option.rs, src/args/arg_matcher.rs, src/completions/bash.rs, src/completions/fish.rs, src/completions/mod.rs, src/completions/powershell.rs, src/completions/zsh.rs, src/fmt.rs, src/macros.rs, src/osstringext.rs, src/usage_parser.rs
=> style: standardizes debug calls and output

examples/20_subcommands.rs, tests/macros.rs
I'm seeing some warnings when running `cargo test` and this should fix them.
=> Fix compilation warnings

src/macros.rs
I need these changes to get all of the tests to pass on Linux.
=> tests: fix clap_app! doctest

Cargo.toml, clap-test.rs
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
=> switch to regex 0.2

src/app/parser.rs
=> Propagate terminal widths to subcommands

src/app/mod.rs, tests/app_settings.rs
Probably should have done that immediately before opening an issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/910)
=> Implement name setter on App; fixes #908

src/app/mod.rs, tests/yaml.rs
Fixes #912.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/914)
=> Add support for loading author info from yaml

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/app/usage.rs, tests/help.rs
cc @BurntSushi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/916)
=> Usage regression

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/args/arg.rs, tests/help.rs
Fixes BurntSushi/ripgrep#426 and BurntSushi/ripgrep#418
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/921)
=> Template fix

CHANGELOG.md, Cargo.toml, README.md, src/app/parser.rs, src/app/settings.rs, src/app/usage.rs, src/app/validator.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, tests/delimiters.rs, tests/help.rs, tests/positionals.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/947)
=> Issues 940,944,946

src/args/arg_builder/positional.rs, tests/help.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/955)
=> fix: fixes a bug where positional argument help text is misaligned

Cargo.toml, tests/help.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/954)
=> Dependency update

examples/09_auto_version.rs, examples/17_yaml.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/956)
=> trivial typo fixes

CHANGELOG.md, Cargo.toml, README.md, src/app/mod.rs, src/app/parser.rs, src/args/arg.rs, src/macros.rs, tests/groups.rs, tests/opts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/961)
=> Issue 960, 949, 917, and 932

src/app/parser.rs, src/app/settings.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/969)
=> fix: Change `who's` -> `whose`

.mention-bot, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/973)
=> Dep resolution docs

examples/22_stop_parsing_with_--.rs
Closes #971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/977)
=> Add slop example

src/app/help.rs, src/app/macros.rs, src/app/parser.rs, src/app/settings.rs, src/app/usage.rs, src/app/validator.rs, src/args/arg_builder/positional.rs, src/args/group.rs, src/args/macros.rs, src/args/settings.rs, src/completions/powershell.rs, src/fmt.rs, src/lib.rs, src/macros.rs
Ideally, we should be able to compile `clap` with clippy without any warning.
I've started to fix them but since there are too many for a PR to be easily reviewable, here is a first batch.
I try to group the commit by type of warnings I fix but I can squash it all if you prefer.
Also let me know if you prefer only one big PR that fixes them all (it might take a while though).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/985)
=> Some clippy fixes

examples/22_stop_parsing_with_--.rs
https://github.com/kbknapp/clap-rs/issues/971#issuecomment-309503995
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/991)
=> Make -- mandatory for the slop example

.github/ISSUE_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1004)
=> Fix up typo and minor grammar

.github/ISSUE_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1006)
=> Fixed grammar and improved formatting of github issue template

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/app/macros.rs, src/app/parser.rs, src/app/validator.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/macros.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1016)
=> Unicode segmentation bump

src/suggestions.rs, tests/subcommands.rs
Fixes #1018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1019)
=> Fix suggestions for flags under subcommands

SPONSORS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1028)
=> chore: adds a sponsors file

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/app/parser.rs, src/app/validator.rs, src/lib.rs, tests/help.rs, tests/opts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1045)
=> Issues 1043,1044

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/app/parser.rs, tests/help.rs, tests/opts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1048)
=> Issues 1046,1047

Cargo.toml, src/app/help.rs, src/lib.rs
Fixes https://github.com/kbknapp/clap-rs/issues/1055.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1059)
=> Reorganize optionally depending on term_width

src/app/help.rs, src/app/mod.rs, src/app/parser.rs, src/app/validator.rs, src/args/any_arg.rs, src/args/arg.rs, src/args/arg_builder/flag.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, src/args/arg_builder/valued.rs, tests/default_vals.rs, tests/env.rs
Closes #814 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1062)
=> Bluejekyll from env

src/app/help.rs, src/args/arg_builder/option.rs, src/args/arg_builder/positional.rs, tests/help.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1067)
=> Issue 1052

src/app/mod.rs, tests/global_args.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1077)
=> Issue 1076

CHANGELOG.md, Cargo.toml, README.md, src/app/parser.rs, src/app/validator.rs, src/args/arg.rs, src/lib.rs, tests/app_settings.rs, tests/conflicts.rs, tests/default_vals.rs, tests/multiple_values.rs, tests/subcommands.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1079)
=> Issues 1031,1050,1056,1066,1071

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1080)
=> chore: fix copy paste typo

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1081)
=> Fix typo in minimum required Rust version

CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
Closes #1083 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1084)
=> Issue 1083

src/app/settings.rs
Fixes #1086.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1087)
=> fix: ignore PropagateGlobalValuesDown deprecation warning

src/app/settings.rs, src/app/usage.rs, src/args/settings.rs, src/completions/shell.rs, src/completions/zsh.rs, src/macros.rs, tests/app_settings.rs, tests/macros.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1096)
=> Issues 1093,1095

src/app/mod.rs
`combile` -> `compile`
Thank you for this nice crate!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1100)
=> docs: fix typo

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1101)
=> bump ansi_term to 0.10

src/app/settings.rs, src/args/settings.rs, src/completions/shell.rs, src/completions/zsh.rs, src/macros.rs
Closes #1095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1102)
=> chore: fixes the attribute to allow unused imports on nightly

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1107)
=> bump version-sync to 0.4

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1111)
=> bump version-sync to 0.5

src/app/parser.rs, src/app/settings.rs, tests/help.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1113)
=> Issue 1112

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1117)
=> Clap derive

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1121)
=> bump lazy_static to 1

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/args/arg.rs, src/args/settings.rs, src/lib.rs, tests/help.rs
cc @softprops
Once this merges I'll put out v2.29.0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1122)
=> Hide env vars

src/completions/bash.rs, tests/completions.rs
Fixes <https://github.com/kbknapp/clap-rs/issues/1129>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1130)
=> Fix for issue #1129: "Bug: Bash completion is broken when sub-commands have hyphens"

src/completions/mod.rs, tests/completions.rs
Fixes #1142
(Hopefully didn't break anything, the tests didn't break at least)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1144)
=> fix(completions/zsh.zsh): Remove redundant code from output

examples/19_auto_authors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1146)
=> fix: Fix typos

SPONSORS.md
:tada:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1148)
=> chore(SPONSORS.md): adds the latest sponsor! Yay

examples/14_groups.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1149)
=> Fix doc typo in 14_groups.rs

src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1152)
=> chore: fix html_doc_root

Cargo.toml
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1153)
=> deps: update strsim to 0.7

README.md, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1163)
=> chore: updates the version tests

examples/01a_quick_example.rs, examples/01b_quick_example.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1168)
=> style: indent lines

.travis.yml
Trying to fix some Travis issues and make the builds a little faster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1181)
=> chore: stops benching on nightly and fixes kcov

src/completions/powershell.rs, tests/completions.rs
Also fixed some small issues with subcommand detection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1189)
=> Use short help as tooltip in PowerShell completion

src/args/arg.rs
This is a reapplication of the work done in #1188 to clean up commit history
cc: @kbknapp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1191)
=> Raw arg functionality

README.md
A small change that might save people some frustration :sweat_smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1195)
=> Hinting that "wrap_help" is a thing

CHANGELOG.md, Cargo.toml, README.md, src/app/help.rs, src/app/mod.rs, src/app/settings.rs, src/args/arg.rs, src/completions/fish.rs, src/completions/powershell.rs, src/errors.rs, src/lib.rs, src/macros.rs, tests/completions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1218)
=> backporting 2.x fixes and features

examples/14_groups.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1219)
=> clippy: A couple of markdown fixes and a typo fix.

examples/01a_quick_example.rs, examples/01b_quick_example.rs, examples/04_using_matches.rs, examples/06_positional_args.rs, examples/07_option_args.rs, examples/08_subcommands.rs, examples/18_builder_macro.rs, examples/21_aliases.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1220)
=> clippy: Remove needless borrows.

CHANGELOG.md, README.md, benches/03_complex.rs, clap-test.rs, examples/05_flag_args.rs, examples/06_positional_args.rs, examples/07_option_args.rs, examples/10_default_values.rs, examples/12_typed_values.rs, examples/17_yaml.rs, examples/20_subcommands.rs, src/app/help.rs, src/app/mod.rs, src/app/parser.rs, src/app/settings.rs, src/completions/mod.rs, src/completions/zsh.rs, src/lib.rs, src/macros.rs, tests/app.yml, tests/help.rs, tests/macros.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1221)
=> chore: Fix typos.

clap-test.rs, src/app/validator.rs, src/args/arg.rs, src/completions/powershell.rs, src/errors.rs, tests/arg_aliases.rs, tests/completions.rs, tests/propagate_globals.rs, tests/tests.rs
This makes some further progress towards being cleaner under clippy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1224)
=> Clippy fixes

src/macros.rs, tests/macros.rs
Fixes https://github.com/kbknapp/clap-rs/issues/1231.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1238)
=> imp(macros): Support shorthand syntax for ArgGroups

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1263)
=> chore: bump textwrap version to 0.10.0

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1266)
=> chore: Update to regex 1.0.

benches/06_rustup.rs
Simple fix for compilation error in the benches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1279)
=> fix(benches): Fix compilation error

examples/05_flag_args.rs, examples/06_positional_args.rs
Very minor, but led to a couple minutes of confusion today.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1272)
=> examples: Method rename

.github/ISSUE_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1293)
=> chore: adds a details block the issue template

.github/ISSUE_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1294)
=> chore: forgot pre html tag

src/app/parser.rs, tests/app_settings.rs
Closes #1254.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1298)
=> exactly match a subcommand when using the infersubcommands

src/app/parser.rs, src/completions/elvish.rs, src/completions/mod.rs, src/completions/shell.rs, tests/completions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1302)
=> feat(Completions): adds completion support for Elvish.

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1305)
=> fixed typo for coveralls key

Cargo.toml, src/app/mod.rs, src/app/settings.rs, src/args/arg.rs, src/args/settings.rs, src/errors.rs, src/lib.rs, src/macros.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1308)
=> docs: fix some broken doc links, formatting, and warnings.

src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1311)
=> refactor: Changed the custom derive traits

src/build/arg/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1312)
=> imp: Hash for Arg

src/app/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kbknapp/clap-rs/1322)
=> imp: add long_version support in YAML parsing

README.md
s/finetuning/fine-tuning/
s/decleare/declare
=> doc: fix two typos.

src/app/parser.rs
I have not tested this change.
=> Fix typo in comment

Cargo.toml
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> update strsim to 0.8

examples/17_yaml.rs, src/build/arg/mod.rs, src/build/macros.rs
=> Yaml mismatched types char

.travis.yml
Simplifies development to focus on one target
=> test: remove support for old and stable targets

Cargo.toml, src/args/arg.rs, src/args/group.rs, src/lib.rs
Fixes #1387 
`cargo test --feature "yaml"` passes
=> Upgrading yaml-rust to 0.4.2

src/app/mod.rs
Fixes docs for https://docs.rs/clap/latest/clap/struct.App.html#method.template
=> Fix App::template docs

src/output/help.rs
=> style(help): add newline after writing help

README.md
Adds a temporary note for contributors till v3-m branch is merged with master.
=> Add note for 3.0 release

src/lib.rs
Hiya!  I _LOVE_ clap.   Here's a *tiny* contribution.
=> add missing 'the'

src/parse/matches/arg_matches.rs
Well...  if you're going to be super responsive...   !  ;)
=> where -> were

benches/03_complex.rs, benches/05_ripgrep.rs, benches/06_rustup.rs, examples/14_groups.rs, examples/18_builder_macro.rs, src/build/app/mod.rs, src/lib.rs, src/output/help.rs, src/parse/arg_matcher.rs, src/parse/parser.rs, src/util/fnv.rs, src/util/osstringext.rs, tests/app_settings.rs, tests/arg_aliases.rs, tests/conflicts.rs, tests/derive_order.rs, tests/groups.rs, tests/help.rs, tests/hidden_args.rs, tests/opts.rs, tests/positionals.rs, tests/possible_values.rs, tests/propagate_globals.rs, tests/require.rs, tests/subcommands.rs, tests/template_help.rs, tests/tests.rs, tests/version.rs
- Manually fix some problems
- Run 'cargo fix --clippy'
Related to #1037.
=> Fix some clippy lints

README.md
=> fixes the custom derive example in the readme

src/parse/errors.rs, src/parse/parser.rs, src/parse/validator.rs
The cause field is the actual error described in the message field,
however without extra information like usage.
Close #861
=> feat(Error): add a cause field to the Error struct

src/parse/parser.rs, tests/version.rs
=> Don't write --version output directly to stdout.

src/build/usage_parser.rs
Fixes #1034 
The niceer [default: X] format is possible, but I don't want add more complexity to this manual parser. (I suggest parser generator for v3).
=> imp(usage_parser.rs): add default value support

examples/05_flag_args.rs, examples/06_positional_args.rs, examples/07_option_args.rs, src/build/arg/mod.rs, src/parse/validator.rs, tests/app.yml, tests/conflicts.rs
Closes #1583 
https://twitter.com/CliRust/status/1212441368317976576
=> feat: Add `Arg::conflicts_with_everything` method #1583

src/build/arg/mod.rs
Related to https://github.com/clap-rs/clap/pull/1624
=> fix: Typos in Arg::conflicts_with_everything`

CHANGELOG.md, tests/app_from_crate.rs, tests/cargo.rs
When you approve this PR, instead of merging it, please comment "bors r+". I want to test the bors workflow.
=> Added tests for cargo macros, fixes #1478

src/build/arg/mod.rs
=> added check for -

src/output/help.rs
Hello everybody, this is my first pull request on github ever. I found a typo in src/output/help.rs. I hope I submitted this pull request the correct way.
=> Fixed typo in help.rs

src/build/app/mod.rs, src/build/app/settings.rs, tests/help.rs
Closes #1683 
There are likely some problems with my solution to this issue. I would be thankful for a review!
=> Added HelpRequired AppSetting

README.md
=> Add "work in progress" disclaimer to readme

clap_derive/tests/boxed.rs, src/derive.rs
=> Implement derive traits for Box<T>

clap_derive/examples/example.rs, clap_derive/examples/keyvalue.rs, clap_derive/examples/skip.rs, clap_derive/src/derives/attrs.rs, clap_derive/src/derives/doc_comments.rs
A work on #1671. Attention! It doesn't close it just yet
=> Remove some mentioning of structopt

clap_generate/src/lib.rs, src/build/app/mod.rs, src/parse/parser.rs, src/parse/validator.rs
=> Fix warnings on nightly

.github/PULL_REQUEST_TEMPLATE.md, bors.toml
This would properly cut it. I had looked into bors code today. https://github.com/bors-ng/bors-ng/pull/886 should fix the issue where we are waiting for CI to finish.
=> Changes to bors

src/derive.rs
Looks like a copy-paste error :)
=> Fix Clap::try_parse_from documentation

.github/ISSUE_TEMPLATE/bug_report.md
=> Tidy up the bug report template

src/parse/errors.rs, src/parse/features/suggestions.rs, src/parse/parser.rs, tests/subcommands.rs
=> Ambiguous suggetions for InferSubcommands

.azure-pipelines.yml, .travis.yml, Cargo.toml, src/macros.rs
=> Make cargo feature additive

clap_generate/src/generators/shells/bash.rs
Closes #1627 
Cherrypicking his commit.
=> fix: bash completions with app name which contains `-`

bors.toml, clap_derive/src/derives/clap.rs, clap_derive/src/derives/from_argmatches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/mod.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/lib.rs, clap_derive/tests/basic.rs, clap_derive/tests/privacy.rs
=> Unit struct

src/build/app/mod.rs, tests/require.rs
Fixes #1643
God bless @kbknapp for extensive debug logging.
I'm really sorry that I'm not putting a lot of effort into bugfixing, despite all the promises. I don't really know when I'll be back to 100% capacity. It sucks.
=> Fix core dump with mutually `requires()` args

Cargo.toml, benches/01_default.rs, benches/02_simple.rs, benches/03_complex.rs, benches/05_ripgrep.rs, benches/06_rustup.rs, clap_derive/Cargo.toml, clap_generate/Cargo.toml
=> Use GH actions/continuous_becnchmark

.github/workflows/ci.yml, .travis.yml, Cargo.toml, benches/01_default.rs, benches/02_simple.rs, benches/03_complex.rs, benches/06_rustup.rs, src/parse/features/suggestions.rs
=> Basic github action for benchmarking

clap_derive/examples/skip.rs, clap_derive/src/derives/from_argmatches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, clap_derive/tests/options.rs, clap_generate/tests/completions.rs, examples/14_groups.rs, tests/app_settings.rs, tests/require.rs
With this, our CI logs will hopefully become clean.
=> Derive clippy

src/build/app/mod.rs, src/mkeymap.rs, src/parse/validator.rs
=> Get rid of extra scopes

.github/workflows/benchmark.yml
=> Fix benchmarks to not use fork anymore

Cargo.toml
=> Select a single docs.rs build target

src/macros.rs
=> Fix value_t documentation

README.md
=> Remove extern crate from README

.travis.yml, src/build/arg/mod.rs, src/macros.rs, src/parse/arg_matcher.rs, tests/macros.rs, tests/multiple_values.rs
Cherry picks #1481. Closes #1480, #1800
=> Few ports from v2

tests/opts.rs
=> Add test for suboptimal flag suggestion

Cargo.toml, src/build/app/mod.rs, src/output/fmt.rs
=> Enable ansi support for windows before refactoring

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/macros.rs, tests/macros.rs
Closes #1762, Closes #1035, Closes #1347
=> Allow literals in builder macros

.github/workflows/benchmark.yml, .github/workflows/linux.yml
Comments are too many notifications. So, I changed it to annotations. If we want to see benchmark, we can just go into the check run. https://github.com/clap-rs/clap/actions/runs/77205807
=> Benchmark annotations

src/macros.rs
=> Suppress `unused_valiables` lint in non-debug builds

.github/workflows/benchmark.yml, .github/workflows/linux.yml, Cargo.toml
This should fix the timeout issues
=> Improve cache steps in github actions

src/parse/parser.rs
A side effect of my ongoing work: a big, scary, uncouth macro has been replaced with a big, scary, uncouth function. Why function is better, I hear you ask? Because it's not duplicated in the resulting binary and doesn't contain `$` symbol.
=> One less giant macro (-0.5 kB)

src/parse/parser.rs, src/util/osstringext.rs, tests/opts.rs
It used to be 4 of them 10 minutes ago, but I could justify only two.
=> Fix a couple of very minor bugs

src/build/app/mod.rs, src/macros.rs, src/mkeymap.rs, src/output/usage.rs, src/parse/features/suggestions.rs, src/parse/parser.rs, src/parse/validator.rs
This pr makes some parts of code more readable.
=> A little cleanup

.github/workflows/benchmark.yml, Cargo.toml
=> Update criterion away from fork

Cargo.toml
=> Bump os_str_bytes in order to support wasi

clap_derive/src/derives/from_argmatches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/mod.rs, clap_derive/src/derives/ty.rs, clap_derive/tests/arg_enum.rs, clap_derive/tests/ui.rs
=> Implemented arg_enum for option and vec

.travis.yml, examples/01a_quick_example.rs, examples/01b_quick_example.rs, examples/01c_quick_example.rs, examples/05_flag_args.rs, examples/18_builder_macro.rs, src/build/app/mod.rs, src/macros.rs, src/output/help.rs, src/parse/arg_matcher.rs, tests/app_settings.rs
Also removes some unused finctions
=> Eradicate warnings

Cargo.toml, clap_derive/Cargo.toml, clap_generate/Cargo.toml
=> Some modifications to allow cargo verification to work

src/lib.rs
=> Minor fix for the README

src/build/arg/mod.rs, src/build/macros.rs, src/mkeymap.rs, src/output/help.rs, tests/arg_aliases_short.rs, tests/fixtures/app.yml, tests/yaml.rs
This should resolve https://github.com/clap-rs/clap/issues/1896
I wasn't totally sure which test cases would be good
@kbknapp
=> implement Arg::short_alias and Arg::short_aliases

clap_generate/src/generators/shells/bash.rs, clap_generate/tests/completions.rs, examples/04_using_matches.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/macros.rs, tests/app_settings.rs, tests/fixtures/app.yml, tests/macros.rs
=> Cherry pick missed commits from v2

src/build/app/mod.rs, src/build/arg_group.rs, src/lib.rs
=> Consistent From<Yaml> for ArgGroup

clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/clap.rs, clap_derive/src/derives/from_arg_matches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/mod.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/lib.rs, clap_derive/tests/ui/arg_enum_on_struct.rs, clap_derive/tests/ui/arg_enum_on_struct.stderr, clap_derive/tests/ui/subcommand_on_struct.rs, clap_derive/tests/ui/subcommand_on_struct.stderr, src/lib.rs
=> Allow separate derives, but do not give examples

src/build/arg/mod.rs
```
Arg {
id: aaa,
name: "aaa",
about: None,
long_about: None,
blacklist: [],
settings: ArgFlags(
DELIM_NOT_SET,
),
overrides: [],
groups: [],
requires: [],
r_ifs: [],
r_unless: [],
short: None,
long: None,
aliases: [],
short_aliases: [],
disp_ord: 999,
unified_ord: 999,
possible_vals: [],
val_names: {},
num_vals: None,
max_vals: None,
min_vals: None,
validator: "None",
validator_os: "None",
val_delim: None,
default_vals: [],
default_vals_ifs: {},
env: None,
terminator: None,
index: None,
help_heading: None,
global: false,
exclusive: false,
default_missing_vals: [],
}
```
=> Use proper fmt::DebugStruct facility in Debug impl

src/build/arg/mod.rs
=> Fix Arg::required doc examples

clap_derive/Cargo.toml
Changelog: https://gitlab.com/CreepySkeleton/proc-macro-error/-/blob/master/CHANGELOG.md#v100-2020-3-25
=> chore(Cargo.toml): bump proc-macro-error to 1

src/build/arg_group.rs, tests/unique_args.rs
=> Proper debug in ArgGroup

src/build/app/mod.rs, src/output/help.rs, tests/help.rs
=> Fix custom help headings

src/lib.rs, src/parse/matches/mod.rs, src/parse/mod.rs
=> Reexport Indices

clap_derive/src/derives/subcommand.rs, clap_derive/tests/ui/external_subcommand_wrong_type.stderr
And update the related test accordingly.
=> Fix the external command subtype check

src/build/arg/mod.rs, src/build/arg/settings.rs
Closes #1962
I've put a couple of FIXMES, @pksunkara could you please get a look?
=> Cleanup setings

src/build/app/mod.rs, src/output/help.rs, src/parse/parser.rs, tests/help.rs
=> feat: Added {before/after}_help_long to App struct, closed #1903

clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs, src/build/arg/mod.rs
Closes #1918 
The issue mentions a financial contribution of $5 ; I do not want it. If clap has a way to receive funds, or an entity for the Rust project, I would rather have it sent there.
This pull request needs some testing across all these different shells, I would really appreciate if some people could test.
I only added completions for visible short aliases, which seems to make the most sense, is that OK?
=> Implementation of feature request #1918

src/build/app/mod.rs, src/build/app/settings.rs, src/parse/errors.rs, src/parse/parser.rs, tests/app_from_crate.rs, tests/cargo.rs, tests/help.rs, tests/subcommands.rs, tests/version.rs
=> style: rename ErrorKind::{VersionDisplayed, HelpDisplayed} to present tense

src/macros.rs
Similar to #1988, but doesn't change MSRV.
=> Suppress deprecation warning

README.md
=> Added opencollective sponsors to readme

benches/05_ripgrep.rs, examples/23_flag_subcommands_pacman.rs, src/build/app/debug_asserts.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/build/macros.rs, tests/default_vals.rs, tests/fixtures/app.yaml, tests/require.rs
That wasn't very promptly, sorry.
=> Unify naming cheme

src/build/app/mod.rs
- Fix some links.
- Make the punctuation consistent.
- Correct some spelling/grammar mistakes.
=> Polish doc comments for App

src/build/app/mod.rs, src/build/app/tests.rs
=> Fix propagation

clap_derive/tests/ui/non_existent_attr.stderr, clap_derive/tests/ui/tuple_struct.stderr
=> Adjust stderr files

src/parse/errors.rs
=> Implement std::error::Error for clap::Error

src/mkeymap.rs, src/parse/parser.rs
This code does not serve any purpose as far as I can tell
=> Remove useless code

src/build/app/mod.rs, src/output/help.rs
=> Fix for issue #2130.

.azure-pipelines.yml, .github/workflows/ci.yml, .travis.yml, CHANGELOG.md, Cargo.toml, README.md, clap_derive/Cargo.toml, clap_generate/Cargo.toml, clap_generate/src/lib.rs, src/lib.rs
=> Release 3.0.0-beta.2

src/build/arg_group.rs, src/lib.rs
=> Remove unneeded cfg_attr

src/output/help.rs, src/parse/errors.rs, tests/help.rs, tests/possible_values.rs
=> fix(help messages): escape values in help messages

.azure-pipelines.yml, .github/workflows/ci.yml, CHANGELOG.md, README.md, clap_derive/src/derives/arg_enum.rs, clap_derive/src/derives/subcommand.rs, src/build/app/mod.rs, src/mkeymap.rs, src/parse/errors.rs
=> More changelog and some consistency

src/parse/errors.rs, src/parse/parser.rs, tests/subcommands.rs
Follow up to #2154  
Closes #1744
Closes #1943
=> Suggest using subcommand when supplied after `--`

src/parse/errors.rs, src/parse/features/suggestions.rs, src/parse/parser.rs, tests/flags.rs, tests/groups.rs, tests/opts.rs, tests/subcommands.rs
=> Fix: Don't mention unused subcommands(Partly cherry pick ef92e2b)

clap_derive/Cargo.toml, clap_derive/README.md, clap_derive/examples/README.md, clap_derive/examples/basic.rs, clap_derive/examples/value_hints_derive.rs, clap_generate/examples/value_hints.rs
Also tweaked clap_generate example a little.
Let me know if you think I'm going overboard with this. :)
=> Add examples for using value_hint with clap_derive

src/build/app/settings.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/parse/errors.rs
This PR fixes a bunch of broken links plus a couple typos.
=> Various documentation fixes

clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs
=> clap_generate skips flags/opts with heading

.github/workflows/ci.yml, .travis.yml
=> Move lint ci to github

src/build/app/debug_asserts.rs, src/build/arg/mod.rs, tests/default_vals.rs, tests/positionals.rs
Closes #1205 
These assertions only really care about required and default_value(s). After reading some docs I think other variants like required_unless or default_value_if could be in the same arg/group and still make sense.
Please tell me if any change is needed!
=>  Add assertions for required and default simultaneously

src/build/app/mod.rs, src/output/usage.rs, src/parse/parser.rs, tests/subcommands.rs
Closes #878
And refactored some rotten suggestion emitting code.
=> Fix suggestions of a subcommand shadowing valid input

.github/workflows/ci.yml, CHANGELOG.md, clap_up/Cargo.toml, clap_up/README.md, clap_up/src/lib.rs
=> Updated changelog and more dep upgrade logic

clap_derive/src/derives/from_arg_matches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/dummies.rs, clap_derive/tests/basic.rs, clap_derive/tests/boxed.rs, clap_derive/tests/custom-string-parsers.rs, clap_derive/tests/flatten.rs, clap_derive/tests/skip.rs, src/derive.rs
=> Add update_from_arg_matches to FromArgMatches

src/parse/parser.rs, tests/positionals.rs
I found the original grammar awkward. Hopefully the change makes the error slightly clearer.
=> Changing grammar for error message

.azure-pipelines.yml, .github/workflows/benchmark.yml, .github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, clap_derive/src/derives/from_arg_matches.rs, clap_derive/src/derives/subcommand.rs, clap_generate/src/generators/shells/fish.rs, justfile, src/build/arg/mod.rs, src/output/usage.rs, tests/help.rs
=> Update MSRV to 1.46

clap_derive/src/derives/from_arg_matches.rs
In the `Clap` derive macro, a function parameter named `arg_matches` is
generated using `quote!` - as a result, this parameter ends up with
call-site hygiene. However, `arg_matches` is written literally within
several `quote_spanned!` blocks, which generate an `arg_matches` token
with the hygiene of whatever span was passed to `quote_spanned!`.
If these two hygienes are different (for example, if the user invokes
the derive macro from a `macro_rules!` macro), then a usage of
`arg_matches` may not resolve to the `arg_matches` parameter definition.
This commit changes the generation of `arg_matches` identifiers to
always use `quote!`, ensuring that they will always be considered the
'same' identifier by Rust.
=> Fix hygiene of `arg_matches` parameter

src/output/usage.rs, tests/help.rs
=> Fix issue 1794 error message

src/build/app/settings.rs, src/parse/parser.rs
We don't need this persistent flag.
=> Remove LowIndexMultiplePositional, stop recalculating positional_count

src/parse/validator.rs, tests/require.rs
=> Fix only one arg printed in multiple required_unless missing situation

src/parse/matches/arg_matches.rs
Closes #1358
I tried to be consistent and clear with existing docs but if there is anyway I could improve it let me know.
=> docs(arg_matches.rs): clarified unclear behavior for is_present and value_of

src/build/app/debug_asserts.rs, src/build/app/mod.rs, src/mkeymap.rs, src/output/help.rs, src/parse/features/suggestions.rs, src/parse/parser.rs, src/parse/validator.rs
Resolve a fixme, and some minor things.
=> Better mkeymap

clap_derive/src/attrs.rs, clap_derive/tests/arg_enum.rs, src/parse/matches/arg_matches.rs
Fix clippy warnings on nightly tests.
=> Fix clippy warnings

tests/opts.rs
=> Add regression test for issue 2279

src/build/app/mod.rs, tests/groups.rs
=> Fix usage of positional grouped arguments uses arg name rather than val_name

src/build/app/mod.rs, src/build/app/settings.rs, src/parse/arg_matcher.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs
=> Parsing function clean up

.github/workflows/ci.yml
=> Fix CI on i686-unknown-linux-gnu

CHANGELOG.md, benches/03_complex.rs, benches/04_new_help.rs, benches/05_ripgrep.rs, benches/06_rustup.rs, clap.schema.json, examples/16_app_settings.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/build/usage_parser.rs, tests/help.rs
=> Remove Arg::settings to be consistent with App

src/build/arg/mod.rs, src/build/macros.rs, src/build/usage_parser.rs, src/mkeymap.rs, src/output/usage.rs, src/parse/arg_matcher.rs, src/parse/errors.rs, src/parse/parser.rs, src/parse/validator.rs
Reduce unneeded number casting.
=> Change some u64 to usize

src/build/arg/mod.rs
Just some minor changes to the documentation for `required_unless_present_any`.
=> Update docs for `required_unless_present_any`

.github/workflows/ci.yml, src/parse/parser.rs
=> Add --all-features for CI, fix build with debug feature.

src/build/app/debug_asserts.rs, src/build/arg/mod.rs, src/build/macros.rs, src/parse/validator.rs, tests/require.rs
=> feat: Implement Arg::required_if_eq_all

src/build/arg/mod.rs
=> Fix code example to match help text

src/build/arg/mod.rs
=> Allow getting the long about, env, and default values of an argument

clap_derive/src/derives/from_arg_matches.rs
=> fix: subcommand with field name subcmd compilation

clap_derive/src/lib.rs, clap_generate/src/generators/mod.rs, clap_generate/src/lib.rs, src/build/app/mod.rs, src/build/app/settings.rs, src/build/arg/mod.rs, src/build/arg/regex.rs, src/build/arg/settings.rs, src/build/arg/value_hint.rs, src/build/arg_group.rs, src/derive.rs, src/macros.rs, src/output/help.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs
=> Apply cargo-intraconv

.azure-pipelines.yml, .github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, Cargo.toml, README.md, clap_derive/Cargo.toml, clap_generate/Cargo.toml, clap_up/src/lib.rs, justfile, src/build/arg/debug_asserts.rs, src/build/arg/mod.rs, src/build/arg/settings.rs, src/parse/errors.rs, src/parse/parser.rs, src/parse/validator.rs, tests/empty_values.rs, tests/examples.rs, tests/opts.rs
- Remove unstable feature flag
- Rename NoEmptyValues to ForbidEmptyValues
- Update changelog and implement more stuff for the upgrader
=> Cleanup and add changelog

examples/10_default_values.rs
=> Fix minor typos in 10_default_values.rs

README.md
Provide a better default which someone would expect, not having this in the first example people will probably not know this feature.
=> Show default derive example with coloredhelp

clap_generate/src/lib.rs
Closes #2422 
This PR adds `Result<PathBuf>` to `clap_generate::generate_to` as return value.
By this change, users can know the actual path of the generated completion file, and handle IO error instead of panic.
=> Add PathBuf to clap_generate::generate_to

clap_derive/Cargo.toml, clap_generate/src/lib.rs, src/lib.rs
=> Specify dep patch versions

clap_derive/src/utils/spanned.rs, src/build/arg/mod.rs, tests/fixtures/app.yaml, tests/yaml.rs
Fixes https://github.com/clap-rs/clap/discussions/2404#discussioncomment-706470
=> Add multiple_* parsing for yaml

src/parse/parser.rs
Just a drive-by mini-improvement.
If you can't be bothered, I understand. Just close it.
=> Input.insert: No need to clone

src/build/app/settings.rs, src/parse/parser.rs, tests/env.rs
Closes https://github.com/clap-rs/clap/issues/2491.
=> feat: Add AppSettings::DisableEnv

src/parse/parser.rs
The `bool` field in `ParseResult::FlagSubCommandShort` is no longer required, since the parsing state has been fully encoded in `Parser`'s `flag_subcmd_at` field.
This also eliminates an unnecessary usage of `.unwrap()`.
=> refactor(parser): remove `bool` field in `ParseResult::FlagSubCommandShort`

clap.schema.json, examples/17_yaml.yaml, src/build/app/mod.rs, src/build/arg/mod.rs, src/build/macros.rs, tests/fixtures/app.yaml, tests/fixtures/app_2space.yaml, tests/fixtures/app_regex.yaml, tests/fixtures/app_regex_invalid.yaml, tests/fixtures/app_setting_invalid.yaml, tests/fixtures/arg_setting_invalid.yaml, tests/fixtures/extra_fields.yaml, tests/fixtures/extra_fields_invalid_app.yaml, tests/fixtures/extra_fields_invalid_arg.yaml, tests/yaml.rs
=> Ignore extra fields in YAML only when specified

CONTRIBUTING.md
=> Fix double space in CONTRIBUTING.md

clap_derive/src/derives/from_arg_matches.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, clap_generate/src/generators/mod.rs, clap_generate/src/generators/shells/bash.rs, clap_generate/src/generators/shells/elvish.rs, clap_generate/src/generators/shells/fish.rs, clap_generate/src/generators/shells/powershell.rs, clap_generate/src/generators/shells/zsh.rs, src/build/app/debug_asserts.rs, src/build/arg/mod.rs, src/output/help.rs, src/output/usage.rs, src/parse/parser.rs, src/parse/validator.rs
=> Fix some nightly clippy warnings

src/build/app/settings.rs, src/build/arg_group.rs, src/lib.rs, src/macros.rs, src/parse/errors.rs, src/parse/matches/arg_matches.rs
=> fix a bunch of intra-doc links

README.md
=> Simplify example code

site/static/css/app.css
@pksunkara please review this PR
=> Fixed overflowed code snippet

src/build/arg/mod.rs
=> Fix grammar in `require_delimiter` fn docs

clap_derive/src/derives/args.rs, clap_derive/src/derives/clap.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/mod.rs, clap_derive/src/derives/subcommand.rs
=> refactor: Move code to future trait locations

clap_derive/src/derives/subcommand.rs
When debugging #2586, I noticed we were developing match cases for
variant names that were flattened.  At minimum, this is dead code and at
worst this could cause the wrong behavior if a user does an update with
one of those names.
Depends on #2587
Fixes #2588
=> fix(derive): Don't generate dead code 

clap_derive/src/attrs.rs, clap_derive/src/derives/arg_enum.rs, clap_derive/tests/arg_enum.rs
=> feat(derive): Allow skipping ArgEnum variants 

src/output/help.rs, tests/help.rs
=> Print `value_name` `number_of_values` times with single value_name

examples/15_custom_validator.rs
=> fix(example): Use correct type in comment

src/parse/parser.rs, tests/require.rs
=> Fix attached_value abandoned even if it's not used.

src/parse/parser.rs
More performance&binary_size-friendly.
=> fmt::write -> push_str

src/build/app/settings.rs, src/parse/errors.rs, src/parse/mod.rs, src/parse/parser.rs, src/parse/validator.rs, src/util/argstr.rs, tests/app_settings.rs
=> Parser refactor

src/util/argstr.rs
cc @dylni , @pksunkara .
Revert some of the rushy work piggy-backed on #2655  . Will open another PR tomorrow with detailed explanation. :-P.
=> Fix some work on `ArgStr`

clap_derive/tests/subcommands.rs
We don't know enough to do partial updates, so we are only doing full
updates.
Closes #2212
=> test: Cover external subcommand updates

clap.schema.json, src/build/arg/mod.rs, tests/help.rs, tests/multiple_values.rs
=> Make `value_delimiter` accept `char` rather than `String`

Cargo.toml, src/build/arg/mod.rs, src/output/help.rs, src/parse/parser.rs, src/util/mod.rs
Doesn't look like this dependency is buying us anything at this point,
so removing it.
=> refactor: Remove vec_map dependency

src/parse/parser.rs
=> Less format & branch

clap_derive/src/attrs.rs, clap_derive/tests/ui/default_value_t_invalid.rs, clap_derive/tests/ui/default_value_t_invalid.stderr
=> fix(derive): Type check `default_value_t`

tests/conflicts.rs, tests/require.rs
=> Fix some test cases to print correct failure message

.github/workflows/site.yml
=> Pin the zola version used to deploy the site

src/build/arg/mod.rs, src/build/usage_parser.rs
=> refactor: Remove unused variable

clap_generate_fig/Cargo.toml
Like with #2903, we are depending on more features than needed, forcing
them onto users.  This also impacts our testing since we aren't truly
getting minimal test runs (see #2976).
=> fix(fig): Reduce deepdencies

tests/yaml.rs
Signed-off-by: Matthew Fisher <matt.fisher@fishworks.io>
=> fix check warnings

README.md
=> corrected minor grammar mistakes in README.md

src/parse/matches/arg_matches.rs
=> Remove extern crate in doc tests to fix coverage

Cargo.toml
These changes don't really affect Clap.
=> Upgrade os_str_bytes

examples/tutorial_derive/README.md
Am not sure if we want the file name to be changed instead.
=> docs: Link correct example

.github/workflows/ci.yml, .github/workflows/rust-next.yml, Makefile, examples/derive_ref/README.md, src/build/app/settings.rs, tests/builder/possible_values.rs
This builds on #3078 with more.
=>  Misc fixes from clapng fork review

Cargo.toml, clap_derive/Cargo.toml, release.toml
Experimenting with treating clap-derive and clap one and the same from
the release process perspective.  The completion generators are a bit
more independent.
=> chore: Configure release process

Cargo.toml
Looks like this is undocumented, see https://github.com/integer32llc/rust-playground/issues/192
Fixes #3065
=> fix: Expose all features in playground

tests/examples.rs
=> test: Actually allow unstable examples to be tested

src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg_group.rs, src/lib.rs, src/macros.rs
- Some still referenced the clapng issue number
- Some YAML ones were missed in the formatting clean up
- I never updated the usage ones with the formatting clean up
=> docs: Update deprecation messages

Cargo.toml, examples/derive_ref/README.md, examples/derive_ref/custom_bool.md, examples/derive_ref/custom_bool.rs
=> docs(derive): Show how to override special types

docs/FAQ.md
Resolves #3148
P.S. Now realized that creating issue about this is even harder than creating a pull request to fix it.
=> docs: Fix numbers of list entries in FAQ.md

docs/FAQ.md
=> docs: List out each API

src/parse/validator.rs
We were storing data off into the struct, obscuring the direct
relationship between gathering and validating conflicts.
With this, not as much code needs to deal with mutable data
=> refactor: Clarify validator relationships

src/build/arg/settings.rs, src/derive.rs, src/lib.rs, src/output/usage.rs, src/parse/matches/matched_arg.rs, src/parse/parser.rs
The intent is to make stand out more the important technical debt hidden in comments.
=> chore: Remove the TODO chaff

src/parse/validator.rs, tests/builder/require.rs
Found this when digging into #3197
=> fix: Ensure we validate required-unless

tests/builder/app_settings.rs, tests/builder/arg_aliases.rs, tests/builder/arg_aliases_short.rs, tests/builder/arg_matcher_assertions.rs, tests/builder/default_missing_vals.rs, tests/builder/default_vals.rs, tests/builder/empty_values.rs, tests/builder/env.rs, tests/builder/flag_subcommands.rs, tests/builder/flags.rs, tests/builder/global_args.rs, tests/builder/grouped_values.rs, tests/builder/groups.rs, tests/builder/help.rs, tests/builder/ignore_errors.rs, tests/builder/indices.rs, tests/builder/multiple_occurrences.rs, tests/builder/opts.rs, tests/builder/positionals.rs, tests/builder/posix_compatible.rs, tests/builder/propagate_globals.rs, tests/builder/require.rs, tests/builder/subcommands.rs, tests/builder/tests.rs
Working on a fix for #3217 and can't see what is failing because the
test process exits.
=> test: Panic, rather than exit, on error

examples/tutorial_derive/README.md
Internal page link is broken and it annoyed the **** out of me.
=> Fix broken internal link

Cargo.toml, src/derive.rs
=> docs(derive): Link to ref from traits

clap_complete/src/shells/bash.rs, clap_complete/src/shells/elvish.rs, clap_complete/src/shells/fish.rs, clap_complete/src/shells/powershell.rs, clap_complete/src/shells/zsh.rs, clap_complete_fig/src/fig.rs, clap_derive/src/attrs.rs, clap_derive/src/parse.rs, clap_derive/src/utils/doc_comments.rs, examples/tutorial_derive/04_04_custom.rs, src/build/app/mod.rs, src/build/arg/mod.rs, src/build/arg/possible_value.rs, src/build/arg_group.rs, src/lib.rs, src/output/fmt.rs, src/output/help.rs, src/parse/errors.rs, tests/builder/double_require.rs, tests/builder/utils.rs
=> refactor: address clippy warnings

src/lib.rs, src/parse/parser.rs, tests/builder/positionals.rs
=> fix(parser): Ignore Last when checking Hyphen Values 

Cargo.toml, README.md, clap_derive/Cargo.toml, clap_derive/README.md
Inspired by https://github.com/clap-rs/clap/discussions/3313
=> docs: More cross-linking to make derive docs discoverable

clap_complete/src/generator/mod.rs, clap_complete/src/shells/bash.rs, clap_complete/src/shells/elvish.rs, clap_complete/src/shells/fish.rs, clap_complete/src/shells/powershell.rs, clap_complete/src/shells/zsh.rs
=> Clarify some panics

examples/tutorial_builder/03_04_subcommands.rs, examples/tutorial_builder/README.md, examples/tutorial_derive/README.md
Inspired by https://github.com/clap-rs/clap/discussions/3342
Looks like we already cover this in the derive reference.
=> docs(tutorial): Talk about required/optional subcommands

clap_man/examples/man-builder.rs, clap_man/examples/man.rs, clap_man/src/lib.rs, clap_man/tests/generate.rs
This is part of #3354
BREAKING CHANGE: Functions now take ownership
=> feat(man)!: Allow customizing man page

docs/FAQ.md
* Remove entries for sections that no longer exist
* Update entry for "How many approaches"
* Renumber entries
=> Fix FAQ table of contents

src/build/app/mod.rs, src/output/help.rs, src/output/usage.rs, src/parse/parser.rs, src/parse/validator.rs
Didn't quite get rid of all of the `pub(crate)`s but merging what we have so far.
=> refactor: Minor progress on reducing Parser's visibility

src/build/arg/arg_predicate.rs, src/build/arg/mod.rs, src/build/mod.rs, src/parse/parser.rs
While this doesn't help in the public API (yet), this at least clarifies
the intent in the implementation.
This is building towards #3020.
=> refactor: Clarify intent of default_value_if

src/build/app/mod.rs, src/build/arg/mod.rs, src/parse/matches/matched_arg.rs
This is based on the work in #3384
=> refactor: Clarify intent behind requires

clap_complete/src/shells/powershell.rs, clap_complete/tests/completions/powershell.rs
Solves #2750 . Suggested by  @benedictleejh.
=> Allow completion of partial commands

src/lib.rs, src/parse/arg_matcher.rs, src/parse/matches/arg_matches.rs, src/parse/matches/matched_arg.rs, src/parse/matches/mod.rs, src/parse/matches/value_source.rs, src/parse/mod.rs, src/parse/parser.rs
Fixes https://github.com/clap-rs/clap/issues/1345
=> feat(parser): Expose ValueSource 

src/build/app/mod.rs, tests/builder/help.rs
For now, we are going to provide a better debug assert in this case.
Resolving https://github.com/clap-rs/clap/issues/3405 is the better long term route.
Fixes https://github.com/clap-rs/clap/issues/3403
=> fix(assert): Provide next steps for '-h' conflicts

src/build/app/mod.rs, tests/builder/global_args.rs
Fixes https://github.com/clap-rs/clap/issues/3428
=> fix: Detect deeply recursed global args

examples/cargo-example-derive.rs, examples/cargo-example.rs, examples/git.rs, examples/multicall-busybox.rs, examples/multicall-hostname.rs
=> docs(examples): Add missing feature flag reqs

README.md, clap_complete/src/shells/bash.rs, clap_complete/src/shells/zsh.rs, examples/derive_ref/README.md, examples/multicall-busybox.md, examples/multicall-hostname.md, examples/tutorial_builder/README.md, examples/tutorial_derive/README.md, src/build/app.rs, src/build/arg.rs, src/build/value_hint.rs, src/error/kind.rs, src/parse/matches/arg_matches.rs
=> docs: Update stale references to AppSettings

Makefile, tests/examples.rs
=> Remove unnecessary unstable-doc usage

examples/pacman.md
Looking at how `App::usage` member is used, and didn't realize we had
this special logic.
=> docs(examples): Show pacman-style help

clap_complete/src/shells/fish.rs, clap_complete/tests/completions/fish.rs
I _think_ this is the right thing to do, but if anyone who actually understands fish's quoting could confirm, that would be useful.
---
0fbabaa3 test(completion): add regression test for fish quoting issue
<br/>
6f36ca3a fix(complete): escape fish possible values
Fixes: https://github.com/clap-rs/clap/issues/3467
<br/>
=> fix(complete): escape fish possible values

src/build/command.rs
=> docs: Tell people to use latest API

examples/derive_ref/README.md
=> Fixed broken Command Attributes link

examples/tutorial_builder/04_04_custom.rs, examples/tutorial_builder/README.md, examples/tutorial_derive/04_04_custom.rs, examples/tutorial_derive/README.md
=> Fix a typo in an example

Cargo.toml, examples/tutorial_builder/01_quick.rs, examples/tutorial_builder/02_app_settings.rs, examples/tutorial_builder/02_crate.rs, examples/tutorial_builder/03_01_flag_bool.rs, examples/tutorial_builder/03_01_flag_count.rs, examples/tutorial_builder/03_02_option.rs, examples/tutorial_builder/03_03_positional.rs, examples/tutorial_builder/03_04_subcommands.rs, examples/tutorial_builder/03_05_default_values.rs, examples/tutorial_builder/04_01_enum.rs, examples/tutorial_builder/04_01_possible.rs, examples/tutorial_builder/04_02_parse.rs, examples/tutorial_builder/04_02_validate.rs, examples/tutorial_builder/04_03_relations.rs, examples/tutorial_builder/04_04_custom.rs, examples/tutorial_builder/05_01_assert.rs, src/macros.rs
=> fix: Reduce chance of missing `cargo` feature

examples/derive_ref/README.md
I think we probably want to make a decision on whether to keep this feature or remove it. But until then, let's document it.
=> Fixes #3464

src/build/command.rs
=> chore: fix typo

clap_complete/tests/common.rs, clap_complete/tests/snapshots/basic.zsh.log, clap_complete/tests/snapshots/feature_sample.zsh.log, clap_complete/tests/snapshots/special_commands.zsh.log, clap_complete/tests/snapshots/sub_subcommands.zsh.log, clap_complete_fig/src/fig.rs, clap_complete_fig/tests/common.rs, clap_complete_fig/tests/snapshots/basic.fig.js, clap_complete_fig/tests/snapshots/feature_sample.fig.js, clap_complete_fig/tests/snapshots/quoting.fig.js, clap_complete_fig/tests/snapshots/special_commands.fig.js, clap_complete_fig/tests/snapshots/sub_subcommands.fig.js, clap_complete_fig/tests/snapshots/value_hint.fig.js
Recovers #3397 
/cc @grant0417
=> feat(clap_complete_fig): Add `exclusiveOn` and `isRepeatable` and improve indentation

examples/README.md, examples/git-derive.md, examples/git-derive.rs, examples/git.md, examples/git.rs
While we don't have a built-in mechanism, its relatively easy to support
with the APIs we provide.
Inspired by #3566
=> docs(examples): Show how to do default subcommands

.github/workflows/ci.yml, examples/git-derive.md, examples/git.md
CI didn't run for #3570, so we missed that some things were off on
Windows.
=> docs: Fix examples

clap_derive/src/derives/arg_enum.rs, examples/derive_ref/README.md, tests/derive/arg_enum.rs, tests/derive_ui/arg_enum_non_unit.rs, tests/derive_ui/arg_enum_non_unit.stderr
Hi!
As promised, I tackled the issue #3543, which I reported.
Please tell me what you think, I will refactor it if needed.
=> Fix ArgEnum non-unit variant

clap_mangen/src/render.rs, clap_mangen/tests/common.rs, clap_mangen/tests/roff.rs, clap_mangen/tests/snapshots/hidden_option.bash.roff
=> Don't include hidden flags in the synopsis section from clap_mangen

src/build/arg.rs, src/build/command.rs, src/error/kind.rs
Its extra maintenance and more likely to cause annoyances.
Fixes #3608
=> docs: Don't encourage index

src/bin/stdio-fixture.rs, tests/ui.rs, tests/ui/V_flag_stdout.toml, tests/ui/arg_required_else_help_stderr.toml, tests/ui/error_stderr.toml, tests/ui/h_flag_stdout.toml, tests/ui/help_cmd_stdout.toml, tests/ui/help_flag_stdout.toml, tests/ui/version_flag_stdout.toml
This is to prevent #3648 from happening again
=> test(output): Ensure correct streams

src/lib.rs
=> fix(clap): Allow disabling color with debug

Cargo.toml, examples/README.md, examples/multicall-hostname.rs, examples/repl.rs, tests/examples.rs
This is to help in cases like https://github.com/clap-rs/clap/issues/3668 and https://github.com/clap-rs/clap/discussions/3673
=> docs: Add REPL example

src/build/command.rs
=> docs(multicall): Expand documentation in prep for stablization

src/parse/parser.rs, src/parse/validator.rs
=> refactor(help): Remove more redundant required checks

src/macros.rs
=> fix(macros): Add needed call for arg_enum

Cargo.toml, clap_complete/Cargo.toml, clap_complete_fig/Cargo.toml, clap_derive/Cargo.toml, clap_lex/Cargo.toml, clap_mangen/Cargo.toml
Now that #3732 bumped our MSRV, we can switch editions!
=> fix: Switch to 2021 edition

src/builder/value_parser.rs
=> fix(parser): Use optimized bool value parser

src/parser/parser.rs
=> refactor(parser): Remove dead code

tests/builder/app_settings.rs
=> fix: Remove deprecation warning

examples/README.md
=> fix cargo.toml link

examples/derive_ref/README.md
=> docs(derive): Make raw attribute more discoverable

src/builder/action.rs
=> docs(builder): Note the type for 'Count'

examples/tutorial_builder/README.md
=> docs(tutorial): Update for new API

src/builder/arg.rs, src/builder/command.rs, src/builder/mod.rs, src/builder/value_parser.rs
=> refactor(builder): Reduce visibility

src/builder/arg.rs, src/builder/command.rs, src/builder/debug_asserts.rs
I identified these problems by porting cargo to master.
=> fix(assert): Reslve regressions for auto-help / auto-version

src/builder/mod.rs, src/builder/value_parser.rs
=> fix: Further discourage `value_parser!` implementation details

src/parser/matches/arg_matches.rs, tests/derive_ui/next/bool_value_enum.stderr, tests/derive_ui/non_existent_attr.stderr, tests/derive_ui/stable/bool_value_enum.stderr
=> docs(parser): Encourage people to read the whole deprecation message

CHANGELOG.md, tests/builder/arg_settings.rs, tests/builder/default_vals.rs
Some minor things to be taken care of
=> Follow up to #3815

clap_derive/src/attrs.rs, clap_derive/src/derives/args.rs, clap_derive/src/derives/mod.rs, clap_derive/src/derives/value_enum.rs, clap_derive/src/dummies.rs, clap_derive/src/lib.rs, tests/derive_ui/next/bool_value_enum.stderr, tests/derive_ui/stable/bool_value_enum.stderr
This is a small step towards #3824
=> fix(derive): Tweak spans

src/lib.rs
=> doc: Explain why examples are missing

clap_complete/src/lib.rs
=> docs(complete): Make example consistent

.github/settings.yml, .github/workflows/ci.yml, .github/workflows/pre-commit.yml
=> chore(gh): Prepare for more branches to be added

CHANGELOG.md, src/parser/parser.rs
=> fix(env)!: Parse help/version like normal

CHANGELOG.md, clap_bench/benches/03_complex.rs, src/builder/arg.rs, src/macros.rs, tests/builder/groups.rs, tests/builder/help.rs, tests/builder/utils.rs, tests/macros.rs
=> fix!: Change `arg!` to use ArgAction

src/builder/command.rs, tests/builder/conflicts.rs
=> fix!: Ignore required when subcommands conflict with required

CHANGELOG.md, src/builder/arg.rs, src/builder/debug_asserts.rs, tests/builder/grouped_values.rs, tests/builder/posix_compatible.rs
This will make it easier to drop support for multiple occurrences
=> fix(assert)!: Disallow self-overrides 

clap_derive/src/attrs.rs, clap_derive/src/parse.rs, src/_derive/mod.rs, tests/derive/default_value.rs, tests/derive/value_enum.rs, tests/derive_ui/default_values_t_invalid.rs, tests/derive_ui/default_values_t_invalid.stderr
=> feat(clap_derive): Add `default_values_t` and `default_values_os_t` (backport for Clap v3)

clap_derive/src/attrs.rs
=> chore: Fix warnings

src/builder/arg.rs, tests/builder/help.rs, tests/builder/multiple_values.rs, tests/derive/options.rs, tests/macros.rs
=> fix(help): Remove '...' for optional values

CHANGELOG.md, src/builder/arg.rs, src/builder/command.rs, src/builder/debug_asserts.rs, src/macros.rs, src/parser/matches/arg_matches.rs, tests/builder/groups.rs, tests/builder/help.rs, tests/builder/multiple_occurrences.rs, tests/builder/multiple_values.rs
=> fix!: Replace takes_value with number_of_values

clap_complete/src/generator/utils.rs, clap_complete/src/shells/fish.rs, clap_complete/src/shells/zsh.rs, clap_complete_fig/src/fig.rs, src/builder/arg.rs, src/builder/debug_asserts.rs, src/macros.rs, src/output/help.rs, src/parser/arg_matcher.rs, src/parser/parser.rs, src/parser/validator.rs, tests/macros.rs
=> fix!: Remove bookkeeping getters from API

examples/tutorial_builder/01_quick.rs, src/_derive/mod.rs
These should not be backported to v3.
=> docs: v4-specific improvements

Cargo.toml, examples/tutorial_builder/04_01_enum.rs, examples/tutorial_derive/01_quick.md, examples/tutorial_derive/02_app_settings.md, examples/tutorial_derive/02_apps.md, examples/tutorial_derive/02_crate.md, examples/tutorial_derive/03_01_flag_bool.md, examples/tutorial_derive/03_01_flag_count.md, examples/tutorial_derive/03_02_option.md, examples/tutorial_derive/03_03_positional.md, examples/tutorial_derive/03_04_subcommands.md, examples/tutorial_derive/03_05_default_values.md, examples/tutorial_derive/04_01_enum.md, examples/tutorial_derive/04_02_parse.md, examples/tutorial_derive/04_02_validate.md, examples/tutorial_derive/04_03_relations.md, examples/tutorial_derive/04_03_relations.rs, examples/tutorial_derive/04_04_custom.md
=> docs(tutorial): Switch to hand-implemented ValueEnum

CONTRIBUTING.md, Cargo.toml, examples/tutorial_builder/03_01_flag_count.rs, examples/tutorial_builder/03_02_option.md, examples/tutorial_builder/03_02_option.rs, examples/tutorial_builder/03_02_option_mult.md, examples/tutorial_builder/03_02_option_mult.rs, examples/tutorial_builder/03_03_positional.md, examples/tutorial_builder/03_03_positional.rs, examples/tutorial_builder/03_03_positional_mult.md, examples/tutorial_builder/03_03_positional_mult.rs, examples/tutorial_builder/03_05_default_values.md, examples/tutorial_builder/03_05_default_values.rs, examples/tutorial_derive/03_02_option_mult.md, examples/tutorial_derive/03_02_option_mult.rs, examples/tutorial_derive/03_03_positional_mult.md, examples/tutorial_derive/03_03_positional_mult.rs, src/_derive/_tutorial.rs, src/_tutorial.rs, src/builder/arg.rs
Inspired by a [reddit thread](https://www.reddit.com/r/rust/comments/wgy6mr/new_alternative_for_clap_declarative_basic_and/ijbfpkl/?context=3)
=> docs: Clarify confusing API points

src/builder/command.rs
=> fix(debug): Make it easier to address help issues

clap_complete/src/shells/zsh.rs, clap_complete_fig/src/fig.rs, src/builder/debug_asserts.rs, src/parser/arg_matcher.rs
=> style: Make clippy happy

clap_complete/src/shells/bash.rs, clap_complete/src/shells/zsh.rs, clap_derive/src/attrs.rs, clap_derive/src/utils/ty.rs, src/builder/arg.rs, src/builder/debug_asserts.rs, src/error/kind.rs, src/output/usage.rs, tests/builder/utf8.rs, tests/derive/flags.rs, tests/derive/skip.rs, tests/derive/subcommands.rs
=> style: Address clippy

examples/tutorial_builder/04_01_enum.rs
=> Fix enum example comment

src/_faq.rs
Happy to add an issue if needed. Getting started with `clap` and wanted to help polish the FAQ section of the docs.
=> Quality improvements to FAQ docs

src/util/id.rs, src/util/os_str.rs, src/util/str.rs
=> fix: Ensure partial eq is symetric

clap_complete_fig/src/fig.rs
Escapes all strings that are included as literals in the final completion
=> fix(clap_complete_fig): Escape all strings

src/builder/value_parser.rs
This is a backport of e7ced880e
=> docs: Fix for 1.63

src/builder/arg.rs, src/builder/command.rs, src/builder/styled_str.rs, src/error/context.rs, src/error/format.rs, src/error/mod.rs, src/output/help.rs, src/output/usage.rs, src/parser/validator.rs, src/util/flat_map.rs, src/util/flat_set.rs
=> feat: Allow stylized usage

clap_derive/src/attrs.rs, clap_derive/src/parse.rs
=> refactor(derive): Prepare for builder attributes

CHANGELOG.md, clap_derive/src/lib.rs, clap_derive/src/parse.rs
=> fix(derive): Remove structopt attribute support

CHANGELOG.md, src/builder/arg.rs
=> docs: Make transition easier

CHANGELOG.md, src/builder/arg.rs, src/builder/command.rs
=> docs: Fix up for changing of help output

clap_derive/src/attrs.rs, clap_derive/src/derives/args.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, clap_derive/src/derives/value_enum.rs
=> refactor(derive): Be explicit in what is being parsed

tests/builder/version.rs
=> test(help): Verify how version interacts

src/output/usage.rs
=> fix(usage): Have spillover use TAB

Cargo.lock, Cargo.toml, clap_complete/Cargo.toml, clap_complete/src/generator/utils.rs, clap_complete_fig/Cargo.toml, clap_mangen/Cargo.toml
=> chore: Update dependencies

src/builder/app_settings.rs, src/builder/command.rs, src/builder/tests.rs, src/error/mod.rs, src/parser/features/suggestions.rs
=> refactor: Use parameters over settings

examples/git-derive.md, examples/git-derive.rs, examples/git.md, examples/git.rs, src/_cookbook/mod.rs
We can't quite get git's behavior because it has `last` as both before
and after `--`
=> docs: Show how last can be used

Makefile, clap_complete/examples/dynamic.rs, clap_complete/src/dynamic.rs, clap_complete/tests/dynamic.rs
=> fix: Tests/clippy/errors bash dynamic completion

CHANGELOG.md, src/output/help.rs
=> fix(help): Respect LINES and COLUMNS

src/builder/command.rs
=> docs: Clarify role of max_term_width

CHANGELOG.md, src/builder/arg.rs, src/builder/arg_group.rs, src/builder/command.rs, src/builder/possible_value.rs, src/builder/resettable.rs, tests/builder/env.rs
=> feat: Allow resetting builder methods

clap_complete/examples/completion-derive.rs, clap_complete/examples/completion.rs
=> docs(complete): Ensure examples work

examples/derive_ref/interop_tests.md, src/builder/styled_str.rs, src/error/format.rs, tests/builder/flags.rs, tests/builder/opts.rs, tests/builder/subcommands.rs, tests/ui/error_stderr.toml
Noticed some issues in an error screenshot in artichoke/artichoke#2196
=> fix(error): Polish up errors a little

src/builder/arg_group.rs
This is a part of #4228
I thought I needed this for another change but it turned out I didn't.
=> feat: Add ArgGroup::is_required_set

src/parser/validator.rs, tests/builder/groups.rs
These were found wh8le working on #3165
=> fix(error): Improve errors when groups are involved

CHANGELOG.md, src/builder/arg.rs, src/builder/command.rs, src/macros.rs
These were identified in #4308
=> docs: Fix a few items

src/builder/arg.rs
=> docs: Fix outdated short comment

examples/derive_ref/interop_tests.md, src/error/context.rs, src/error/format.rs, src/error/mod.rs, src/parser/parser.rs, tests/builder/error.rs, tests/builder/opts.rs, tests/builder/subcommands.rs, tests/ui/error_stderr.toml
This is a first pass at #2766 so we can collect further feedback
=> fix(error): Don't suggest '--' when it doesn't help

examples/tutorial_builder/04_01_enum.md, examples/tutorial_builder/04_01_possible.md, examples/tutorial_builder/04_02_parse.md, examples/tutorial_builder/04_02_validate.md, examples/tutorial_derive/04_01_enum.md, examples/tutorial_derive/04_02_parse.md, examples/tutorial_derive/04_02_validate.md, examples/typed-derive.md, src/error/format.rs, src/error/mod.rs, src/parser/parser.rs, tests/builder/default_missing_vals.rs, tests/builder/default_vals.rs, tests/builder/possible_values.rs, tests/builder/subcommands.rs
Quoting wasn't consistent and wee didn't were miscoloring some parts.
=> fix(error): Be more consistent in error quoting

src/error/format.rs, tests/builder/subcommands.rs
=> fix(error): Consistently indent suggestions

src/builder/debug_asserts.rs
=> fix(complete): Support last(true) with CommandWithArguments

Cargo.lock, Cargo.toml, clap_complete/Cargo.toml
=> chore: Update trycmd

src/builder/command.rs
Closes https://github.com/clap-rs/clap/issues/4485
=> Gate term_width and max_term_width APIs on wrap_help

src/parser/validator.rs, tests/builder/conflicts.rs
=> fix(parser): Override required when parent group has conflict 

src/derive.rs
Relevant comment: https://github.com/clap-rs/clap/issues/3864#issuecomment-1374297155
=> Fix example that as runtime panic. Relates to #3864

tests/builder/possible_values.rs
=> test(builder): Fix failing test

clap_derive/src/derives/args.rs, clap_derive/src/derives/into_app.rs, clap_derive/src/derives/subcommand.rs, tests/derive/basic.rs, tests/derive/boxed.rs, tests/derive/skip.rs, tests/derive/subcommands.rs
=> fix(derive): Allow update_from when explicit requireds used 

clap_derive/src/derives/args.rs
My guess is this was left over from switching to using the type based API. The generated code for extracting values from `ArgMatches` had some code that didn't actually do anything, like mapping over the identity function, and wrapping a value in an `Ok` only to immediately use "?" on it.
=> refactor(derive): Clean up unnecessary noop parsing

examples/tutorial_builder/01_quick.rs, src/builder/action.rs, src/builder/arg.rs, src/builder/command.rs, src/derive.rs, src/parser/matches/arg_matches.rs, tests/builder/action.rs, tests/builder/multiple_values.rs
=> docs: Prefer `get_flag` over `get_one::<bool>`

src/parser/features/suggestions.rs
These were both not enabled and missing some cases as highlighted by #4660 
Fixes #4661
=> test: Verify suggestions

Cargo.lock, Cargo.toml, clap_bench/Cargo.toml, clap_complete/Cargo.toml, clap_complete_fig/Cargo.toml, clap_derive/Cargo.toml, clap_lex/Cargo.toml, clap_mangen/Cargo.toml
=> chore: Upgrade dependencies

src/mkeymap.rs
=> perf: Reduce alloc calls when building

CHANGELOG.md, clap_builder/src/error/format.rs
=> fix(error): Don't highlight 'similar'

Cargo.lock, clap_builder/Cargo.toml
=> chore: Update anstyle/anstream

.github/renovate.json5
=> chore: Update from '_rust/main' template

clap_derive/src/parse.rs, src/builder/arg.rs, src/builder/value_parser.rs
=> docs: Clean up so CI passes

clap_builder/src/builder/debug_asserts.rs, clap_builder/src/output/usage.rs
=> fix(builder): Assert earlier on bad requires/conflicts 

clap_mangen/src/render.rs
A minor noop to remove large duplicated code
=> chore: remove dup code in mangen

clap_complete/src/shells/powershell.rs
Makes powershell code more concise
=> chore: Deduplicate powershell code complete

clap_builder/src/output/help_template.rs
=> refactor(help): Be consistent in join style

clap_builder/src/builder/value_hint.rs, clap_complete/src/generator/mod.rs
Two minor cleanups to make Clippy happy.
=> chore: Make Clippy happy

clap_builder/src/builder/debug_asserts.rs, tests/builder/multiple_values.rs
An incremental improvement for #4911.
=> fix(assert): Clarify last assertion

Cargo.lock, clap_builder/Cargo.toml, clap_builder/src/builder/app_settings.rs, clap_builder/src/builder/arg_settings.rs
=> chore: Update bitflags

clap_builder/src/builder/arg.rs
=> docs: Note user-values subject to value_delimiter

Cargo.lock, clap_complete/Cargo.toml, clap_complete/tests/snapshots/home/test/fish/fish/config.fish
=> chore(complete): Update completest

Cargo.lock, clap_complete/Cargo.toml, clap_complete/tests/testsuite/common.rs
=> chore: Update completest

clap_builder/src/derive.rs
=> fix(builder): Update documentation comments

clap_builder/src/builder/debug_asserts.rs, tests/builder/multiple_values.rs
=> fix(assert): Call out the action in positional assert

Cargo.lock, Cargo.toml, clap_builder/Cargo.toml, clap_complete/Cargo.toml
=> chore: Upgrade anstream

clap_builder/src/builder/command.rs
=> docs: Provide custom version/help flag examples

Cargo.lock, clap_complete/Cargo.toml, clap_complete_nushell/Cargo.toml
=> chore: Bump completest

clap_builder/src/builder/arg.rs, clap_builder/src/builder/command.rs, clap_builder/src/parser/matches/arg_matches.rs, clap_complete/src/generator/mod.rs, clap_complete/src/generator/utils.rs, src/_derive/mod.rs
=> docs(ref): Be clear about implicit ArgGroup behavior

clap_builder/src/output/help_template.rs, examples/git-derive.md, examples/git.md, tests/builder/help.rs
=> fix(help): Use right about when flattening

clap_derive/Cargo.toml
https://github.com/dtolnay/proc-macro2/issues/398
=> proc-macro2 bump to 1.0.69 to fix unknown feature proc_macro_span_shrink

clap_complete/Cargo.toml, clap_complete/src/lib.rs
=> docs: Include more content on docs.rs

clap_complete/src/shells/bash.rs, clap_complete/tests/snapshots/aliases.bash, clap_complete/tests/snapshots/basic.bash, clap_complete/tests/snapshots/feature_sample.bash, clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/quoting.bash, clap_complete/tests/snapshots/special_commands.bash, clap_complete/tests/snapshots/sub_subcommands.bash, clap_complete/tests/snapshots/subcommand_last.bash, clap_complete/tests/snapshots/two_multi_valued_arguments.bash, clap_complete/tests/snapshots/value_hint.bash, clap_complete/tests/snapshots/value_terminator.bash
=> Skip nosort option below bash 4.4

Cargo.lock, clap_builder/Cargo.toml
=> fix: Update anstream

clap_builder/src/parser/validator.rs
Skipping a test for now because we don't have a mixed-feature testing strategy.
Fixes #5312
=> fix(parser): Don't duplicate requireds when usage disabled

.github/FUNDING.yml
Adds our org GH sponsor link to this repo.
=> Add Github Sponsors on this repo

examples/tutorial_builder/01_quick.rs
This is just an essentially cosmetic change that hopefully does not require an issue.
=> Pretty sure that apostrophe does not belong

clap_builder/src/output/help_template.rs
=> fix(help): Take long_help into account for next_line_help detection

CONTRIBUTING.md, clap_builder/src/parser/parser.rs
=> chore: fix some comments

.github/workflows/ci.yml, Makefile, tests/derive_ui.rs, tests/derive_ui/flatten_enum_in_struct.stderr, tests/derive_ui/flatten_struct_in_enum.stderr, tests/derive_ui/group_name_attribute.stderr
=> test(derive): Update UI tests to stable

Cargo.lock, Cargo.toml, tests/builder/help.rs
=> test(help): Switch to snapbox

clap_builder/src/output/help_template.rs, tests/builder/help.rs
=> fix(help): Properly wrap subcommand about

clap_complete/src/lib.rs
=> feat(complete): Reexport ValueHint for transition to ArgExt

Cargo.toml
=> fix: Ensure unstable-ext gets enabled

clap_builder/src/builder/arg.rs
=> docs(builder): Remove bad copy/paste docs

Cargo.lock, Cargo.toml, examples/cargo-example-derive.rs, examples/cargo-example.rs, src/_cookbook/mod.rs
Inspired by part of the conversation at #3234
=> docs(cookbook): Style cargo plugin

clap_complete/src/dynamic/completer.rs
=> refactor(complete): Minor clean up

clap_complete/src/dynamic/complete.rs, clap_complete/src/dynamic/custom.rs, clap_complete/src/dynamic/shells/bash.rs, clap_complete/src/dynamic/shells/elvish.rs, clap_complete/src/dynamic/shells/fish.rs, clap_complete/src/dynamic/shells/mod.rs, clap_complete/src/dynamic/shells/zsh.rs
=> docs(complete): Expand dynamic docs

clap_complete/src/dynamic/candidate.rs
=> docs(complete): Clarify CompletionCandidate

clap_complete/src/dynamic/shells/shell.rs, clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish, clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive
=> feat(complete): Infer shell for dynamic completions

clap_complete/src/dynamic/shells/mod.rs, clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/static/exhaustive/elvish/elvish/rc.elv, clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish, clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive
I think `comp_words` is always required, so in theory this should work
=> feat(complete): Make registration args optional

clap_complete/tests/testsuite/dynamic.rs, clap_complete/tests/testsuite/elvish.rs, clap_complete/tests/testsuite/zsh.rs
=> test(complete): Normalize snapshot format

clap_complete/src/dynamic/shells/command.rs, clap_complete/tests/snapshots/home/dynamic/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/register_minimal.bash
=> fix(complete): Ensure bash does not sort, we do

clap_complete/src/dynamic/shells/command.rs, clap_complete/tests/snapshots/home/dynamic/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/dynamic/exhaustive/elvish/elvish/rc.elv, clap_complete/tests/snapshots/home/dynamic/exhaustive/fish/fish/completions/exhaustive.fish, clap_complete/tests/snapshots/home/dynamic/exhaustive/zsh/zsh/_exhaustive, clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/static/exhaustive/elvish/elvish/rc.elv, clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish, clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive, clap_complete/tests/snapshots/register_minimal.bash, clap_complete/tests/testsuite/common.rs
=> fix(complete)!: Adjust built-in completion CLI

clap_complete/src/dynamic/shells/command.rs
=> fix(complete)!: Error, rather than default, on unknown shell

clap_complete/src/dynamic/shells/command.rs
=> fix(complete)!: Remove unused CommandCompleter trait method

clap_complete/src/dynamic/complete.rs
I worry we've been increasing in entropy so took a look around for some areas to improve things.
=> refactor(complete): Misc code cleanup for dynamic completions

clap_complete/src/command/shells.rs, clap_complete/src/env/shells.rs, clap_complete/tests/snapshots/home/dynamic-command/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/dynamic-command/exhaustive/zsh/zsh/_exhaustive, clap_complete/tests/snapshots/home/dynamic-env/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/dynamic-env/exhaustive/zsh/zsh/_exhaustive, clap_complete/tests/snapshots/register_minimal.bash
=> fix(complete): Don't cause endless completions for bash/zsh

clap_complete/src/engine/custom.rs, clap_complete/tests/testsuite/engine.rs
=> fix(complete): Allow completing '.'

Cargo.toml
=> docs: Ensure examples are scraped

clap_complete/tests/testsuite/bash.rs, clap_complete/tests/testsuite/elvish.rs, clap_complete/tests/testsuite/fish.rs, clap_complete/tests/testsuite/zsh.rs
=> test(complete): Run completion tests in parallel

clap_complete/src/env/shells.rs, clap_complete/tests/snapshots/home/dynamic-env/exhaustive/fish/fish/completions/exhaustive.fish, clap_complete/tests/testsuite/fish.rs
=> fix(complete): Put clap in chage of Fish ordering

clap_complete/src/env/mod.rs, clap_complete/src/env/shells.rs, clap_complete/tests/snapshots/home/dynamic-env/exhaustive/zsh/zsh/_exhaustive
=> docs(complete): Clarify CompleteEnv's Shell trait

clap_derive/src/derives/args.rs, tests/derive/flatten.rs
=> chore: add the missing symbol

clap_complete/src/engine/complete.rs, clap_complete/tests/testsuite/bash.rs, clap_complete/tests/testsuite/engine.rs, clap_complete/tests/testsuite/fish.rs
=> fix(complete): Prioritize subcommands, positionals over flags

clap_complete/src/engine/candidate.rs, clap_complete/src/engine/complete.rs, clap_complete/tests/testsuite/bash.rs, clap_complete/tests/testsuite/elvish.rs, clap_complete/tests/testsuite/engine.rs, clap_complete/tests/testsuite/fish.rs, clap_complete/tests/testsuite/zsh.rs
=> fix(complete): De-duplicate built-in candidates

clap_complete/src/engine/complete.rs, clap_complete/tests/testsuite/engine.rs
=> fix(complete): When completing -[TAB], prioritize shorts

clap_complete/src/env/mod.rs
issue https://github.com/clap-rs/clap/issues/3919
- fix how to set env in elvish
- output of external command in elvish script will be treated as bytes rather than string. So we need convert it to string. See [slurp](https://elv.sh/ref/builtin.html#slurp) and [eval](https://elv.sh/ref/builtin.html#eval)
=> doc(complete): Fix how to add completions in elvish

.github/workflows/ci.yml
=> chore(ci): Ensure all tests run on the same runner

clap_complete/src/engine/complete.rs, clap_complete/src/engine/custom.rs, clap_complete/src/env/mod.rs
=> fix(complete): Adjust dynamic for MSRV

src/_tutorial/chapter_3.rs
Adding missing "to"
There is no linked issue as this is only correcting a missing preposition.
=> docs: Update chapter_3.rs - missing "to"

CONTRIBUTING.md
Hey !
I fixed several spelling issues.
Br, futreall.
=>  docs fix spelling issues

clap_complete/examples/exhaustive.rs, clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc, clap_complete/tests/snapshots/home/static/exhaustive/elvish/elvish/rc.elv, clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish, clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive, clap_complete/tests/testsuite/bash.rs, clap_complete/tests/testsuite/elvish.rs, clap_complete/tests/testsuite/fish.rs, clap_complete/tests/testsuite/zsh.rs
This was meant to help with #5856 but I couldn't reproduce the behavior
=> test(complete() Show empty candidate behavior

tests/builder/cargo.rs, tests/builder/default_vals.rs, tests/builder/double_require.rs, tests/builder/error.rs, tests/builder/multiple_values.rs, tests/builder/subcommands.rs, tests/builder/utils.rs, tests/builder/version.rs
=> test(builder): Switch more to assert_error

clap_builder/src/parser/parser.rs, tests/builder/ignore_errors.rs
=> fix(parser): Set correct source on ignore-errors with did-you-mean

clap_builder/src/builder/action.rs, clap_builder/src/builder/arg.rs, clap_builder/src/builder/debug_asserts.rs, clap_builder/src/builder/range.rs, clap_complete/src/engine/complete.rs, tests/builder/action.rs, tests/builder/flags.rs, tests/derive/flags.rs
=> feat(builder): Allow flags to take `num_args=0..=1`

tests/builder/ignore_errors.rs
=> test(parser): Correct misleading test names

Cargo.toml, examples/tutorial_builder/03_06_required.md, examples/tutorial_builder/03_06_required.rs, examples/tutorial_derive/03_02_option.md, examples/tutorial_derive/03_03_positional.rs, examples/tutorial_derive/03_06_optional.md, examples/tutorial_derive/03_06_optional.rs, src/_derive/_tutorial.rs, src/_tutorial.rs
=> docs(tutorial): Explicitly cover required vs optional 

clap_complete/tests/testsuite/engine.rs
=> test(complete): Minor test cleanup

clap_builder/src/builder/debug_asserts.rs, tests/builder/multiple_values.rs
=> (chore) update quote

clap_builder/src/parser/matches/arg_matches.rs
Resolves https://github.com/clap-rs/clap/issues/5973.
This PR just provides a method suggested in the issue linked above. Use case is described there.
=> Support clearing args matches

src/lib.rs
=> docs: Improve starting point for builder reference

examples/tutorial_builder/03_04_subcommands.md, examples/tutorial_derive/03_04_subcommands.md, src/_derive/mod.rs
=> docs(derive): Specify arg_required_else_help is set for users

.cargo/config.toml, .github/renovate.json5, .pre-commit-config.yaml, Cargo.toml, clap_builder/README.md, clap_builder/src/lib.rs, clap_complete/src/lib.rs, clap_complete_nushell/src/lib.rs, clap_derive/README.md, clap_lex/src/lib.rs, clap_mangen/src/lib.rs, deny.toml, src/lib.rs
=> chore: Update from _rust/main template

src/_faq.rs
=> docs: Fix minor grammar issues in FAQ

clap_builder/src/macros.rs, tests/builder/macros.rs
=> feat(builder): Allow quoted id's for arg macro

clap_builder/src/builder/command.rs
Added some doc comments to clarify the intent and make it easier to understand the tests
=> Chore: document several internal assertion helper methods

clap_complete/src/engine/custom.rs
=> feat(complete): Expand ~ in native completions

clap_builder/src/builder/command.rs, src/_derive/mod.rs
=> docs: Try to clarify several points
