src/derive.rs

The deprecation notice for `from_clap` was mentioning the wrong replacement function.
Thanks for all your work on clap, and congratulations on the v3 release!

Correct replacement function for Parser::from_clap

---

Cargo.toml
examples/cargo-example-derive.md
examples/cargo-example.md
examples/demo.md
examples/derive_ref/custom-bool.md
examples/escaped-positional-derive.md
examples/escaped-positional.md
examples/git-derive.md
examples/git.md
examples/keyvalue-derive.md
examples/multicall-busybox.md
examples/multicall-hostname.md
examples/pacman.md
examples/tutorial_builder/README.md
examples/tutorial_derive/README.md

This just affects how it's rendered; rather than attempting to highlight
these blocks as a shell script, they'll get highlighted as console
output.
See the rendered versions for a better comparison.
This supersedes #3260

docs: Fix messed up highlighting

---

src/parse/arg_matcher.rs
src/parse/matches/arg_matches.rs

This is a surgical workaround for #3263.  It makes `cargo` pass tests!

fix(parser): Loosen asserts for now

---

clap_derive/src/attrs.rs
tests/derive/arg_enum.rs

The error was when doing `#[clap(arg_enum, default_value_t = ...)]`.
Good example of why we should minimize `use`, at least in tests
(besides reducing merge conflicts, code churn, etc).

fix(derive): Don't assume `use clap::ArgEnum`

---

README.md
examples/cargo-example-derive.rs
examples/demo.rs
examples/derive_ref/README.md
examples/derive_ref/custom-bool.rs
examples/escaped-positional-derive.rs
examples/git-derive.rs
examples/tutorial_derive/01_quick.rs
examples/tutorial_derive/02_app_settings.rs
examples/tutorial_derive/02_apps.rs
examples/tutorial_derive/02_crate.rs
examples/tutorial_derive/03_01_flag_bool.rs
examples/tutorial_derive/03_01_flag_count.rs
examples/tutorial_derive/03_02_option.rs
examples/tutorial_derive/03_03_positional.rs
examples/tutorial_derive/03_04_subcommands.rs
examples/tutorial_derive/03_05_default_values.rs
examples/tutorial_derive/04_01_enum.rs
examples/tutorial_derive/04_02_validate.rs
examples/tutorial_derive/04_03_relations.rs
examples/tutorial_derive/04_04_custom.rs
examples/tutorial_derive/05_01_assert.rs

`#[clap(about)]` only overrides `about`.  If the doc comment also sets
`long_about`, it won't be overridden.  This change is to help raise
visibility of reseting `long_about` in these cases.

docs(examples): Steer people to know about about vs long_about

---

clap_complete/src/shells/elvish.rs
clap_complete/tests/completions/elvish.rs

[Elvish v0.17](https://elv.sh/blog/0.17.0-release-notes.html#deprecated-features) deprecated the old lambda syntax (`[arg1 arg2] { body }`) in favour of the new `{|arg1 arg2| body }` syntax. This PR uses the new syntax to stop deprecation warnings.

fix(complete): Use Elvish v0.17 lambda syntax

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/completions/zsh.rs

```
> my_app <tab>
_my_app:40: parse error near `;;'
```
invalid zsh (see line: `::file -- some input's file:_files'`):
```zsh
local context curcontext="$curcontext" state line
_arguments "${_arguments_options[@]}" \
'-h[Print help information]' \
'--help[Print help information]' \
'-V[Print version information]' \
'--version[Print version information]' \
'::file -- some input's file:_files' \
":: :_myapp_commands" \
"*::: :->myapp" \
&& ret=0
case $state in
(myapp)
words=($line[2] "${words[@]}")
(( CURRENT += 1 ))
curcontext="${curcontext%:*:*}:myapp-command-$line[2]:"
case $line[2] in
(test)
_arguments "${_arguments_options[@]}" \
'--case=[test'\''s cases to test]: : ' \
'-h[Print help information]' \
'--help[Print help information]' \
'-V[Print version information]' \
'--version[Print …
```

fix: unescaped chars appearing in zsh completion script

---

src/parse/errors.rs

Fix the mismatched \` in [`clap::Error::raw`](https://docs.rs/clap/latest/clap/struct.Error.html#implementations).

docs: Fix mismatched `

---

src/parse/matches/arg_matches.rs

I've got an assertion failure that pointed to `/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.7/src/parse/matches/arg_matches.rs:220:24`, which isn't a helpful location.

Track caller on methods using assertions

---

clap_complete/tests/completions/bash.rs
clap_complete/tests/completions/zsh.rs
clap_complete_fig/tests/completions/fig.rs
src/build/app/mod.rs
src/parse/parser.rs

We might be able to handle version/help before propagation but I didn't
want to hold up this fix for that to happen and increase the risk
associated with this fix.
Fixes #3298

fix(help): Always respect DisableColoredHelp

---

src/build/app/mod.rs

Similar to `App::find_subcommand`, except it returns a mutable reference to the subcommand.

implement App::find_subcommand_mut

---

src/build/app/mod.rs
tests/builder/help.rs

I thought I was adding a test in #3305.  Maybe I considered the
clap_complete changes sufficient for this.  Doing more `debug_assert`s
would be good also.
Unsetting `PropagateVersion` helps in some cases but we need to unset it
globally to override the global propagation.
Fixes #3310

fix: Don't panic when propagating

---

src/parse/arg_matcher.rs
src/parse/matches/matched_arg.rs
tests/builder/conflicts.rs

We were only tracking the last value source (default, env, cli, etc).
This works for args because they only come from one source.  Groups
however can come from multiple sources and this was making us treat a
group with a default value as being completely from defaults despite
some values maybe being from the commandline.
We now track the highest precedence value for a group.
Fixes #3330

fix(parser): Track the most explicit value source

---

clap_derive/src/attrs.rs
clap_derive/src/parse.rs
examples/derive_ref/README.md

Add `default_value_os_t` attribute
The order of suffixes allows us to preserve the original builder function name.
This is a part of #2813

feat: add default_value_os_t

---

README.md

- "Builder API" was a link to https://docs.rs/clap, which is incorrect. Fixed it with a link to the tutorial.
- Updated "Derive API" to also target the relevant tutorial instead of the list of examples.

Fix link to Builder API in README

---

examples/derive_ref/README.md

The proper syntax for the attribute is "parse" not "parser".

Correct README syntax for bool flag

---

src/build/arg/mod.rs
src/output/help.rs
tests/builder/help.rs
tests/builder/utils.rs
tests/derive/options.rs

When an Arg uses .min_values(0), that arg's value(s) are effectively
optional. This is conventionaly denoted in help messages by wrapping the
arg's values in square brackets. For example:
--foo[=value]
--bar [value]
This kind of argument can be seen in the wild in many git commands; e.g.
git-status(1).
Signed-off-by: Peter Grayson <pete@jpgrayson.net>

fix(help): Optional arg values in brackets

---

src/output/fmt.rs
src/output/help.rs

These tweaks shrink the argparse-benchmark-rs test app by 40KB and cut the release build time by half a second.
There might be other low-hanging fruit. I found these by skimming cargo-bloat and trying a few different things.

Optimize code size

---

clap_derive/src/attrs.rs
tests/derive_ui/positional_bool.stderr

The example at https://github.com/clap-rs/clap_derive/tree/master/examples/true_or_false.rs has been superseded by the combination of [custom-bool.md](https://github.com/clap-rs/clap/blob/master/examples/derive_ref/custom-bool.md) and [custom-bool.rs](https://github.com/clap-rs/clap/blob/master/examples/derive_ref/custom-bool.rs).
Instead of updating the link to point to the example source, I updated the link to point to the new Markdown since the Markdown includes the rendered `--help` as well as a link to the source.

Update link to explicit bool parser example

---

src/parse/matches/arg_matches.rs

In clap2, `ArgMatches.args` was public but hidden.  We made it private
in clap3, giving us more implementation flexibility but many people
relied on it, like to short-circuit defaulting, providing their own
`ArgRequiredElseHelp`, etc.
The main problem was how to expose this
- If we think of `ArgMatches` as a container (a DAG), should we have an
`is_empty` and what all is included in that, like subcommands?
- If we focus on only args, what term how do we refer to this to convey
the right intent?
In the end, I realized that this aligns most with our existing
`is_present` check and reporting if args are present fits the best
within the existing API.
I looked into also exposing iterating over the args (`present_arg_ids`)
but we have no way to expose the Id.  The Id is currently private and if …

feat(parser): Check if args were present

---

src/build/app/mod.rs
src/output/usage.rs
src/parse/validator.rs
tests/builder/double_require.rs
tests/builder/require.rs

For some errors, we use the unroll logic to get the list of required
arguments.  The usage then does the same, but without a matcher.  This
was causing the lists to not match.
As a side effect, this fixed an ordering issue where we were putting the
present arg after the not-present arg.  I assume its because we ended up
reporting the items twice but the first time is correctly ordered and
gets precedence.
This was split out of #3020

fix(error): Be more accurate in smart usage

---

src/parse/errors.rs
tests/builder/possible_values.rs

We respected it for `--help` but not error messages.
Fixes #1549

fix(error): Consistently respect possible values order

---

src/parse/errors.rs
src/parse/validator.rs
tests/builder/possible_values.rs

This is inspired by cargo which allows you to run `cargo test --test`
and it will list the possible tests (obviously we can't support that atm
because that requires a lot of runtime processing).  When we do have a
static list of possible values, we can at least show those.
Fixes #3320

feat(error): Show possible values when none are supplied

---

examples/keyvalue-derive.md
examples/tutorial_builder/README.md
examples/tutorial_derive/README.md
src/error/context.rs
src/error/kind.rs
src/error/mod.rs
src/parse/matches/arg_matches.rs
src/parse/parser.rs
src/parse/validator.rs
tests/builder/subcommands.rs
tests/builder/validators.rs

This has some limited programmatic use but the focus is on allowing people to format the errors as they wish.
Downside is that the `.text` section for the `git` example went from 547.9KiB to 566.8KiB.  `Error::formatted` is the sixth largest clap function at 6.0KiB.
Fixes #2628
Fixes #3227

feat(error): Expose error building blocks

---

clap_mangen/README.md
clap_mangen/src/lib.rs

This is just to help get people started.  We need to document the entire life cycle for man pages (generation to being read by user).

docs(man): Add some basic documentation

---

src/build/app/mod.rs
src/build/arg/mod.rs
src/build/arg_group.rs
src/output/usage.rs
src/parse/arg_matcher.rs
src/parse/matches/matched_arg.rs
src/parse/validator.rs
tests/builder/conflicts.rs
tests/builder/require.rs

This supersedes #3020 
Fixes #3076

 Requires and Conflicts should ignore default_value

---

src/parse/arg_matcher.rs
src/parse/validator.rs
tests/builder/app_settings.rs

fix(help): ArgsRequiredElseHelp should ignore defaults

---

src/build/arg/debug_asserts.rs
tests/builder/default_missing_vals.rs
tests/builder/default_vals.rs

This can help people catch them via `App::debug_assert` rather than
waiting until the default is used and validated.
Fixes #3202

fix(assert): Report invalid defaults in debug asserts

---

Cargo.toml
examples/tutorial_builder/04_02_parse.rs
examples/tutorial_builder/04_02_validate.rs
examples/tutorial_builder/README.md
examples/tutorial_derive/04_02_parse.rs
examples/tutorial_derive/04_02_validate.rs
examples/tutorial_derive/README.md

Adds a more in depth validator to validate that the port is in range in the derive and builder tutorial (section 4.2).
This supersedes #3416

docs(tutorial): Demonstrate custom parsing

---

src/build/arg/mod.rs

Documentation wasn't changed when the implementation was.
Explicit doc link removed because `cargo doc` resolves the link fine without it (tested on 1.58.0 and 1.54.0).

Doc that `validator` takes &str, not String

---

clap_complete/src/shells/fish.rs
clap_complete/src/shells/zsh.rs
src/build/app.rs
src/build/arg.rs
src/build/arg_settings.rs
src/build/possible_value.rs
src/build/usage_parser.rs
src/error/mod.rs
tests/builder/app_settings.rs
tests/builder/arg_settings.rs
tests/builder/help.rs
tests/builder/version.rs

- ArgSettings are part of #2717
- Errors are part of #2628
- `help_heading` is part of #1807 and #1553
- Some misc parts are for API consistency

fix: Deprecate various APIs

---

examples/tutorial_builder/03_04_subcommands.rs
examples/tutorial_derive/03_04_subcommands.rs
src/build/app_settings.rs
src/parse/parser.rs
tests/builder/app_settings.rs
tests/derive/structopt.rs

Like was said in #2435, this is what people would expect.
While we should note this in a compatibility section in the changelog, I
do not consider this a breaking change since we should be free to adjust
the help output as needed.  We are cautious when people might build up
their own content around it (like #3312) but apps should already handle
this with `--help` so this shouldn't be a major change.
We aren't offering a way for people to disable this, assuming people
won't need to.  Longer term, we are looking at support "Actions" (#3405)
and expect those to help customize the flags.  We'll need something
similar for the `help` subcommand.
Fixes #3440

fix(help): Subcommand `help` looks like `--help`

---

clap_derive/src/attrs.rs
clap_derive/src/parse.rs

I'm assuming this is from when structopt always set author, version, and
about and you had to apply other attributes to remove them.

refactor(derive): Remove redundant code paths

---

clap_complete/src/shells/zsh.rs
clap_complete_fig/src/fig.rs
clap_mangen/src/render.rs
src/build/arg.rs
src/build/arg_group.rs
src/build/debug_asserts.rs
src/macros.rs
tests/builder/help.rs
tests/builder/tests.rs
tests/derive/help.rs
tests/macros.rs

This adjusts names.  Adjusting the derive naming (and re-naming) is left
to #2475.
Fixes #3335

fix: Clarify Arg/ArgGroup id's role

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/into_app.rs
clap_derive/src/derives/subcommand.rs
clap_mangen/src/render.rs
examples/git.rs
examples/pacman.rs
examples/tutorial_builder/03_04_subcommands.rs
examples/tutorial_builder/README.md
src/build/app_settings.rs
src/output/usage.rs
src/parse/parser.rs
src/parse/validator.rs
tests/builder/app_settings.rs

#3280 will see us switch the derive to `ArgRequiredElseHep`.  This prepares the way by resolving some lingering issues with it.  Now, there is little value in offering `SubcommandRequiredElseHelp`, so we also deprecate it.

fix: ArgRequiredElseHep is viable alt to SubcommandRequiredElseHelp

---

src/build/app.rs
src/build/app_settings.rs
src/build/arg.rs
src/build/arg_group.rs
src/build/arg_settings.rs
src/derive.rs
src/error/mod.rs
src/lib.rs
src/macros.rs

We left them in the docs for a period of time to help people find docs
for code that was still in use.  Balancing that with the need for clean
docs, it seems like 3.1 is an appropriate time to mark them hidden in
the docs.

docs: Hide items deprecated in 3.0.0

---

clap_mangen/src/render.rs
src/build/app.rs
src/build/app_tests.rs
src/build/debug_asserts.rs
src/error/mod.rs
src/output/help.rs
src/output/usage.rs
src/parse/arg_matcher.rs
src/parse/features/suggestions.rs
src/parse/parser.rs
src/parse/validator.rs

The long term goals are
- Easier refactoring
- Identify needs for reflection API
Shorter term, if I want to rename `App` to `Command` and deprecate
`App`, it will mark all member access as deprecated.  This works around
that.
I gave up in exploring abstractions when it came to `MKeyMap` access.
This can be refined in the future.

refactor: Reduce visibility on App members 

---

examples/pacman.md
src/build/app.rs
src/output/help.rs
tests/builder/flag_subcommands.rs

This fixes issues with the output and makes it more consistent.
See #1361 for example pacman output for any concern of inconsistency with that.  Pacman uses a space for alternate.  The original PR used a comma.  This switches to pipe since that is the generally expected alternate character in usage.

fix(help): Improve pacman help output

---

tests/derive_ui/unsupported_parser.rs
tests/derive_ui/unsupported_parser.stderr

This PR adds a UI test for the `unsupported parser` error.
I noticed that the span of the error was set to the call site rather than the parser tokens. I wanted to fix that, but when doing so I noticed that is has already been fixed on the main branch,
Nevertheless, I already added a UI test for it. So if you feel the UI test is useful to prevent regressions, here it is :)

test: Add UI test for unsupported parsers.

---

examples/cargo-example.rs
examples/escaped-positional.rs
examples/tutorial_builder/01_quick.rs
examples/tutorial_builder/02_app_settings.rs
examples/tutorial_builder/02_crate.rs
examples/tutorial_builder/03_01_flag_bool.rs
examples/tutorial_builder/03_01_flag_count.rs
examples/tutorial_builder/03_02_option.rs
examples/tutorial_builder/03_03_positional.rs
examples/tutorial_builder/03_04_subcommands.rs
examples/tutorial_builder/03_05_default_values.rs
examples/tutorial_builder/04_01_enum.rs
examples/tutorial_builder/04_01_possible.rs
examples/tutorial_builder/04_02_parse.rs
examples/tutorial_builder/04_02_validate.rs
examples/tutorial_builder/04_03_relations.rs
examples/tutorial_builder/04_04_custom.rs
examples/tutorial_builder/05_01_assert.rs
examples/tutorial_builder/README.md
examples/tutorial_derive/README.md
src/build/command.rs
src/macros.rs
tests/builder/app_from_crate.rs
tests/builder/command.rs
tests/builder/main.rs

This is a follow up to #3472 and is part of resolving #3089.
Instead of just renaming it, I reconsidered what the API should look
like.  A custom separator for author does not make sense positionally
but accepting a name, and defaulting it, does fit with what someone
would expect.
I removed the `_from_crate` suffix because it doesn't seem necessary.
We don't have this kind of naming for the derive.  I feel it cleans
things up this way.

fix: Update app_from_crate for App rename

---

clap_complete/examples/value_hints_derive.rs
clap_derive/src/derives/into_app.rs
clap_derive/src/dummies.rs
examples/tutorial_derive/04_04_custom.rs
examples/tutorial_derive/05_01_assert.rs
src/build/command.rs
src/derive.rs
src/lib.rs
tests/derive/app_name.rs
tests/derive/arguments.rs
tests/derive/custom_string_parsers.rs
tests/derive/default_value.rs
tests/derive/doc_comments_help.rs
tests/derive/help.rs
tests/derive/utils.rs

This is a follow up to #3472 and is part of resolving #3089.
With `Command` renamed, we need to handle the renaming of `IntoApp::into_app`.  `into_*` functions are meant to take `self` as a parameter (see https://rust-lang.github.io/api-guidelines/naming.html#c-conv) which this does not.  I think switching to `command` is sufficient for the function.  That leaves naming the trait.  Java has given a lot of us a negative feeling towards the name `Factory` but calling this a `CommandFactory` is the best, descriptive name I've been able to come up with.
For compatibility, we `pub use CommandFactory as IntoApp` and have `command()` be an inherent function that calls the deprecated `into_app`.  While in #3472, I shied away from using `use` because it doesn't trigger the deprecation warning, …

fix: Change `IntoApp::into_app` to `CommandFactory::command`

---

CHANGELOG.md
CONTRIBUTING.md
src/build/arg.rs
src/build/command.rs
src/lib.rs
src/parse/matches/arg_matches.rs

I did a spot check of the generated docs in case things didn't look or work as expected.

docs: Polish in prep for 3.1.0

---

src/parse/matches/arg_matches.rs

These UTF-8-validating functions can panic, and should point to the user code.

More track_caller

---

Cargo.toml
examples/README.md
examples/derive_ref/README.md
examples/tutorial_builder/README.md
examples/tutorial_derive/03_04_subcommands_alt.rs
examples/tutorial_derive/README.md

This is another step to helping with #3189.  The main thing I want to add is to show equivalencies between derives and builders so people understand how they translate into each other.

docs(examples): Help smooth out some rought edges

---

.github/workflows/ci.yml
Makefile
clap_derive/src/attrs.rs
tests/derive/subcommands.rs

This was overlooked when we added support for `#[clap(subcommand)]` to
variants.
Fixes https://github.com/clap-rs/clap/issues/3504

fix(derive): Allow other attributes with subcommand that has subcommands

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml
Cargo.toml
Makefile
README.md
clap_complete/src/shells/bash.rs
clap_complete/src/shells/zsh.rs
src/build/possible_value.rs
src/output/help.rs
src/parse/parser.rs
src/parse/validator.rs
tests/builder/help.rs
tests/builder/utils.rs

- unstable-v4 feature
- Show help for possible values
#3312

Possible Value help

---

examples/derive_ref/README.md

Before, we had the focus on attributes and how they were impacted by
various features.  Now we separate out language items and put both magic
and raw attributes under the type of attribute (command, arg, etc)
This supersedes #3526
This helps towards #3189 and captures a subset of #3520.

docs(derive): Shift structure around lang->builder

---

examples/tutorial_derive/README.md

Hi,
this fixes a link in your documentation that tripped me :-)
Jörg

Fix link to example

---

src/build/debug_asserts.rs
tests/derive/arg_enum.rs

Fixes a regression when combining `ArgEnum` and a `default_value` with multiple values, e.g.:
```rust
#[derive(ArgEnum)]
enum Arg {
Foo,
Bar,
}
#[derive(Parser)]
struct Opts {
#[clarp(arg_enum, default_value="foo,bar", value_delimiter=',')]
arg: Vec<Arg>
}
```
This results in the following error and backtrace:
```
thread 'arg_enum::vec_type_default_value' panicked at 'Argument `arg`'s default_value=foo,bar doesn't match possible values', src/build/debug_asserts.rs:691:21
stack backtrace:
0: rust_begin_unwind
at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/8769f4ef2fe1efddd1f072485f97f568e7328f79/library/core/src/panicking.rs:143:14
2: clap::build::debug_asserts::assert_defaults
at …
```

fix: multiple default values combined with `ArgEnum` / `PossibleValues`

---

src/parse/matches/arg_matches.rs

Add documentation for grouped_values_of

---

clap_complete/tests/common.rs
clap_complete/tests/snapshots/special_commands.bash.log
clap_complete/tests/snapshots/special_commands.elvish.log
clap_complete/tests/snapshots/special_commands.fish.log
clap_complete/tests/snapshots/special_commands.powershell.log
clap_complete/tests/snapshots/special_commands.zsh.log
clap_complete_fig/src/fig.rs
clap_complete_fig/tests/common.rs
clap_complete_fig/tests/snapshots/special_commands.fig.js

Hi there!
This PR adds support for:
- `.hide(true)` on both subcommands and options
- `require_equals` on args.

feat(clap_complete_fig): support `hide` and `require_equals`

---

clap_complete/tests/common.rs
clap_complete/tests/snapshots/special_commands.bash.log
clap_complete/tests/snapshots/special_commands.zsh.log
clap_complete_fig/src/fig.rs
clap_complete_fig/tests/common.rs
clap_complete_fig/tests/snapshots/special_commands.fig.js

I actually mis-read our docs and used the wrong name + added requiresEqual to the wrong sub-object.
Sorry for that!

fix(clap_complete_fig): Correct `requiresEquals` name and add it to the right objects

---

clap_complete_fig/src/fig.rs
clap_complete_fig/tests/snapshots/special_commands.fig.js

Support printing hidden and non-hidden aliases to fig completion specs.

feat(clap_complete_fig): Add subcommand aliases support

---

src/macros.rs

Small documentation fix, help string in `arg!()` must be double-quoted.

docs: arg! macro uses double quotes for help string

---

clap_mangen/src/render.rs
clap_mangen/tests/snapshots/aliases.bash.roff
clap_mangen/tests/snapshots/feature_sample.bash.roff
clap_mangen/tests/snapshots/special_commands.bash.roff
clap_mangen/tests/snapshots/sub_subcommands.bash.roff
clap_mangen/tests/snapshots/value_hint.bash.roff

This was split out from https://github.com/clap-rs/clap/pull/3580

Use `Arg::value_name()` as header for positionals in clap_mangen

---

CHANGELOG.md

I found unnecessary backtick in changelog breaks one of items. This PR fixes it. No issue is linked to this PR because this is very small typo fix.

docs: Remove unnecessary backtick in changelog

---

Cargo.toml
README.md
clap_lex/CHANGELOG.md
clap_lex/CONTRIBUTING.md
clap_lex/Cargo.toml
clap_lex/LICENSE-APACHE
clap_lex/LICENSE-MIT
clap_lex/README.md
clap_lex/src/lib.rs
clap_lex/tests/lexer.rs
clap_lex/tests/parsed.rs
clap_lex/tests/shorts.rs
src/build/command.rs
src/build/debug_asserts.rs
src/mkeymap.rs
src/parse/lexer.rs
src/parse/mod.rs
src/parse/parser.rs

This splits out a `clap_lex`, somewhat inspired by `lexopt`.  The main difference is that `lexopt` manages all state in one object while we have to split out the state to support:
- Peeking to know if we should treat a flag as a flag
- Inserting replacements
This was also done with an eye towards rust-driven completions.  This will let the completion engine reuse the same lexer.  The parsers will be different for now but as we learn more about a completion parser, we can look to see if and how we can use the same parser between the two.  One side effect of this is that we treat `--` as potentially a long and `-` as potentially a short.  The problem with this approach is we aren't treating `-` as a long as well because there is nothing good for us to return.  We might need to reconsider …

feat: Expose clap_lex

---

.github/workflows/ci.yml
.github/workflows/post-release.yml
.github/workflows/rust-next.yml
.github/workflows/spelling.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Set permissions for GitHub actions

---

Cargo.toml

While `clap` depends on `clap_derive`, `clap_derive` inherently has a
dependency on `clap` because it generates code assuming at least a
specific clap version.  If a new `clap_derive` is used with an old
`clap`, it'll generate code that won't compile.
We've kept things loose because of
- Bad experiences with overly constrained version reqs
- To not force new `clap` versions to release `clap_derive`.
- People should have a lock file anyways
The downsides:
- `cargo install` does not use `Cargo.lock` by default, required
`--locked`
- If we want people to not skip non-patch releases when upgrading, we
need it to not be a pain

fix(derive): Couple derive version to clap

---

clap_complete/src/generator/mod.rs
clap_complete/src/generator/utils.rs
clap_mangen/src/lib.rs
src/build/command.rs
src/build/tests.rs
src/parse/features/suggestions.rs
src/parse/parser.rs
tests/builder/app_settings.rs
tests/builder/help.rs

`Command::_build_all` started as an internal function for
`clap_complete` as a stopgap until #2911.  Overtime, we've been finding
more cases where this function needs to be called, so now we're going to
fully embrace it until #2911 so people aren't scrared off by the hidden
implementation from using it.
This was inspired by #3602
Comptibility: Though this adds a deprecation which we general reserve
for minor or major versions, this is enough of a corner case that I'm
fine doing this in a patch release.

feat(clap): Publicly expose `Command::build`

---

clap_mangen/Cargo.toml

`Command.build()` is not available in 3.1.9.
Fixes: 8f182067e345 ("feat(clap): Publicly expose `Command::build`")

fix(man): Explicitly depend on clap 3.1.10

---

clap_mangen/src/render.rs
clap_mangen/tests/common.rs
clap_mangen/tests/roff.rs
clap_mangen/tests/snapshots/value_env.bash.roff

This PR updates the man page renderer to add a space between argument help text and environment variable information. There is also a new test-case added for testing this change.
fixes #3630

fix(man): show the environment info with separate paragraph

---

src/build/arg.rs
src/build/command.rs
src/error/mod.rs
src/macros.rs
src/output/fmt.rs
src/parse/parser.rs
src/parse/validator.rs
tests/builder/app_settings.rs

This both makes intent clearer and will make it easier in the future to [allow users to customize the parts](https://github.com/clap-rs/clap/discussions/3476)
On the way to getting there, some of the refactors ended up fixing a couple of bugs
- We had two different implementations for detecting conflicts with one being a subset of the other.  This brings the subset to be in line with the superset
- We inconsistently treated overrides as conflicts.  Now we do so

refactor(validator): Decouple parser

---

src/output/fmt.rs

stderr and stdout got mixed up by [6a9a5d05](https://github.com/clap-rs/clap/commit/6a9a5d05) in v3.1.11
fixes https://github.com/rust-lang/cargo/issues/10591

fix: Mixup between stderr and stdout introduced in v3.1.11

---

src/parse/parser.rs
tests/builder/groups.rs

This adds a test for de89c050c9e20690c3abbbe53f5868299ba15d46 that
confirms #3647 is fixed
Fixes #3647

test(group): Verify overrides required 

---

Cargo.toml
src/build/command.rs
src/error/mod.rs
src/parse/parser.rs
tests/builder/app_settings.rs
tests/builder/arg_aliases.rs
tests/builder/arg_aliases_short.rs
tests/builder/conflicts.rs
tests/builder/default_vals.rs
tests/builder/derive_order.rs
tests/builder/display_order.rs
tests/builder/empty_values.rs
tests/builder/error.rs
tests/builder/flag_subcommands.rs
tests/builder/flags.rs
tests/builder/groups.rs
tests/builder/help.rs
tests/builder/help_env.rs
tests/builder/hidden_args.rs
tests/builder/opts.rs
tests/builder/possible_values.rs
tests/builder/require.rs
tests/builder/subcommands.rs
tests/builder/template_help.rs
tests/builder/utils.rs
tests/builder/version.rs

This started off with working towards one problem but I ended up getting side tracked when I noticed some of these bugs in the help output
- We inconsistently generate the usage string for help
- We showed a bad error for `foo help sub doesnt_exist`
As part of this, we moved the help-subcommand to work more like how the parser traversed `Command`s.

fix(help): Make help output more consistent

---

clap_complete/tests/snapshots/sub_subcommands.bash
clap_complete/tests/snapshots/sub_subcommands.elvish
clap_complete/tests/snapshots/sub_subcommands.fish
clap_complete/tests/snapshots/sub_subcommands.ps1
clap_complete/tests/snapshots/sub_subcommands.zsh
clap_complete_fig/tests/snapshots/sub_subcommands.fig.js
src/build/command.rs
tests/builder/tests.rs

Besides addressing the panic from assuming things were built when they
weren't, this should fix some completion issues for some people.
Fixes #3669

fix(builder): Fully recurse when building

---

examples/repl.rs
src/build/command.rs
src/build/debug_asserts.rs
src/error/mod.rs
src/output/usage.rs
src/parse/parser.rs
tests/builder/help.rs
tests/builder/subcommands.rs

This goes a long way towards resolving #2862 and in general polishing multicall for becoming stable.
The only thing that isn't ideal is that the error message refers to it as a subcommand when in some cases its a command.

fix(multicall): Polish user messages

---

src/build/command.rs
src/output/help.rs
tests/builder/help.rs

This is a step towards #992.  When help renders the application name, it
uses the `bin` template variable which is just the `bin` name with
spaces converted to ` `.  While having `app.exe sub` makes sense,
`app.exe-sub` does not.
To get around needing this for usage, we've created a `display_name`
field that is fairly similar but
- The root name is the `name` and not `bin_name`
- We always join with `-`
This means that the derived `bin_name` will only show up in usage.
For now, the default template has not been updated as that is a minor
compatibility change and should be in a minor release, at least.  I was
worried this would be a full breaking change.  The main case I was
worried about was cargo subcommands but our tests show they should just
work.

fix(help): Offer a html_template variable for display name

---

examples/tutorial_builder/README.md
examples/tutorial_derive/README.md

When evaluating the documentation for #3681, I realized the tutorial doesn't link the APIs.  Right now, its fairly subtle but this is hopefully a good starting point.

docs(tutorial): Link the derive API to the builder API

---

src/parse/validator.rs
tests/builder/conflicts.rs

`Arg::exclusive` is just another way of defining conflicts, so a
present-exclusive arg should override required like other conflicts.
Instead of going through the message of enumerating all other arguments
as exclusive, I shortcutted it and special case exclusive in the
required check like we do with conflicts.  The big downside is the
implicit coupling between the code paths rather than having a consistent
abstraction for covering conflicts.
This isn't a breaking change because if someone defined an exclusive arg
as a sibling to a required arg, the exclusive arg could never be used,
it always errored, and so no valid application can be written with it.
Fixes https://github.com/clap-rs/clap/issues/3595

fix(parser): Exclusive overrides required

---

clap_complete/tests/common.rs
clap_complete_fig/tests/common.rs
clap_mangen/tests/common.rs
src/bin/stdio-fixture.rs
src/build/arg.rs
src/build/command.rs
src/build/debug_asserts.rs
tests/builder/flags.rs
tests/builder/possible_values.rs
tests/builder/unicode.rs

This is a step towards #3309.  We want to make longs and long aliases
more consistent in how they handle leading dashes.  There is more
flexibility offered in not stripping and it matches the v3 short
behavior of only taking the non-dash form.  This starts the process by
disallowing it completely so people will catch problems with it and
remove their existing leading dashes.  In a subsequent breaking release
we can remove the debug assert and allow triple-leading dashes.

fix(v4): Disallow leading dashes in long's

---

src/output/help.rs
tests/builder/help.rs

Confusingly, there are two similar but slightly different settings in
`textwrap`.  We need both set.
Fixes #3222

fix(help): Don't wrap URLs

---

src/output/help.rs
tests/builder/help.rs

This will mean we won't have an awkard `.exe` in the middle on Windows
This means users can have a display name for their application rather
than it being dependent on the binary name it was run as
This means users can manually set it to use spaces instead of dashes for
separating things out.
Fixes #992
Fixes #1474
Fixes #1431

fix(help): Use display name instead of bin name (unstable-v4)

---

src/output/usage.rs
src/parse/validator.rs
tests/builder/double_require.rs
tests/builder/require.rs

Gave up trying to decipher the existing logic for safe ways to
de-duplicate manually and switched to an `IndexSet` to enforce only one
of each argument exists.
Fixes #3556

fix(error): Don't duplicate args in usage

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/sub_subcommands.bash
clap_complete/tests/snapshots/value_hint.bash

In a refactor for #3503, one of the checks for `is_hide_set` got flipped
and we are completing hidden `PossibleValue`s rather than visible.
Fixes #3697

fix(complete): Complete visible, rather than hidden, values

---

src/build/debug_asserts.rs

Fixes https://github.com/clap-rs/clap/issues/3660

fix(assert): Detect conflicting arguments (unstable)

---

clap_derive/src/derives/subcommand.rs
src/build/command.rs
src/parse/arg_matcher.rs
src/parse/parser.rs
tests/builder/app_settings.rs
tests/derive/subcommands.rs

When you escape subcommand (`cmd -- subcmd`), it always becomes an external subcommand even if a built-in one matches.  There wasn't a way to detect this.  Now, a user can check `matches.is_present("")` and that will signal its an external subcommand.
With this change, we've updated `clap_derive` to correctly populate external subcommands rather than the built-in version (and error if it didn't work out).
With all of that done, we can now remove the hack where we disable unknown argument assertions since users can correctly guard to prevent hitting it.
Because of compatibility concerns, this is all gated behind `unstable-v4`.
Fixes #3263

fix(parser): Disambiguate whether built-in subcommands are escaped (unstable)

---

src/builder/arg.rs

feat(builder): Updated min_value and required docs 

---

tests/derive_ui.rs
tests/derive_ui/enum_variant_not_args.stderr
tests/derive_ui/flatten_enum_in_struct.stderr
tests/derive_ui/flatten_struct_in_enum.stderr
tests/derive_ui/next/tuple_struct.stderr
tests/derive_ui/skip_without_default.stderr
tests/derive_ui/stable/tuple_struct.stderr

`derive_ui.rs` did not have a marker for needing to be updated on MSRV
changes, so it got missed.

test: Re-enable ui tests

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/subcommand.rs
examples/derive_ref/flatten_hand_args.rs
src/builder/value_parser.rs
src/parser/matches/any_value.rs
src/parser/matches/arg_matches.rs

The remove functions no longer return `Arc` but the core type, at the
cost of requiring `Clone`.  I originally held off on this
in #3732 in the hope of gracefully transition the derive and requiring
`Clone` would have been a breaking change but when it came to #3734, I didn't
find a way to make it work without a breaking change, so I made it
opt-in.  This means I can force the `Clone` requirement now.
I added the requirement for `Clone` everywhere else in the hopes that in
the future, we can drop the `Arc` without a breaking change.

fix(parser): Clean up remove types

---

src/parser/matches/arg_matches.rs
src/parser/matches/matched_arg.rs
src/parser/matches/mod.rs
src/parser/mod.rs

When I added the `get_many` and friends, I went the fast route of `impl Iterator<>`.  When handling deprecations, I found there were uses in the tests for `unwrap_or_default()` on the iterators.  This is nice and I'd like to preserve it, so I created named iterator types that implement more traits.

fix(parser): Switch to concrete iterators

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/subcommand.rs
examples/cargo-example.md
examples/derive_ref/flatten_hand_args.rs
examples/escaped-positional.rs
examples/git.rs
examples/pacman.rs
examples/tutorial_builder/01_quick.rs
examples/tutorial_builder/02_app_settings.rs
examples/tutorial_builder/02_apps.rs
examples/tutorial_builder/02_crate.rs
examples/tutorial_builder/03_02_option.rs
examples/tutorial_builder/03_03_positional.rs
examples/tutorial_builder/03_04_subcommands.rs
examples/tutorial_builder/03_05_default_values.rs
examples/tutorial_builder/04_01_enum.rs
examples/tutorial_builder/04_01_possible.rs
examples/tutorial_builder/04_02_parse.rs
examples/tutorial_builder/04_02_validate.rs
examples/tutorial_builder/04_03_relations.rs
examples/tutorial_builder/04_04_custom.rs
examples/tutorial_builder/05_01_assert.rs
src/builder/arg.rs
src/builder/value_parser.rs
src/parser/matches/arg_matches.rs

Clap has focused on reporting development errors through assertions
rather than mixing user errors with development errors.  Sometimes,
developers need to handle things more flexibly so included in https://github.com/clap-rs/clap/pull/3732 was
the reporting of value accessor failures as internal errors with a
distinct type.  I've been going back and forth on whether the extra
error pessimises the usability in the common case vs dealing with the
proliferation of different function combinations.  In working on
deprecating the `value_of` functions, I decided that it was going to be
worth duplicating so long as we can keep the documentation focused.

fix(parser): Simplify the common getter API

---

examples/derive_ref/README.md
src/builder/mod.rs
src/builder/value_parser.rs

For most users, this won't be worth doing, they can just specify the
parser if needed.  Where this has value is crates that integrate custom
types into clap, like creating click-like file integration.  See
https://click.palletsprojects.com/en/8.0.x/arguments/#file-arguments

feat(parser): Allow people to plug into 'value_parser' macro

---

src/builder/arg.rs
tests/builder/regex.rs

fix(validator): Deprecate validator_regex

---

src/builder/action.rs
src/builder/arg.rs
src/builder/command.rs
src/builder/mod.rs
src/parser/arg_matcher.rs
src/parser/matches/matched_arg.rs
src/parser/parser.rs
tests/builder/default_missing_vals.rs
tests/builder/default_vals.rs
tests/builder/multiple_values.rs

Overall this is refactoring to slowly prepare the parser for customizable responses to arguments needed for #3405.  Some of these fixed bugs along the way while others just cleaned up the parser, making it easier to understand what is going on.
The line between a bug fix and a breaking change is awkward at times.  The part that seems most questionable to me is changing how we count occurrences for positional arguments.  This gets us closer to the documented behavior and makes the parser more consistent.  I'm trying to stop short of #3763 because I worry that resolving that would be too much of a change for the 3.x line since it ties into validation.

fix(parser): Make behavior more consistent

---

src/builder/action.rs
src/builder/arg.rs
src/builder/command.rs
src/builder/mod.rs
src/parser/arg_matcher.rs
src/parser/matches/matched_arg.rs
src/parser/mod.rs
src/parser/parser.rs
tests/builder/grouped_values.rs
tests/builder/multiple_values.rs

This is not publicly exposed yet and is a step towards #3405.  Nearly all storing of data into `ArgMatches` is extracted into a `react` function that is based on an `Action` enum associated with the `Arg`.  I said "nearly" because we can't quite do this for external subcommand values.
The parser iterates once per argv field.  This presented a problem for flags with values and multi-valued positionals.  We handle this by tracking "pending" values and resolving them before reacting to the current value.  This comes at some behavior changes for `ArgMatches::occurrences_of` that could be fine for future versions of the actions though we should reconsider this before release.

refactor(parser): Extract Actions from Parser

---

src/builder/action.rs
src/builder/arg.rs
src/builder/debug_asserts.rs
src/builder/mod.rs
src/parser/parser.rs
tests/builder/action.rs
tests/builder/main.rs

This is the minimum set of actions for the derive to move off of
`parse`.  These are inspired by Python's native actions.
These new actions have a "unified" behavior with defaults/envs.  This
mostly means that occurrences aren't tracked.  Occurrences were used as
a substitute for `ValueSource` or for counting values.  Both cases
shouldn't be needed anymore but we can re-evaluate this later if needed.
There is room for performance improvements where we reuse allocations but we can worry about that as a profiler says its a case to care about.
Now that we can store constants for flags, we can apply defaults for
flags too.
Fixes #3294

feat(parser): SetTrue/SetFalse/Count Actions

---

src/builder/action.rs
src/parser/parser.rs
tests/builder/action.rs

This round out the new style actions and allow us to start deprecating
occurrences.
As part of an effort to unify code paths, this does change flag parsing
to do splits.  This will only be a problem if the user enables splits
but we'll at least not crash.  Once we also address #3776, we'll be able
to have envs all work the same.

feat(builder): Set/Append Actions

---

.github/workflows/ci.yml
Makefile
src/builder/action.rs
src/builder/arg.rs
src/builder/value_parser.rs
src/lib.rs
src/output/help.rs
src/parser/arg_matcher.rs
src/parser/parser.rs
src/parser/validator.rs
tests/builder/action.rs
tests/builder/conflicts.rs
tests/builder/default_missing_vals.rs
tests/builder/default_vals.rs
tests/derive/help.rs
tests/derive_ui/next/tuple_struct.stderr

refactor: Prep for actions in derive

---

src/output/usage.rs
src/parser/validator.rs
tests/builder/action.rs

This is a follow up to https://github.com/clap-rs/clap/pull/3420.  Its easy to overlook this because it is only
useful for the conditionals (we actually prevent applying unconditional
defaults to unconditional requireds).  This became apparent with the
increased use of defaults with `SetTrue`.
As always, there is the question of when is a bug fix a breaking change.
I'm going to consider this safe since we prevent some instances of this
from even happening and we already did https://github.com/clap-rs/clap/pull/3420 and this is in line with
those.

fix(validator): Ignore defaults for requireds

---

src/builder/value_parser.rs
src/parser/matches/any_value.rs
src/parser/matches/mod.rs

Hiding `AnyValueParser` has given us a bit more flexibility to prepare for `any_vec` in the future.  Granted, `ArgGroup`s are still a blocker.

fix(builder): Clean up after hiding `AnyValueParser`

---

src/parser/parser.rs

fix(parser): Always include pending arguments in errors

---

examples/derive_ref/README.md

Small documentation fix to update the documentedt expected signature of `try_from_os_str`. The error type of the return `Result` was stated as `OsString`, but it is actually `String`. This is confirmed by this test https://github.com/clap-rs/clap/blob/e8ad62b784b3430fbaf0f819c45330ab6c264d85/tests/derive/legacy/custom_string_parsers.rs#L109
When I was trying to use `OsString` I was unable to compile with the error ``error[E0277]: `OsString` doesn't implement `std::fmt::Display` ``. Changing the error type to `String` fixed this.

docs: update return signature for try_from_os_str

---

Cargo.toml
clap_derive/src/attrs.rs
src/lib.rs
src/macros.rs

Though this is changing an API item we export, we do not consider this a
breaking change because
- This was an implementation detail of the macros and people shouldn't be using it directly
- The `macro_rules` macro is coupled to `clap` because they are in the
same crate
- The derive macro is coupled to `clap` because `clap` declares a
`=x.y.z` dependency on `clap_derive
Fixes #3828

refactor: Switch to once_cell

---

Cargo.toml
clap_derive/Cargo.toml
clap_derive/src/attrs.rs
clap_derive/src/derives/args.rs
clap_derive/src/derives/subcommand.rs

This is a step towards #3822.  I'd say this fixes it but I'd want some
user acceptance before doing so.
To do this, we
- Mask all `ArgMatches` deprecation messages with assumption being that any message from these has its roots in an `augment_args` deprecation.  You can see the raw deprecations with `clap_derive/raw-deprecation`
- Create call generated functions with a targeted deprecation message that we call for each `parse` case. 
- Mask all deprecation messages for implicit `Arg` methods, delegating to the messages for the generated functions
We intentionally do not provide a deprecation message for implicit `parse` attributes since resolving that is just busywork that most likely won't help users in migrating to clap 4.
I had originally assumed this would be difficult to be precise …

fix(derive): Provide derive-friendly deprecation messages

---

clap_derive/src/attrs.rs
tests/derive/default_value.rs

Fixes `default_value_os_t` which was broken in https://github.com/clap-rs/clap/pull/3829

fix: default_value_os_t

---

src/output/help.rs

This was done when looking into #3835

fix(help): Improve debug output for help

---

src/builder/action.rs
src/builder/arg.rs

Between
- `ArgAction::SetTrue` storing actual values
- `ArgAction::Set` making it easier for derive users to override bool
behavior
- `Arg::default_missing_value` allowing hybrid-flags
- This commit documenting hybrid-flags even further
There shouldn't be anything left for #1649
Fixes #1649

docs: Provide a hybrid-flag example

---

clap_complete/tests/general.rs

Looks like I forgot to add a test case for this.
I put this in `clap_complete` because I expect `ValueHint` to move here
as we move towards a plugin system.
Fixes #3840

test(complete): Ensure we infer path completions from value_parser

---

Cargo.toml
clap_complete/Cargo.toml
clap_complete_fig/Cargo.toml
clap_derive/Cargo.toml
clap_lex/Cargo.toml
clap_mangen/Cargo.toml

See...
- https://doc.rust-lang.org/cargo/reference/manifest.html?#the-documentation-field
- https://doc.rust-lang.org/cargo/reference/manifest.html?#the-readme-field

chore: trim Cargo manifest fields whose values are defaults

---

.clippy.toml
.github/workflows/ci.yml
.github/workflows/rust-next.yml
Cargo.toml
Makefile
README.md
clap_bench/Cargo.toml
clap_complete/Cargo.toml
clap_complete_fig/Cargo.toml
clap_derive/Cargo.toml
clap_lex/Cargo.toml
clap_mangen/Cargo.toml

Being a patch release, I'm fine doing this outside of a minor release.
This avoids us having to deal with indexmap having a higher MSRV.

chore: Bump MSRV from 1.56.0 to 1.56.1

---

src/builder/app_settings.rs
src/builder/arg_settings.rs
src/derive.rs
src/macros.rs

Before, I was mixed on doing this as ideally people would upgrade
through the minor releases, going through the release notes.  This also
saves us havin to audit deprecations to make sure they are all pointing
to the latest.
First, this isn't practical for users.  Its annoying to pin your version (at least
its easier now that we pin `clap_derive` for users) and a lot of work to
go through them one step at a time.
On top of that, we've changed our deprecation policy to put the timing
of responding to deprecations into the user's hands with, with us
putting them behind the `deprecated` feature flag.  This means someone
might respond to deprecations every once in a while or might not do it
until right before the 4.0 release.  Our deprecation messages should be
updated to respond to that. …

fix(docs): Update deprecations to latest target

---

examples/derive_ref/README.md

It was spelled 'APIS' before. The 'APIs' spelling is consistent with the rest of the code base.

Fix spelling of 'APIs' in the derive docs

---

clap_derive/src/attrs.rs
src/lib.rs
src/macros.rs
tests/derive_ui/next/bool_value_enum.stderr

When upgrading our company projects from clap 3.1 to clap 3.2 I had
to fix several references to `clap::lazy_init`. People are not
supposed to do that, but that's hard to enforce.
Hope placing `once_cell` reexport into `__macro_refs` prevent at
least some of the such issues in the future.

Put once_cell reexport into __macro_refs

---

Cargo.toml
src/builder/command.rs
src/error/mod.rs
src/parser/error.rs
src/parser/matches/arg_matches.rs
tests/derive_ui/next/tuple_struct.stderr

By checking these types, we'll get some other types for free, like
`Command` verifying `Arg`.
This was inspired by #3876

test: Verify auto-traits for core types

---

src/builder/command.rs
tests/builder/tests.rs

feat: add `mut_subcommand` method to modify existing subcommands

---

clap_complete_fig/src/fig.rs

This removes the deprecated `is_multiple_occurrences_set` and uses `ArgAction` instead

feat(clap_complete_fig): Switch to using `ArgAction`

---

README.md

This example is the first example on the [main documentation page](https://docs.rs/clap/latest/clap/). However, by default, copy pasting just the example doesn't work since it requires enabling the `derive` feature first. The necessity of this is described after the example, which makes it easy to miss. By adding this comment to the top of the example it is more likely to be noticed by devs eager to get their command line handling going.
It's a minor thing, I missed it, got a compile failure and only then scrolled down far enough to see the note about the feature. I expect I'm not the only one who has done that, so maybe this prevents others from running into this. Feel free to close if not deemed important enough.

Add comment about requiring the derive feature.

---

examples/derive_ref/README.md

This makes it more clear that quotes are needed. When deriving `ValueEnum` (and possibly in other cases as well), the attribute is silently ignored if the user leaves off these quotes: see #3907.

docs(derive): Clarify `rename_all` takes a string literal

---

src/builder/command.rs
tests/builder/tests.rs

follow-up to PR #3882, as discussed in that PR's comments `mut_subcommand` does not resolve aliases and, if an alias name is passed for `subcmd_id`, would trigger invalid behavior as per #3888.
thus to avoid this, one might resolve the alias name to the actual name before calling `mut_subcommand`, but this is currently almost impossible to do due to `mut_subcommand` signature's with the `'help` lifetime. specifically, looking at the test code included in this PR and without the lifetime changes, we get the following error:
```
error[E0597]: `true_name` does not live long enough
--> tests/builder/tests.rs:459:32
|
459 |     cmd = cmd.mut_subcommand(&*true_name, |subcmd| subcmd.about("modified about"));
|                                ^^^^^^^^^ borrowed value does not live long enough
460 …
```

fix: loosen lifetime constraint on mut_subcommand

---

src/builder/command.rs
tests/builder/conflicts.rs

So that it doesn't panic if trying to get the conflicts for an Arg that
conflicts with a group.
Fixes: #3900

Include groups in `get_arg_conflicts_with`

---

src/parser/parser.rs
tests/builder/multiple_values.rs

We had some tests for this but not sufficient obviously.  The problem is
we were tweaking the positional argument counter when processing flags
and not just positional arguments.  Delaying it until after flags seems
to fix this.
Fixes #3959

fix(parser): low index multiples work with flags

---

CHANGELOG.md
src/error/kind.rs
src/error/mod.rs
tests/builder/default_vals.rs
tests/builder/empty_values.rs
tests/builder/opts.rs

There isn't a reason to programmatically differentiate them so this
merges them simplify programamtic cases and to hopefully reduce binary
size.

fix(error):! Merge EmptyValue into InvalidValue

---

CHANGELOG.md
clap_derive/src/derives/subcommand.rs
examples/derive_ref/hand_subcommand.rs
src/error/kind.rs
src/error/mod.rs
tests/builder/app_settings.rs
tests/builder/help.rs
tests/builder/subcommands.rs

fix(error)!: Merge UnrecognizedSubcommand into InvalidSubcommand

---

CHANGELOG.md
clap_bench/benches/06_rustup.rs
clap_derive/src/derives/args.rs
clap_derive/src/derives/into_app.rs
clap_derive/src/derives/subcommand.rs
clap_mangen/src/render.rs
examples/derive_ref/interop_tests.md
src/builder/app_settings.rs
src/output/usage.rs
src/parser/validator.rs
tests/builder/app_settings.rs

This also let us remove the deprecated attribute
Fixes #3280

fix(derive): Move off of SubcommandRequiredElseHelp

---

src/builder/command.rs

When checking into binary size, I noticed that the `git` example is a
lot larger than v3.  `git bisect` narrowed it down to
11076a5c7033b25c34e3e3008f02b9c5d4efa3d3 which doesn't make sense.  I
did noticed we could remove some bloat from monomorphization.
Overall for `cargo-example, we've dropped about 47 KiB.
Related to #1365

perf: Remove some monomorphization bloat

---

CHANGELOG.md
src/builder/command.rs
src/builder/possible_value.rs
src/parser/matches/arg_matches.rs

fix!: Remove more deprecated APIs

---

Cargo.lock
Cargo.toml
clap_bench/Cargo.toml
clap_complete/Cargo.toml
clap_complete_fig/Cargo.toml
clap_derive/Cargo.toml
clap_mangen/Cargo.toml

The main goal is to reduce the risk of people developing on the wrong
release, assuming they are using something like starship to raise the
visibility of the crate version.

chore: Update version

---

clap_derive/src/attrs.rs
clap_derive/src/parse.rs
src/_derive/mod.rs
tests/derive/default_value.rs
tests/derive/value_enum.rs
tests/derive_ui/default_values_t_invalid.rs
tests/derive_ui/default_values_t_invalid.stderr

feat(clap_derive): Add `default_values_t` and `default_values_os_t` for Vec field types

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/snapshots/aliases.zsh
clap_complete/tests/snapshots/basic.zsh
clap_complete/tests/snapshots/feature_sample.zsh
clap_complete/tests/snapshots/quoting.zsh
clap_complete/tests/snapshots/special_commands.zsh
clap_complete/tests/snapshots/sub_subcommands.zsh
clap_complete/tests/snapshots/value_hint.zsh
clap_complete_fig/tests/snapshots/basic.fig.js
clap_complete_fig/tests/snapshots/feature_sample.fig.js
clap_complete_fig/tests/snapshots/quoting.fig.js
clap_complete_fig/tests/snapshots/special_commands.fig.js
clap_complete_fig/tests/snapshots/sub_subcommands.fig.js
src/builder/arg.rs
src/builder/arg_settings.rs
src/builder/command.rs
src/builder/debug_asserts.rs
src/error/kind.rs
src/error/mod.rs
src/parser/arg_matcher.rs
src/parser/validator.rs
tests/builder/multiple_values.rs
tests/derive/custom_string_parsers.rs

For num_vals and friends, this only implements hacks until #2688
Fixes #3021

fix!: Remove multiple occurrences in favor of Append/Count

---

CHANGELOG.md
src/builder/debug_asserts.rs
tests/builder/subcommands.rs

fix(assert)!: Prevent repeated subcommand names

---

CHANGELOG.md
clap_derive/src/derives/subcommand.rs
examples/git.rs
src/builder/app_settings.rs
src/builder/command.rs
src/builder/debug_asserts.rs
src/error/kind.rs
src/parser/matches/arg_matches.rs
tests/builder/app_settings.rs
tests/builder/utf8.rs

This changes the default type as well to encourage preserving the full
information for shelling out.  If people need UTF-8, then they can
change the value parser.
Fixes #3733

fix!: Use value parsers for external subcommands

---

CHANGELOG.md
src/parser/parser.rs
tests/builder/default_missing_vals.rs

This both simplifies the code and the model we present to the user,
making more sense.
There is room for further exploration of tying flag actions into this.

fix(parser)!: Apply default_missing_value per occurrence

---

CHANGELOG.md
src/builder/arg.rs
src/builder/debug_asserts.rs
src/builder/mod.rs
src/lib.rs
src/output/help.rs
src/parser/arg_matcher.rs
src/parser/parser.rs
src/parser/validator.rs
tests/builder/app_settings.rs
tests/builder/help.rs
tests/builder/multiple_values.rs
tests/builder/opts.rs
tests/builder/utils.rs
tests/macros.rs

Splitting this out and getting it merged so I can more easily iterate on different approaches to resolving #2688.

fix: Misc clean up in prep for #2688

---

CHANGELOG.md
src/builder/action.rs
src/builder/arg.rs
src/parser/parser.rs

In the short term, this just provides a back door to custom actions.
Longer term, we can explore a `SetConst` action that relies on this
behavior.  Really, `SetTrue` and `SetFalse` are shortcuts for such an
action but shortcuts can be helpful for usability.
Apparently, this also reduced `.text` size by 1k

fix(parser): Rely on default_missing_value for flag actions

---

CHANGELOG.md
examples/tutorial_builder/01_quick.md
examples/tutorial_builder/03_01_flag_count.md
examples/tutorial_derive/01_quick.md
examples/tutorial_derive/03_01_flag_count.md
src/builder/arg.rs
src/output/help.rs
tests/builder/conflicts.rs
tests/builder/help.rs
tests/builder/template_help.rs

fix(help): Show when a flag 'ArgAction::Count's

---

src/output/usage.rs
tests/builder/require.rs

When suggesting required arguments, we wanted to avoid an argument
showing up in both a group and by itself but we didn't correctly
calculate that, causing no required arguments to show up at times.
Now, we all use the same pool of information for doing the calculations.
This was the type of cleanup that I expected it to drop our binary size
but this added 1k to our .text.  Strange.
Fixes #4004

fix(parser): Include required argument in message 

---

src/builder/arg.rs

Just a tiny typo I spotted while reading docs

[Documentation] fix typo in arg.rs

---

examples/tutorial_derive/04_01_enum.rs
src/_derive/mod.rs

This is a partial backport of #4015
Fixes #4008
Fixes #4009

docs: Remove references to ArgEnum

---

CHANGELOG.md
examples/multicall-busybox.rs
src/builder/arg.rs
src/builder/arg_settings.rs
src/builder/command.rs
src/builder/debug_asserts.rs
src/error/kind.rs
src/parser/matches/arg_matches.rs
tests/builder/app_settings.rs
tests/builder/default_vals.rs
tests/builder/delimiters.rs
tests/builder/env.rs
tests/builder/grouped_values.rs
tests/builder/help.rs
tests/builder/indices.rs
tests/builder/multiple_values.rs
tests/builder/opts.rs

fix!: Remove Arg::use_value_delimiter in favor of Arg::value_delimiter

---

src/parser/parser.rs

refactor(parser): Prep for more #2688 work

---

CHANGELOG.md
src/error/kind.rs
src/parser/arg_matcher.rs
src/parser/parser.rs
tests/builder/opts.rs

This will allow `num_args(0..=1).value_delimiter(',')` to work properly.
This hacks in support for `require_value_delimiter` until we can remove
it.
This no longer recognzes value terminators in delimited lists.
It looks like there is a bug with recognizing value terminators in
positionals arguments.  We'll need to dig into that more.
This is a part of #2688

fix(parser)!: Split on value delimiter after validating num_args

---

CHANGELOG.md
src/builder/arg.rs
src/builder/arg_settings.rs
src/builder/debug_asserts.rs
src/parser/arg_matcher.rs
tests/builder/app_settings.rs
tests/builder/default_vals.rs
tests/builder/help.rs
tests/builder/multiple_values.rs
tests/builder/opts.rs

In clap v3, `require_value_delimiter` activated an alternative parse
mode where
- `multiple_values` meant "multiple values within a single arg"
- `number_of_values` having no parse impact, only validation impact
- `value_names` being delimited values
For unbounded `number_of_values`, this is exactly what `value_delimiter`
provides.  The only value is if someone wanted `value_name` to be
`<file1>,<file2>,...` which can be useful and we might look into adding
back in.
Alternatively, this could be used for cases like key-value pairs but
that has issues like not allowing the delimiter in the value which might
be ok in some cases but not others.  We already instead document that
people should instead use `ValueParser` for this case.
In removing this, we remove points of confusion at how the …

fix!: Remove `Arg::rwquire_value_delimiter`

---

src/builder/arg.rs
src/builder/debug_asserts.rs

As we move people off takes_value/multiple_values, this will provide
something to check.
This was previously blocked on other issues related to flag handling
(#4023)

fix: Always ensure `num_args` is initialized

---

src/builder/arg.rs
src/builder/arg_settings.rs

TakesValue helps because it provides a way for a lot of settings to say
a value is needed without specifying how many.  Multiple values didn't
have enough call sites to make this worthwhile.
This is a part of #2688

refactor: We don't need MultipleValues for bookkeeping afterall

---

CHANGELOG.md
clap_bench/benches/03_complex.rs
clap_bench/benches/04_new_help.rs
clap_bench/benches/05_ripgrep.rs
clap_bench/benches/06_rustup.rs
clap_complete/src/shells/zsh.rs
clap_complete_fig/src/fig.rs
src/builder/arg.rs
src/builder/arg_settings.rs
src/builder/debug_asserts.rs
src/builder/mod.rs
src/builder/range.rs
src/macros.rs
tests/builder/help.rs
tests/builder/help_env.rs
tests/derive/flags.rs
tests/macros.rs

This removes the need for `TakesValue` bookkeeping for when we knew we
took values but didn't know how many we should take.
Fixes #2687

fix!: Make ArgAction::Set the default 

---

src/_derive/mod.rs

Noticed this was missing when responding to #4041
This is specific to v3.  #4044 is the v4 equivalent.

docs(derive): Clarify what defaulted action/value_parser does

---

clap_derive/src/attrs.rs
src/_derive/mod.rs
tests/derive/naming.rs

Previously the Arg id was set with the "name" attribute. This allows use of an "id" attribute to match the underlying struct.
A side effect of this is that the "id" attribute may also be used on Commands. This isn't desired, but given the current architecture of the attribute parser, it's hard to avoid.
Fixes: #3785

fix(derive): Add "id" attribute

---

src/builder/arg.rs
src/macros.rs
tests/builder/help.rs
tests/builder/hidden_args.rs
tests/builder/version.rs
tests/derive/help.rs
tests/macros.rs

Documenting the existing behavior is challenging which suggests it can
cause user confusion.  So long as its not too hard to explicitly
specify actions, we should just do it.
Fixes #4057

fix: No implicit version/help actions

---

.clippy.toml
.github/workflows/ci.yml
.github/workflows/rust-next.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
Makefile
clap_bench/Cargo.toml
clap_complete/Cargo.toml
clap_complete_fig/Cargo.toml
clap_derive/Cargo.toml
clap_lex/Cargo.toml
clap_mangen/Cargo.toml
examples/tutorial_derive/04_04_custom.rs
src/lib.rs
tests/derive_ui.rs
tests/derive_ui/bool_value_enum.stderr
tests/derive_ui/default_value_wo_value_removed.stderr
tests/derive_ui/default_values_t_invalid.stderr
tests/derive_ui/enum_variant_not_args.stderr
tests/derive_ui/flatten_enum_in_struct.stderr
tests/derive_ui/flatten_struct_in_enum.stderr
tests/derive_ui/skip_without_default.stderr

While at it, this cleans up all of the features.  For some reason, I
couldn't do `dep:clap_derive` though.

chore: Bump MSRV to 1.60.0 

---

Cargo.lock
Cargo.toml
src/builder/command.rs
src/builder/debug_asserts.rs
src/builder/value_parser.rs
src/output/help.rs
src/output/usage.rs
src/parser/arg_matcher.rs
src/parser/matches/arg_matches.rs
src/parser/validator.rs
src/util/flat_map.rs
src/util/flat_set.rs
src/util/mod.rs

For the number of items we manage, straight iteration is probably fast enough or faster and this reduces the amount of memory we use.
The map is modeled after the proposed version in C++ so that the keys are more likely to be in cache lines.  If we ever add sorting to this, it'll get messy though.  Since this is all internal, direct types are exposed rather than newtypes.
This is a good step towards #1365.  The `.text` size dropped by 30.8KB according to 
```console
$ cargo bloat --features cargo --example cargo-example --release
```
While I didn't measure build times, things should be improved for #2037 because we are sending less code to LLVM.

refactor: Move off of HashMap/IndexMap to flat containers

---

clap_derive/src/attrs.rs
src/_derive/mod.rs
tests/derive/naming.rs

Backported from future version 4 (original commit 1a2ae767388a452d99173c4d3043eb2d0e8a5b41)
> Previously the Arg id was set with the "name" attribute. This allows use of an "id" attribute to match the underlying struct.
>
> A side effect of this is that the "id" attribute may also be used on Commands. This isn't desired, but given the current architecture of the attribute parser, it's hard to avoid.
>
> Fixes: #3785
---
Almost forgot to submit this. The original PR was #4049. Let me know if you’d like me to make any changes.

v3 fix(derive): Add "id" attribute

---

CHANGELOG.md
clap_bench/benches/03_complex.rs
clap_bench/benches/04_new_help.rs
clap_derive/src/attrs.rs
src/builder/arg.rs
src/builder/command.rs
src/builder/possible_value.rs
src/util/id.rs
tests/builder/arg_aliases.rs
tests/builder/arg_aliases_short.rs
tests/builder/default_vals.rs
tests/builder/flag_subcommands.rs
tests/builder/help.rs
tests/builder/multiple_values.rs
tests/builder/subcommands.rs
tests/builder/utils.rs
tests/derive/non_literal_attributes.rs

The main breakinge change cases:
- `&[char]`: now requires removing `&`
- All other non-ID `&[_]`: hopefully #1041 will make these non-breaking
Fixes #2870

fix!: Prefer `IntoIterator` over `&[]`

---

CHANGELOG.md
src/builder/arg.rs
src/builder/arg_group.rs
src/builder/arg_predicate.rs
src/builder/command.rs
src/builder/mod.rs
src/lib.rs
src/output/usage.rs
src/parser/arg_matcher.rs
src/parser/matches/matched_arg.rs
src/parser/parser.rs
src/parser/validator.rs
src/util/id.rs
src/util/mod.rs
src/util/os_str.rs
src/util/str.rs
tests/builder/action.rs
tests/builder/default_vals.rs
tests/builder/require.rs

This helps with
- API cleanup by not having ambigious `None`, see #950
- Removes ambiguity with `None` when using owned/borrowed types for
#1041

fix!: Require/default conditional APIs are more explicit

---

CHANGELOG.md
src/builder/action.rs
tests/derive/flags.rs

Not sure if we could have originally made this work but it definitely
does now that we use `default_missing_value` for this (#4000)

fix: Allow non-bool value_parsers for SetTrue

---

CHANGELOG.md
src/builder/action.rs
src/builder/mod.rs
src/builder/value_parser.rs
tests/derive/flags.rs

While `TypedValueParser` will generally make it easier to reuse value
parsers, this was particularly written for flags.  Besides having a
concrete API to document, an advantage over `fn(&str) -> Result<bool, E>`
value parsers is you get all of the benefits of the existing value
parsers for environment variable parsing.

feat(parser): Make customizeing flags easier

---

Cargo.toml
clap_derive/src/attrs.rs
src/builder/arg.rs
src/builder/debug_asserts.rs
src/builder/mod.rs
src/builder/resettable.rs
src/lib.rs
src/output/help.rs
src/parser/parser.rs
src/util/os_str.rs
tests/builder/default_vals.rs
tests/derive/default_value.rs

Another step towards #1041
This allowed removing a dependency as well which helps towards #2037

fix: Switch to owned OsStr type

---

clap_complete/src/dynamic.rs
clap_complete/src/generator/utils.rs
clap_complete/src/shells/bash.rs
clap_complete/src/shells/fish.rs
clap_complete/src/shells/shell.rs
clap_complete/src/shells/zsh.rs
clap_derive/src/attrs.rs
clap_derive/src/derives/value_enum.rs
clap_derive/src/dummies.rs
examples/tutorial_builder/04_01_enum.rs
src/builder/arg.rs
src/builder/possible_value.rs
src/builder/value_parser.rs
src/derive.rs
src/error/mod.rs
src/lib.rs
src/output/help.rs
src/parser/parser.rs
src/parser/validator.rs
src/util/mod.rs
src/util/os_str.rs
src/util/str.rs

Another step towards #1041
This isn't the long term type for `PossibleValue::help`, I just wanted
to get the lifetime out of the way first before figuring out how help
will work.

fix!: Remove lifetime from PossibleValue 

---

clap_mangen/src/render.rs
clap_mangen/tests/common.rs
clap_mangen/tests/roff.rs
clap_mangen/tests/snapshots/feature_sample.bash.roff
clap_mangen/tests/snapshots/possible_values.bash.roff
clap_mangen/tests/snapshots/special_commands.bash.roff
clap_mangen/tests/snapshots/sub_subcommands.bash.roff
clap_mangen/tests/snapshots/value_hint.bash.roff
src/builder/arg.rs

This adds feature parity for mangen with the standard help output. Users
will now see the list of possible values for value arguments.
One change that was made to make this possible was adding the method
`get_possible_values` to the public API for an arg. I tried to think of
a way to get around this, but because this is the interface that the
help generation uses, and it is part of the crate public interface
I thing adding it as a part of the public API might be for the best.
If that is not the best option, please let me know and i can go back and look at it.
fixes: #3861

fix: Show possible values in generated man file

---

CHANGELOG.md
src/builder/command.rs
src/builder/mod.rs
src/builder/styled_str.rs
src/error/context.rs
src/error/format.rs
src/error/kind.rs
src/error/mod.rs
src/parser/parser.rs
src/parser/validator.rs
src/util/flat_map.rs
tests/builder/error.rs

For now, there isn't much a custom implementation can do.
Going from `Rich` to `Null` drops about 6 KiB from the binary
This is a part of #1365 and #1384

perf(error): Allow custmizing formatting

---

src/builder/command.rs

Extend Command::override_usage() doc string to describe how to format
multiple usage lines to be compatible with clap's default help formatter.
Relates-to: #3413

docs: overriding multi-line usage

---

src/builder/command.rs

This is a backport of #4106 to the v3-master branch.

docs: How to override multi-line usage

---

CHANGELOG.md
src/builder/arg.rs
src/builder/styled_str.rs
src/output/help.rs
src/output/usage.rs

fix(help): Use a more neutral palette

---

clap_derive/src/derives/value_enum.rs
tests/derive_ui/value_enum_non_unit.stderr

This PR fixes the `abort!` message when applying the derive directive to enums containing variants that are non-unit. 
I found the previous message confusing due to using double negation:
> "`#[derive(ValueEnum)]` only supports non-unit variants, unless they are skipped"
I believe the message should instead be:
> "`#[derive(ValueEnum)]` only supports non-unit variants if they are skipped"
Or even more explicit, as provided in the patch:
> "`#[derive(ValueEnum)]` only supports unit variants. Non-unit variants must be skipped"

Fix abort message when deriving non-unit enum variants

---

src/output/usage.rs

This is a follow up to #4117.  Didn't notice due to the differences in rendering ANSI codes between machines.

fix(error): Don't underline indentation

---

clap_derive/src/derives/value_enum.rs
tests/derive_ui/value_enum_non_unit.stderr

Backported from v4 (`master`). Original change: https://github.com/clap-rs/clap/pull/4118

[Backport] Fix: Amend error message when deriving enums

---

src/builder/styled_str.rs

This came from feedback: https://rust-lang.zulipchat.com/#narrow/stream/220302-wg-cli/topic/Help.20changes.20in.20clap.20v4

fix(help): Don't dim placeholders

---

CHANGELOG.md
clap_complete/examples/completion-derive.rs
clap_derive/src/parse.rs
examples/tutorial_derive/04_01_enum.rs

fix(derive): Remove deprecated arg_enum attribute

---

.github/workflows/audit.yml
.github/workflows/pre-commit.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

src/builder/command.rs

fix(help): Command::print_help should respect disable_colored_help

---

CHANGELOG.md
clap_derive/src/attrs.rs
src/builder/arg.rs
tests/builder/default_vals.rs
tests/derive/default_value.rs

fix: Deprecate _os variants

---

src/output/usage.rs
src/util/flat_set.rs

Some clean up done on the way to making changes for #4132

refactor(help): Prep for usage fixes

---

src/builder/arg.rs
src/output/usage.rs

This will become more apparent as we stop collapsing args
Working towards #4132

fix(help): Ensure consistency in usage

---

examples/derive_ref/custom-bool.md
examples/tutorial_builder/04_03_relations.md
examples/tutorial_derive/04_03_relations.md
src/output/usage.rs
src/parser/validator.rs
src/util/flat_map.rs
src/util/flat_set.rs
tests/builder/default_vals.rs
tests/builder/require.rs

A lot of this came out of prep for more changes for #4132.
I do wonder if the other types of requires should be included in `self,.required` and should check for conflicts.
This dropped binary size by 3 KiB (#1365)

fix(parser): Improve required error messages

---

src/builder/command.rs
tests/builder/help.rs

This was identified in https://github.com/clap-rs/clap/discussions/4134

fix(usage): Don't include irrelevant parent args

---

CHANGELOG.md
examples/pacman.md
examples/tutorial_builder/04_03_relations.md
examples/tutorial_derive/04_03_relations.md
src/builder/app_settings.rs
src/builder/command.rs
src/output/usage.rs
tests/builder/app_settings.rs
tests/builder/conflicts.rs
tests/builder/help.rs
tests/builder/opts.rs
tests/builder/positionals.rs
tests/builder/require.rs

The setting was added to resolve #769.  The reason it was optional is out
of concern for applications with a lot of positional arguments.  I think
those cases are rare enough that we should just push people to override
the usage.  Positional arguments are generally important enough, even if
optional, to show.
As a side effect, this fixed some bugs with
`dont_collapse_args_in_usage` where it would repeat an argument in a
smart usage.
As a side effect, smart usage now shows `--` when it should
Along the way, misc other usage bugs were fixed
This was `.text` size neutral.
This is a part of #4132

fix(usage): Make dont_collapse_args_in_usage the default 

---

clap_mangen/src/render.rs
clap_mangen/tests/common.rs
clap_mangen/tests/roff.rs
clap_mangen/tests/snapshots/feature_sample.bash.roff
clap_mangen/tests/snapshots/possible_values.bash.roff
clap_mangen/tests/snapshots/special_commands.bash.roff
clap_mangen/tests/snapshots/sub_subcommands.bash.roff
clap_mangen/tests/snapshots/value_hint.bash.roff
src/builder/arg.rs

This pull request cherry picks the commits from #4082  to fix #3861 for v3.

Backport Bugfix/3861 to V3: Mangen not showing possible values

---

CHANGELOG.md
examples/cargo-example-derive.md
examples/cargo-example.md
examples/derive_ref/interop_tests.md
examples/git-derive.md
examples/git.md
examples/pacman.md
examples/tutorial_builder/01_quick.md
examples/tutorial_builder/03_04_subcommands.md
examples/tutorial_derive/01_quick.md
examples/tutorial_derive/03_04_subcommands.md
src/builder/command.rs
src/output/help.rs
src/output/usage.rs
tests/builder/app_settings.rs
tests/builder/derive_order.rs
tests/builder/display_order.rs
tests/builder/help.rs
tests/builder/subcommands.rs
tests/builder/template_help.rs
tests/derive/help.rs
tests/ui/arg_required_else_help_stderr.toml
tests/ui/error_stderr.toml
tests/ui/h_flag_stdout.toml
tests/ui/help_cmd_stdout.toml
tests/ui/help_flag_stdout.toml

In switching to title case for help headings (#4123), it caused me to
look at "subcommand" in a fresh light.  I can't quite put my finger on
it but "Subcommand" looks a bit sloppy.  I also have recently been
surveying other CLIs and they just use "command" as well.
All of them are commands anyways, just some are children of others
(subcommands) while others are not (root or top-level commands, or just
command).  Context is good enough for clarifying subcommands from root
commands.
This is part of #4132

fix(help): Use Command in place of Subcommand

---

CHANGELOG.md
src/output/help.rs
tests/builder/help.rs

This ensures we don't end up with accidental leading or trailing
newlines due to help template variables not being used when a section is
empty.
This is prep for removing name/version from the default template and is
part of #4132

fix(help): Always trim output

---

CHANGELOG.md
clap_mangen/tests/snapshots/possible_values.bash.roff
clap_mangen/tests/snapshots/value_env.bash.roff
src/builder/command.rs
tests/builder/help.rs
tests/builder/hidden_args.rs
tests/derive/help.rs
tests/ui/arg_required_else_help_stderr.toml
tests/ui/h_flag_stdout.toml
tests/ui/help_cmd_stdout.toml
tests/ui/help_flag_stdout.toml

In reviewing CLIs for #4132, I found some were providing helps on `-h`
vs `--help` and figured that could be built directly into clap.  I had
considered not making this hint automatic but I figured the overhead of
checking if long exists wouldn't be too bad.  The code exists (no binary
size increase) and just a simple iteration is probably not too slow
compared to everything else.
Fixes #1015

fix(help): Clarify short vs long help

---

examples/derive_ref/augment_args.rs
examples/derive_ref/flatten_hand_args.rs
examples/escaped-positional.rs
examples/pacman.rs
examples/tutorial_builder/03_01_flag_bool.rs
examples/tutorial_builder/03_01_flag_count.rs
examples/tutorial_builder/04_03_relations.rs
examples/tutorial_builder/04_04_custom.rs
src/builder/action.rs
src/parser/matches/arg_matches.rs

This is scoped specifically to Actions and not something we'll create for everything.  These actions have two unique properties: a fixed type and a default which makes more of a difference.
I know something like this already exists in cargo and probably elsewhere.  Seems probably worth while to make this easier.

feat(parser): Provide convenience accessors for Actions

---

clap_derive/src/attr.rs
clap_derive/src/item.rs

fix(derive): Remove helper for removed help_heading

---

CHANGELOG.md
clap_derive/src/attr.rs
clap_derive/src/derives/args.rs
clap_derive/src/derives/subcommand.rs
clap_derive/src/derives/value_enum.rs
clap_derive/src/item.rs
clap_derive/src/lib.rs
clap_derive/src/utils/spanned.rs
tests/derive_ui/external_subcommand_misuse.stderr
tests/derive_ui/skip_flatten.stderr
tests/derive_ui/skip_subcommand.stderr
tests/derive_ui/struct_subcommand.stderr
tests/derive_ui/subcommand_and_flatten.stderr

refactor(derive): Prepare for builder attributes

---

clap_derive/src/item.rs
tests/derive/explicit_name_no_renaming.rs
tests/derive/naming.rs
tests/derive/non_literal_attributes.rs
tests/derive_ui/flatten_and_methods.rs
tests/derive_ui/flatten_and_methods.stderr
tests/derive_ui/subcommand_and_methods.rs
tests/derive_ui/subcommand_and_methods.stderr

fix(derive): Report deprecations/errors in more cases

---

CHANGELOG.md
examples/tutorial_builder/02_app_settings.md
examples/tutorial_derive/02_app_settings.md
src/output/help.rs
tests/builder/help.rs

If short help is too long for the terminal, clap will automatically switch to next line help.  As part of next line help for longs, we add a blank line between args.  This helps make the args clearer when dealing with multiple paragraphs.  However, its not as much needed for short and subcommands (always short), so now short matches subcommands.
This was inspired by #3300 and a part of #4132

fix(help):Be dense on short next line help

---

CHANGELOG.md
clap_derive/src/attr.rs
clap_derive/src/item.rs

When I removed these in v5, we didn't have a deprecation approach for the derive and I didn't want to forget.  Now we do have a deprecation approach and that is the reminder, so we don't need to carry around v5 changes.

revert(derive): Bald action/value_parser are deprecated, its good enough

---

CHANGELOG.md
src/builder/value_parser.rs

This is a partial backport of #4095.  This was written to allow mapping bools to other types but this will be useful for people using `PossibleValue` with non-string types to upgrade to value parsers.

feat(parser): TypedValueParseer::map for adapting value parsers

---

clap_complete/src/shells/shell.rs
clap_derive/src/derives/args.rs
src/builder/action.rs
src/builder/app_settings.rs
src/builder/arg.rs
src/builder/arg_group.rs
src/builder/arg_settings.rs
src/builder/command.rs
src/parser/matches/arg_matches.rs

docs: Expand on deprecation instructions

---

CHANGELOG.md
clap_derive/src/attr.rs
clap_derive/src/derives/args.rs
clap_derive/src/item.rs
clap_derive/src/lib.rs
src/derive.rs
tests/derive/groups.rs
tests/derive/main.rs
tests/derive/naming.rs

These are the building blocks for us to automatically create an `ArgGroup` when deriving `Args` on a struct.  This will make it easier to compose (write validation rules) particularly when the struct comes from a third party.
The next step will then be to support deriving `Args` on enums, see #2621

feat(derive): Reserve behavior needed for implicit ArgGroups

---

CHANGELOG.md
examples/derive_ref/interop_tests.md
src/builder/command.rs
src/mkeymap.rs
src/parser/parser.rs
tests/builder/app_settings.rs
tests/derive/subcommands.rs

Just having `--help` or `--version` can make us get invalid args instead
of invalid subcommands.   It doesn't make sense to do this unless
positionals are used.  Even then it might not make sense but this is at
least a step in the right direction.
Unsure how I feel about this being backported to clap 3.  It most likely would be fine?
This was noticed while looking into #4218

fix(parser): Prefer invalid subcommands over invalid args

---

Cargo.lock
Cargo.toml

Together because `textwrap` also depends on `terminal_size`.
- `terminal_size` from `0.1.12` to `0.2.1`
- `textwrap` from `0.15.0` to `0.15.1`

chore(deps): bump `terminal_size` dependency to `0.2.1` and `textwrap` to `0.15.1`

---

CHANGELOG.md
clap_derive/src/derives/args.rs
clap_derive/src/derives/parser.rs
clap_derive/src/derives/subcommand.rs
examples/tutorial_builder/03_05_default_values.md
examples/tutorial_builder/03_05_default_values.rs
examples/tutorial_derive/03_05_default_values.md
examples/tutorial_derive/03_05_default_values.rs
src/builder/arg.rs
src/builder/command.rs
src/mkeymap.rs
src/parser/arg_matcher.rs
src/parser/matches/arg_matches.rs
src/util/flat_map.rs
tests/builder/version.rs
tests/derive/help.rs

fix: Misc fixes found when optimizing code size

---

.github/workflows/audit.yml

`permission: read` is invalid. There are three styles `permissions: {}`, `permissions: read-all` or
```yaml
permissions:
contents: read
...
```

fix: Permissions syntax

---

examples/pacman.md
src/builder/styled_str.rs
src/output/help.rs

fix(help): Separate command flags like options

---

src/error/format.rs
src/error/mod.rs
src/lib.rs
tests/builder/error.rs

`clap::Error::raw` was producing ambiguity errors with a default generic
parameter on `clap::error::Error` (which `clap::Error` is a re-export
of).
I tried making `clap::Error` a type alias with a default generic
parameter but that ran into an ambiguity error with `map_err`.
So I'm going ahead and hard coding `clap::Error`.  We don't expect
people to change this all that often.

fix(error): Use a non-generic Error alias 

---

src/builder/str.rs
src/builder/value_parser.rs

Last time I tried this, I wasn't able to resolve the lifetime issues.  I
seemed to have gotten it working this time.
This brings us more inline with `parser(...)` behavior from clap_derive v3
This came up in #4254.

feat(parser): Support more types with `value_parser!`

---

src/builder/command.rs
src/builder/range.rs
src/builder/styled_str.rs
src/builder/value_parser.rs
src/derive.rs
src/error/mod.rs
src/macros.rs
src/output/fmt.rs
src/output/help_template.rs
src/output/usage.rs
src/parser/features/suggestions.rs
src/parser/matches/any_value.rs
src/parser/matches/arg_matches.rs
src/parser/parser.rs
src/parser/validator.rs
src/util/flat_map.rs

For binary size, this only dropped 0.2 KiB
For performance, before:
- parse_rustup_with_sc    time:   [7.9866 µs 8.0138 µs 8.0470 µs]
After:
- parse_rustup_with_sc    time:   [7.5387 µs 7.5722 µs 7.6157 µs]
For build-time, before
```console
$ hyperfine --warmup=1 --min-runs=5 "--prepare=cargo clean" "cargo build -F cargo --example cargo-example"
Benchmark 1: cargo build -F cargo --example cargo-example
Time (mean ± σ):     16.988 s ±  1.190 s    [User: 68.178 s, System: 6.637 s]
Range (min … max):   15.550 s … 18.277 s    5 runs
```
After:
```console
$ hyperfine --warmup=1 --min-runs=5 "--prepare=cargo clean" "cargo build -F cargo --example cargo-example"
Benchmark 1: cargo build -F cargo --example cargo-example
Time (mean ± σ):     15.674 s ±  0.222 s    [User: 62.287 s, System: 4.608 s] …
```

perf: Drop use of Into::into for '?'

---

CHANGELOG.md
examples/tutorial_builder/03_01_flag_bool.md
examples/tutorial_derive/03_01_flag_bool.md
src/builder/action.rs
src/builder/app_settings.rs
src/builder/command.rs
src/builder/value_parser.rs
src/parser/arg_matcher.rs
src/parser/matches/arg_matches.rs
src/parser/parser.rs
tests/builder/action.rs
tests/builder/app_settings.rs
tests/builder/flags.rs
tests/builder/grouped_values.rs
tests/builder/indices.rs
tests/builder/multiple_occurrences.rs
tests/builder/multiple_values.rs
tests/derive/flags.rs
tests/derive/options.rs

fix(parser): Conflict-with-self is back on by default

---

src/builder/command.rs

The styling of usage has changed in #4188 such that the usage string is on the same line as the "Usage:" title. Previously, the usage went on the line below the title. As such, the rules have changed for how to make a multiline usage format correctly.
These updated rules achieve the following output for the documented example:
Usage: myapp -X [-a] [-b] <file>
myapp -Y [-c] <file1> <file2>
myapp -Z [-d|-e]
Relates-to: #4132

docs: Update multiline usage override rules

---

src/parser/parser.rs
tests/builder/flags.rs

This error was untested and didn't fit the style of our other errors
```
error: The value 'value' was provided to '--flag' but it wasn't expecting any more values
example --other <path>...
For more information try '--help'
```
- It should show a usage type
- It should show the flag in the usage so people can scan more quickly for what is wrong
This supersedes #4268

fix(error): Polish `--flag=bad-value` error

---

clap_mangen/src/render.rs

Respect remaining hidden flags
- Arg::hide_default_value
- Arg::hide_long_help
- Arg::hide_short_help
Fixes #3361

fix(mangen): Respect more hide values

---

src/_derive/_tutorial.rs

There are a couple of typos where a backtick is missing / too much which results in slightly broken formatting. This PR should hopefully fix them.

Fix inline code snippet typos

---

clap_derive/src/item.rs

The problem with updating all code to use non-deprecated APIs, there
aren't tests for the old way anymore.
Fixes #4274

fix(derive): Ensure clap/structopt attributes still work 

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/snapshots/aliases.zsh
clap_complete/tests/snapshots/basic.zsh
clap_complete/tests/snapshots/feature_sample.zsh
clap_complete/tests/snapshots/quoting.zsh
clap_complete/tests/snapshots/special_commands.zsh
clap_complete/tests/snapshots/sub_subcommands.zsh
clap_complete/tests/snapshots/value_hint.zsh

In zsh completion rules, the `*` denotes whether a flag/argument is allowed multiple times or not. However, in clap 4.0.0, all flag/option rules are always marked with `*` even if it makes no sense to supply them multiple times, such as `--help`.
This regressed for flags/options in 6f03b4f948af4d862db3343a1fd8b48454404a2f, the logic for handling non-multiple arguments with zsh was simply thrown out. While the consequences of this are minor, it's discouraging to see logic discarded without an understanding of why it's there.
The printing of positional multiple args was also tweaked, `ValueRange::new(0..=1)` should not be treated as multiple values.

fix(complete): Fix zsh handling of multiple arguments

---

src/builder/action.rs
src/builder/debug_asserts.rs
src/parser/parser.rs
tests/builder/action.rs
tests/builder/posix_compatible.rs

bat needed this.
See also #4261

fix(parser): Allow one-off self-overrides

---

examples/tutorial_builder/03_01_flag_bool.md
examples/tutorial_derive/03_01_flag_bool.md
src/error/format.rs
tests/builder/conflicts.rs

Inspired by rust-lang/cargo#11159

fix(error): Specialize the self-conflicts error

---

clap_complete/examples/completion-derive.rs
clap_complete/examples/completion.rs
clap_complete/src/generator/utils.rs
clap_complete/src/shells/bash.rs
clap_complete/src/shells/zsh.rs
clap_complete/tests/common.rs
clap_complete/tests/snapshots/aliases.bash
clap_complete/tests/snapshots/basic.bash
clap_complete/tests/snapshots/feature_sample.bash
clap_complete/tests/snapshots/quoting.bash
clap_complete/tests/snapshots/special_commands.bash
clap_complete/tests/snapshots/sub_subcommands.bash
clap_complete/tests/snapshots/sub_subcommands.zsh
clap_complete/tests/snapshots/value_hint.bash

This should fix https://github.com/clap-rs/clap/issues/4273, https://github.com/clap-rs/clap/issues/4280, and the Bash part of https://github.com/clap-rs/clap/issues/4265. I haven't started looking at the Fish side or other shells yet.
This is a new attempt after checks for #4284 got into a weird state.

Generate subcommand alias

---

src/builder/arg.rs
src/builder/command.rs
src/builder/debug_asserts.rs
src/output/help_template.rs
src/output/usage.rs
src/parser/arg_matcher.rs
src/parser/parser.rs
src/parser/validator.rs

This originally stemmed from wrapping `Arg` in a `Box`, but we had to smash it with a hammer as it didn't improve things enough.
- This dropped binary size by 3-7 KiB
- Parsing slowed by 20%.
- Incremental rebuilds slowed down by 1%

refactor: Use getters internally

---

examples/README.md

> fix : Tutorials (derive, builder > Tutorials (derive, builder)
Fixes #4297

doc(fix typo): no close bracket in example

---

clap_derive/src/attr.rs
clap_derive/src/derives/args.rs
clap_derive/src/item.rs
src/_derive/mod.rs
tests/derive/groups.rs

This was prioritized to allow users to workaround problems when the
implicit `ArgGroup` is getting in the way.
Fixes #4279

feat(derive): Allow skipping the implicit ArgGroup 

---

clap_derive/src/derives/args.rs
tests/derive/groups.rs
tests/derive/utils.rs

This implements the basics for #3165, just missing
- `flatten` support (waiting on improved group support)
- `group` attributes

feat(derive): Implicitly populate groups from some structs

---

clap_derive/src/derives/args.rs
tests/derive/groups.rs

This will be needed when we support flattening for #3165

feat(derive): Report the group id

---

examples/git-derive.md
examples/git-derive.rs
examples/git.md
examples/git.rs

docs(cookbook): Provide example of --color[=WHEN]

---

src/parser/parser.rs

These didn't make sense for the builder but are helpful for the derive. The assert was assuming people wouldn't do this and to catch internal problems.
Fixes #4326

fix(parser): Allow defaults for Help/Version

---

Cargo.toml

This was a bug that this wasn't done before and improves the `cargo add` behavior.

fix: Hide clap_derive

---

src/builder/arg_group.rs

> ☝🏼 I open it as a draft to see if my approach to doc and test is good.
Ref: #4228

feat: expose `is_multiple` & `get_args` API for `ArgGroup`

---

clap_derive/src/item.rs
tests/derive/doc_comments_help.rs

This was broken in 8a5a9ba931dd45a4976a5600eb24a91b202472f3.  I had
missed this case for parsing doc comments.

fix(derive): Apply doc comments for `#[command(subcommand)]`

---

examples/tutorial_builder/04_01_enum.md
examples/tutorial_builder/04_01_enum.rs
examples/tutorial_derive/04_01_enum.md
examples/tutorial_derive/04_01_enum.rs
tests/derive/doc_comments_help.rs

`PossibleValue` does not have a long help text and the "body" part of the doc comment on a `ValueEnum` is ignored.
Improve a test case and the example to clarify this behavior.

Clarify that the "body" part of the doc comment on a `ValueEnum` is ignored

---

src/_derive/mod.rs

Documenting the `skip` attribute for the `ValueEnum` derive macro promptly, as it's not mentioned anywhere else.
Fixes #4327

docs: Describe the skip attribute for ValueEnums

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/subcommand.rs
clap_derive/src/item.rs
tests/derive/flatten.rs

feat(derive): Support `Option` when flattening

---

examples/typed-derive.md
examples/typed-derive.rs

This used to be more magical in clap 3 and people are having a hard time discovering how to get this in clap 4, so let's add examples:
- discrete numbers
- foreign enums
Fixes #4351

docs(cookbook): PossibleValues with custom types

---

src/output/textwrap/core.rs

counting ascii control sequences leads to unpredictable line breaks on colorized inputs (e.g. syntax highlighted strings)
https://github.com/clap-rs/clap/issues/4360

fix(clap): line wrap on strings that contain ascii control characters

---

src/builder/value_parser.rs
src/error/mod.rs

feat(error): Allow reproducing clap's errors

---

src/error/context.rs
src/error/format.rs
src/error/mod.rs

While `ContextKind` is useful for general information, it can't handle more nuanced suggestions, so we are falling back to a more general approach to suggestions.
This is a follow up to #4380 to make it API neutral.
Technically, there is a slight compatibility change here that only affects people who are doing custom formatted errors or manually generating errors.

refactor(error): Generalize how we report suggestions

---

src/error/format.rs
tests/builder/empty_values.rs
tests/builder/opts.rs

fix(error): Be consistent in puncutation

---

examples/tutorial_builder/03_03_positional_mult.md
examples/tutorial_builder/03_03_positional_mult.rs
examples/tutorial_derive/03_03_positional_mult.md

Right now the builder [tutorial example](https://docs.rs/clap/latest/clap/_tutorial/index.html#positionals) for positional append shows basically the same example as for the default 'Set' action.
Having an example where there are multiple arguments along with extracting logic provides a better explanation on how to use this API.

docs: Provide a better example for positional arg append

---

src/parser/validator.rs
tests/builder/conflicts.rs

This is most obvious with the derive API as it creates `ArgGroup`s all over the place now.
Fixes #4396

fix(parser): Don't make Args `exclusive` with their ArgGroup

---

clap_derive/src/derives/subcommand.rs
tests/derive/subcommands.rs

fix(derive): Allow skipping enum variants with a value

---

Cargo.lock
Cargo.toml

Version 0.15.1 was yanked because it should have been 0.16.
Fixes #4418.

fix: Require textwrap 0.16 (clap V3)

---

clap_mangen/src/render.rs
clap_mangen/tests/snapshots/aliases.bash.roff
clap_mangen/tests/snapshots/basic.bash.roff
clap_mangen/tests/snapshots/feature_sample.bash.roff
clap_mangen/tests/snapshots/quoting.bash.roff
clap_mangen/tests/snapshots/special_commands.bash.roff
clap_mangen/tests/snapshots/sub_subcommands.bash.roff

Fixes #4410.
The help generator for the main clap package uses the `Arg::is_takes_value_set()` method to determine whether it should show a default argument. (See `Arg::stylize_arg_suffix`, on line 4148 of `arg.rs`.) 
I ported the same logic over to clap_mangen, so boolean flag arguments no longer show `[default=false]` (or `[default=0]` for repeatable options), which is not valid.
I also noticed that the generated synopsis does not add a `...` ellipsis for repeatable flags, so I added that as well.
Finally, I updated the snapshot tests to reflect the above changes.
For the following program (this is essentially `clap_mangen/examples/man.rs`):
```rs
fn main() -> Result<(), std::io::Error> {
let cmd = Command::new("myapp")
.version("1.0")
.author("Kevin K. <kbknapp@gmail.com>:Ola Nordmann …
```

fix(man): Don't show default values for flags, show ellipsis for repeatable arguments

---

src/util/color.rs

Implement ValueEnum for ColorChoice

---

clap_derive/src/derives/args.rs
tests/derive/flags.rs

Inspired by #4458
This is a compatible change because it turns a compiler error into a working case.

fix(derive): Allow defaulted value parser for '()' fields

---

clap_complete/src/shells/shell.rs

Add support for determining current shell from environment

---

src/output/help_template.rs
tests/builder/help.rs

In clap v4, we changed the padding from 4 to 2 but we didn't update our
calculation for when to switch to next-line-help as it was a magic
number (we tried to catch all of these).
When updating the tests, we also missed that a test was being wrapped
too narrowly
This was found while discussing #3300

fix(help): Update auto-next-line to use new padding

---

src/builder/command.rs
tests/builder/help.rs

Making this plural can go either way as
- Clarify it is plural
- This is all really to simulate actually doing subcommands and you only do one at a time
For now, I lean towards clarifying it is plural
I also tweaked the message to be more consistent with how `--help` and `-h` describe themselves.
Fixes #4342

fix(help): Clarify that 'help' command accepts multiple

---

tests/builder/multiple_values.rs

Wondered if we had this for #4467.  Figured we should actually test it.

test(assert): Verify empty positional assert exists

---

src/lib.rs
src/parser/features/suggestions.rs
src/parser/parser.rs
tests/builder/utf8.rs

fix(parser): Don't panic on invalid UTF-8 values 

---

src/builder/arg.rs

For num_args, we'll just use the default
Fixes #4479

fix: Don't panic on non-built arg rendering

---

src/error/context.rs
src/error/format.rs
src/error/mod.rs
src/parser/validator.rs
tests/builder/app_settings.rs

Similar to
- Listing all required arguments when one is missing
- Listing all possible values when no value is provided
This came up when discussing #3572

feat(parser): Show available subcommands when one is missing

---

clap_complete/src/generator/mod.rs

This points to "the example above", but there's no example above when this gets rendered in docs.rs:
https://docs.rs/clap_complete/latest/clap_complete/generator/fn.generate.html
I suppose this reference is just stale since moving docs from a single markdown file or something similar.

Update reference to example in docs

---

Cargo.lock
Cargo.toml
src/output/fmt.rs

Not sure whether this would be something you'd want to have, but I'm a bit
unhappy with how widespread the atty crate is being used, because it both has a
[soundness issue on Windows](https://github.com/softprops/atty/issues/50) and
even though a well reviewed fix for that issue is available it hasn't been
merged, making it look like atty is unmaintained.
Luckily, someone has created a new crate which is re-using a lot of the code
from atty, but with the soundness issue fixed, which has a nice API as you can
tell here. My suggestion would be to switch to this instead.

chore: replace atty with is-terminal

---

src/builder/possible_value.rs
src/builder/value_parser.rs
src/lib.rs
src/util/color.rs

feat: Improve ValueParser experience

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml

Fixes #4510 
Note: `terminal_size` is using old version of rustix and this causes a bit dependency duplication.
Will check to bump upstream. EDIT: Someone already did - https://github.com/eminence/terminal-size/pull/46 (needs a release)

fix: wasm32 targets with is-terminal

---

src/_tutorial.rs

This extra backtick causes typo.

docs: Fix a typo

---

src/builder/resettable.rs
src/builder/styled_str.rs

docs: Clarify role of Resettable

---

src/parser/parser.rs
tests/builder/app_settings.rs
tests/builder/conflicts.rs

The new error message still isn't great but its better than the old one.
Reported at https://hachyderm.io/@eminence/109548978776785113

fix(parser): Be less confusing with args/subcommand conflicts

---

clap_bench/benches/04_new_help.rs
clap_bench/benches/05_ripgrep.rs
src/builder/command.rs
src/builder/debug_asserts.rs
src/output/help_template.rs
tests/builder/help.rs
tests/builder/template_help.rs

removed {bin} variable from help_template

---

clap_mangen/src/lib.rs
clap_mangen/src/render.rs
examples/repl.rs
src/builder/command.rs
src/parser/arg_matcher.rs
src/parser/validator.rs
src/util/mod.rs

We already need to lookup every present-arg for conflicts, so we might
as well cache it ahead of time.  This let's us move some operations to
be immutable so we can more easily cache other lookups.
For me, this gave a 70% speed improvement for #4516 with mixed results
on normal benchmarks

perf(parser): Reduce lookups for conflicts 

---

clap_derive/src/attr.rs

I assume "litersl" should be "literals"?

Fix typo in clap-derive error message

---

src/macros.rs

This PR will add a note to the description on `crate_name!` macro about where the name in the output come from.
There are 3 name-related environment variables in cargo, `CARGO_PKG_NAME`, `CARGO_CRATE_NAME`, and `CARGO_BIN_NAME`, and the `crate_name!` macro uses the 1st one among them.  This means that `foo` is used as the name in the case of Cargo.toml as shown below:
```toml
[package]
name = "foo"
[[bin]]
name = "bar"
```
Since the `crate_*` macros are under consideration for deprecation in #2840, and changing the source to another environment variable would result in the behavior change, I think it would be best to add a note to the documentation.
If you have suggestions, I would appreciate it.
Thank you very much.

docs: Present other environment variable alternatives to `crate_name!`

---

examples/derive_ref/interop_tests.md
src/error/format.rs
src/error/mod.rs
tests/builder/empty_values.rs
tests/builder/error.rs
tests/builder/flags.rs
tests/builder/opts.rs
tests/builder/possible_values.rs
tests/builder/subcommands.rs

From
https://rustc-dev-guide.rust-lang.org/diagnostics.html#suggestion-style-guide
> Suggestions should not be a question. In particular, language like
> "did you mean" should be avoided. Sometimes, it's unclear why a
> particular suggestion is being made. In these cases, it's better to be
> upfront about what the suggestion is.
>
> The message may contain further instruction such as "to do xyz, use"
> or "to do xyz, use abc".
Inspired by #2766

fix(error): Be consistent with rustc diagnostic guidelines

---

Cargo.lock
Cargo.toml
examples/derive_ref/interop_tests.md
examples/escaped-positional-derive.md
examples/escaped-positional.md
examples/tutorial_builder/03_01_flag_bool.md
examples/tutorial_builder/04_01_enum.md
examples/tutorial_builder/04_01_possible.md
examples/tutorial_derive/03_01_flag_bool.md
examples/tutorial_derive/04_01_enum.md
examples/typed-derive.md
src/error/format.rs
src/error/kind.rs
tests/builder/conflicts.rs
tests/builder/default_missing_vals.rs
tests/builder/default_vals.rs
tests/builder/error.rs
tests/builder/flags.rs
tests/builder/help.rs
tests/builder/opts.rs
tests/builder/possible_values.rs
tests/builder/subcommands.rs
tests/ui/error_stderr.toml

In text communication you need to balance
- Scannability, putting the most important information upfront
- Brevity so people don't get lost in the message
- Softness to help ease people through a frustrating experience
I feel we weren't doing great on the first two points, so tried to
iterate on the messages to improve them.  I hope we aren't suffering too
much on the third point as a side effect.

fix(error): Try to polish/clarify messages 

---

.clippy.toml
.github/workflows/ci.yml
.github/workflows/rust-next.yml
Cargo.toml
Makefile
clap_bench/Cargo.toml
clap_complete/Cargo.toml
clap_complete_fig/Cargo.toml
clap_derive/Cargo.toml
clap_lex/Cargo.toml
clap_mangen/Cargo.toml
src/builder/range.rs
src/lib.rs
src/parser/arg_matcher.rs
src/util/flat_map.rs
tests/derive_ui.rs
tests/derive_ui/bool_value_enum.stderr
tests/derive_ui/enum_variant_not_args.stderr
tests/derive_ui/flatten_enum_in_struct.stderr
tests/derive_ui/flatten_struct_in_enum.stderr
tests/derive_ui/tuple_struct.stderr

This allows using workspace inheritance which reduces the number of places we need to update on changes.  Before, it was easy to remember to update the root manifest and forget the rest.

chore: Bump MSRV to 1.64.0

---

clap_derive/src/derives/args.rs
clap_derive/src/item.rs
clap_derive/src/utils/ty.rs
tests/derive/main.rs
tests/derive/occurrences.rs

Add support for deriving grouped options for Vec<Vec<T>>

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/bash.rs
clap_complete/tests/common.rs
clap_complete/tests/elvish.rs
clap_complete/tests/fish.rs
clap_complete/tests/powershell.rs
clap_complete/tests/snapshots/value_terminator.bash
clap_complete/tests/snapshots/value_terminator.elvish
clap_complete/tests/snapshots/value_terminator.fish
clap_complete/tests/snapshots/value_terminator.ps1
clap_complete/tests/snapshots/value_terminator.zsh
clap_complete/tests/zsh.rs
src/builder/arg.rs

fix(completion): emit value terminators on zsh

---

src/parser/matches/arg_matches.rs

While reading API documents, I found these typos.

fix(doc): Fix typos in document of `ArgMatches` methods

---

clap_mangen/README.md

As suggested by clippy when using the example code.

Prefer ok_or to ok_or_else in README example

---

examples/derive_ref/interop_tests.md
examples/escaped-positional-derive.md
examples/escaped-positional.md
src/error/format.rs
src/error/kind.rs
tests/builder/conflicts.rs
tests/builder/error.rs
tests/builder/flags.rs
tests/builder/opts.rs
tests/builder/subcommands.rs
tests/ui/error_stderr.toml

Adding "found" might seem minor but I feel it has a slight softening on the message.  It also maintains scanability as it is at the end and short.
As this is a one-off message change and not a styling issue to be consistent with, I think this is safe to put in a patch release.

fix(error): Try to soften unexpected argument/value errors

---

src/builder/command.rs

Fixes a small typo in the `help_template` `tab` tag.

docs: Typo in tab tag

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/aliases.bash
clap_complete/tests/snapshots/basic.bash
clap_complete/tests/snapshots/feature_sample.bash
clap_complete/tests/snapshots/quoting.bash
clap_complete/tests/snapshots/special_commands.bash
clap_complete/tests/snapshots/sub_subcommands.bash
clap_complete/tests/snapshots/value_hint.bash
clap_complete/tests/snapshots/value_terminator.bash

Fix for the generation bash completion script, the `cmd` variable should be local, `cmds` was probably a typo.

fix: Make cmd variable (bash completion) local

---

src/parser/features/suggestions.rs

Implementation of Jaro-Winkler similarity in the dguo/strsim-rs crate
is wrong, causing strings with common prefix >=10
to all be considered perfect matches
Using Jaro instead from the same crate fixes this issue
Benefit of favoring long prefixes exists for matching common names
But not for typo detection
Hence use of Jaro instead of Jaro-Winkler is acceptable
Confidence threshold adjusted so that `bar` is still suggested for `baz`
since Jaro is strictly < Jaro-Winkler
such an adjustment is expected. This is acceptable.
While exact suggestions may change, the net change will be positive
Suggestions are purely decorative and should thus not breaking change
Fixes #4660
Also see https://github.com/dguo/strsim-rs/issues/53

fix(suggestions): Replace wrong Jaro-Winkler

---

src/error/format.rs
tests/builder/subcommands.rs

I looked at the code and this seemed the best place to fix the behavior
Fixes #4666

fix: Add plural s to context in suggestions

---

src/error/mod.rs

fix(help): Respect `disable_colored_help` for `arg_required_else_help`

---

src/macros.rs

To "append" calls, we were passing in a more and more complex expression on each recursive invocation.  We now pass in a fixed amount of data on each iteration, reducing how much the macro machinery needs to parse, speeding up builds.
Fresh builds went from 39s to 32s on my machine.
Inspired by #4670

perf: Speed up compiling `arg!` macro

---

src/builder/str.rs

Since `Inner::into_string` already takes ownership of `self` we can avoid unnecessary copy and allocation by moving `Box<str>` and using its implementation of `Into<String>`.

Improve builder::str::inner::Inner::into_string implementation

---

src/builder/command.rs
tests/builder/hidden_args.rs

We were accidentally showing long help just because a hidden argument had a description for a possible value.  This is most likely to be hit with the derive API as the value descriptions are automatically applied from documentation.

fix(help): Don't accidentally show long help with `--help` when it isn't intended.

---

clap_complete/examples/completion-derive.rs
examples/derive_ref/hand_subcommand.rs
tests/derive/groups.rs

Noticed via [reddit](https://www.reddit.com/r/rust/comments/115wovh/clap_documentation/)

docs: Remove remaining references to clap attribute

---

clap_mangen/src/render.rs
clap_mangen/tests/common.rs
clap_mangen/tests/roff.rs
clap_mangen/tests/snapshots/value_name_without_arg.bash.roff

derive arguments like this:
#[arg(long)]
pub flag: bool,
were producing option descriptions like this:
--flag=FLAG
`FLAG` is spurious.  It turns out that derive always sets a value name, for simplicity, even when there are no arguments.  Check for this case.
Fixes #4443.

fix(mangen): Avoid spurious value names for derive args without values

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/bash.rs
clap_complete/tests/common.rs
clap_complete/tests/elvish.rs
clap_complete/tests/fish.rs
clap_complete/tests/powershell.rs
clap_complete/tests/snapshots/two_multi_valued_arguments.bash
clap_complete/tests/snapshots/two_multi_valued_arguments.elvish
clap_complete/tests/snapshots/two_multi_valued_arguments.fish
clap_complete/tests/snapshots/two_multi_valued_arguments.ps1
clap_complete/tests/snapshots/two_multi_valued_arguments.zsh
clap_complete/tests/zsh.rs

Properly handle two consecutive multi-valued arguments.
Currently the zsh completion generates an error:
$ my-app <TAB>
_arguments:comparguments:325: doubled rest argument definition:
*::second -- second set of of multi-length arguments:
Special-case multi-valued arguments to avoid emitting duplicate catch-all arguments.
Closes #3022
Signed-off-by: David Aguilar <davvid@gmail.com>

clap_complete: fix support for two multi-length arguments in zsh

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/into_app.rs
clap_derive/src/derives/subcommand.rs
clap_derive/src/derives/value_enum.rs

fix(derive): Allow `clippy::almost_swapped`

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/into_app.rs
clap_derive/src/derives/subcommand.rs
clap_derive/src/derives/value_enum.rs

fix https://github.com/clap-rs/clap/issues/4733
Removes `#[deny(clippy::correctness)]` from generated code, added in https://github.com/clap-rs/clap/pull/1726
Macros really shouldn't be making lints stricter, just causes more noise in user code when they're triggered. Macro code naturally will have lint false positives

fix: remove strict linting from generated code

---

.github/workflows/ci.yml
CITATION.cff
Cargo.toml

This PR introduces a CITATION.cff (#4750 ), valid according to CFF v1.2.0.

[Documentation] Create CITATION.cff

---

src/parser/matches/arg_matches.rs

fix(parser): Clarify get_count/get_flag assertion

---

Cargo.lock
Cargo.toml
src/builder/app_settings.rs
src/builder/arg_settings.rs

This reverts commit 6878a1911b2509b1fb2afbaee616f6257758af41.
This was updated in #4771 but rustix is still on the old version, making us depend on
two versions of bitflags.  Once rustix is updated, we can update.

Revert "chore: Update bitflags dep to 2.0"

---

clap_complete/examples/completion-derive.rs
clap_complete/examples/completion.rs

Fixed wrong file names for comments in `clap_complete/examples/completion-derive.rs` and `clap_complete/examples/completion.rs`.

docs(clap_complete): clap_complete example documentation updated with corresponding file names

---

CONTRIBUTING.md
clap_complete/examples/completion-derive.rs
clap_complete/examples/completion.rs
clap_complete/src/generator/mod.rs
src/builder/action.rs
src/builder/arg.rs
src/builder/command.rs
src/builder/value_parser.rs
src/derive.rs
src/error/kind.rs
src/error/mod.rs
src/lib.rs
src/output/help_template.rs
src/parser/matches/arg_matches.rs
src/util/color.rs

doc: Clean up cfgs

---

Cargo.lock
clap_builder/src/builder/debug_asserts.rs
clap_builder/src/parser/parser.rs
clap_complete/Cargo.toml
clap_complete/src/dynamic.rs
clap_lex/Cargo.toml
clap_lex/src/ext.rs
clap_lex/src/lib.rs
clap_lex/tests/parsed.rs
clap_lex/tests/shorts.rs

We are doing direct transmutes between `OsStr` and `[u8]`. https://github.com/rust-lang/rust/pull/95290 would make this natively supported but I got tired of waitin for it.
This only saves about 1/4s off of `cargo build`.
This took 2.9 KiB off of `cargo bloat --release --example git` on Linux

perf!(lex): Build faster by removing `os_str_bytes`

---

clap_builder/src/parser/parser.rs
clap_complete/src/dynamic.rs
clap_lex/src/lib.rs
clap_lex/tests/parsed.rs

fix(lex): Allow reporting errors for non-UTF8 longs

---

clap_builder/src/error/format.rs
examples/derive_ref/interop_tests.md
tests/builder/error.rs
tests/builder/flags.rs
tests/builder/opts.rs
tests/builder/possible_values.rs
tests/builder/subcommands.rs

This also has the advantage of aligning with `error:`
This is a small part of #4638

fix(error): Change from neutral 'note' to helpful 'tip'

---

clap_builder/src/error/format.rs
tests/builder/opts.rs
tests/builder/possible_values.rs
tests/builder/subcommands.rs

One challenge with this is finding something that generally works. Making this work perfectly for one setting will make it inconsistent with other settings and take up more binary size / compile time.
So in the end, I felt like just mirroring rustc (with a bit more brevity) seemed like a decent experiment.  This will be evaluated by the feedback on release.
This is a small part of #4638

fix(error): Give more idea why we are suggesting an arg

---

Cargo.toml
clap_builder/Cargo.toml
clap_builder/src/parser/matches/arg_matches.rs

fix!: Remove stablized `unstable-grouped` feature

---

clap_lex/src/ext.rs

This is a followup to comments on #4802

fix(lex): Clarify unsafe safety

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/snapshots/quoting.zsh

Closes #4751.
The original problem is because of unescaped colons, which is included in this PR. However, there are other characters that might cause similar issues, such as backticks and dollar signs. I don't think one would expect something like `$PATH` to be expanded when he or she puts it in a helper string.
Added a few test cases for unit testing. I think we should add integration tests for this, i.e., help strings from comments, but I'm not sure how to do it.

fix(complete): Escape special characters properly for zsh

---

clap_builder/src/builder/command.rs

I was recently migrating from clap 3 to 4, and one of the things pointed out as a big change [here](https://epage.github.io/blog/2022/09/clap4/#removing-implicit-version-help-behavior) was that `mut_args` no longer works for pre-defined `help` and `version` flags.
However, in docs.rs, [for `mut_arg`, it still states](https://docs.rs/clap/latest/clap/struct.Command.html#method.mut_arg):
> This can be useful for modifying the auto-generated help or version arguments.
Which might be confusing, since if you try that, you'll get something like:
```bash
thread 'main' panicked at 'Argument `help` is undefined'
```
This just removes that line since IMO it'll just lead to confusion with the newer behaviour.

docs: Update mut_arg docs on help + version flags 

---

clap_builder/src/builder/arg.rs

The tests `positional_display_val_names_required` and `positional_display_val_names_req` are equivalent.
`positional_display_val_names_required` was added in Aug 2022 in https://github.com/clap-rs/clap/commit/02db3043e2bfc6658ad7a4a4d69dadd73e813dfd#diff-f1b965dbd6b694e7419437ace420b4fac5e8e0366848860ce5e63523fd7b835fR4430-L4438.
Keep `positional_display_val_names_required` and remove `positional_display_val_names_req`.

test(help): Remove redundant test

---

clap_builder/src/util/any_value.rs

Allow equality comparison for AnyValueId and TypeId.
**Background**:
I am trying to write a schema command for my CLI. I am using the type_id method on the ValueParser to get the data type for an argument but cannot actually compare it to anything without this implementation.

impl Eq<std::any::TypeId> for clap_builder::util::AnyValueId

---

clap_builder/src/parser/matches/arg_matches.rs

Maybe it was just me, but I didn't realize that the length had to be updated as we went but it can cause panics with a bad message.
Fixes #4870

fix(parser): Update iterator sizes as we go

---

clap_builder/src/error/format.rs

This is a minor noop code cleanup
* writing possible values and subcommands used nearly identical code
* writing elements used duplicate code once for items and once for last item
This actually resulted in an interesting discussion in [stackoverflow](https://stackoverflow.com/questions/76157860/optimal-code-pattern-to-process-a-lists-separator-in-rust/76158844) and a resulting https://github.com/rust-itertools/itertools/issues/697 request.

refactor: Minor code dedup for writing possible vals

---

clap_builder/src/error/format.rs
clap_builder/src/parser/matches/arg_matches.rs
clap_complete/src/shells/powershell.rs
clap_complete/src/shells/zsh.rs
clap_derive/src/item.rs
tests/builder/double_require.rs
tests/builder/help.rs
tests/builder/ignore_errors.rs
tests/builder/opts.rs
tests/builder/positionals.rs
tests/builder/tests.rs

This command cleaned up all the format args, making code significantly shorter and more readable.
```
cargo clippy --workspace --fix -- -A clippy::all -W clippy::uninlined_format_args
```

chore: Inline format args using clippy fix

---

clap_complete/src/generator/mod.rs

Tiny nit to make IDE happy - keep trait impl ordering same as in trait itself.

chore: Order trait impl same as trait

---

clap_builder/src/builder/possible_value.rs
clap_builder/src/output/help_template.rs
tests/builder/help.rs

My hope is to eventually generalize how we print help, reducing a lot of our pre-calculation.

refactor(help): Clean up long possible value handling

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/value_hint.bash

The bash completion currently generates `compgen -f` by default, or `compgen -W ...` for exhaustive values. This checks for `ValueHint::Other` so that file completion can at least be disabled where inappropriate

completion: Respect `ValueHint::Other` in Bash

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/bash.rs
clap_complete/tests/common.rs
clap_complete/tests/elvish.rs
clap_complete/tests/fish.rs
clap_complete/tests/powershell.rs
clap_complete/tests/snapshots/subcommand_last.bash
clap_complete/tests/snapshots/subcommand_last.elvish
clap_complete/tests/snapshots/subcommand_last.fish
clap_complete/tests/snapshots/subcommand_last.ps1
clap_complete/tests/snapshots/subcommand_last.zsh
clap_complete/tests/zsh.rs

Fixes #4898
I'm not entirely sure this is correct, but it fixes the linked case and doesn't regress any existing tests.

fix: (complete, zsh) Don't emit catchall when we have subcommands

---

clap_complete/src/generator/mod.rs

Resolves #4900 
This continues the example in `generate_to()'`s docs to demonstrate generating all possible shell completions at once

doc(complete): Add an example generating all shell completions

---

clap_builder/src/builder/command.rs

All the other `global_setting` setters have this note, I was confused about whether this one had to be manually applied until checking the source.

Add note about Command::disable_help_subcommand applying to children

---

clap_builder/src/builder/arg.rs

docs(builder): Remove stale docs references (set is default)

---

clap_builder/src/output/help_template.rs
tests/ui/help_cmd_stdout.toml
tests/ui/help_flag_stdout.toml

Subcommands don't switch their behavior on `--help`, so let's not switch to next-line-help based on `--help`.
Fixes #4897

fix(help): Don't use next-line-help on long-help for subcommands

---

clap_builder/src/builder/debug_asserts.rs
clap_builder/src/parser/parser.rs
tests/builder/multiple_values.rs

While this doesn't directly address #4919, this fixes problems around it
- One value terminated positional was allowed, but a second would hit asserts relate to `last`
- The parser didn't correctly update the state when multiple were present (yet somehow it worked when followed by a single value)

fix(parser): Allow multiple value terminated positionals

---

tests/builder/multiple_values.rs

Looks like #4924 accidentally fixed #4919, so adding the tests to prove that and to avoid regressions.
Fixes #4919

test(parser): Verify value terminator precedence

---

clap_lex/src/ext.rs

fix(lex)!: Remove unsafe safe method

---

Cargo.lock
Cargo.toml
clap_complete_nushell/CHANGELOG.md
clap_complete_nushell/Cargo.toml
clap_complete_nushell/LICENSE-APACHE
clap_complete_nushell/LICENSE-MIT
clap_complete_nushell/README.md
clap_complete_nushell/examples/nushell_completion.rs
clap_complete_nushell/examples/sub_subcommands.rs
clap_complete_nushell/src/lib.rs
clap_complete_nushell/tests/common.rs
clap_complete_nushell/tests/completion.rs
clap_complete_nushell/tests/nushell.rs
clap_complete_nushell/tests/snapshots/aliases.nu
clap_complete_nushell/tests/snapshots/basic.nu
clap_complete_nushell/tests/snapshots/feature_sample.nu
clap_complete_nushell/tests/snapshots/quoting.nu
clap_complete_nushell/tests/snapshots/special_commands.nu
clap_complete_nushell/tests/snapshots/sub_subcommands.nu
clap_complete_nushell/tests/snapshots/value_hint.nu

feat(nu): 'nushell' completion support

---

clap_derive/src/derives/args.rs

Don't generate error string with `format!`, as there can be used `concat!`, reducing code size.
Example expanded code (from bindgen-cli) before:
```rust
no_layout_tests: __clap_arg_matches
.remove_one::<bool>("no_layout_tests")
.ok_or_else(|| clap::Error::raw(
clap::error::ErrorKind::MissingRequiredArgument,
{
let res = ::alloc::fmt::format(
format_args!(
"The following required argument was not provided: {0}",
"no_layout_tests"
),
);
res
},
))?,
```
after:
```rust
no_layout_tests: __clap_arg_matches
.remove_one::<bool>("no_layout_tests")
.ok_or_else(|| clap::Error::raw(
clap::error::ErrorKind::MissingRequiredArgument,
"The following required argument was not provided: no_layout_tests",
))?,
```
This shave off ~10kb for bindgen-cli.

perf(derive): reduce amount of generated code

---

clap_builder/src/builder/command.rs
tests/builder/propagate_globals.rs
tests/builder/subcommands.rs
tests/builder/version.rs

This is mostly targeted at reducing startup time for no-op commands
within *very* large applications, like deno (see clap-rs#4774).
This comes at the cost of 1.1 KiB of binary size

feat: Allow deferred initialization of subcommands

---

clap_builder/src/error/mod.rs

… and simplifies method `Error.exit` as a side effect.
<details>
<summary>
The motivation for this pull request was to allow simplification of the code below (click to expand) where marked with <code>XXX</code> with future releases of clap.
</summary>
```rust
// Copyright (c) 2023 Sebastian Pipping <sebastian@pipping.org>
// SPDX-License-Identifier: MIT
// ..snip..
// Matches the two internal constants from [clap_builder-4.3.1]/src/util/mod.rs  // XXX
const SUCCESS_CODE: i32 = 0;                                                     // XXX
const USAGE_CODE: i32 = 2;                                                       // XXX
fn main() {
exit(middle_main(args_os()));
}
fn middle_main<I, T>(argv: I) -> i32
where
// to match clap::Command.get_matches_from
I: IntoIterator<Item = T>,
T: …
```

Extract/add public method `Error.exit_code`

---

clap_builder/src/builder/arg.rs
clap_builder/src/builder/command.rs

I must have been moving too fast with 6e1e754 as it changed the wrong part of the text when really the whole thing needed an overhaul.
So this correctly fixed #4728

docs(builder): Describe current sort semantics

---

clap_builder/src/util/color.rs

This is done because of the decisions made in discussion for `colorchoice_clap` crate, see rust-cli/anstyle#102.
`ColorChoice::possible_values` is a convenience for builder users.
As for `ValueEnum::to_possible_value`, it was originally written this way to mimic ripgrep's `--help` output.  However, this forces short/long help distinction when there might not be otherwise.  Looking at other programs, like `git`, there doesn't seem to be a longer description of the values (an "always ansi" makes things more complicated).

Improve colorchoice enum

---

clap_derive/CONTRIBUTING.md
src/_derive/mod.rs

docs(derive): Ensure magic attributes are searchable

---

src/_derive/_tutorial.rs
src/_tutorial.rs

Some problems we've identified
- People are missing the `cargo add -F derive` on the main docs page and the footnote about using `derive`, so specifying `cargo add -F derive` in the tutorial should help draw attention to it
- People are confused by the inferred behavior from args, so prefer linking to the derive reference on the topic so people discover it sooner
- People are confused by magic vs raw attributes
- Call this out in the "next steps" from the tutorial
- Link out to the builder API more to help build the connection in people's minds
This is not a definitive fix but incremental improvement

docs(tutorial): Smooth over tutorial problems, a little

---

clap_builder/src/parser/parser.rs
tests/builder/opts.rs

See https://github.com/clap-rs/clap/issues/4815

fix: Broken long arg inference on conflicts

---

clap_builder/src/builder/value_parser.rs

Inspired by #4994
- Atomic types are not supported as they aren't `Clone`
- `NonZero` types aren't supported because I didn't want to deal with`NonZeroI` types

feat(derive): Better match serde in built-in type support

---

clap_derive/src/derives/subcommand.rs

Well, thats annoying how easy it is to get this wrong but tests can only help with regressions; it would be hard to prevent future failures.
Fixes #5007

fix(derive): Don't fail on variant field attributes

---

CHANGELOG.md
clap_builder/src/builder/command.rs
clap_builder/src/output/help_template.rs
tests/builder/help.rs

This is gated behind `unstable-v5` feature flag
Fixes #4295

fix(help): Defaulting max_term_width instead of max_term_width

---

clap_builder/src/output/help_template.rs
tests/builder/help.rs

We weren't taking the name into account when determining the wrap width.
Fixes #5022

fix(help): Wrap long possible values correctly

---

clap_builder/src/error/mod.rs
clap_builder/src/parser/parser.rs
tests/builder/error.rs
tests/builder/subcommands.rs

fix(parser): Don't suggest -- as often 

---

clap_builder/src/parser/parser.rs
tests/builder/multiple_values.rs

This is one of several bugs found when looking at #4960.

fix(parser): Value terminator has higher precedence than later multiple values

---

Cargo.lock
clap_complete/Cargo.toml
clap_complete/tests/testsuite/common.rs
clap_complete_nushell/Cargo.toml
clap_complete_nushell/examples/test.rs
clap_complete_nushell/tests/common.rs
clap_complete_nushell/tests/completion.rs
clap_complete_nushell/tests/snapshots/home/test/nu/.config/nushell/completions/test.nu

refactor(test): Move nushell tests to completest

---

clap_builder/src/builder/command.rs
clap_builder/src/mkeymap.rs

This implements the `mut_args` method proposed in https://github.com/clap-rs/clap/issues/5050 .
Convenient when you want to modify most or all arguments, without having
to call `mut_arg` for each one and name them all.
There may be a more efficient implementation that doesn't involve recreating
an entire `Vec`.
Fixes #3002

Add `Command::mut_args` to modify all arguments of a `Command`

---

clap_builder/src/builder/mod.rs

When searching for relevant discussions and issues I happened upon #4362, which suggests using `TypedValueParser::try_map`. Unfortunately, this is not suitable for `ValueParserFactory` implementations that automatically register a `TypedValueParser` for a given type, as the `TryMapValueParser` type returned from try_map is not public.
Partial fix for #5065

feat: Allow referencing `TypedValueParser` in`ValueParserFactory` associated type

---

clap_builder/src/builder/mod.rs
clap_builder/src/builder/value_parser.rs
clap_builder/src/error/mod.rs
clap_builder/src/parser/parser.rs
tests/builder/error.rs

feat(builder): Allow injecting known unknowns

---

clap_builder/src/builder/value_parser.rs
clap_builder/src/parser/parser.rs
tests/builder/error.rs

fix(builder): UnknownValueParser shouldn't error on flag absense

---

clap_builder/src/builder/styled_str.rs
clap_builder/src/output/help.rs
tests/builder/help.rs

fix(help): Ensure padding isn't stripped

---

.clippy.toml
.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Makefile
clap_builder/Cargo.toml
src/lib.rs
tests/derive_ui.rs

perf(builder): Speed up builds by dropping is-terminal

---

clap_complete_nushell/src/lib.rs
clap_complete_nushell/tests/snapshots/aliases.nu
clap_complete_nushell/tests/snapshots/basic.nu
clap_complete_nushell/tests/snapshots/feature_sample.nu
clap_complete_nushell/tests/snapshots/home/test/nu/.config/nushell/completions/test.nu
clap_complete_nushell/tests/snapshots/quoting.nu
clap_complete_nushell/tests/snapshots/special_commands.nu
clap_complete_nushell/tests/snapshots/sub_subcommands.nu
clap_complete_nushell/tests/snapshots/value_hint.nu

The generated scripts can be used as script, module and overlay.
* script `source completion_script.nu`
* module `use completion_script.nu *`
* overlay `overlay use completion_script.nu`
Closes #5117

feat(nu): Make the completion scripts more general 

---

examples/tutorial_builder/03_04_subcommands.md
examples/tutorial_derive/03_04_subcommands.md
src/_derive/_tutorial.rs

This was inspired by a [reddit discussion](https://www.reddit.com/r/rust/comments/16eeeep/clap_v4_extremely_confusing_api_docs/)

docs(tutorial): Try to clean up the text

---

src/_derive/_tutorial/chapter_0.rs
src/_derive/_tutorial/chapter_1.rs
src/_derive/_tutorial/chapter_2.rs
src/_derive/_tutorial/chapter_3.rs
src/_derive/_tutorial/chapter_4.rs
src/_derive/_tutorial/chapter_5.rs
src/_derive/_tutorial/mod.rs
src/_tutorial/chapter_0.rs
src/_tutorial/chapter_1.rs
src/_tutorial/chapter_2.rs
src/_tutorial/chapter_3.rs
src/_tutorial/chapter_4.rs
src/_tutorial/chapter_5.rs
src/_tutorial/mod.rs
src/lib.rs

Unsure how much to read into this but some refer to the tutorial a a big
wall of ... and maybe breaking it down will help?

docs(tutorial): Split into separate modules per section

---

Cargo.lock
clap_builder/Cargo.toml

For some reason, terminal_size bumped semver recently; they also bumped the rustix version to 0.38.
I'd like to reduce the number of copies of OS integration crates (rustix and nix) in my dependency chain.  By updating terminal_size to 0.3.x we allow builders to keep then number of dependencies to a minimum
(Now honestly, given terminal_size boils down to basically
*one function* I have no idea why they bumped semver, the
API appears to be the same because we continue to build
with both, as you'd expect)

chore: Update terminal_size to 0.3.0

---

clap_builder/src/parser/parser.rs
tests/builder/app_settings.rs

This fixes 3 behaviors with inferring subcommands
-  When name matches are for the same command, allow the match
- Don't panic when inferring long_flags because of a mix up between flag and name
-  When long flag matches are for the same command, allow the match
Testing of long flags was covered in #4971
Fixes #5021

fix: Resolve conflicting name inference if from aliases

---

clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

fix(complete): Include positionals in subcommands 

---

Cargo.lock
Cargo.toml
clap_builder/Cargo.toml

These dependencies are used elsewhere in clap, but not in these crates.
`cargo test` and `cargo check --examples` both still pass with these
dependencies removed.

Remove unused dev-dependencies

---

clap_builder/src/builder/command.rs
clap_builder/src/builder/debug_asserts.rs
clap_builder/src/builder/os_str.rs
clap_builder/src/builder/str.rs
clap_builder/src/util/any_value.rs
clap_complete/src/dynamic/completer.rs
clap_derive/src/derives/args.rs
clap_derive/src/derives/into_app.rs
clap_derive/src/derives/parser.rs
clap_derive/src/derives/subcommand.rs
clap_derive/src/derives/value_enum.rs
tests/builder/multiple_occurrences.rs
tests/derive/doc_comments_help.rs

style: Make clippy happy

---

clap_builder/src/parser/parser.rs
clap_lex/src/lib.rs
clap_lex/tests/parsed.rs
clap_lex/tests/shorts.rs

This commit is a tiny win in compiled code size of a final binary including `clap` which shaves off 19k of compiled code locally. Previously tokens were checked if they were a number by using `.parse::<f64>().is_ok()`, but parsing floats is relatively heavyweight in terms of code size. This replaces the check with a more naive "does this string have lots of ascii digits" check where the compiled size of this check should be much smaller.
I'll note that this is not a critical optimization at all and is one I'm mostly curious if it's of interest. There's other various edge cases that were previously classified as numbers which will no longer be classified as numbers such as `nan`, `inf`, `+1`, `1e10`, etc. That would mean that this is technically a breaking change, and if that's not …

Reduce code size of testing tokens if they're a number

---

clap_builder/src/builder/styled_str.rs
clap_builder/src/output/usage.rs

refactor(help): Clean up the usage code

---

clap_builder/src/builder/command.rs
clap_builder/src/output/usage.rs
clap_builder/src/parser/parser.rs
clap_builder/src/parser/validator.rs

refavtor: Prepare for help flattening

---

clap_builder/src/builder/app_settings.rs
clap_builder/src/builder/command.rs
clap_builder/src/output/help_template.rs
clap_builder/src/output/usage.rs
examples/git-derive.md
examples/git-derive.rs
examples/git.md
examples/git.rs
tests/builder/help.rs

feat(help): Opt-in to flatten subcommands into parent command help

---

clap_builder/src/output/help_template.rs
clap_builder/src/output/usage.rs
tests/builder/help.rs

fix(help): Hide subcommands in flattened usage

---

src/_derive/mod.rs

docs(derive): Link to tutorial sections for attributes

---

Cargo.toml
src/lib.rs

docs: Link out to the changelog at the relevant tag

---

clap_builder/src/output/help_template.rs
clap_mangen/src/render.rs
tests/builder/possible_values.rs

In some sophisticated situations, these may be expensive to calculate. One example might be a '--branch' option accepting any single Git branch that exists on the remote -- in such a case, the remote would need to be queried for all possible_values. The cost is ultimately unavoidable at runtime since this validation has to happen eventually, but there's no need to pay it when generating help text if `is_hide_possible_values_set`.
To keep '-h' fast, avoid collecting `possible_values` during '-h' unless we're actually going to use the values in display.
This optimization is repeated for the manpage renderer.
This is trivially based on the short-circuiting logic at `clap_builder/src/builder/command.rs:long_help_exists_`, which at least supports the idea that actually consuming the iterator …

perf: avoid retrieving possible_values unless they're used

---

clap_lex/src/ext.rs
clap_lex/src/lib.rs

They weren't referring to the right thing.

Correct safety docs

---

clap_builder/src/builder/arg.rs
clap_builder/src/builder/debug_asserts.rs
clap_mangen/src/render.rs
examples/find.md
examples/find.rs

In writing up a reply to #5287, I tested our `find` example and realized it had the bug they were trying to workaround.  This PR adds support for options to act like flags.  We were already half-way there with `num_args(0..=1)`.  Not the most elegant solution for the user (elegant architecturally in clap) but it at least unblocks users.

fix: Allow position-sensitive flags

---

clap_builder/src/error/format.rs
clap_builder/src/error/mod.rs
clap_builder/src/parser/parser.rs
tests/builder/conflicts.rs

The error was bad and there were holes from adding subcommand flags
Fixes #5297

fix(parser): Improve `args_conflicts_with_subcommands` experience

---

clap_complete/src/dynamic/shells/mod.rs
clap_complete/tests/snapshots/home/static/exhaustive/elvish/elvish/rc.elv
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive

We shouldn't be injecting help when being flattened.
Unsure why this made tests fail inconsistentkly between CI and local

fix(complete): Don't provide help output for user

---

clap_builder/src/builder/command.rs
clap_builder/src/derive.rs

Clap's default exit code has changed over time, and although it's documented it's a bit hard to find. This adds hyperlinks to the docs to make it easier to discover.
This follows on from #1653, #1327, #3426

Link to exit code info

---

examples/cargo-example-derive.rs
examples/demo.rs
examples/escaped-positional-derive.rs
examples/pacman.rs
examples/tutorial_builder/02_apps.rs
examples/tutorial_derive/01_quick.rs
examples/tutorial_derive/02_app_settings.rs
examples/tutorial_derive/02_apps.rs
examples/tutorial_derive/02_crate.rs
examples/tutorial_derive/03_01_flag_bool.rs
examples/tutorial_derive/03_01_flag_count.rs
examples/tutorial_derive/03_02_option.rs
examples/tutorial_derive/03_02_option_mult.rs
examples/tutorial_derive/03_03_positional.rs
examples/tutorial_derive/03_03_positional_mult.rs
examples/tutorial_derive/03_04_subcommands.rs
examples/tutorial_derive/03_04_subcommands_alt.rs
examples/tutorial_derive/03_05_default_values.rs
examples/tutorial_derive/04_01_enum.rs
examples/tutorial_derive/04_02_parse.rs
examples/tutorial_derive/04_02_validate.rs
examples/tutorial_derive/04_03_relations.rs
examples/tutorial_derive/04_04_custom.rs
examples/tutorial_derive/05_01_assert.rs
src/_derive/_tutorial/chapter_1.rs
src/_derive/mod.rs

We've been getting questions like #5316 which shows that the discoverability of how to see that field is less than ideal.  In fact, it only is talked about for the sake of version migration and for `Command::author`.  Most derive users won't see that.
Steps
- Point derive users to `help_template,` like `Command::author` does
- Don't have useless `author` attributes that raise the question (rather than document it in the tutorial)
`command!` doesn't mention `author`, so I left it alone.

docs: Adjust how we approach `author`

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/custom_bin_name.bash
clap_complete/tests/snapshots/custom_bin_name.elvish
clap_complete/tests/snapshots/custom_bin_name.fish
clap_complete/tests/snapshots/custom_bin_name.ps1
clap_complete/tests/snapshots/custom_bin_name.zsh
clap_complete/tests/testsuite/bash.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/powershell.rs
clap_complete/tests/testsuite/zsh.rs

fix(clap_complete): Use bin name instead of package name for bash completions in subcommands

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/value_hint.bash
clap_complete/tests/testsuite/bash.rs

This PR tries to improve bash completion support.
* Fix #5239
* Add support for `ValueHint::DirPath`
* Suppress a useless space appended during completion for `ValueHint::Other`

Improve bash completion with compopt

---

clap_mangen/src/lib.rs
clap_mangen/src/render.rs
clap_mangen/tests/snapshots/sub_subcommand_help.roff

Print the "full" command in the name,title, and synopsis of subcommand man pages. Currently if clap was to generate a man page for `git add` the title and name would be simply `add`, not `git-add` like expected, and the synopsis would be `add <args>` not  `git add <args>`
- This PR changes this to obtain the title and name the same way as the subcommand names list in a man page, which was fixed by #4255 
- ~~To obtain the proper usage string (ex: `git add` not `git-add`) I believe we want [`Command.usage_name`](https://github.com/clap-rs/clap/blob/cbc9c9dd44fc4be25c196213d508b9d2a9c282f3/clap_builder/src/builder/command.rs#L92), but it is private and the only way I could find to obtain it is via `Command.render_usage()` which unfortunately forces an unnecessary clone. This also causes …

Correct title,name and synopsis in generated man pages for subcommands

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/value_hint.bash
clap_complete/tests/testsuite/bash.rs

Fix #5313 (and continuation of #5240)
The root cause is field splitting by bash.
It is erroneously performed when processing `compgen` output.
The delimiters used for field splitting are defined in `IFS` environment variable, which is `$' \t\n'` (space, tab, newline) by default. If the output of `compgen` contains these characters, they are split out.
This patch (partially) fixes that by restricting `IFS` to newline.
Now we can handle filenames with spaces and/or tabs, but not newlines because we cannot distinguish "newline as a delimiter" from "newline contained in filename".
Handling newlines would be more difficult than handling spaces. It seems that other completion scripts cannot handle this.
I think this should be a separate issue if we really try to fix this.

fix(complete): Prevent filenames splitting in bash completion

---

clap_mangen/src/lib.rs

The API is inspired by clap_complete. Similar code is already used by other people like in #4231. Not everyone should write the same code again.
In order to correctly create the man pages of the subcommands #5301 is also needed.

feat(mangen): generate filename and files

---

.clippy.toml
.github/workflows/ci.yml
Cargo.toml
Makefile
src/lib.rs
tests/derive_ui.rs
tests/derive_ui/flatten_enum_in_struct.stderr
tests/derive_ui/flatten_struct_in_enum.stderr

chore: Update MSRV to 1.74

---

clap_lex/src/ext.rs

fix(lex): Use new-ish OsStr API

---

clap_builder/src/builder/os_str.rs

Found via rust-lang/cargo#10554

fix: Add missing clap::builder::OsStr impl

---

clap_builder/src/parser/parser.rs
tests/builder/error.rs

Inspired by rust-lang/cargo#12494.
Part of this is that our "did you mean" does prefix checks so it can be
overly aggressive in providing suggestions.
To avoid providing needless suggestions I limited this change to `last`
/ `trailing_var_arg` as those convey that `--` is more likely a valid
suggestion.

fix(error): Include -- in more cases 

---

clap_builder/src/builder/command.rs

(This is an obvious bug or documentation fix, so that's why I skip the issue creation process.)
Currently, the method [`Command::dont_delimit_trailing_values`](https://docs.rs/clap/latest/clap/struct.Command.html#method.dont_delimit_trailing_values) contains a link to `Command::trailing_var_arg`, but that link is dead, as the method is not documented ([anymore](https://github.com/clap-rs/clap/commit/bffce7f57a278d6e9026491c1d47933b987c61f2#diff-0ec4d4c3449555af0c6e9991c62e6d12d3b5d7a09e412f90b7b2b4e865007899R2003)).
Therefore, the documentation for this method should link to `Arg::trailing_var_arg` instead, which is exactly what this PR does.
Note that there are a few more questionable uses of `Command::trailing_var_arg`, which I didn't dare to touch:
```console
$ git grep -Firn …
```

docs(builder): Avoid creating link to now-undocumented method

---

clap_builder/src/macros.rs

This just quiets an annoying clippy warning :)

fix: use SCREAMING_SNAKE_CASE for static variable `authors`

---

Cargo.lock
clap_derive/Cargo.toml

I suspect automation would notify you of this eventually, but here you go.

chore: Update `heck` requirement

---

src/_derive/_tutorial/chapter_0.rs
src/_derive/_tutorial/chapter_1.rs
src/_derive/_tutorial/chapter_2.rs
src/_derive/_tutorial/chapter_3.rs
src/_derive/_tutorial/chapter_4.rs
src/_derive/_tutorial/chapter_5.rs

docs(derive): Fix ToC links within tutorial chapters

---

clap_derive/src/derives/args.rs
clap_derive/src/item.rs
tests/derive/non_literal_attributes.rs

fix(derive): Re-allow expressions for id's 

---

clap_complete/src/shells/bash.rs
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/value_hint.bash

fix(complete): Avoid use of -v in bash completion

---

examples/tutorial_builder/03_02_option_mult.md
examples/tutorial_builder/03_02_option_mult.rs
examples/tutorial_derive/03_02_option_mult.md

The examples `03_02_option_mult_derive` in https://docs.rs/clap/latest/clap/_derive/_tutorial/chapter_2/index.html#options did not include a case where the same option name is specified multiple times.
This PR adds such examples.

docs(examples): Add examples of same names multiple options.

---

clap_builder/src/builder/value_parser.rs

There seems to be an inconsistency between the docstring and the behavior of `BoolishValueParser::new()`. The docstring makes it seem as if a non-boolish value will default to `true`. This is not the case. Instead, an error occurs during parsing, which can be seen in the example code for `BoolishValueParser`.
Updating the docstring to align with current behavior.

Update doctring for BoolishValueParser::new

---

clap_builder/src/builder/command.rs

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cebf442ae95b10a4d07dacb24072c2e3) showing that .afer_long_help() isn't shown with -h.

Fix documentation for Command::after_long_help()

---

Cargo.lock
Cargo.toml
clap_complete/Cargo.toml
clap_complete/tests/testsuite/bash.rs
clap_complete/tests/testsuite/common.rs
clap_complete/tests/testsuite/dynamic.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/zsh.rs
clap_complete_fig/Cargo.toml
clap_complete_fig/tests/common.rs
clap_complete_nushell/Cargo.toml
clap_complete_nushell/tests/common.rs
clap_complete_nushell/tests/completion.rs
clap_mangen/Cargo.toml
clap_mangen/tests/testsuite/common.rs
tests/builder/error.rs
tests/builder/help.rs
tests/builder/multiple_values.rs
tests/builder/positionals.rs
tests/builder/subcommands.rs
tests/builder/tests.rs
tests/builder/utils.rs
tests/derive/help.rs
tests/derive/utils.rs

chore: Upgrade snapbox

---

clap_builder/src/parser/validator.rs
tests/builder/conflicts.rs

There are other cases for `required` that aren't being handled
- Groups
- Conflicts
I'm concerned there might be weird corner cases and didn't want the
analysis for that to block fixing this.
Fixes #5507

fix(parser): Allow exclusive to override required_* 

---

clap_complete/src/shells/zsh.rs
clap_complete/tests/snapshots/aliases.zsh
clap_complete/tests/snapshots/basic.zsh
clap_complete/tests/snapshots/custom_bin_name.zsh
clap_complete/tests/snapshots/feature_sample.zsh
clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive
clap_complete/tests/snapshots/quoting.zsh
clap_complete/tests/snapshots/special_commands.zsh
clap_complete/tests/snapshots/sub_subcommands.zsh
clap_complete/tests/snapshots/subcommand_last.zsh
clap_complete/tests/snapshots/two_multi_valued_arguments.zsh
clap_complete/tests/snapshots/value_hint.zsh
clap_complete/tests/snapshots/value_terminator.zsh

This PR resolves #5521 
The zsh _arguments completion function has the following syntax:
```
_arguments [ARGUMENTS_OPTIONS] [:] COMMAND_ARG...
```
Where the optional colon is used to disambiguate options consumed by the `_arguments` function itself.
If this colon is missing and the first `COMMAND_ARG` conflicts with one of the options supported by `_arguments`, then it is misinterpreted resulting in missing options or the "unknown match specification character" seen above.

fix(zsh): Separate options from _arguments options

---

clap_builder/src/error/format.rs
tests/builder/multiple_values.rs

fix(parser): Report correct num_args on too-few 

---

src/lib.rs

This fixes a trivial typo in the documentation.

docs: Fix typo (cio->clio)

---

clap_builder/src/error/mod.rs
clap_builder/src/util/mod.rs

I noticed the calls to flush standard out and err before calling `std::process:exit()` and I believe they aren't necessary.
Standard out is flushed when calling `std::process::exit()`:
- [std::process::exit()](https://github.com/rust-lang/rust/blob/3d5d7a24f76006b391d8a53d903ae64c1b4a52d2/library/std/src/process.rs#L2318)
- [std::rt::cleanup()](https://github.com/rust-lang/rust/blob/3d5d7a24f76006b391d8a53d903ae64c1b4a52d2/library/std/src/rt.rs#L105)
- [std::io::cleanup()](https://github.com/rust-lang/rust/blob/3d5d7a24f76006b391d8a53d903ae64c1b4a52d2/library/std/src/io/stdio.rs#L679)
And standard error is [unbuffered](https://github.com/rust-lang/rust/blob/3d5d7a24f76006b391d8a53d903ae64c1b4a52d2/library/std/src/io/stdio.rs#L919), and so doesn't need to be flushed.
I noticed this …

Exit without flushing stdout and stderr

---

clap_complete/src/shells/fish.rs
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/sub_subcommands.fish
clap_complete/tests/snapshots/value_hint.fish

It seems that fish [prefers \t over literal tab character][1].
[1]: https://github.com/fish-shell/fish-shell/blob/4d7ef1fad82986b8e5210979ab91fc424a645c87/share/completions/ls.fish#L61-L71

style: fish: escaping tab as \t for more readibility

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml
Cargo.lock
clap_complete/Cargo.toml
clap_complete/tests/snapshots/home/static/exhaustive/bash/.inputrc
clap_complete/tests/snapshots/home/static/exhaustive/zsh/.zshenv
clap_complete/tests/testsuite/common.rs
clap_complete/tests/testsuite/dynamic.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/zsh.rs
clap_complete_nushell/tests/common.rs

They was not run on CI, so they're siliencely falling for a long time.
Close #5540.

fix: Don't silently ignore complete tests when missing installed shells on CI

---

clap_builder/src/error/format.rs
clap_builder/src/error/mod.rs
tests/builder/help.rs

Discussion at https://github.com/clap-rs/clap/discussions/5573
The first commit adds test cases, the second updates the "try 'help'" hints to use user-defined help flags.

feat: Show user defined help flags in hints

---

clap_complete/src/shells/fish.rs
clap_complete/tests/snapshots/basic.fish
clap_complete/tests/snapshots/custom_bin_name.fish
clap_complete/tests/snapshots/feature_sample.fish
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/quoting.fish
clap_complete/tests/snapshots/special_commands.fish
clap_complete/tests/snapshots/sub_subcommands.fish
clap_complete/tests/snapshots/subcommand_last.fish

[As guided][1] by fish's maintainer, to handle nested subcommands, we try to generate 3 new functions for completion scripts:
* `__fish_{name}_global_optspecs` will gather global [option specifications][3],
* `__fish_{name}_needs_command`, with `rustup \t`,  used to check for `rustup`
* `__fish_{name}_using_subcommand show`, with `rustup show \t`,  check if current cmd is `show`
This pattern is popular within [fish-shell ](https://github.com/fish-shell/fish-shell)repository, for some commands:
* [npm](https://github.com/fish-shell/fish-shell/blob/e67ffc1a3b91df44e9aa1602852242a3c6cc9b1d/share/completions/npm.fish#L85-L86)
* [git](https://github.com/fish-shell/fish-shell/blob/e67ffc1a3b91df44e9aa1602852242a3c6cc9b1d/share/completions/git.fish#L2161-L2164)
* …

fish/complete: Generate helper functions to check for subcommands

---

clap_complete/src/dynamic/shells/mod.rs
clap_complete/src/dynamic/shells/shell.rs
clap_complete/src/dynamic/shells/zsh.rs
clap_complete/tests/snapshots/home/dynamic/exhaustive/zsh/.zshenv
clap_complete/tests/snapshots/home/dynamic/exhaustive/zsh/zsh/_exhaustive
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive
clap_complete/tests/testsuite/zsh.rs

Related issue https://github.com/clap-rs/clap/issues/3916
- Add zsh glue script code to support that we could call external native completion.
- Add the same level of tests as fish

feat(clap_complete): add native completion support for zsh

---

clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

related issue: https://github.com/clap-rs/clap/issues/3951#issuecomment-2182830925

feat(clap_complete): Add support for visible subcommand aliases

---

clap_complete/src/dynamic/shells/elvish.rs
clap_complete/src/dynamic/shells/mod.rs
clap_complete/src/dynamic/shells/shell.rs
clap_complete/tests/snapshots/home/dynamic/exhaustive/elvish/elvish/rc.elv
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive
clap_complete/tests/testsuite/elvish.rs

Related issue #3919
- Add elvish glue script code to support that we could call external native completion.
- Add the same level of tests as fish

feat(clap_complete): add native completion support for elvish

---

clap_complete/src/dynamic/shells/mod.rs

Related issue https://github.com/clap-rs/clap/issues/2488
In track issue https://github.com/clap-rs/clap/issues/3166
> Ideally, we have the registration script sourced on-demand in the docs so that it is "auto-updating" with the users tool

docs: Add document comments how to source dynamic completions

---

clap_builder/src/builder/arg.rs
clap_complete/src/dynamic/completer.rs
clap_complete/src/dynamic/shells/bash.rs
clap_complete/src/dynamic/shells/elvish.rs
clap_complete/src/dynamic/shells/fish.rs
clap_complete/src/dynamic/shells/zsh.rs
clap_complete/tests/testsuite/dynamic.rs

Based on PR: https://github.com/clap-rs/clap/pull/5549
Related issue: https://github.com/clap-rs/clap/issues/3951
-  refactor: Add `CompletionCandidate`  to replace `(OsString, Option<StyledStr>)`. There will be a new field named `visible` for  `CompletionCandidate`. If we don't need this struct, there will be a type `(OsString, Option<StyledStr>, bool)`.
-  Support hiding long flags and their long aliases. The specific behavior is reflected in the differences between the test commit and the feat commit.

feat(clap_complete): Support hiding long flags and their long aliases

---

clap_builder/src/builder/command.rs
clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/zsh.rs

Based on PR: https://github.com/clap-rs/clap/pull/5583
Related issue: https://github.com/clap-rs/clap/issues/3951
Support hiding subcommands and their aliases. The specific behavior is reflected in the differences between the test commit and the feat commit.

feat(clap_complete): Support hiding subcommands and their aliases

---

clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

Based on PR: https://github.com/clap-rs/clap/pull/5584
Related to https://github.com/clap-rs/clap/issues/3951
Support hiding possible values. The specific behavior is reflected in the differences between the test commit and the feat commit.

feat(clap_complete): Support hiding possible values

---

clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

related issue: https://github.com/clap-rs/clap/issues/3920
what is left
- support `-fbar` and `-f=bar`
- error parsing for `--flag=bar` in bash
- `foo --bar\t` offering both `--bar <value>` and `--bare`

feat(clap_complete): Support flags with values `--flag bar`and `-f bar` in native completions

---

clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

related issue: https://github.com/clap-rs/clap/issues/3920
This is a later PR based on https://github.com/clap-rs/clap/pull/5539
Error parsing for `--flag=bar` in `bash`
**more details:**
https://github.com/clap-rs/clap/blob/43e73682835653ac48f32cc786514553d697c693/clap_complete/src/dynamic/shells/mod.rs#L36-L48
The `comp_words` will be ['command', '--flag', '=', 'value'] rather than ['command', '--flag=value'] because of `COMP_WORDBREAKS`.

feat(clap_complete): Support `-fbar` and `-f=bar` in native completions

---

clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

**Related issue** https://github.com/clap-rs/clap/issues/3921
- Support multi-values for both short flag and long flag
What we can complete now?
```
dynamic --flag bar1 [TAB]
```
It will complete`bar1 bar2 bar3`.
Also,
```
dynamic -F bar1 [TAB]
```
will complete`bar1 bar2 bar3`.
- Support multi-values for positional argument with `num_args(N)` which N is fixed.
```
dynamic pos_a [TAB]
```
will complete `pos_a pos_b pos_c`
```
dynamic -- pos_a [TAB]
```
will complete `pos_a pos_b pos_c`
- Support multi-values for both short flag and long flag with format as follows
```
dynamic --flag=bar1 [TAB]
dynamic -F=bar1 [TAB]
```
- Support multi-values for positional argument with `last` or `trailing_var_arg`

Support multiple values in native completions

---

clap_derive/src/derives/args.rs
tests/derive/flatten.rs

- Improves the error message
- Happens on initialization, rather than parse, making it so it will
always show up and not just when certain parts of the CLI are
exercised
Fixes #5609

fix(derive): Improve flattening-skipped-group assert 

---

clap_builder/src/builder/command.rs
src/_features.rs

docs: Cross-link color control to Command::styles

---

Cargo.toml
clap_builder/Cargo.toml
clap_builder/src/builder/arg.rs
clap_builder/src/builder/ext.rs
clap_builder/src/builder/mod.rs
clap_builder/src/builder/value_hint.rs

This is behind `unstable-ext`
This is the first step towards #3476.
In the short term, this will allow
- Moving knowledge of `ValueHint` out of `clap` and into `clap_complete`
- Open the door for `clap_complete` to have user-provided completers (#1232)

feat(builder): Add Extension API

---

Cargo.lock
clap_builder/Cargo.toml
clap_builder/src/builder/command.rs
src/bin/stdio-fixture.rs

I was trying to set up colours for the derive macro, and copying this didn't immediately work, but using `.bold()` as per https://github.com/clap-rs/clap/issues/3234#issuecomment-2056568175 did work, so figured it would be worth updating the defaults so things are a bit easier for the next person.
---
6f215eee refactor(styles): make styles example use a const
This makes it easier to copy this example for use in the derive API,
like so:
```rust
const STYLES: Styles = Styles::styled()
.header(AnsiColor::Green.on_default().bold())
.usage(AnsiColor::Green.on_default().bold())
.literal(AnsiColor::Blue.on_default().bold())
.placeholder(AnsiColor::Cyan.on_default());
#[derive(Parser)]
#[clap(styles = STYLES)]
struct Cmd {
...
}
```
If you use the `|` method then it's not a constant function. …

refactor(styles): make styles example use a const

---

Cargo.toml
clap_complete/Cargo.toml
clap_complete/src/dynamic/completer.rs
clap_complete/tests/testsuite/dynamic.rs

Related issue https://github.com/clap-rs/clap/issues/1232
- Add `CustomCompleter` trait and `ArgValueCompleter` struct to provide users a way to add custom value of argument completion.
- Add test case to show the feat.
> Open question: does the completion function accept just the arg and current value or does it have access to `ArgMatches` for completing based on other data like in https://github.com/clap-rs/clap/issues/1910

Support dynamic value of argument completion

---

clap_builder/src/builder/value_hint.rs
clap_complete/examples/dynamic.rs
clap_complete/examples/exhaustive.rs
clap_complete/src/dynamic/mod.rs
clap_complete/src/dynamic/shells/mod.rs

doc(complete): More polish

---

clap_complete/src/dynamic/shells/mod.rs
clap_complete/src/dynamic/shells/powershell.rs
clap_complete/src/dynamic/shells/shell.rs
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/home/static/exhaustive/powershell/powershell/Microsoft.PowerShell_profile.ps1
clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive

feat(clap_complete): Add support for Powershell

---

clap_complete/src/dynamic/shells/mod.rs

We have issues open for other Windows shells, so this seems like a bad idea.

fix(complete)!: Dont assume powershell on Windows

---

clap_complete/Cargo.toml
clap_complete/examples/exhaustive.rs
clap_complete/src/dynamic/candidate.rs
clap_complete/src/dynamic/complete.rs
clap_complete/src/dynamic/mod.rs
clap_complete/src/dynamic/shells/command.rs
clap_complete/src/dynamic/shells/mod.rs
clap_complete/tests/testsuite/bash.rs
clap_complete/tests/testsuite/common.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/zsh.rs

fix(complete)!: Put CompleteCommand behind unstable-command 

---

clap_complete/src/dynamic/candidate.rs

Fix typo in dynamic completion doc comment

---

src/lib.rs

This allows rustc to give a nice note about activating feature when it has not been activated.
Before:
```
error[E0433]: failed to resolve: could not find `Parser` in `clap`
--> ssh/src/main.rs:1:16
|
1 | #[derive(clap::Parser, Debug)]
|                ^^^^^^ could not find `Parser` in `clap`
```
After:
```
error[E0433]: failed to resolve: could not find `Parser` in `clap`
--> ssh/src/main.rs:1:16
|
1  | #[derive(clap::Parser, Debug)]
|                ^^^^^^ could not find `Parser` in `clap`
|
note: found an item that was configured out
--> /home/nora/.cargo/git/checkouts/clap-cf0796c5889852a8/ec804fa/src/lib.rs:93:35
|
93 | pub use clap_derive::{self, Args, Parser, Subcommand, ValueEnum};
|                                   ^^^^^^
note: the item is gated behind the `derive` feature
--> …
```

feat: Explicitly list items to re-export from derive

---

clap_complete/src/dynamic/env/mod.rs

feat(complete): Make `Shells` more flexible

---

clap_complete/src/dynamic/command/mod.rs
clap_complete/src/dynamic/env/mod.rs

docs(complete): Specify the compatibility guarentees

---

clap_complete/src/dynamic/complete.rs
clap_complete/tests/testsuite/dynamic.rs

**Related issue** https://github.com/clap-rs/clap/issues/3922

Support delimited values in native completions

---

clap_complete/src/env/mod.rs

fix: Typos in documentation to `CompleteEnv`

---

Cargo.lock
clap_complete/Cargo.toml
clap_complete/src/command/mod.rs
clap_complete/src/engine/candidate.rs
clap_complete/src/engine/complete.rs
clap_complete/src/engine/custom.rs
clap_complete/src/engine/mod.rs
clap_complete/src/env/mod.rs
clap_complete/src/lib.rs
clap_complete/tests/testsuite/engine.rs

This allows us to migrate away from `ValueHint`, as shown by `PathCompleter`

feat(complete): Provide ArgValueCompleter

---

clap_complete/src/command/shells.rs
clap_complete/src/engine/candidate.rs
clap_complete/src/engine/complete.rs
clap_complete/src/env/shells.rs
clap_complete/tests/testsuite/engine.rs

fix(complete)!: Be consistent in value language

---

clap_builder/src/builder/arg.rs
clap_builder/src/builder/command.rs
clap_builder/src/error/format.rs
clap_builder/src/error/mod.rs
clap_builder/src/macros.rs
clap_builder/src/output/help_template.rs
clap_builder/src/output/usage.rs

Noticed this with `cargo override`.  Verified on `cargo override --help`

fix(help): Style arg groups

---

clap_complete/src/engine/complete.rs
clap_complete/tests/testsuite/engine.rs

Support `allow_hyphen_values` in native completions

---

clap_complete/src/env/shells.rs
clap_complete/tests/snapshots/home/dynamic-env/exhaustive/bash/.bashrc

No idea why using passing along `IFS` isn't workong on my machine (but is for tests).
Fixes #5730

fix(complete): Adjust how IFS is passed to clap

---

clap_complete/examples/exhaustive.rs
clap_complete/src/env/mod.rs

My hope is this will make the `source <(CARGO_COMPLETE=bash cargo +nightly)` case work while providing a workaround for anyone who this doesn't work for.

fix(complete): Strip wrappers for running completer

---

clap_builder/src/builder/arg.rs

Just a small fix in the documentation of `Arg::raw`

docs: fix small error in Arg::raw

---

.github/workflows/ci.yml
clap_complete/Cargo.toml
clap_complete/tests/testsuite/bash.rs
clap_complete/tests/testsuite/common.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/zsh.rs
clap_complete_nushell/Cargo.toml
clap_complete_nushell/tests/common.rs
clap_complete_nushell/tests/completion.rs

We're running into the problem of tests being dependent on the version of the command.

test: Make shell integration tests non-blocking

---

clap_complete/src/engine/complete.rs

`AnyPath` is the documented behavior *but* thats to help when there isn't much other information.  With us choosing a `ValueHint` based on the value parser, we are less likely to get benefit from `AnyPath`.
Instead, this will greatly improve cases like Cargo where we offer path completions on many arguments where it doesn't make sense.

fix(complete): Change ValueHint::Unknown to Other, from AnyPath

---

clap_complete/src/env/mod.rs

refactor(complete): Better separate concerns

---

clap_complete/src/engine/complete.rs
clap_complete/src/engine/custom.rs
clap_complete/src/engine/mod.rs
clap_complete/tests/testsuite/engine.rs

This PR aims to simply add support for external subcommand completions. It does not provide any support for forward completions regarding issue https://github.com/clap-rs/clap/issues/5653.

feat: Simple support to complete external subcommand

---

clap_complete/src/env/shells.rs
clap_complete/tests/snapshots/home/dynamic-env/exhaustive/zsh/zsh/_exhaustive
clap_complete/tests/testsuite/zsh.rs

When using `unstable-dynamic` completions in Zsh, suggested values are not described. It's a step backwards compared to the default behavior and it makes things more difficult for users.
I had a quick look and it seems relatively easy to fix. But I'm not familiar with either clap or Zsh autocompletion, so I may miss something here.

feat(complete): Add descriptions to dynamic Zsh completions

---

clap_complete/src/aot/shells/zsh.rs
clap_complete/tests/snapshots/aliases.zsh
clap_complete/tests/snapshots/feature_sample.zsh
clap_complete/tests/snapshots/home/static/exhaustive/zsh/zsh/_exhaustive
clap_complete/tests/snapshots/special_commands.zsh
clap_complete/tests/snapshots/sub_subcommands.zsh
clap_complete/tests/snapshots/subcommand_last.zsh
clap_complete/tests/snapshots/two_multi_valued_arguments.zsh
clap_complete/tests/snapshots/value_hint.zsh
clap_complete/tests/snapshots/value_terminator.zsh

This is consistent with bash where `compgen -f` is used in such cases. In long experience with completions distributed with zsh, the worst thing you can do is break filename completion as that's the minimum most user's expect. By default, _default just completes files. It is also far better to leave the final component blank from `ValueHint::Other` as using empty parentheses will cause zsh to do slightly more work for the same result.
For context, note that I'm a zsh developer and have a lot of experience of writing zsh completions manually.

fix(zsh): Use _default as the completion fallback where the ValueHint is Unknown

---

clap_builder/src/builder/action.rs
clap_builder/src/builder/app_settings.rs
clap_builder/src/builder/arg.rs
clap_builder/src/builder/arg_group.rs
clap_builder/src/builder/command.rs
clap_builder/src/builder/os_str.rs
clap_builder/src/builder/possible_value.rs
clap_builder/src/builder/str.rs
clap_builder/src/builder/value_parser.rs
clap_builder/src/derive.rs
clap_builder/src/error/format.rs
clap_builder/src/macros.rs
clap_builder/src/parser/matches/arg_matches.rs
clap_builder/src/util/color.rs
clap_complete/src/aot/generator/mod.rs
clap_complete/src/aot/generator/utils.rs
clap_complete/src/env/mod.rs
clap_lex/src/lib.rs
examples/pacman.md
src/_derive/mod.rs

docs: Highlight notes/warnings in a block

---

clap_builder/src/parser/matches/matched_arg.rs
clap_builder/src/parser/mod.rs
clap_builder/src/parser/parser.rs
clap_builder/src/parser/validator.rs

refactor(parser): Remove redundant error check

---

clap_builder/src/parser/parser.rs
tests/builder/ignore_errors.rs

This came up in clap-rs#5812 and is especially problematic for derives.
Not really a fan of this solution but its the least invasive.
I also considered going wild with error recovery or moving towards a
solution for clap-rs#1546.

fix(parser): Fill in defaults on ignored error 

---

.github/workflows/bench-baseline.yml

This changeset slugifies the output of `${{ github.repository }}` to work with the Bencher CLI `--project` option.
Implementing this change should fix the error seen [in this CI run](https://github.com/clap-rs/clap/actions/runs/11901042045/job/33163189244#step:7:17).
Also see: https://github.com/epage/_rust/issues/25

Slugify `github.repository` for Bencher

---

clap_complete/src/lib.rs

The document formatting is inconsistent, so I aligned it with the style used in [generate_to](https://docs.rs/clap_complete/latest/clap_complete/aot/fn.generate_to.html)

docs: fix command formatting

---

clap_builder/src/builder/debug_asserts.rs
tests/builder/require.rs

It's non-sensical for an argument to require itself, so it must be a mistake, and should be prevented.
This is arguably a breaking change, but of the spacebar heating kind.
Let me know if I should add any tests for this.

fix(assert): Prevent arguments from requiring self

---

clap_lex/src/lib.rs
clap_lex/tests/testsuite/parsed.rs

This PR allows an `E` in scientific notation. Currently only `e` is allowed.

fix(lex): allow `E` in scientific notation

---

clap_derive/src/item.rs
tests/derive_ui/default_values_t_invalid.stderr

fix(derive): Update link for derive attributes

---

clap_complete/src/aot/shells/bash.rs
clap_complete/tests/snapshots/sub_subcommands.bash

Visible alias completions were causing duplicate case conditions when offering subcommand completions, due to the fact that they share the same function name as the command they are aliasing. This commit deduplicates them so as to not redefine the exact same case statement logic.

fix(complete): remove duplicate bash subcmd cases caused by aliases

---

clap_complete/src/env/mod.rs
clap_complete/src/env/shells.rs

PowerShell does not support inline syntax for assigning environment variables, so we must instead set the value before running the completer and restore it after it exits.
The completer will often, if not always, be surrounded by double quotes on Windows. To avoid syntax errors, define the argument to Invoke-Expression as a here-string so the quotes don't create a syntax error.
Updates the instructions for adding the argument completer to the profile. Piping a native command to Invoke-Expression invokes each line separately. Adding `Out-String` to the pipeline ensures that Invoke-Expression receives the whole script as a single value from the pipeline.
Fixes: #5847

fix(complete): Fix PowerShell dynamic completion

---

clap_complete_nushell/src/lib.rs
clap_complete_nushell/tests/snapshots/feature_sample.nu
clap_complete_nushell/tests/snapshots/home/static/test/nu/.config/nushell/completions/test.nu
clap_complete_nushell/tests/snapshots/special_commands.nu
clap_complete_nushell/tests/snapshots/sub_subcommands.nu
clap_complete_nushell/tests/snapshots/value_hint.nu

fixes #5605 
- Modified `append_value_completion_and_help` to set argument type to `path` for `ValueHint::AnyPath`, `ValueHint::FilePath`, and `ValueHint::DirPath`, and to `string` for other `ValueHint`s.
- Updated test snapshots to reflect the changes in argument types.

fix(nu): Set argument type based on `ValueHint`

---

clap_builder/src/output/help_template.rs

While looking into the still troublesome binary size I was investigating the noticeable amount of monomorphised sort functions. Looking at the few callers I noticed that they're creating custom `Vec`s and then sorting them with a custom lambda functions to sort them.
As it turns out, it's a win to insert the entries into a `BTreeMap` instead of creating a `Vec` and manually sorting it.
E.g. for the `stdio-fixture` binary, we're going from:
```
Finished `release` profile [optimized] target(s) in 1.81s
Analyzing target/release/stdio-fixture
File  .text     Size        Crate Name
1.7%   3.0%  15.6KiB    [Unknown] __mh_execute_header
1.6%   2.8%  14.8KiB clap_builder clap_builder::parser::parser::Parser::get_matches_with
1.5%   2.7%  14.1KiB clap_builder …
```

Use BTreeMap instead of a sorted Vec

---

clap_complete/src/aot/shells/fish.rs
clap_complete/tests/snapshots/home/static/exhaustive/fish/fish/completions/exhaustive.fish
clap_complete/tests/snapshots/sub_subcommands.fish
clap_complete/tests/snapshots/value_hint.fish
clap_complete/tests/testsuite/fish.rs

fix(complete): Remove `{}` and use newline instead of comma in Fish completions

---

clap_builder/src/parser/features/suggestions.rs

Turns out to be another win by doing a manual insertion sort of the suggestion rather than using `sort_by`.
Before:
```
Finished `release` profile [optimized] target(s) in 0.05s
Analyzing target/release/examples/git
File  .text     Size        Crate Name
1.6%   2.8%  15.2KiB          git git::main
1.5%   2.7%  14.8KiB clap_builder clap_builder::parser::parser::Parser::get_matches_with
1.5%   2.6%  14.1KiB clap_builder clap_builder::builder::command::Command::_build_self
1.0%   1.7%   9.4KiB          std std::backtrace_rs::symbolize::gimli::resolve
0.9%   1.6%   8.6KiB          std std::backtrace_rs::symbolize::gimli::Context::new
0.7%   1.3%   7.1KiB          std gimli::read::dwarf::Unit<R>::new
0.7%   1.3%   7.1KiB    [Unknown] __mh_execute_header
0.7%   1.3%   7.0KiB clap_builder …
```

Replace another sort_by call by a manual insertion with a binary_search

---

clap_mangen/src/lib.rs
clap_mangen/src/render.rs
clap_mangen/tests/snapshots/help_headings.bash.roff
clap_mangen/tests/testsuite/common.rs
clap_mangen/tests/testsuite/roff.rs

An implementation for #3363
Could also make this a flag on `Man`.

feat(mangen): Separate options based on `help_heading`

---

clap_builder/src/builder/arg.rs
src/_derive/_tutorial/chapter_2.rs
src/_derive/mod.rs
src/_tutorial/chapter_2.rs

Inspired by https://www.reddit.com/r/rust/comments/1i5np88/clap_documentation_is_too_confusing_for_me/m87mutm/
> I always use derive, and I mostly use the reference. From manual
> experimentation I’ve had to develop the mental model that short
> implicitly is what makes an argument non-positional, and if I want an
> argument to be positional then it will be by default unless I specify
> short. When I search for the word “positional” in the reference, there
> are no results. When I search for it in the tutorial, there is one
> result that says something I can do with an argument that i’ve made
> positional, but there’s no indication for how to make the argument
> positional in the first place. The reference documentation on short
> doesn’t mention anything about the fact that that’s what …

docs: Clarify the default state of an Arg/field

---

clap_complete/src/aot/shells/powershell.rs

fix #5820
PowerShell treats `’` as regular single quote, so it needs to be escaped with single quote as well.

fix(complete): Fix single quote escaping in PowerShell

---

clap_complete/src/aot/shells/powershell.rs

fix #5341
Fallback to `data.to_string()` as well if help strig is empty.

fix(complete): Check if help string is empty

---

clap_complete/src/env/mod.rs

You can remove the env variable but sometimes you want to override it.

feat(complete): Provide a way to disable env completions

---

Cargo.lock
Cargo.toml
Makefile
clap_derive/Cargo.toml
clap_derive/src/utils/doc_comments.rs
tests/derive/markdown.rs
tests/derive/snapshots/blocks.term.svg
tests/derive/snapshots/headers.term.svg
tests/derive/snapshots/html.term.svg
tests/derive/snapshots/inline_styles.term.svg
tests/derive/snapshots/links.term.svg
tests/derive/snapshots/lists.term.svg
tests/derive/snapshots/paragraphs.term.svg

fixes #2389
| markdown | output | comment |
| - | - | - |
|  paragraph | surrounded by empty line |
| `# heading` | bold + underline + surrounded by empty line | default style for heading |
| `![image]()` | alt text | anyone feeling sixel?!|
| `<html>` | verbatim |
| `> blockquote` | ![image](https://github.com/user-attachments/assets/3eec1b6e-fcc5-4293-9bb5-1fa1e869b270) | alternatively could use `>` |
| code block | ![image](https://github.com/user-attachments/assets/a3ce198c-a4e1-43d9-9a42-bd77dc2733c6)| same styling as `` `code` ``|
| (un)ordered lists | ![ordered list example](https://github.com/user-attachments/assets/880b93b9-b19c-445e-9605-280f41dff941) | |
| `*emphasis*` | italic |
| `**strong**` | bold |
| `~stikethrough~` | strikethrough |
| `[link](url)` | underlined alt text …

Markdown parsing in doc comments

---

clap_builder/src/parser/matches/arg_matches.rs
clap_builder/src/util/flat_map.rs
tests/builder/arg_matches.rs

When we switched flags to `ArgAction::SetTrue`,
we overlooked updating `args_present`.
Because of the default value for `ArgAction::SetTrue`,
`args_present` will always report true when a flag is defined.
I went with the trivial implementation for now.  We could proactively
track this but was unsure about correctness vs overhead and so I thought
I'd have those using it pay for it.
Looking over uses on github, this will fix a couple bugs but should
otherwise be unnoticeable.
Fixes #5860

fix(parser): Dont report missing flags as present 

---

clap_complete/examples/completion-derive.rs
clap_complete/examples/completion.rs
clap_complete/examples/exhaustive.rs
clap_complete/src/aot/generator/mod.rs
clap_complete/src/aot/mod.rs
clap_complete/src/lib.rs
clap_complete/tests/testsuite/common.rs
clap_complete_nushell/tests/common.rs

In the rust 2024 edition, [`gen` has been a reserved keyword](https://doc.rust-lang.org/edition-guide/rust-2024/gen-keyword.html), so we should avoid using it.

chore: Avoid using `gen` for rust 2024 preserved keyword

---

clap_builder/src/error/mod.rs

This is very minor, and could be considered obvious, but I didn't notice the return value immediately so why not mention it.

document `clap::Error::insert` a bit better

---

clap_builder/src/error/mod.rs
tests/builder/error.rs

#5935
The added test covers both `Error::insert` and `Error::remove`.
If we merge this after #5942, I could make the new test use the same `assert_error` as the other ones (though I'm not sure that would be better, up to you). I could also make `assert_error` take `&Error`, but that changes a lot of call sites.

feat(builder): Add `clap::Error::remove` and a test

---

clap_complete/src/engine/complete.rs
clap_complete/tests/testsuite/engine.rs

NOTE This text is outdated; see commit messages.
TODO: should double-check the root cause and add automated tests
jj dynamic completions of option names work as expected ...
$ COMPLETE=fish jj -- jj abandon --ignore-
--ignore-working-copy
--ignore-immutable
... unless there is a positional argument
$ COMPLETE=fish jj -- jj abandon @ --ignore-
The positional arguments are defined in the "abandon" subcommand as:
```rust
#[derive(clap::Args, Clone, Debug)]
pub(crate) struct AbandonArgs {
/// The revision(s) to abandon (default: @)
#[arg(
value_name = "REVSETS",
add = ArgValueCandidates::new(complete::mutable_revisions)
)]
revisions_pos: Vec<RevisionArg>,
}
```
After clap_complete sees the first positional argument ("@") we are stuck
in "ParseState::Pos(..)" even when we get to parsing …

Fix arbitrary-cardinality positionals shadowing option name completion

---

clap_builder/src/parser/parser.rs
tests/derive/doc_comments_help.rs
tests/derive/groups.rs
tests/derive/help.rs
tests/derive/utils.rs

If we are assuming the arguments are present, then there is no reason to
show alternatives from the group.
There may be other ways large groups show up.
For now, I'm taking the whack-a-mole approach of handling them on a
case-by-case basis.
When we get to one where the group is relevant to show,
we should handle a general case then.
Fixes #5958

fix(parser): Don't include groups in argument suggestions 

---

clap_builder/src/output/help_template.rs
tests/builder/help.rs

Check to see if a subcommand has arguments and only print the preceding newline if it does.
Fixes #5960.

fix(help): Don't add \n when a flat subcommand has no args

---

clap_builder/src/output/help_template.rs
examples/find.md
examples/git-derive.md
examples/git.md
tests/builder/help.rs

Fixes the alignment of sections with mixed argument types, including those without short arguments. This is done by adding an extra 4 to the length of arguments that will show a short flag (by calling `fn short`) instead of trying to account for it elsewhere.
For example:
```
Options:
--from <FROM_VER>  The version to upgrade from
[TO_VER]           The version to upgrade to
```
Will now show as:
```
Options:
--from <FROM_VER>  The version to upgrade from
[TO_VER]           The version to upgrade to
```
Fixes #3835.

fix(help): Align mixed argument types

---

clap_builder/src/output/help_template.rs
examples/find.md
tests/builder/help.rs

Concern was raised over the alignment in #5963 and decided to defer this for now.  This wasn't part of the original issue and hadn't been discussed before.
If someone wants to move this forward again, I'd recommend starting with an issue to discuss the trade offs.
This reverts commit 78e41f66665f89ceea5975ab6320cfd4524122f2.

Revert "feat(help): Only print short when required"

---

clap_builder/src/builder/action.rs

Fixed the doc comment in the builder.
The fixed part appears to be `version`, not `help`.   
I created a PR without an associated issue because this seems to be an obvious and simple mistake. 
edited: sorry for forgetting `committed`

fix: minor fix for builder docs (help -> version)

---

clap_complete/src/aot/shells/bash.rs
clap_complete/tests/snapshots/aliases.bash
clap_complete/tests/snapshots/basic.bash
clap_complete/tests/snapshots/custom_bin_name.bash
clap_complete/tests/snapshots/feature_sample.bash
clap_complete/tests/snapshots/home/static/exhaustive/bash/.bashrc
clap_complete/tests/snapshots/quoting.bash
clap_complete/tests/snapshots/special_commands.bash
clap_complete/tests/snapshots/sub_subcommands.bash
clap_complete/tests/snapshots/subcommand_last.bash
clap_complete/tests/snapshots/two_multi_valued_arguments.bash
clap_complete/tests/snapshots/value_hint.bash
clap_complete/tests/snapshots/value_terminator.bash
clap_complete/tests/testsuite/bash.rs

complete: Only parse arguments before current in Bash

---

clap_builder/src/output/help_template.rs
tests/builder/arg_aliases.rs
tests/builder/arg_aliases_short.rs

feat(help): Prefix argument long and short aliases in output with `--` and `-`

---

clap_builder/src/output/help_template.rs
tests/builder/arg_aliases_short.rs

Short aliases are displayed before long aliases, consistent with the order of the short and long argument variants at the start of each line.
Based on [this suggestion][1] from @epage.
[1]: https://github.com/clap-rs/clap/pull/5996#discussion_r2083363726

feat(help): Merge lists of short and long aliases

---

clap_complete/src/aot/shells/zsh.rs
clap_complete/tests/snapshots/external_subcommands.bash
clap_complete/tests/snapshots/external_subcommands.elvish
clap_complete/tests/snapshots/external_subcommands.fish
clap_complete/tests/snapshots/external_subcommands.ps1
clap_complete/tests/snapshots/external_subcommands.zsh
clap_complete/tests/testsuite/bash.rs
clap_complete/tests/testsuite/common.rs
clap_complete/tests/testsuite/elvish.rs
clap_complete/tests/testsuite/fish.rs
clap_complete/tests/testsuite/powershell.rs
clap_complete/tests/testsuite/zsh.rs

Proposal for #6016.
Same fix is applied as in the linked issue. Added zsh only test since the issue only persists on zsh.
This fix allows default completions on external commands. Right now the completions are disabled, making for an annoying DX. The behaviour is now in line with bash, fish.

Fix: external_subcommand does not 'tab complete' in ZSH

---

Cargo.toml
clap_builder/Cargo.toml
clap_complete/Cargo.toml
src/_tutorial.rs

This PR fixes an intra-doc link warning and remove unneeded `--cfg=docsrs` set in `Cargo.toml` files.
Also: the `--generate-link-to-definition` currently doesn't work and I think it's because docs.rs related values are not read in workspace `Cargo.toml` files. I think it should be declared in all sub-`Cargo.toml` files.

Cleanup docs.rs related issues

---

clap_complete_nushell/Cargo.toml
clap_derive/Cargo.toml
clap_mangen/Cargo.toml

Follow-up of https://github.com/clap-rs/clap/pull/6045.
Hopefully it should make the option work on docs.rs once next version of `clap` is published.

Add missing `--generate-link-to-definition` docs.rs options

---

clap_builder/src/builder/styling.rs
clap_builder/src/output/help_template.rs
src/bin/stdio-fixture.rs
tests/ui/arg_required_else_help_stderr.toml
tests/ui/error_stderr.toml
tests/ui/h_flag_stdout.toml
tests/ui/help_cmd_stdout.toml
tests/ui/help_flag_stdout.toml

Styles for [aliases], [default], [env], and [possible values] as well as their values
fix https://github.com/clap-rs/clap/issues/5093
Continuation of PR https://github.com/clap-rs/clap/pull/5482 but clean.
I created an issue (https://github.com/clap-rs/clap/issues/6056) about `literal` possible values in long help for when 5.0 is rolling out as @pksunkara asked. 
I added more granularity in the styling of each "context" but still a general one to style all of them at once too.

feat(help): Allow styling for inline context

---

clap_mangen/src/render.rs
clap_mangen/tests/snapshots/multiple_optional_values.bash.roff
clap_mangen/tests/snapshots/optional_value.bash.roff
clap_mangen/tests/snapshots/optional_with_required_equals_value.bash.roff
clap_mangen/tests/snapshots/value_with_required_equals.bash.roff
clap_mangen/tests/snapshots/variadic_values.bash.roff
clap_mangen/tests/testsuite/common.rs
clap_mangen/tests/testsuite/roff.rs

In #3358 we discovered clapmangen wouldn’t render optional `required_equals` values with `[=<VALUE>]`. After further experimentation it was also found out that it didn’t appropriately render optional values `[VALUE]` and variadic values `<Val>…`  as well. This commit adds a check to the options render section where it will add the correct formatting. e.g instead of
`--option=VALUE` it will render `—option \<VALUE\>`, `—option [VALUE]`
`--option[=VALUE]` or option `<VALUE>…` and so on
Bringing it more in line with what clap shows when running --help. 
Fixes #3358

fix: clap_man doesn't render optional values with [=<VALUE>]

---

clap_builder/src/output/help_template.rs
tests/builder/flag_subcommands.rs
tests/builder/help.rs
tests/ui/arg_required_else_help_stderr.toml
tests/ui/h_flag_stdout.toml
tests/ui/help_cmd_stdout.toml
tests/ui/help_flag_stdout.toml

fix https://github.com/clap-rs/clap/issues/6067
fix https://github.com/clap-rs/clap/issues/6073

fix: added visible long flag aliases in help

---

clap_complete/src/engine/custom.rs
clap_complete/tests/testsuite/engine.rs

fix(complete): Hide dot files on dynamic completer

---

clap_derive/src/item.rs
tests/derive/doc_comments_help.rs

fix(ValueEnum): Detailed help for ValueEnum variant #6096

---

clap_builder/src/builder/styled_str.rs

Mark `StyledStr::push_str` as public, so that `ErrorFormatter` trait available outside of clap crate.
https://github.com/clap-rs/clap/issues/380#issuecomment-3217975004

feat: mark `StyledStr::push_str` functions public

---

clap_derive/src/derives/args.rs
clap_derive/src/derives/subcommand.rs
examples/derive_ref/interop_tests.md
tests/derive/help.rs

fix(derive): Match rustc's error style

---

clap_complete/src/env/mod.rs

Unlike most other shells, fish [supports sourcing directly from the standard input](https://github.com/fish-shell/fish-shell/blob/898cc3242b15efc9be514538ff97048ed40c2d77/doc_src/cmds/source.rst), which is simpler and more idiomatic.
This is for instance how jj now recommend sourcing their dynamic completions since https://github.com/jj-vcs/jj/pull/4847.

docs(complete): Simplify sourcing fish completions

---

clap_builder/src/builder/arg.rs
clap_builder/src/builder/command.rs

docs(builder): Explain dont_delimit_trailing_values
